### ISSUE TITLE
[feature request] deprecated repo `yurt-app-manager-api`

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/openyurt#1010]
**What would you like to be added**:

Use [api](https://github.com/openyurtio/api) to replace  [app-manager-api](https://github.com/openyurtio/yurt-app-manager-api
).
We need to modify go import which used by `openyurt` etc.

**Why is this needed**:

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@huiwq1990 yes, we shoud search all repos and find out all codes that are using `yurt-app-manager-api`.

**Comment by YTGhost** [comment]
Maybe I can get this done, what specific repositories need to be modified at this point? @rambohe-ch

**Comment by rambohe-ch** [comment]
> Maybe I can get this done, what specific repositories need to be modified at this point? @rambohe-ch

@YTGhost maybe we can start from `openyurtio/openyurt` repo.

**Comment by YTGhost** [comment]
@rambohe-ch The controller migration is now complete and I think it's time to start this work?

**Comment by rambohe-ch** [comment]
> @rambohe-ch The controller migration is now complete and I think it's time to start this work?

@YTGhost yes, would you like to take over this work?

**Comment by YTGhost** [comment]
> > @rambohe-ch The controller migration is now complete and I think it's time to start this work?
> 
> @YTGhost yes, would you like to take over this work?

/assign

**Comment by YTGhost** [comment]
> @YTGhost Do you have any progress about this issue?

@rambohe-ch I see that this part(https://github.com/openyurtio/yurt-app-manager-api/tree/main/pkg/yurtappmanager/client) is not in the api repository, how should this piece be migrated?

**Comment by rambohe-ch** [comment]
> > @YTGhost Do you have any progress about this issue?
> 
> @rambohe-ch I see that this part(https://github.com/openyurtio/yurt-app-manager-api/tree/main/pkg/yurtappmanager/client) is not in the api repository, how should this piece be migrated?

@YTGhost  we should divide this feature into two parts: (take NodePool as a example)
- import NodePool in yurt-app-manager-api: we can import NodePool in `pkg/apis/apps`
- use nodepool client: we can use `controller-runtime` client to manage nodepool resource.
