### ISSUE TITLE
[BUG] If a node updates openyurt.io/is-edge-worker to true again, the tunnel server needs to be restarted to take effect

### ISSUE THREAD

**Issue by huweihuang** [openyurtio/openyurt#1012]
**What happened**:

If a node updates openyurt.io/is-edge-worker to true again, the tunnel agent will be redeployed.  But cannot access the container by tunnel.  the the tunnel server needs to be restarted to solve the problem.

**What you expected to happen**:

If a node updates openyurt.io/is-edge-worker to true again, there is no need to restart the tunnel server.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

 openyurt/yurt-tunnel-server:latest

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@huweihuang Thank you for raising issue. This problem has been fixed in OpenYurt v1.0.0 version. how about use `yurt-controller-manager:v1.0.0/yurt-tunnel-server:v1.0.0/yurt-tunnel-agent:v1.0.0` to have a try?

**Comment by rambohe-ch** [comment]
@huweihuang i will close this issue because this bug has been fixed in OpenYurt v1.0, and you can feel free to reopen this issue if you need.
