### ISSUE TITLE
[BUG] kubectl apply -f work/nodepool.yaml failed calling webhook "mnodepool.kb.io"

### ISSUE THREAD

**Issue by fujitatomoya** [openyurtio/openyurt#1023]
**What happened**:

```bash
Error from server (InternalError): error when creating "work/nodepool.yaml": Internal error occurred: failed calling webhook "mnodepool.kb.io": failed to call webhook: Post "https://yurt-app-manager-webhook.kube-system.svc:443/mutate-apps-openyurt-io-v1alpha1-nodepool?timeout=10s": dial tcp 10.110.157.235:443: connect: connection refused
Connection to 127.0.0.1 closed.
```

**What you expected to happen**:

No error observed to create `nodepool`.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
root@ceci-control-plane:/home/vagrant/ceci-work# cat work/nodepool.yaml 
apiVersion: apps.openyurt.io/v1alpha1
kind: NodePool
metadata:
  name: master
spec:
  type: Cloud
root@ceci-control-plane:/home/vagrant/ceci-work# kubectl apply -f work/nodepool.yaml
```

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: v1.0.0
- Kubernetes version (use `kubectl version`): 1.22.13
- OS (e.g: `cat /etc/os-release`): Ubuntu20.04
- Kernel (e.g. `uname -a`): 5.15.0-48-generic
- Install tools: https://openyurt.io/docs/installation/manually-setup
- Others:

**others**

/kind bug

**Comment by fujitatomoya** [comment]
According to error message, it obviously issues API to `https://yurt-app-manager-webhook.kube-system.svc:443/mutate-apps-openyurt-io-v1alpha1-nodepool?timeout=10s` in cluster, that means this service must be up before this API call.

We have script setup to entire procedure, that means there could be possibility not to give enough time window until this service is online, that led to this failure.

while this is understandable, we would want to check the service is there before issue the API.

**Comment by rambohe-ch** [comment]
@fujitatomoya Thank you for raising issue. `yurt-app-manager` pod and service should be ready before `NodePool` resource can be created. and your pull request https://github.com/openyurtio/openyurt.io/pull/222 has been merged.

**Comment by fujitatomoya** [comment]
closing this in favor of https://github.com/openyurtio/openyurt.io/pull/222
