### ISSUE TITLE
[feature request]yurtappdaemon need a node pool type selector

### ISSUE THREAD

**Issue by donychen1134** [openyurtio/openyurt#1038]
**What would you like to be added**:
Add selector to select node pool by its type for yurtappdaemon CRD.

**Why is this needed**:
When the time developing pool-coordinator feature, we found that pool-coordinator should be deploy to the node pool which type is edge. But yurtappdaemon only supports to select node pool by label.
If we add node selector to the podSpec of yurtappdaemon, we will see that the pool-coordinator in cloud type of node pool will always be the pending status.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@donychen1134 maybe it's a good idea to remove this issue to openyurtio/yurt-app-manager repo where yurtappdaemon resource is hosted.

**Comment by donychen1134** [comment]
@rambohe-ch OK, I will close this issue and open another in yurt-app-manager.
