### ISSUE TITLE
stop using beta.kubernetes.io/os  and arch

### ISSUE THREAD

**Issue by pacoxu** [openyurtio/openyurt#1039]
https://github.com/openyurtio/openyurt/blob/daa3acd2cb44d4118c9d8ee9633450f63e95a020/pkg/controller/nodelifecycle/node_lifecycle_controller.go#L68-L73

See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

Kube plan to remove support in next releases(maybe v1.28).

**Comment by rambohe-ch** [comment]
@pacoxu Thank you for raising issue. `node life cycle` controller will be removed in OpenYurt v1.2, and the job is under working.

**Comment by pacoxu** [comment]
It sounds like there is not need to update here. 
Thanks for confirmation.

**Comment by rambohe-ch** [comment]
> It sounds like there is not need to update here. Thanks for confirmation.

@pacoxu yes, the newly added controller that provide autonomy functions will work together with native NodeLifeCycle controller in Kube-controller-manager.
