### ISSUE TITLE
yurtadm init failed

### ISSUE THREAD

**Issue by hongcaohu** [openyurtio/openyurt#1050]
when I use Yurtadm init method to init yurtadm according to zhe document,  some failed happened bellow.
2022-11-08 16:04:24 [INFO] [init.go:259] start to init master0...
2022-11-08 16:04:25 [INFO] [init.go:214] join command is: kubeadm join  apiserver.cluster.local:6443 --token h3a1lx.egzk904uvi37nzbt \
	--discovery-token-ca-cert-hash sha256:12f74fcca14db24def0ec15a690b4a272b8faea99c08f6105090f78397f3e4ba \
	--control-plane --certificate-key 36340db0c20eaafc6f00f2bc1dc343ed53f9defca83b41a2d966d991bd731d84

[INFO] Label master node: openyurt.io/is-edge-worker=false
node/fnaiot-test labeled
[INFO] Install flannel
Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
podsecuritypolicy.policy/psp.flannel.unprivileged created
clusterrole.rbac.authorization.k8s.io/flannel created
clusterrolebinding.rbac.authorization.k8s.io/flannel created
serviceaccount/flannel created
configmap/kube-flannel-cfg created
daemonset.apps/kube-flannel-ds created
[INFO] Adjust kube-controller-manager
Waiting for kube-controller-manager to restart...
timed out waiting for the kube-controller-manager to restart
kube-controller-manager adjustment completed
[INFO] Install yurt-tunnel-dns
serviceaccount/yurt-tunnel-dns created
clusterrole.rbac.authorization.k8s.io/system:yurt-tunnel-dns created
clusterrolebinding.rbac.authorization.k8s.io/system:yurt-tunnel-dns created
configmap/yurt-tunnel-dns created
configmap/yurt-tunnel-nodes created
deployment.apps/yurt-tunnel-dns created
service/yurt-tunnel-dns created
[INFO] Adjust kube-apiserver
Waiting for kube-apiserver to restart...
Kube-apiserver has been restarted successfully
[INFO] Adjust coreDNS
daemonset.apps/coredns created
deployment.apps/coredns scaled
service/kube-dns annotated
[INFO] Adjust kube-proxy
Warning: resource configmaps/kube-proxy is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
configmap/kube-proxy configured
[INFO] Install helm
helm is not installed, start to install helm
linux-amd64/
linux-amd64/helm
linux-amd64/LICENSE
linux-amd64/README.md
successfully installed helm v3.9.4
[INFO] Add openyurt helm repo
"openyurt" already exists with the same configuration, skipping
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "aliyun" chart repository
...Successfully got an update from the "openyurt" chart repository
Update Complete. ⎈Happy Helming!⎈
[INFO] Install yurt-controller-manager, yurt-tunnel-server, yurt-tunnel-agent, yurthub-cfg
Release "openyurt" does not exist. Installing it now.
NAME: openyurt
LAST DEPLOYED: Tue Nov  8 16:31:19 2022
NAMESPACE: kube-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
[INFO] Install yurt-app-manager
Release "yurt-app-manager" does not exist. Installing it now.
Error: failed to download "openyurt/yurt-app-manager"
[INFO] OpenYurt is successfully installed
2022-11-08 16:04:33 [INFO] [local.go:297] Succeeded in creating a new cluster, enjoy it!

use:  kubectl get po -A command,  not find "yurt-controller-manager, yurt-tunnel-server, yurt-tunnel-agent, yurthub-cfg pod running" result below:
![image](https://user-images.githubusercontent.com/15919714/200516629-429dd763-48ac-47de-bbce-2556cab606c7.png)

what a i do to resolve this problem

- OpenYurt version: had try many version: v1.0.0 - v1.1.0
- Kubernetes version:  v1.22.8
- OS: Ubuntu 20.04.4 LTS 
- Kernel : Linux fnaiot-test 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: yuradm init ..
- Others:

**Comment by rambohe-ch** [comment]
@hongcaohu we recommend you to use [manual setup](https://openyurt.io/docs/installation/manually-setup) instead of yurtadm init to install OpenYurt, and yurtadm init command tutorial has been concealed in openyurt.io.

we will support yurtadm init command in the future version. so i will close this issue, and you can feel free to reopen this issue or create new issue.
