### ISSUE TITLE
[BUG] The flannel-edge image provided only supports amd64, no image for arm64 is provided

### ISSUE THREAD

**Issue by ccjjxx99** [openyurtio/openyurt#1053]
**What happened**:
The pod `kube-flannel-ds` keeps failing to initialize when I join a cluster created by yurtadm using a machine with arm64 architecture. When I check the container logs, there is only one sentence with "exec /bin/cp: exec format error".
I checked the doc on https://openyurt.io/docs/user-manuals/network/edge-pod-network. The image you provided on https://hub.docker.com/r/openyurt/flannel-edge/tags is only the amd64 image, so it won't run successfully on my arm64 edge node.

**What you expected to happen**:
Cloud you please provide the arm64 image of kube-flannel that has patched for edge environment on registry.cn-hangzhou.aliyuncs.com?

**How to reproduce it (as minimally and precisely as possible)**:
Easily with an arm64 machine.

**Anything else we need to know?**:
No.

**Environment**:
- OpenYurt version: 1.0
- Kubernetes version (use `kubectl version`): 1.22.8
- OS (e.g: `cat /etc/os-release`): ubuntu
- Kernel (e.g. `uname -a`):
- Install tools: yurtadm
- Others:

**others**

/kind bug

**Comment by ccjjxx99** [comment]
#731

**Comment by ccjjxx99** [comment]
#731

**Comment by rambohe-ch** [comment]
@ccjjxx99 Thank you for raising issue for improved flannel.
@wenjun93 Do you have any time to solve this problem?

**Comment by ccjjxx99** [comment]
@wenjun93 这个事情其实挺简单，不到十分钟就搞定了，按照[边缘Pod网络的文档](https://openyurt.io/zh/docs/user-manuals/network/edge-pod-network/#%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95-%E5%9C%A8flannel%E4%B8%AD%E5%A2%9E%E5%8A%A0mac%E5%9C%B0%E5%9D%80%E4%BF%9D%E6%8C%81%E5%8A%9F%E8%83%BD)打补丁后，再按照[flannel的文档](https://github.com/flannel-io/flannel/blob/master/Documentation/building.md#building-for-other-platforms)使用命令`ARCH=arm64 make image`就可以打包了。

可能会提示一个“qemu-aarch64-static”找不到的问题，我发现只要把dist文件夹里的qemu-arm64-static复制一份改名叫qemu-aarch64-static就可以成功生成镜像，并且在我的arm64的机器上可以成功运行。

希望您能抽出宝贵的时间把镜像上传到阿里云的镜像仓库中，这样对于边缘节点是arm64架构的用户可以方便很多，万分感谢！
