### ISSUE TITLE
autonomy test failed for deleting namespace

### ISSUE THREAD

**Issue by Congrool** [openyurtio/openyurt#1054]
#### Which jobs are failing:

When cleaning the test environment after all tests pass, e2e tests sometimes fail for deleting test namespace. The error log is like this:
```
[AfterSuite] [FAILED] [0.185 seconds]
[AfterSuite] 
/home/runner/work/openyurt/openyurt/test/e2e/autonomy/autonomy_test.go:251

  Begin Captured GinkgoWriter Output >>
    STEP: delete namespace:yurt-e2e-test 11/09/22 06:59:13.458
  << End Captured GinkgoWriter Output

  fail to delete created namespaces:yurt-e2e-test
  Unexpected error:
      <*url.Error | 0xc000550c90>: {
          Op: "Delete",
          URL: "https://127.0.0.1:39939/api/v1/namespaces/yurt-e2e-test",
          Err: <*net.OpError | 0xc000386820>{
              Op: "read",
              Net: "tcp",
              Source: <*net.TCPAddr | 0xc000550ab0>{IP: [127, 0, 0, 1], Port: 48720, Zone: ""},
              Addr: <*net.TCPAddr | 0xc000550ae0>{IP: [127, 0, 0, 1], Port: 39939, Zone: ""},
              Err: <*os.SyscallError | 0xc000558700>{
                  Syscall: "read",
                  Err: <syscall.Errno>0x68,
              },
          },
      }
      Delete "https://127.0.0.1:39939/api/v1/namespaces/yurt-e2e-test": read tcp 127.0.0.1:48720->127.0.0.1:39939: read: connection reset by peer
  occurred
  In [AfterSuite] at: /home/runner/work/openyurt/openyurt/test/e2e/common/ns/ns.go:37
```

It seems that the connection was closed by APIServer. I have not figured out the reason why it is reset. 

Sometimes it can pass: 
https://github.com/openyurtio/openyurt/actions/runs/3425939958/jobs/5707228507

,and sometimes cannot:
https://github.com/openyurtio/openyurt/actions/runs/3425905272/jobs/5707158117

#### labels

/kind failing-test

**Comment by Congrool** [comment]
BTW, there's no such problem at local host.

**Comment by Congrool** [comment]
It seems that this problem has influenced the Github Action and makes contributor confused.
How about skip deleting namespace `yurt-e2e-test` after suite to make it work around? @rambohe-ch

**Comment by rambohe-ch** [comment]
> It seems that this problem has influenced the Github Action and makes contributor confused. How about skip deleting namespace `yurt-e2e-test` after suite to make it work around? @rambohe-ch

@Congrool It's not reasonable to skip namespace deletion after suite, maybe we can wait some time and dive deep into the error and then fix it.

**Comment by YTGhost** [comment]
Encountered the same problem

**Comment by Congrool** [comment]
> @Congrool I still have this problem in my case, maybe ten seconds is not enough to make sure that the connection to kube-apiserver is normal?
> 
> ```
> [AfterSuite] 
> /home/runner/work/openyurt/openyurt/test/e2e/autonomy/autonomy_test.go:251
> I1116 15:35:02.844672   41982 autonomy_test.go:256] successfully reconnected cloud node
> STEP: delete namespace:yurt-e2e-test 11/16/22 15:35:02.844
> ------------------------------
> [AfterSuite] [FAILED] [10.178 seconds]
> [AfterSuite] 
> /home/runner/work/openyurt/openyurt/test/e2e/autonomy/autonomy_test.go:251
> 
>   Begin Captured GinkgoWriter Output >>
>     STEP: delete namespace:yurt-e2e-test 11/16/22 15:35:02.844
>   << End Captured GinkgoWriter Output
> 
>   Timed out after 10.001s.
>   Expected success, but got an error:
>       <*url.Error | 0xc0001adcb0>: {
>           Op: "Delete",
>           URL: "https://127.0.0.1:45749/api/v1/namespaces/yurt-e2e-test",
>           Err: <*errors.errorString | 0xc000054110>{s: "EOF"},
>       }
>       Delete "https://127.0.0.1:45749/api/v1/namespaces/yurt-e2e-test": EOF
>   In [AfterSuite] at: /home/runner/work/openyurt/openyurt/test/e2e/autonomy/autonomy_test.go:261
> ```

Well, it seems that it's not the original problem. Because we use the `Foreground delete policy` which will block until all resources under the namespace have vanished, maybe 10s is not enough for this.

Would you like to submit a pr to adjust the timeout ? @YTGhost

**Comment by YTGhost** [comment]
> > @Congrool I still have this problem in my case, maybe ten seconds is not enough to make sure that the connection to kube-apiserver is normal?
> > ```
> > [AfterSuite] 
> > /home/runner/work/openyurt/openyurt/test/e2e/autonomy/autonomy_test.go:251
> > I1116 15:35:02.844672   41982 autonomy_test.go:256] successfully reconnected cloud node
> > STEP: delete namespace:yurt-e2e-test 11/16/22 15:35:02.844
> > ------------------------------
> > [AfterSuite] [FAILED] [10.178 seconds]
> > [AfterSuite] 
> > /home/runner/work/openyurt/openyurt/test/e2e/autonomy/autonomy_test.go:251
> > 
> >   Begin Captured GinkgoWriter Output >>
> >     STEP: delete namespace:yurt-e2e-test 11/16/22 15:35:02.844
> >   << End Captured GinkgoWriter Output
> > 
> >   Timed out after 10.001s.
> >   Expected success, but got an error:
> >       <*url.Error | 0xc0001adcb0>: {
> >           Op: "Delete",
> >           URL: "https://127.0.0.1:45749/api/v1/namespaces/yurt-e2e-test",
> >           Err: <*errors.errorString | 0xc000054110>{s: "EOF"},
> >       }
> >       Delete "https://127.0.0.1:45749/api/v1/namespaces/yurt-e2e-test": EOF
> >   In [AfterSuite] at: /home/runner/work/openyurt/openyurt/test/e2e/autonomy/autonomy_test.go:261
> > ```
> 
> Well, it seems that it's not the original problem. Because we use the `Foreground delete policy` which will block until all resources under the namespace have vanished, maybe 10s is not enough for this.
> 
> Would you like to submit a pr to adjust the timeout ? @YTGhost

ok

**Comment by Congrool** [comment]
/reopen

It seems that the problem still exists.

```plain-text
[AfterSuite] [FAILED] [21.265 seconds]
[AfterSuite] 
/home/runner/work/openyurt/openyurt/test/e2e/autonomy/autonomy_test.go:251

  Timed out after 21.030s.
  Expected success, but got an error:
      <*url.Error | 0xc00044a750>: {
          Op: "Get",
          URL: "https://127.0.0.1:33881/version?timeout=32s",
          Err: <*net.OpError | 0xc000158370>{
              Op: "read",
              Net: "tcp",
              Source: <*net.TCPAddr | 0xc00044a6c0>{IP: [127, 0, 0, 1], Port: 38970, Zone: ""},
              Addr: <*net.TCPAddr | 0xc00044a6f0>{IP: [127, 0, 0, 1], Port: 33881, Zone: ""},
              Err: <*os.SyscallError | 0xc0004ae2a0>{
                  Syscall: "read",
                  Err: <syscall.Errno>0x68,
              },
          },
      }
      Get "https://127.0.0.1:33881/version?timeout=32s": read tcp 127.0.0.1:38970->127.0.0.1:33881: read: connection reset by peer
  In [AfterSuite] at: /home/runner/work/openyurt/openyurt/test/e2e/autonomy/autonomy_test.go:261
```
