### ISSUE TITLE
[BUG]  'yurtadm init' executed the subsequent operation before the apiserver had finished restarting

### ISSUE THREAD

**Issue by ccjjxx99** [openyurtio/openyurt#1055]
**What happened**:
As you can see from the logs, after adjusting the apiserver configuration, the logs show "Kube-apiserver restarted successfully". However, all subsequent operations return "6443 was refused", which is because the apiserver has not finished restarting and kubectl is not running yet. 
Therefore, from the step "Adjust coreDNS", all the following operations are not performed at all.
![image](https://user-images.githubusercontent.com/32434705/200828304-12baa670-93e9-4308-8b94-a9292c596265.png)

**What you expected to happen**:
Yurtadm can correctly identify if apiserver restart is complete. Then proceed with the subsequent configuration.

**How to reproduce it (as minimally and precisely as possible)**:
Just run `yurtadm init --apiserver-advertise-address=192.168.31.209 --yurt-tunnel-server-address=192.168.31.209 --pod-network-cidr=10.244.0.0/16 --service-cidr=10.96.0.0/12`

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: 1.1.0
- Kubernetes version (use `kubectl version`): 1.22.8
- OS (e.g: `cat /etc/os-release`): Ubuntu 20.04.5
- Kernel (e.g. `uname -a`): `Linux master2015 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: yurtadm
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@ccjjxx99 Thank you for raising issue about `yurtadm init` command. `yurtadm init` command is maintained by @windydayc, but now he has not enough energy to take part in open source. and we recommend you to use `manually setup` to create OpenYurt cluster or use `make docker-build-and-up-openyurt` command to create a OpenYurt cluster for test.

of course, if you can take part in OpenYurt community and solve `yurtadm init` problem, more end user will benefit from your contributions.

**Comment by ccjjxx99** [comment]
@rambohe-ch  Thank you for your reply. Actually, now `yurtadm init` command implemented to help me build a normal k8s cluster and successfully complete the configuration from 1.1 to 2.3 in the [documentation of manually setup](https://openyurt.io/docs/next/installation/manually-setup/). 
And I was able to successfully build the OpenYurt cluster by continuing with the operations after 2.4 in the documentation.

By the way, I'll be happy to contribute to the community when I'm capable of taking part in coding.

**Comment by rambohe-ch** [comment]
@ccjjxx99 we recommend you to use `manual setup` instead of `yurtadm init` to install OpenYurt, and `yurtadm init` command tutorial has been concealed in openyurt.io. 

 we will support `yurtadm init` command in the future version. so i will close this issue, and you can feel free to reopen this issue or create new issue.
