### ISSUE TITLE
[feature request]merge `yurtctl init test` command into yurtadm tool

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1059]
**What would you like to be added**:
yurtctl tool is only used by e2e tests, in order to make OpenYurt tools more clearly, it's a good idea to merge the features of yurtctl into yurtadm tool. and yurtctl tool will be removed from OpenYurt.

**Why is this needed**:
end user is recommended to use kubectl(K8s native tool) to interact with the OpenYurt cluster. and yurtadm tool will be used for OpenYurt like kubeadm for K8s.

**others**
/kind feature

**Comment by YTGhost** [comment]
Maybe I can do this after I completely finish yurtadm join refactoring

**Comment by rambohe-ch** [comment]
> Maybe I can do this after I completely finish yurtadm join refactoring

good job. /assign @YTGhost

**Comment by rambohe-ch** [comment]
> > Maybe I can do this after I completely finish yurtadm join refactoring
> 
> good job. 

/assign @YTGhost

**Comment by rambohe-ch** [comment]
@YTGhost I think that `yurtctl markautonomous` and `yurtctl cluster-info`, these two commands are rarely used by end users, so just deprecated them. and merge `yurtctl test init`  into yurtadm tool. 

maybe we should consider a new name for `yurtctl test init` command in yurtadm.

**Comment by Congrool** [comment]
As we disscussed, it's werid to have such test command in `yurtadm`. We can add the binary into test/e2e which has the ability of starting up an openyurt cluster with kind. For users, we can provide a make target like current `make local-up-openyurt` which will call this binary to start up the openyurt clusters, hence no influence will be imposed on users. For e2e test, we can still use the existing scripts [run-e2e-test.sh](https://github.com/openyurtio/openyurt/blob/master/hack/make-rules/run-e2e-tests.sh), which may not be affected by this change. 

@YTGhost @rambohe-ch what do you think?

**Comment by rambohe-ch** [comment]
> As we disscussed, it's werid to have such test command in `yurtadm`. We can add the binary into test/e2e which has the ability of starting up an openyurt cluster with kind. For users, we can provide a make target like current `make local-up-openyurt` which will call this binary to start up the openyurt clusters, hence no influence will be imposed on users. For e2e test, we can still use the existing scripts [run-e2e-test.sh](https://github.com/openyurtio/openyurt/blob/master/hack/make-rules/run-e2e-tests.sh), which may not be affected by this change.
> 
> @YTGhost @rambohe-ch what do you think?

@Congrool Yes, i agree with you that combine yurtctl init test command into yurtadm is not suitable. and it's a good idea to integrate with e2e. agree +1

**Comment by YTGhost** [comment]
> As we disscussed, it's werid to have such test command in `yurtadm`. We can add the binary into test/e2e which has the ability of starting up an openyurt cluster with kind. For users, we can provide a make target like current `make local-up-openyurt` which will call this binary to start up the openyurt clusters, hence no influence will be imposed on users. For e2e test, we can still use the existing scripts [run-e2e-test.sh](https://github.com/openyurtio/openyurt/blob/master/hack/make-rules/run-e2e-tests.sh), which may not be affected by this change.
> 
> @YTGhost @rambohe-ch what do you think?

It's a good idea, agree + 1
