### ISSUE TITLE
[Question]请问yurthub 会通过yurt-tunnel 访问控制面吗

### ISSUE THREAD

**Issue by ghtian123** [openyurtio/openyurt#1064]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
请问边缘节点访问中心端，会走yurt-tunnel 吗？

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`)
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by ghtian123** [comment]
@rambohe-ch @denverdino

**Comment by rambohe-ch** [comment]
@ghtian123 yurthub目前不会走yurt-tunnel，而是直接通过http/2访问控制面。

**Comment by ghtian123** [comment]
> @ghtian123 yurthub目前不会走yurt-tunnel，而是直接通过http/2访问控制面。

后续是否会考虑这个功能

**Comment by rambohe-ch** [comment]
> > @ghtian123 yurthub目前不会走yurt-tunnel，而是直接通过http/2访问控制面。
> 
> @rambohe-ch 后续是否会考虑这个功能

@ghtian123 嗯，英雄所见略同，后续会规划这块的能力，能力会在raven项目上承载。

**Comment by rambohe-ch** [comment]
@ghtian123 i think that your question has been solved, so i will close this issue. and you can feel free to reopen this issue if you need.
