### ISSUE TITLE
[feature request]move scattered controllers into yurt-manager

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1067]
**What would you like to be added**:
As we have discussed on the community meeting, in order to improve the management of all repos in OpenYurt, and reduce the complexity of deploying OpenYurt. we will create a new component named `yurt-manager` for managing all controllers and webhooks. so we will move controllers in `raven-controller-manager`, `yurt-app-manager`, `yurt-controller-manager`, even `yurt-edgex-manager` into `yurt-manager` component.

After controllers and webhooks unify, only three components(yurt-manager, raven, yurthub) should be installed for OpenYurt(IoT components(yurt-device-controller) will be managed by yurt-iot-manager controlelr).

so following controllers will be moved into yurt-manager:

| no. | component  | controller/webhook | owner | status |
| ------------- | ------------- | ------------- |------------- |------------- |
| 1 | yurt-controller-manager  | csr approver  | @rambohe-ch | pr merged |
| 2 | yurt-controller-manager  | daemon pod updater  | @xavier-hou | pr merged |
| 3 | yurt-controller-manager  | pool-coordinator cert manager | @luc99hen | pr merged |
| 4 | yurt-controller-manager  | pool-coordinator delegate lease | @gnunu | pr merged |
| 5 | yurt-controller-manager  | pool-coordinator pod binding | @LindaYu17 | pr merged |
| 6 | yurt-controller-manager  | service topology | @YTGhost  | |
| 7 | yurt-app-manager  | nodepool(include webhook) | @kadisi | pr merged |
| 8 | yurt-app-manager  | yurtappset(include webhook) | @huiwq1990 | pr submitted |
| 9 | yurt-app-manager  | yurtappdaemon(include webhook) | @theonefx  | pr submitted |
| 10 | yurt-app-manager  | static pod updater | @xavier-hou | pr merged |
| 11 | raven-controller-manager | gateway controller| @DrmagicE | pr merged |
| 12 | raven-controller-manager | dns controller| @River-sh | NA |
| 13 | raven-controller-manager | service controller| @River-sh | NA |
| 14 | yurt-iot-manager | yurtiotmanager(include webhook) |  @Rui-Gan | NA |
| 15 | yurt-device-controller | device controller in edge side |  @wawlian | NA |
| 16 | - | nodepool autonomy |  @JameKeal | pr merged |

if anyone have interest to migrate above controllers into yurt-manager, please reply in this issue and let me know which controller you will take over. 

**Why is this needed**:
1. improve the management of all repos in OpenYurt, reduce the number of repos in OpenYurt community.
2. reduce the complexity of installation OpenYurt

**Plan**:

Now, OpenYurt v1.2 has been released, and we will complete these works in OpenYurt v1.3. After yurt-manager component completed, original components(like yurt-controller-manager, yurt-app-manager, raven-controller-manager) will be removed.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@JcJinChen @kadisi

**Comment by rambohe-ch** [comment]
we should make sure that `k8s.io/kubernetes` package will not be imported into `Yurt-Controller-Manager` when migrating controllers.

**Comment by kadisi** [comment]
/assign @kadisi 

I will design a new framework for controller and webhook based on the Controller-Runtime package, put it in the cmd directory, and then all the controller logic will be put in this framework。 cc @rambohe-ch

**Comment by xavier-hou** [comment]
@rambohe-ch I wanna to take migration tasks about daemon pod updater and static pod updater.

**Comment by River-sh** [comment]
I will  take migration tasks about dns controller and service controller (no. 14 and no. 15)

**Comment by rambohe-ch** [comment]
i will handle the `csr approver controller` migration(no. 1)

**Comment by gnunu** [comment]
We can take 4 and 5:
4 | yurt-controller-manager | pool-coordinator delegate lease
5 | yurt-controller-manager | pool-coordinator pod binding

**Comment by huiwq1990** [comment]
i will take `yurtappset(include webhook)`

**Comment by DrmagicE** [comment]
i will handle the `gateway controller` migration(no. 13)

**Comment by YTGhost** [comment]
Maybe I can take the `service topology`(no. 6)

**Comment by theonefx** [comment]
i will take `yurtappdaemon` (no. 10)

**Comment by LavenderQAQ** [comment]
Information about the controller combination work of the OpenYurt IoT-sig

no. | component | controller/webhook | owner
-- | -- | -- | --
16 | yurt-iot-manager | yurtiotmanager(include webhook) |  
17 | yurt-device-controller | device controller in edge side |  @wawlian

**Comment by Rui-Gan** [comment]
I will handle the yurt-iot-manager(include webhook) migration(no. 16)
