### ISSUE TITLE
[Question] Is the prometheus tutorial suitable for the current version? Cloud you please update it?

### ISSUE THREAD

**Issue by ccjjxx99** [openyurtio/openyurt#1086]
**What happened**:
I checked out this tutorial when I wanted to deploy prometheus to an openyurt cluster: https://openyurt.io/zh/docs/user-manuals/monitoring/prometheus/ . I found that `kubectl edit servicemonitor prom-kube-prometheus-stack-node-exporter` returns `Error from server (NotFound): servicemonitors.monitoring.coreos.com "prom-kube-prometheus-stack-node-exporter" not found
`. 
I checked out the servicemonitor using `kubectl get servicemonitor` and it returns `No resources found in default namespace.`
I think we should look for `prom-kube-prometheus-stack-node-exporter` in the `monitoring` namespace, and I found an servicemonitor named `node-exporter`. Is this the right file to change?

**Environment**:
- OpenYurt version: 1.1.0
- Kubernetes version (use `kubectl version`): 1.22.8

**others**
/kind question

**Comment by ccjjxx99** [comment]
By the way, to change coredns config, you gave the command `kubectl patch deployment coredns -n kube-system -p ...`. 
But the coredns is deployed by daemonset following your tutorial of openyurt setup, so the command needs to change to `kubectl patch ds coredns -n kube-system -p ...`.

**Comment by River-sh** [comment]
Hi, we have added raven component in the latest release to enable communication across network areas, installing and using prometheus in openyurt will be as simple as in kubernetes, you can refer to the openyurt documentation (v1.2+) and try out.

**Comment by rambohe-ch** [comment]
@ccjjxx99 please excuse for my late reply, prometheus tutorial is updated, please take a took.
https://openyurt.io/docs/user-manuals/monitoring/prometheus

btw: i will close this issue, and you can feel free to reopen this issue or create other new issues.

**Comment by ZhangShangyu** [comment]
> @ccjjxx99 please excuse for my late reply, prometheus tutorial is updated, please take a took. https://openyurt.io/docs/user-manuals/monitoring/prometheus
> 
> btw: i will close this issue, and you can feel free to reopen this issue or create other new issues.

hello, may i ask how to implement pull edge pods metrics? 
in the doc example is kubelet which can access by node host, then how about the pod ip?

**Comment by rambohe-ch** [comment]
> > @ccjjxx99 please excuse for my late reply, prometheus tutorial is updated, please take a took. https://openyurt.io/docs/user-manuals/monitoring/prometheus
> > btw: i will close this issue, and you can feel free to reopen this issue or create other new issues.
> 
> hello, may i ask how to implement pull edge pods metrics? in the doc example is kubelet which can access by node host, then how about the pod ip? @rambohe-ch

@ZhangShangyu yes, pod ip and service ip are also supported by raven, please take a try.
