### ISSUE TITLE
[feature request] yurtadm reset caches executable files for user experience

### ISSUE THREAD

**Issue by fujitatomoya** [openyurtio/openyurt#1095]
**What would you like to be added**:

- adding reset flag like `--cache-executable` to save executables such kubeadm, kubelet and kubectl so on.
- this option is `opt-in` option, so that it is effective only if this option is enabled. (keep the current behavior in default)

**Why is this needed**:

this will reduce the time window to complete `yurtadm join` in next time after `yurtadm reset` significantly.
according to the use case about the user devices are likely to join and leave the OpenYurt cluster system in edge environment, this will be really helpful to manage the devices.

**others**

actually i am not really sure why these executables need to be removed complete as following.
on the other hand, it sounds reasonable to reap the temporary and configuration data during reset to avoid unexpected behavior for next time to join the cluster.

https://github.com/openyurtio/openyurt/blob/c25be06cb4ae034038bc5b501e23356fa7941dc6/pkg/yurtadm/cmd/reset/phases/cleanyurtfile.go#L28-L49

**Implementation Consideration**

This could be really straight-forward to add the new flag option in,

https://github.com/openyurtio/openyurt/blob/c25be06cb4ae034038bc5b501e23356fa7941dc6/pkg/yurtadm/cmd/reset/reset.go#L66

take it effect during reset to see if it needs to keep the executable binaries as it is or not.

What needs to be cached needs to be discussed with mainline.
As far as i can see, all executable files as followings would be able to be cached.

- kubeadm, kubectl and kubelet
- all binaries under `/opt/cni/bin`

any thoughs?

/kind feature

**Comment by fujitatomoya** [comment]
CC: @Windrow @FengGaoCSC

**Comment by Windrow14** [comment]
The `tar.gz` files are downloaded to `/tmp` by `yurtadm`, maybe we can save them and their version to somewhere else?

By the way, downloading these binaries to local during using `yurtadm`, unlike downloading with `wget`, does not reconnect when network is unstable, it returns immediately. This is also annoying.

```
I1205 12:50:11.048345  644427 util.go:105] Check and install kubelet v1.22.16
I1205 12:50:11.048606  644427 util.go:129] Download kubelet from: https://dl.k8s.io/v1.22.16/kubernetes-node-linux-arm64.tar.gz
 66.42 MiB / 104.52 MiB [===============================================================================================>------------------------------------------------------]  63.55% 388.22 KiB/s 01m40s
Error: error execution phase initialize: Download kubelet fail: Get "https://dl.k8s.io/v1.22.16/kubernetes-node-linux-arm64.tar.gz": proxyconnect tcp: dial tcp xx.xx.xx.xx:xxxxx: connect: connection refused
```

**Comment by rambohe-ch** [comment]
@YTGhost Do you have any comments about this feature request?

**Comment by rambohe-ch** [comment]
> The `tar.gz` files are downloaded to `/tmp` by `yurtadm`, maybe we can save them and their version to somewhere else?
> 
> By the way, downloading these binaries to local during using `yurtadm`, unlike downloading with `wget`, does not reconnect when network is unstable, it returns immediately. This is also annoying.
> 
> ```
> I1205 12:50:11.048345  644427 util.go:105] Check and install kubelet v1.22.16
> I1205 12:50:11.048606  644427 util.go:129] Download kubelet from: https://dl.k8s.io/v1.22.16/kubernetes-node-linux-arm64.tar.gz
>  66.42 MiB / 104.52 MiB [===============================================================================================>------------------------------------------------------]  63.55% 388.22 KiB/s 01m40s
> Error: error execution phase initialize: Download kubelet fail: Get "https://dl.k8s.io/v1.22.16/kubernetes-node-linux-arm64.tar.gz": proxyconnect tcp: dial tcp xx.xx.xx.xx:xxxxx: connect: connection refused
> ```

@Windrow14 `yurtadm join` recently has been refactored by @YTGhost in this pull request: https://github.com/openyurtio/openyurt/pull/1049

and `kubeadm/kubelet` will be download from this link: https://dl.k8s.io/release/v1.22.16/bin/linux/amd64/kubeadm{kubelet}. 
meanwhile, if `kubeadm/kubelet` are prepared on the node, `yurtadm join` will not download these binaries. the code reference is here: https://github.com/openyurtio/openyurt/blob/master/pkg/yurtadm/util/kubernetes/kubernetes.go#L115-L127

**Comment by rambohe-ch** [comment]
@fujitatomoya plus comment for cni binary, because we can not check the version of cni binaries, so how to process cni binary maybe need more discussion. 

I think we need to open a way for end user to prepare cni binary beforehand, and can keep cni binaries unremoved when run `yurtadm reset`. @YTGhost  would you like to give comments about cni binaries?

**Comment by YTGhost** [comment]
> @fujitatomoya Thank you for raising issue. because `yurtadm join` will check if `kubeadm/kubelet` version is suitable when joining nodes. and if binary version is not suitable, new binary will be download from official website. so maybe we can keep `kubeadm/kubectl/kubelet` binary on the node as a default action in `yurtadm reset` command.

@rambohe-ch Yes, I think we can keep these binary files by default, and subsequently if the user calls `yurtadm join` to connect to another version of the Kubernetes cluster, the existing code logic will also go back to pulling the corresponding version of the binary file to replace it.

**Comment by YTGhost** [comment]
> @fujitatomoya plus comment for cni binary, because we can not check the version of cni binaries, so how to process cni binary maybe need more discussion.
> 
> I think we need to open a way for end user to prepare cni binary beforehand, and can keep cni binaries unremoved when run `yurtadm reset`. @YTGhost would you like to give comments about cni binaries?

@rambohe-ch In `yurtadm reset`, `/opt/cni/bin` is removed at the end, but not in `kubeadm reset`. Maybe we can keep `/opt/cni/bin` and give the user a flag to configure the cni plugins version (in the current logic, it's fixed to v0.8.0)

**Comment by rambohe-ch** [comment]
> > @fujitatomoya plus comment for cni binary, because we can not check the version of cni binaries, so how to process cni binary maybe need more discussion.
> > I think we need to open a way for end user to prepare cni binary beforehand, and can keep cni binaries unremoved when run `yurtadm reset`. @YTGhost would you like to give comments about cni binaries?
> 
> @rambohe-ch In `yurtadm reset`, `/opt/cni/bin` is removed at the end, but not in `kubeadm reset`. Maybe we can keep `/opt/cni/bin` and give the user a flag to configure the cni plugins version (in the current logic, it's fixed to v0.8.0)

@YTGhost @fujitatomoya As discussed above, i'd like to write a summary for improving yurtadm:
1.  yurtadm join: 
  - add a new parameter(like reuse-cni-bin) to specify whether reuse local cni binaries or not, default value is `false`, specify not to reuse cni binaries. if end user want to reuse cni, they should specify `--reuse-cni-bin=true` explicitly.
 
2. yurtadm reset:
 - do not remove `kubeadm/kubectl/kubelet` and `cni binaries`

**Comment by YTGhost** [comment]
> > > @fujitatomoya plus comment for cni binary, because we can not check the version of cni binaries, so how to process cni binary maybe need more discussion.
> > > I think we need to open a way for end user to prepare cni binary beforehand, and can keep cni binaries unremoved when run `yurtadm reset`. @YTGhost would you like to give comments about cni binaries?
> > 
> > 
> > @rambohe-ch In `yurtadm reset`, `/opt/cni/bin` is removed at the end, but not in `kubeadm reset`. Maybe we can keep `/opt/cni/bin` and give the user a flag to configure the cni plugins version (in the current logic, it's fixed to v0.8.0)
> 
> @YTGhost @fujitatomoya As discussed above, i'd like to write a summary for improving yurtadm:
> 
> 1. yurtadm join:
> 
> * add a new parameter(like reuse-cni-bin) to specify whether reuse local cni binaries or not, default value is `false`(specify not to reuse cni binaries). if end user want to reuse cni, they should specify `--reuse-cni-bin=true` explicitly.
> 
> 2. yurtadm reset:
> 
> * do not remove `kubeadm/kubectl/kubelet` and `cni binaries`
> 
> @YTGhost @fujitatomoya @Windrow14 please comment this summary.

I think that's enough, agree +1

**Comment by fujitatomoya** [comment]
> Yes, I think we can keep these binary files by default, and subsequently if the user calls yurtadm join to connect to another version of the Kubernetes cluster, the existing code logic will also go back to pulling the corresponding version of the binary file to replace it.

this does make sense to me. this can be opt-in by default.

> plus comment for cni binary, because we can not check the version of cni binaries, so how to process cni binary maybe need more discussion.

according to the implementation, yuradm join will down load the all binaries if the folder does not exist. It does not check the version at all, only checks if `/opt/cni/bin` exists or not.

all binaries are stored under https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-amd64-v0.8.0.tgz .

probably we would want to add the version file above download link and check if the current binaries are expected version or not. and if not, we can install all required binaries over that folder. this will request the change for https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com server, instead we cannot do this.

**Comment by fujitatomoya** [comment]
either @Windrow14 or @FengGaoCSC, you want to take this over? i would not have much bandwidth for the verification in short time.

**Comment by rambohe-ch** [comment]
> > Yes, I think we can keep these binary files by default, and subsequently if the user calls yurtadm join to connect to another version of the Kubernetes cluster, the existing code logic will also go back to pulling the corresponding version of the binary file to replace it.
> 
> this does make sense to me. this can be opt-in by default.
> 
> > plus comment for cni binary, because we can not check the version of cni binaries, so how to process cni binary maybe need more discussion.
> 
> according to the implementation, yuradm join will down load the all binaries if the folder does not exist. It does not check the version at all, only checks if `/opt/cni/bin` exists or not.
> 
> all binaries are stored under https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-amd64-v0.8.0.tgz .
> 
> probably we would want to add the version file above download link and check if the current binaries are expected version or not. and if not, we can install all required binaries over that folder. this will request the change for https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com server, instead we cannot do this.

@fujitatomoya In fact, we have improved the native cni for keeping PodIP(detail info is here: https://openyurt.io/docs/user-manuals/network/edge-pod-network), and the cni binaries: https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-amd64-v0.8.0.tgz has included the improved working. 

maybe it's a tough work to maintain all versions of cni binaries, and `https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-amd64-v0.8.0.tgz` is only a default option, and end user can use `--reuse-cni-bin`(need to add) to overwrite the default cni binaries.

so how about leave the version check of cni binaries to end user? this means end users should make sure the correct version of cni binaries they use.  and we only add a new parameter(like `--reuse-cni-bin`) for end user to use the customized cni binaries.

**Comment by fujitatomoya** [comment]
> In fact, we have improved the native cni for keeping PodIP(detail info is here: https://openyurt.io/docs/user-manuals/network/edge-pod-network),

thanks for elaborating the reason we have these CNI implementation for OpenYurt users.
i see this makes sense, since it is likely that network between cloud and edge could be unstable, this feature is required in CNI implementation to cache the configuration via reboot.
so that everything in edge environment can work as it was before reboot.

> how about leave the version check of cni binaries to end user?

makes sense. it will be hard to guarantee versions for each CNI implementation anyway.
so that we can provide this option for user, and saying it is user responsibility to use this option.

**Comment by rambohe-ch** [comment]
@fujitatomoya @Windrow14 @FengGaoCSC would you like to take over this work to improve `yurtadm join/reset` command?

**Comment by fujitatomoya** [comment]
> would you like to take over this work to improve yurtadm join/reset command?

yeah happy to, either me or @Windrow14 / @FengGaoCSC will take this over, thanks for iterating with us.
