### ISSUE TITLE
[feature request] Enhancement of NodePool Coordinator Functions

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [openyurtio/openyurt#1101]
I am a production user of Openyurt, and I have been supporting the application of Openyurt ecological components in edge computing scenarios. I will optimize the performance of cloud-edge network communication in the future. It is a great honor to have the opportunity to cooperate with you.

Scene data: 500 nodes, 17k pods. Cloud edge network bandwidth is about 50Kbit/s

During the previous landing process, it was found that during the initialization process of the edge machine, the network components required a large amount of list-watch resources, and these resources could not be returned for a long time due to bandwidth limitations, resulting in watch failures, edge-side program retries, and full bandwidth .

I think that if there is a full resource cache (including native resources and CR) at the node pool granularity on the edge side, and the edge side machine first queries the cache, and synchronizes resources to the edge cache with a small amount of bandwidth overhead. This can greatly improve the resource consumption of the cloud-side network.

This idea is similar to the Coordinator being developed by the community. Currently, the Coordinator is under development and temporarily supports the offline cache of Endpoints and Endpointslice resources.

I am very interested in this component and have three desired capabilities:

1. It can support custom resources and full resources through configuration
2. Even if the network is healthy, you can reuse long links on the cloud side as much as possible instead of direct forwarding, reducing the number of connections and concurrent watches of same resources.
3. You can configure resource limits individually for nodes with large resource consumption (such as the yurthub static pod where the coordinator resides).

Hope to discuss and build together with you.

我是 Openyurt 生产落地用户，一直在支持 Openyurt 生态组件在边缘计算场景的应用，后续会重点关注针对云边网络通信的带宽优化。

场景数据：500 node，17k pods。云边网络带宽约为 50Kbit/s

在之前的落地过程中，发现了在边缘机器的初始化过程，网络组件需要 list-watch 大量资源，而这些资源由于带宽限制长时间无法回传，导致 watch 失败，边缘侧程序重试，带宽打满。

我认为如果边缘侧可以存在节点池粒度的全量资源缓存（其中包括原生资源和CR），而边缘侧机器优先查询缓存，通过少量的带宽开销，将资源同步至边缘缓存。就能极大提升云边网络资源消耗。
![image](https://user-images.githubusercontent.com/45508533/207830275-59c83449-5321-4388-8458-e70d79524d56.png)

这一思路和社区正在开发的 Coordinator 类似。目前Coordinator 正在开发中，暂时支持 Endpoints，Endpointslice 资源的断网缓存。

我对这个组件很感兴趣，并有三点期望的能力：

1. 可通过配置支持自定义资源、全量资源
2. 即使网络健康，可以尽可能复用云边长链接，而非直接转发，降低连接数、降低单一资源的并发watch。
3. 可以针对资源消耗较大的节点（例如coordinator 所在的yurthub静态pods），单独配置资源限制。

希望能与大家一起讨论，一起建设。

**Comment by rambohe-ch** [comment]
@LaurenceLiZhixin Thank you for raising issue about reducing public network traffic through sharing native resources in the nodePool.
I think we can discuss these requirements on the community meeting on next Wednesday. by the way, pool-coordinator maybe is satisfied for the second requirement.
