### ISSUE TITLE
[BUG] yurtadm join fails with k8s version 1.19.4

### ISSUE THREAD

**Issue by YTGhost** [openyurtio/openyurt#1102]
**What happened**:
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/40822107/208364929-cdbf5d99-7626-469a-b541-3fd088e3702f.png">
When we use k8s version v1.19.4, yurtadm join will fail

**What you expected to happen**:
yurtadm join has no exceptions and can join nodes smoothly

**How to reproduce it (as minimally and precisely as possible)**:
When refactoring the yurtadm join, we constructed the `JoinConfiguration` file as the configuration file for calling `kubeadm`, which `apiVersion` is `kubeadm.k8s.io/v1beta3`. According to https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/, `v1beta3` is only supported for v1.22.x and above.

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):v1.19.4
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by YTGhost** [comment]
@rambohe-ch I think we need to switch the `apiVersion` of the `JoinConfiguration` file to `v1beta2` so that it supports v1.15.x and above, WDYT?
Another question is whether we still need to be compatible with k8s below v1.15.x. If so, perhaps we should dynamically switch the `apiVersion` used depending on the k8s version of the cluster.

**Comment by rambohe-ch** [comment]
> @rambohe-ch I think we need to switch the `apiVersion` of the `JoinConfiguration` file to `v1beta2` so that it supports v1.15.x and above, WDYT? Another question is whether we still need to be compatible with k8s below v1.15.x. If so, perhaps we should dynamically switch the `apiVersion` used depending on the k8s version of the cluster.

@YTGhost I think we only need to support K8s with versions larger than v1.18, and don't need to consider any smaller version.

maybe it's a good idea to switch the apiVersion of JoinConfiguration according to K8s version.
