### ISSUE TITLE
[BUG] Init

### ISSUE THREAD

**Issue by 1486756632** [openyurtio/openyurt#1106]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by 1486756632** [comment]
i git project.when i do make command.it fail.
![lALPJu1c4yLwmmnNAxjNBbI_1458_792 png_620x10000q90](https://user-images.githubusercontent.com/51595387/209311824-e48e981a-58ba-4882-9432-81aa93d395fb.jpg)

![lALPJu1c4yLvN6bNAdzNAuE_737_476 png_620x10000q90](https://user-images.githubusercontent.com/51595387/209311811-30a2437d-e6f7-4587-9ed3-68dd54a0aa22.jpg)

**Comment by rambohe-ch** [comment]
@kadisi PTAL

**Comment by rambohe-ch** [comment]
@1486756632 Thanks for raising issue. it looks like that compile yurtadm caused this error, @YTGhost would you be able to take a look this issue?

**Comment by YTGhost** [comment]
@1486756632 This problem should have been solved, you can try pulling the latest code and try again.
