### ISSUE TITLE
[BUG] flush kube-proxy entries in nat table in edge-autonomy e2e test

### ISSUE THREAD

**Issue by Congrool** [openyurtio/openyurt#1109]
**What happened**:

Currently we use `iptables -F` in edge autonomy test when testing kube-proxy. However, it defaultly flush the filter table while kube-proxy mainly uses nat table for service discovery. So, we need to clean the nat table instead. 

We may also not flush the whole nat table, because there're not only rules set by kube-proxy but also other components like flannel, which will not be recreate through restarting kube-proxy.
```plain-text
Chain FLANNEL-POSTRTG (1 references)
target     prot opt source               destination         
RETURN     all  --  10.244.0.0/16        10.244.0.0/16        /* flanneld masq */
MASQUERADE  all  --  10.244.0.0/16       !base-address.mcast.net/4  /* flanneld masq */ random-fully
RETURN     all  -- !10.244.0.0/16        10.244.2.0/24        /* flanneld masq */
MASQUERADE  all  -- !10.244.0.0/16        10.244.0.0/16        /* flanneld masq */ random-fully
```

As a solution, we can only clean the nat rules of the service we will test.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@Congrool yes, we need to tune `iptables -F` command to cleanup nat rules only for autonomy test. would you be able to take this work?

**Comment by Congrool** [comment]
sure, I'll fix it.

/assign
