### ISSUE TITLE
[Question] The purpose that modify startup parameters --kubelet-preferred-address-types=Hostname,InternalIP,ExternalIP

### ISSUE THREAD

**Issue by FengGaoCSC** [openyurtio/openyurt#1113]
**What happened**:
According https://openyurt.io/docs/installation/openyurt-prepare/#3-kube-apiserver-adjustment
```
To make sure kube-apiserver on the master node use hostname:port to access kubelet, and at the same time this hostname resolution request should be handled by yurt-tunnel-dns pod. We should apply some adjustments to kube-apiserver configurations.

We assume your kube-apiserver is installed through static pod(/etc/kubernetes/manifests/kube-apiserver.yaml)

modifiy dnsPolicy="None"
add dnsConfig configurations which set the nameservers as the clusterIP of yurt-tunnel-dns service (assumed to be 1.2.3.4 here)
modify startup parameters --kubelet-preferred-address-types=Hostname,InternalIP,ExternalIP, to make sure that Kube-apiserver prefers to use Hostname to access kubelet
```
that this guide modify the startup paramters --kubelet-preferred-address-types=Hostname,InternalIP,ExternalIP, seems that OpenYurt uses hostname to resolve Node IP to see if the communication is via tunneling or not.

But this should be able to fallback to use Internal IP registered as cluster node, Do we need to reorder `-kubelet-preferred-address-types=Hostname,InternalIP,ExternalIP`, I am not very sure about this. since on the ubuntu distribution on the /etc/hosts. it may include `127.0.1.1 Hostnamexxx` like, then when we to modify the startup paramter --kubelet-preferred-address-types=Hostname on the first position, it will cause the tunnel dns using that IP of 127.0.1.1 and tunnel cannot be established .

**What you expected to happen**:
Could you explain if we should reorder  `-kubelet-preferred-address-types=Hostname,InternalIP,ExternalIP` as Must?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by Congrool** [comment]
In my mind, it's not the hard requirement, since yurt-tunnel also supports IP mode, which using node ip to establish the tunnel between cloud and edge and do not need to modify the parameter of kube-apiserver.

However, it has a main drawback of this way that it cannot solve the node ip conflict. Because we may have nodes behind multiple NATs, which may have overlapped subnet IPs. Tunnel-Server cannot distinguish node IPs across these subnets. To overcome such problem, we recommend using dns mode because the node name is unique among the cluster.

**Comment by rambohe-ch** [comment]
@FengGaoCSC we are merging yurt-tunnel into raven project, and this work will take community some time.

The progress you can look the link here: https://github.com/orgs/openyurtio/projects/9

**Comment by fujitatomoya** [comment]
> However, it has a main drawback of this way that it cannot solve the node ip conflict. Because we may have nodes behind multiple NATs, which may have overlapped subnet IPs. Tunnel-Server cannot distinguish node IPs across these subnets. To overcome such problem, we recommend using dns mode because the node name is unique among the cluster.

makes sense :+1:

**Comment by FengGaoCSC** [comment]
> @FengGaoCSC we are merging yurt-tunnel into raven project, and this work will take community some time.
> 
> The progress you can look the link here: https://github.com/orgs/openyurtio/projects/9

Got it and thanks

**Comment by fujitatomoya** [comment]
@FengGaoCSC i think the question has been answered? if that is so, probably we can close this one?

**Comment by FengGaoCSC** [comment]
Answered. Close this issue.
