### ISSUE TITLE
[Question] For pool coordinator feature, why not let yurthub use admin.conf instead of 'pool-coordinator-yurt-hub' cluster role?

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [openyurtio/openyurt#1129]
The pool coordinator and yurthub are our own components, so letting yurthub use admin.conf would will be very convenient :
1. Omit the step of initializing the pool-coordinator-yurt-hub clusterrole to the pool-coordinator
2. We can cache any resource without any additional permission configuration.

**Comment by rambohe-ch** [comment]
> The pool coordinator and yurthub are our own components, so letting yurthub use admin.conf would will be very convenient :
> 
> 1. Omit the step of initializing the pool-coordinator-yurt-hub clusterrole to the pool-coordinator
> 2. We can cache any resource without any additional permission configuration.

@LaurenceLiZhixin Thank you for raising issue to discuss client certificates for pool-coordinator. and i agree with you that yurthub use admin.conf to access pool-coordinator is more convenient.

@luc99hen please give some comments?

**Comment by rambohe-ch** [comment]
@LaurenceLiZhixin This issue looks like that has been fixed. please close this issue.
