### ISSUE TITLE
[Question] Setup OpenYurt on k3s

### ISSUE THREAD

**Issue by batthebee** [openyurtio/openyurt#1150]
**What happened**:

I'm trying to install openyurt on k3s, but fail already with the configuration of the kube-api server. K3s integrates the kube-apiserver as a separate process in the k3s binary and not as a pod. So I can not set separate dns settings. 

To configure the kube-api-server for openyurt I have the option to either configure the kube-api-server via commandline args, disable it completely and deploy it myself, or customize the host system, e.g. with my own DNS server.

How would you proceed?  

In case kube-api-server should be deployed by my self: I haven't found any instructions for this anywhere. Can I just take any one?

/kind question

**Comment by batthebee** [comment]
After a few modifications everything seems to run on the masternode. The adjustments were not necessary for the time being. Now I want to install the yurthub on the nodes. Thereby a token is requested. What exactly must it be able to do? Can I create one myself for this?

K3s has a shared token with its own authentication. Is a different mechanism like in kubeadm. Don't think this is the right one.

**Comment by batthebee** [comment]
I have found some additional infos. https://stackoverflow.com/questions/58695172/what-is-cluster-info-configmap-in-tls-bootstrap-in-k8s 

Seems openyurt heavily rely on kubeadm join process, right? Maybe that should be added to docs as a requirement.
So, whats needed to work with distributions like k3s/rke2/talos ?

**Comment by rambohe-ch** [comment]
@batthebee The destination for configuring dns setting of kube-apiserver is to make the traffic from kube-apiserver to kubelet can go through yurt-tunnel, because edge nodes usually have no public IP, and kube-apiserver can not connect with kubelet on edge nodes directly.

but In OpenYurt v1.2(will be released soon), we will use raven(openyurtio/raven) to replace yurt-tunnel, raven is a very elegant communication solution across network domains. and kube-apiserver don't need to re-configured, and traffic from kube-apiserver to kubelet on edge nodes will pass through raven unwarenessly.

**Comment by rambohe-ch** [comment]
> I have found some additional infos. https://stackoverflow.com/questions/58695172/what-is-cluster-info-configmap-in-tls-bootstrap-in-k8s
> 
> Seems openyurt heavily rely on kubeadm join process, right? Maybe that should be added to docs as a requirement. So, whats needed to work with distributions like k3s/rke2/talos ?
> 
> At first glance it looks to me like the token is only used for initial validation. That means, a switch between kubeadm and e.g. k3s would be needed?!

@batthebee yes, `yurtadm join` will call `kubeadm join` to join edge nodes into cluster. and for edge nodes join, @YTGhost maybe can give some comments.

**Comment by YTGhost** [comment]
> I have found some additional infos. https://stackoverflow.com/questions/58695172/what-is-cluster-info-configmap-in-tls-bootstrap-in-k8s
> 
> Seems openyurt heavily rely on kubeadm join process, right? Maybe that should be added to docs as a requirement. So, whats needed to work with distributions like k3s/rke2/talos ?
> 
> At first glance it looks to me like the token is only used for initial validation. That means, a switch between kubeadm and e.g. k3s would be needed?!

Yes, currently `yurtadm join` relies on `kubeadm join`, I'm not familiar with `k3s`, maybe we should adapt it for distributions like k3s/k0s, e.g. users can specify `kubeadm driver`, `k3s driver`, etc.? WDYT @rambohe-ch

**Comment by batthebee** [comment]
@YTGhost @rambohe-ch  Support for rke2 or k3s would be great. In conjunction with e.g. rancher it would simplify the management of openyurt clusters significantly. For production use, I'm a little bit afraid to maintain kubeadm clusters by hand.

I would be happy to assist with the implementation of any of the above distributions. You guys would just have to give me a little jump start. What do you think?

I've had a little look at yurthub's source code and also looked into what k3s is doing, but can't get it together at the moment.

**Comment by rambohe-ch** [comment]
> > I have found some additional infos. https://stackoverflow.com/questions/58695172/what-is-cluster-info-configmap-in-tls-bootstrap-in-k8s
> > Seems openyurt heavily rely on kubeadm join process, right? Maybe that should be added to docs as a requirement. So, whats needed to work with distributions like k3s/rke2/talos ?
> > At first glance it looks to me like the token is only used for initial validation. That means, a switch between kubeadm and e.g. k3s would be needed?!
> 
> Yes, currently `yurtadm join` relies on `kubeadm join`, I'm not familiar with `k3s`, maybe we should adapt it for distributions like k3s/k0s, e.g. users can specify `kubeadm driver`, `k3s driver`, etc.? WDYT @rambohe-ch

@YTGhost yes, maybe we can add a new parameter(like --driver) for `yurtadm join` command in order to use different node bootstrap mode.

**Comment by rambohe-ch** [comment]
> @YTGhost @rambohe-ch Support for rke2 or k3s would be great. In conjunction with e.g. rancher it would simplify the management of openyurt clusters significantly. For production use, I'm a little bit afraid to maintain kubeadm clusters by hand.
> 
> I would be happy to assist with the implementation of any of the above distributions. You would just have to give me a little jump start. What do you think?
> 
> I've had a little look at yurthub's source code and also looked into what k3s is doing, but can't get it together at the moment.

@batthebee how about start from integrating OpenYurt into K3s cluster at first?

**Comment by batthebee** [comment]
@rambohe-ch You got that exactly right. 

Whether keadm, k3s, rke2, talos etc. doesn't really make much difference. As far as I can see, they all implement their own bootstrap mechanism. kubeadm uses the official proposal with cluster-info cm etc. (was also developed for kubeadm) k3s/rke2 uses its own bootstrap mechanism with a shared token. 

But there is something going on in k3s right now (and thus probably in rke2). I would wait for the PR and see if this works out-of-the-box: https://github.com/k3s-io/k3s/pull/6663

**Comment by drinktee** [comment]
How about run k3s as a edge node for openyurt, and join a k8s cluster?

**Comment by rambohe-ch** [comment]
> How about run k3s as an edge node for openyurt, and join a k8s cluster?

@drinktee agree +1. I think it's a interesting idea to join k3s as an edge node because it looks like that k3s is a lite solution for edge devices.
