### ISSUE TITLE
[feature request] Bump golang from 1.16 to 1.17

### ISSUE THREAD

**Issue by YTGhost** [openyurtio/openyurt#1190]
**What would you like to be added**:

**Why is this needed**:
fix #1059 need to bump ginkgo from 2.1.4 to 2.8.0, ginkgo's dependencies require go1.17.

**others**
/kind feature

**Comment by YTGhost** [comment]
Is there any obstacle to upgrading go version to 1.17? @rambohe-ch

**Comment by rambohe-ch** [comment]
> Is there any obstacle to upgrading go version to 1.17? @rambohe-ch

@YTGhost Thank you for raising issue. There is no obstacle to upgrading go version to 1.17, and in fact, we have used golang v1.17 to build OpenYurt components. take yurthub as a example: https://github.com/openyurtio/openyurt/blob/master/hack/dockerfiles/Dockerfile.yurthub#L3

would you be able to make a pull request to upgrade go version to 1.17?
