### ISSUE TITLE
[feature request] `NodePool Governance Capability`: pool-coordinator controller need to deal with a sence that nodepool disconnect with cloud

### ISSUE THREAD

**Issue by JameKeal** [openyurtio/openyurt#1197]
**What would you like to be added**:
pool-coordinator controller need to deal a sence when nodepool disconnect with cloud, the node in nodepool can be autonomy, the pod in node cannot be evict.

- node actually down, close the node autonomy, the pod binding controller cannot use, the pod in node can be evict.
- nodepool disconnect cloud, controller can add node autonomy for nodepool, then the pod binding controller will working, k8s cannot evict the pod.

**Why is this needed**:
On the current situation, when nodepool disconnect with cloud, if node does not open autonomy, the pod in node wil be evict. In another way, if the node open autonomy, when node actually down, the pod binding controller will not evict the pod, it`s different from nodepool governance.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@JameKeal Thank you for raising issue. yes, we need to consider how to handle pods eviction when the network between cloud and all nodes in nodePool disconnected. I think we need to keep the pods un-evicted at that time.

**Comment by rambohe-ch** [comment]
@gnunu @LindaYu17 do you have any comments?

**Comment by AndyEWang** [comment]
Any progress? Should nodelifecycle be considered since zone disruption can make the minimal change to handle this case. (refer to partialDisruption and FullDisruption in kube node lifecycle controller)

**Comment by rambohe-ch** [comment]
> Any progress? Should nodelifecycle be considered since zone disruption can make the minimal change to handle this case. (refer to partialDisruption and FullDisruption in kube node lifecycle controller)

@AndyEWang Do you have any suggestions how to integrate `original partialDisruption and FullDisruption` into `NodePool` in OpenYurt?

**Comment by gnunu** [comment]
Remember we talked about this issue during our earlier discussion about pool coordinator design, then we decided to let apiserver decide what to do when whole pool is lost. 

However it's natural that pods should not be evicted on pool disconnection occurring. Anyway pool should be in automate mode if pods are pool binding. So the implementation should take care of this requirement.

How about we add this capability during our migration to yurt-controller?

**Comment by AndyEWang** [comment]
Personally, OpenYurt can take charge of node lifecycle like old versions before v1.2. If not, we must find out many workarounds against kube-controller-manager. Should OpenYurt give an option to let users decide which node lifecycle to use?

**Comment by rambohe-ch** [comment]
> Personally, OpenYurt can take charge of node lifecycle like old versions before v1.2. If not, we must find out many workarounds against kube-controller-manager. Should OpenYurt give an option to let users decide which node lifecycle to use?

@AndyEWang I think It's not a good idea to maintain two selections for nodelifecycle contorller because it will be very difficult to maintain OpenYurt.

by the way, the original solution also can not satisfy the requirements when nodepool disconnects with cloud kube-apiserver, and we need to add webhooks and controllers to handle nodepool network disconnection too.

**Comment by rambohe-ch** [comment]
> Remember we talked about this issue during our earlier discussion about pool coordinator design, then we decided to let apiserver decide what to do when whole pool is lost.
> 
> However it's natural that pods should not be evicted on pool disconnection occurring. Anyway pool should be in automate mode if pods are pool binding. So the implementation should take care of this requirement.
> 
> How about we add this capability during our migration to yurt-controller?

@gnunu @JameKeal is migrating pull request #1234 which handle this case into yurt-manager.
