### ISSUE TITLE
[Question] Edge cpu and memory footprint optimization in roadmap?

### ISSUE THREAD

**Issue by fujitatomoya** [openyurtio/openyurt#1211]
**What happened**:

I would like to open the question about the subject for edge optimization.
Since OpenYurt is one of the solution for Edge IoT devices with Cloud Native, efficiency and optimization would be huge architecture driver.
I understand that it is always trading-off like `How much we can pay for what?`, but would like to open the discussion and future plan if there is any.

So far I do not see anything related to https://github.com/openyurtio/openyurt/blob/master/docs/roadmap.md

Just FYI, here is the memory footprint so far we checked.

**Environment**:
- OpenYurt version: V1.0.0
- Kubernetes version (use `kubectl version`): v1.22
- OS (e.g: `cat /etc/os-release`): Ubuntu20.04
- Kernel (e.g. `uname -a`): 5.15.0-58-generic

the following checked wit using `crictl status` to see how much memory is consumed by container.

### Cloud Components

Those components should be fine since those are likely running in cloud instance.

| Common or BridgeType | container  name         | MEM(MiB) |  note    |
|:-------------:| :---------------------: |:--------:|:--------:|
|      OpenYurt    | yurt-tunnel-server      | 21.37M    | OpenYurt cloud tunnel server|
|      OpenYurt    | yurt-app-manager        | 22.68M    | OpenYurt cloud app manager|
|      OpenYurt    | yurt-tunnel-dns         | 18.93M    | OpenYurt cloud tunnel dns|
|      OpenYurt    | yurt-controller-manager | 21.76M    | OpenYurt cloud controller manager|

### Edge Components

| Common or BridgeType | container  name         | MEM(MiB) |  note    |
|:-------------:| :---------------------: |:--------:|:--------:|
|      OpenYurt     | yurt-tunnel-agent       | 8.836M    | OpenYurt edge tunnel agent |
|      OpenYurt     | yurt-hub                | 38M       | OpenYurt cloud hub|

38MB could be huge memory for system application, probably build configuration or runtime configuration to reduce memory would be useful.
We do not have exact number as hard requirements, but experience from edge production perspective, this number is huge.
The same question goes to Kubernetes components, but I would like to keep this question dedicated to OpenYurt.

**others**
/kind question

**Comment by rambohe-ch** [comment]
@fujitatomoya Thank you for raising issue. and we recommend end users to prepare edge nodes that have more than 2 CPU core and 4GB memory in order to run system components(like container runtime, kubelet, kube-proxy, yurthub, etc.) and user's workloads. would you be able to provide more information such as actual scenarios?

**Comment by fujitatomoya** [comment]
@rambohe-ch thanks for the comment.

about CPU consumption, we will work on details. currently we can see `yurt-hub` on edge 38MB memory footprint, it would be probably better to be less than 10MB. as I mentioned in this issue, we do not have concrete requirements for now, but having the application running more than 10MB would be really huge for edge IoT devices.

I think it does not have to be pure reduction, but build or runtime option would be really useful to adjust the memory and cpu consumption. e.g) trading-off with feature, we can reduce the memory or cpu consumption via build or runtime option.

**Comment by rambohe-ch** [comment]
> @rambohe-ch thanks for the comment.
> 
> about CPU consumption, we will work on details. currently we can see `yurt-hub` on edge 38MB memory footprint, it would be probably better to be less than 10MB. as I mentioned in this issue, we do not have concrete requirements for now, but having the application running more than 10MB would be really huge for edge IoT devices.
> 
> I think it does not have to be pure reduction, but build or runtime option would be really useful to adjust the memory and cpu consumption. e.g) trading-off with feature, we can reduce the memory or cpu consumption via build or runtime option.

@fujitatomoya yeah, i want to keep this issue and maybe have a try in the future version.

**Comment by fujitatomoya** [comment]
@rambohe-ch thanks for iterating with me. sounds good, you can even assign this to me 👍 we will get more information.

**Comment by fujitatomoya** [comment]
Just FYI. Raven consumes `12.27MiB` via `docker stats`.

```bash
root@cloud141:/home/kube# docker stats | grep raven
CONTAINER ID        NAME                                                                                                         CPU %               MEM USAGE 
......
81ef467de673        k8s_raven-agent_raven-agent-ds-crs8c_kube-system_5912c1bf-724d-44c2-ac56-bcb065ae9d17_0                      0.04%               12.62MiB e8d855883707        k8s_manager_raven-controller-manager-58967476b-wlls9_kube-system_b0409426-9389-4121-bd76-57a025693ce5_4      0.07%               12.27MiB
......
```
