### ISSUE TITLE
[BUG] pool-coordinator isn't rescheduled when its node disconnects from others

### ISSUE THREAD

**Issue by AndyEWang** [openyurtio/openyurt#1212]
**What happened**:
when the node disconnects from all nodes except itself, pool-coordinator in this node cannot be evicted.

**What you expected to happen**:
pool-coordinator should be rescheduled into a healthy node.

**How to reproduce it (as minimally and precisely as possible)**:
just shutdown the node where pool-coordinator is located and the Pod of pool-coordinator won't be rescheduled.

**Anything else we need to know?**:
found that charts/openyurt/templates/pool-coordinator.yaml is configured with
```
            tolerations:
              - effect: NoExecute
                operator: Exists
```

**Environment**:
- OpenYurt version: 1.2
- Kubernetes version (use `kubectl version`): 1.22

/kind bug

**Comment by rambohe-ch** [comment]
@LaurenceLiZhixin @Congrool PTAL

**Comment by Congrool** [comment]
I think we can remove such toleration from pool-coordinator. Would you like to submit a pr? @AndyEWang

**Comment by AndyEWang** [comment]
@Congrool Ok, I will submit one if there is no special case to bind pool-coordinator to a node.
