### ISSUE TITLE
Pod will not be expelled after the cloud node goes down

### ISSUE THREAD

**Issue by henkuaifacai** [openyurtio/openyurt#1253]
大佬，我部署了yurt-app-manager yurt-controller-manager想试下关机后pod的变化，发现不管是不是边缘自治节点上的Pod都不会驱逐，还有你们钉钉的二维码好像是过期了，扫不了，加不了了

`[root@master01 openyurt-helm]# kubectl  get node  --show-labels  | grep node01
node01      NotReady   <none>                 64m   v1.23.8   beta.kubernetes.io/arch=amd64,beta.kubernetes.io/os=linux,kubernetes.io/arch=amd64,kubernetes.io/hostname=node01,kubernetes.io/os=linux,openyurt.io/is-edge-worker=false`

`[root@master01 openyurt-helm]# kubectl  get pod -o wide
NAME                        READY   STATUS    RESTARTS      AGE     IP                NODE        NOMINATED NODE   READINESS GATES
busy-box-5df6cc9447-5k469   1/1     Running   1 (41m ago)   43m     100.108.11.198    node2       <none>           <none>
busy-box-5df6cc9447-b6cc9   1/1     Running   0             45m     100.96.174.132    node03      <none>           <none>
busy-box-5df6cc9447-gzxxh   1/1     Running   1 (41m ago)   45m     100.82.37.199     egde-node   <none>           <none>
**busy-box-5df6cc9447-srj66   1/1     Running   0             4m45s   100.117.144.135   node01      <none>           <none>**`

`[root@master01 openyurt-helm]# kubectl  get pod -n kube-system -o wide | grep yurt 
yurt-app-manager-b8677d956-vncds           1/1     Running   2 (43m ago)    60m   100.108.11.200    node2       <none>           <none>
yurt-controller-manager-7787f67564-rsqcq   1/1     Running   1 (55m ago)    59m   192.168.139.184   node03      <none>           <none>`

**Comment by rambohe-ch** [comment]
@henkuaifacai Thank you for raising issue.

1. which version of OpenYurt have you used?
2. `nodelifecycle` controller of kube-controller-manager component is enabled or not? this controller should be enabled.
3.  ok, we will update dingtalk QR code, @luc99hen

**Comment by henkuaifacai** [comment]
1 yurt-controller-manager:v1.2.0
2 开启和关闭都试过了，还是不行

**Comment by henkuaifacai** [comment]
> @henkuaifacai Thank you for raising issue.
> 
> 1. which version of OpenYurt have you used?
> 2. `nodelifecycle` controller of kube-controller-manager component is enabled or not? this controller should be enabled.
> 3. ok, we will update dingtalk QR code, @luc99hen
配置完之后可以了，感谢
