### ISSUE TITLE
[Question]Version 1.2 cannot find yurt-tunnel-server.yaml yurt-tunnel-agent.yaml, nor can it be found in the charts package

### ISSUE THREAD

**Issue by henkuaifacai** [openyurtio/openyurt#1259]
Version 1.2 cannot find yurt-tunnel-server.yaml yurt-tunnel-agent.yaml, nor can it be found in the charts package

**Comment by Congrool** [comment]
Yes, we recommand to use raven instead of yurt-tunnel since v1.2. You can find some instructions at [manually-setup-doc](https://openyurt.io/docs/installation/manually-setup#4-setup-cross-network-domain-communication-components-of-openyurt).

BTW, we'll remove yurt-tunnel in future version.

**Comment by henkuaifacai** [comment]
好的，谢谢，因为没看到是用raven代替 yurt-tunnel，以为是你们漏了
