### ISSUE TITLE
kube-controller-manager will not run as normal after "revert"

### ISSUE THREAD

**Issue by vincent-pli** [openyurtio/openyurt#126]
After `revert`, the `ServiceAccount: node-controller` will be created by `yurtctl` and the binding `secret` will be generated , but the  `kube-controller-manager` will not work, keep raising exception like this:
```
Error updating node thump2.fyre.ibm.com: Unauthorized
Failed while getting a Node to retry updating node health. Probably Node thump2.fyre.ibm.com was deleted
```

Restart `kube-controller-manager` could fix the issue, but `kube-controller-manager` is a static pod(kubeadm, kind, openshift), manged by `kublet`,  can not restart it gracefully, I think we need document it.

**Comment by Fei-Guo** [comment]
Yes, it is unfortunate that we need to "delete the kcm pod" to let the new SA take effect.

Maybe we can improve the log msg here to indicate that the ycm Pod needs to be recreated. 
https://github.com/alibaba/openyurt/blob/cdc6acf7c8ecef546cda39fbc8f4d9fad9159541/pkg/yurtctl/cmd/revert/revert.go#L165

**Comment by vincent-pli** [comment]
I think we could add some warning message at the end of the process, like:
`Warning, you must restart "kube-controller-manager" to make it(node_lifecycle_controller) work again.`
or something similar.

**Comment by charleszheng44** [comment]
@vincent-pli that's a good point. I will add the warning message
