### ISSUE TITLE
Can't Join openyurt（use yurtadm join）

### ISSUE THREAD

**Issue by mica1002** [openyurtio/openyurt#1263]
**I compile yurtadm join to join my openyurt sever but i can't 

here is my log from yurtadm join:**
{
./yurtadm join 47.243.253.79:6443 --token=uoknt0.uynx1gryz7dj0oh4 --discovery-token-unsafe-skip-ca-verification --organizations=openyurt:tenant:17688241156 --v=5
I0223 09:54:22.138066   32569 token.go:105] [discovery] Created cluster-info discovery client, requesting info from "47.243.253.79:6443"
I0223 09:54:22.138139   32569 token.go:230] [discovery] kube client is nil, use bootstrap config(&{  {false map[]} map[kubernetes:0x40003b6f80] map[] map[token-bootstrap-client@kubernetes:0x400035f720] token-bootstrap-client@kubernetes map[]}) to create client
I0223 09:54:22.249891   32569 token.go:130] [discovery] Cluster info signature and contents are valid and no TLS pinning was specified, will use API Server "47.243.253.79:6443"
I0223 09:54:22.321860   32569 kubernetes.go:348] kubernetes version: v1.20.11
I0223 09:54:22.321897   32569 join.go:312] node join data info: join.joinData{joinNodeData:(*joindata.NodeRegistration)(0x4000438380), apiServerEndpoint:"47.243.253.79:6443", token:"uoknt0.uynx1gryz7dj0oh4", tlsBootstrapCfg:(*api.Config)(0x400010e900), clientSet:(*kubernetes.Clientset)(0x400045e000), ignorePreflightErrors:sets.String{}, organizations:"openyurt:tenant:17688241156", pauseImage:"registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2", yurthubImage:"registry.cn-hangzhou.aliyuncs.com/openyurt/yurthub:latest", kubernetesVersion:"v1.20.11", caCertHashes:[]string{}, nodeLabels:map[string]string{}, kubernetesResourceServer:"dl.k8s.io", yurthubServer:"127.0.0.1", reuseCNIBin:false}
I0223 09:54:22.322078   32569 system.go:43] Setting ipv4 forward
I0223 09:54:22.322174   32569 system.go:52] Setting bridge settings for kubernetes.
I0223 09:54:22.322436   32569 system.go:74] Disabling SELinux.
I0223 09:54:22.322457   32569 kubernetes.go:111] Check and install kubelet v1.20.11
I0223 09:54:22.451456   32569 kubernetes.go:120] kubelet --version: v1.20.11
I0223 09:54:22.451564   32569 kubernetes.go:132] Kubelet v1.20.11 already exist, skip install.
I0223 09:54:22.451579   32569 kubernetes.go:202] Check and install kubeadm v1.20.11
I0223 09:54:22.527318   32569 kubernetes.go:209] "kubeadm" version="{\n  \"clientVersion\": {\n    \"major\": \"1\",\n    \"minor\": \"20\",\n    \"gitVersion\": \"v1.20.11\",\n    \"gitCommit\": \"27522a29febbcc4badac257763044d0d90c11abd\",\n    \"gitTreeState\": \"clean\",\n    \"buildDate\": \"2021-09-15T19:20:34Z\",\n    \"goVersion\": \"go1.15.15\",\n    \"compiler\": \"gc\",\n    \"platform\": \"linux/arm64\"\n  }\n}\n"
I0223 09:54:22.527456   32569 kubernetes.go:226] Kubeadm v1.20.11 already exist, skip install.
I0223 09:54:22.527496   32569 kubernetes.go:177] Skip download cni, use already exist file: /tmp/cni-plugins-linux-arm64-v0.8.0.tgz
I0223 09:54:23.625689   32569 kubernetes.go:252] Setting kubelet service.
I0223 09:54:23.626027   32569 prepare.go:83] [join-node] Adding edge hub static yaml
I0223 09:54:23.626288   32569 prepare.go:121] [join-node] Add hub agent static yaml is ok
I0223 09:54:23.626322   32569 token.go:105] [discovery] Created cluster-info discovery client, requesting info from "47.243.253.79:6443"
I0223 09:54:23.626334   32569 token.go:230] [discovery] kube client is nil, use bootstrap config(&{  {false map[]} map[kubernetes:0x40001cc200] map[] map[token-bootstrap-client@kubernetes:0x4000454050] token-bootstrap-client@kubernetes map[]}) to create client
I0223 09:54:23.672160   32569 token.go:130] [discovery] Cluster info signature and contents are valid and no TLS pinning was specified, will use API Server "47.243.253.79:6443"
[preflight] Running pre-flight checks
	[WARNING DirAvailable--etc-kubernetes-manifests]: /etc/kubernetes/manifests is not empty
	[WARNING FileAvailable--etc-kubernetes-kubelet.conf]: /etc/kubernetes/kubelet.conf already exists
	[WARNING FileExisting-ethtool]: ethtool not found in system path
	[WARNING FileExisting-socat]: socat not found in system path
	[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 23.0.1. Latest validated version: 19.03
	[WARNING SystemVerification]: missing optional cgroups: hugetlb
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
[kubelet-check] Initial timeout of 40s passed.
error execution phase kubelet-start: error uploading crisocket: timed out waiting for the condition
To see the stack trace of this error execute with --v=5 or higher
Error: exit status 1
Usage:
  yurtadm join [api-server-endpoint] [flags]

Flags:
      --cri-socket string                             Path to the CRI socket to connect (default "/var/run/dockershim.sock")
      --discovery-token-ca-cert-hash strings          For token-based discovery, validate that the root CA public key matches this hash (format: "<type>:<value>").
      --discovery-token-unsafe-skip-ca-verification   For token-based discovery, allow joining without --discovery-token-ca-cert-hash pinning.
  -h, --help                                          help for join
      --ignore-preflight-errors strings               A list of checks whose errors will be shown as warnings. Example: 'IsPrivilegedUser,Swap'. Value 'all' ignores errors from all checks.
      --kubernetes-resource-server string             Sets the address for downloading k8s node resources (default "dl.k8s.io")
      --node-labels string                            Sets the labels for joining node
      --node-name string                              Specify the node name. if not specified, hostname will be used.
      --node-type string                              Sets the node is edge or cloud (default "edge")
      --organizations string                          Organizations that will be added into hub's client certificate
      --pause-image string                            Sets the image version of pause container (default "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2")
      --reuse-cni-bin                                 Whether to reuse local CNI binaries or to download new ones
      --token string                                  Use this token for both discovery-token and tls-bootstrap-token when those values are not provided.
      --yurthub-image string                          Sets the image version of yurthub component (default "registry.cn-hangzhou.aliyuncs.com/openyurt/yurthub:latest")
      --yurthub-server-addr string                    Sets the address for yurthub server addr (default "127.0.0.1")

Global Flags:
      --add_dir_header                   If true, adds the file directory to the header of the log messages
      --alsologtostderr                  log to standard error as well as files
      --kubeconfig string                The path to the kubeconfig file
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --log_file string                  If non-empty, use this log file
      --log_file_max_size uint           Defines the maximum size a log file can grow to. Unit is megabytes. If the value is 0, the maximum file size is unlimited. (default 1800)
      --logtostderr                      log to standard error instead of files (default true)
      --one_output                       If true, only write logs to their native severity level (vs also writing to each lower severity level)
      --skip_headers                     If true, avoid header prefixes in the log messages
      --skip_log_headers                 If true, avoid headers when opening log files
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          number for the log level verbosity (default 0)
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
}

Here is i use journalcrtl -u kubelet -xe

root@debian:/work/openyurt/_output/local/bin/linux/arm64# journalctl -u kubelet -xe
Feb 23 10:25:27 debian.telpo kubelet[32838]: E0223 10:25:27.964193   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.064359   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.086754   32838 eviction_manager.go:260] eviction manager: failed to get summary stats: failed to get node info: node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.164510   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.264667   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.364834   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.465002   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.565151   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.665289   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.765429   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.865568   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:28 debian.telpo kubelet[32838]: E0223 10:25:28.965714   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:29 debian.telpo kubelet[32838]: E0223 10:25:29.065862   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:29 debian.telpo kubelet[32838]: E0223 10:25:29.166006   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:29 debian.telpo kubelet[32838]: E0223 10:25:29.266152   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:29 debian.telpo kubelet[32838]: E0223 10:25:29.366298   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:29 debian.telpo kubelet[32838]: E0223 10:25:29.466422   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:29 debian.telpo kubelet[32838]: E0223 10:25:29.566551   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:29 debian.telpo kubelet[32838]: E0223 10:25:29.666666   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:29 debian.telpo kubelet[32838]: E0223 10:25:29.766785   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:29 debian.telpo kubelet[32838]: E0223 10:25:29.866905   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:29 debian.telpo kubelet[32838]: E0223 10:25:29.967023   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:30 debian.telpo kubelet[32838]: E0223 10:25:30.067160   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:30 debian.telpo kubelet[32838]: E0223 10:25:30.167520   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:30 debian.telpo kubelet[32838]: E0223 10:25:30.267632   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:30 debian.telpo kubelet[32838]: E0223 10:25:30.367742   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:30 debian.telpo kubelet[32838]: E0223 10:25:30.468049   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:30 debian.telpo kubelet[32838]: E0223 10:25:30.568187   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:30 debian.telpo kubelet[32838]: E0223 10:25:30.668323   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:30 debian.telpo kubelet[32838]: E0223 10:25:30.768427   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:30 debian.telpo kubelet[32838]: E0223 10:25:30.868557   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:30 debian.telpo kubelet[32838]: E0223 10:25:30.968676   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.068792   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.168908   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.269029   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.369162   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.469546   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.495215   32838 controller.go:144] failed to ensure lease exists, will retry in 7s, error: Get "http://127.0.0.1:10261/apis/coordination.k8s.io/v1/name>
Feb 23 10:25:31 debian.telpo kubelet[32838]: W0223 10:25:31.526800   32838 cni.go:239] Unable to update cni config: no networks found in /etc/cni/net.d
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.569904   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.670231   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.770970   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.871092   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:31 debian.telpo kubelet[32838]: E0223 10:25:31.971214   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:32 debian.telpo kubelet[32838]: E0223 10:25:32.071329   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:32 debian.telpo kubelet[32838]: E0223 10:25:32.171433   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:32 debian.telpo kubelet[32838]: E0223 10:25:32.271538   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:32 debian.telpo kubelet[32838]: E0223 10:25:32.364621   32838 kubelet.go:2183] Container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is>
Feb 23 10:25:32 debian.telpo kubelet[32838]: E0223 10:25:32.371646   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:32 debian.telpo kubelet[32838]: E0223 10:25:32.471875   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:32 debian.telpo kubelet[32838]: E0223 10:25:32.571994   32838 kubelet.go:2263] node "debian.telpo" not found
Feb 23 10:25:32 debian.telpo kubelet[32838]: E0223 10:25:32.672112   32838 kubelet.go:2263] node "debian.telpo" not found

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: V1.2.0
- Kubernetes version (use `kubectl version`):V1.20.11
- OS (e.g: `cat /etc/os-release`):Debian11 arm64
- Kernel (e.g. `uname -a`):Linux debian.telpo 5.10.66#3 SMP  aarch64 GNU/linux
- Install tools: compile
- Others: none

**others**

/kind bug

**Comment by YTGhost** [comment]
@mica1002 Thanks for raising the issue. would you be able to upload the logs of yurthub component on edge device?

**Comment by River-sh** [comment]
You need to install yurt-controller-manager before join node, which is to approve yurthub's certificate.

**Comment by rambohe-ch** [comment]
@mica1002 It seems that `kubeadm` tool failed to work, and from detail logs there is a same error on this link:
https://stackoverflow.com/questions/53525975/kubernetes-error-uploading-crisocket-timed-out-waiting-for-the-condition

please take a look.

**Comment by YTGhost** [comment]
I think this issue can be closed.

**Comment by rambohe-ch** [comment]
> I think this issue can be closed.

@mica1002 this issue has no activities for a long time, and i will close it.  you can feel free to reopen it if you need it.
