### ISSUE TITLE
install yurt-app-manager struck in ContainerCreate status 

### ISSUE THREAD

**Issue by mica1002** [openyurtio/openyurt#1267]
**Detail Log**

root@debian:/work/openyurt/_output/local/bin/linux/arm64/charts/yurt-app-manager# helm install yurt-app-manager -n kube-system .
Error: INSTALLATION FAILED: failed pre-install: timed out waiting for the condition
root@debian:/work/openyurt/_output/local/bin/linux/arm64/charts/yurt-app-manager# kubectl get pod --all-namespaces
NAMESPACE     NAME                                      READY   STATUS              RESTARTS   AGE
default       mysql-1677154548-0                        0/1     Pending             0          14h
kube-system   etcd-debian.telpo                         1/1     Running             1          14h
kube-system   kube-apiserver-debian.telpo               1/1     Running             1          14h
kube-system   kube-controller-manager-debian.telpo      1/1     Running             4          14h
kube-system   kube-flannel-ds-ss64v                     0/1     CrashLoopBackOff    23         14h
kube-system   kube-proxy-vvxb6                          1/1     Running             1          14h
kube-system   kube-scheduler-debian.telpo               1/1     Running             4          14h
kube-system   yurt-app-manager-admission-create-t7r89   0/1     ContainerCreating   0          12m
kube-system   yurt-tunnel-dns-b5d9c74d9-bqnch           0/1     ContainerCreating   0          14h
root@debian:/work/openyurt/_output/local/bin/linux/arm64/charts/yurt-app-manager# kubectl describe pod yurt-app-manager-admission-create-t7r89 -n kube-system
Name:           yurt-app-manager-admission-create-t7r89
Namespace:      kube-system
Priority:       0
Node:           debian.telpo/192.168.2.83
Start Time:     Fri, 24 Feb 2023 02:31:08 +0000
Labels:         app=yurt-app-manager-admission-create
                app.kubernetes.io/instance=yurt-app-manager
                app.kubernetes.io/managed-by=Helm
                app.kubernetes.io/name=yurt-app-manager
                app.kubernetes.io/version=0.6.0
                controller-uid=0900efc7-34ed-47d4-ba4e-76c4c055205c
                helm.sh/chart=yurt-app-manager-0.1.3
                job-name=yurt-app-manager-admission-create
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  Job/yurt-app-manager-admission-create
Containers:
  create:
    Container ID:  
    Image:         docker.io/oamdev/kube-webhook-certgen:v2.4.1
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      create
      --host=yurt-app-manager-webhook,yurt-app-manager-webhook.kube-system.svc
      --namespace=kube-system
      --secret-name=yurt-app-manager-admission
      --key-name=tls.key
      --cert-name=tls.crt
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from yurt-app-manager-admission-token-g745r (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  yurt-app-manager-admission-token-g745r:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  yurt-app-manager-admission-token-g745r
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node-role.kubernetes.io/master:NoSchedule op=Exists
                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age                    From               Message
  ----     ------                  ----                   ----               -------
  Normal   Scheduled               14m                    default-scheduler  Successfully assigned kube-system/yurt-app-manager-admission-create-t7r89 to debian.telpo
  Warning  FailedCreatePodSandBox  14m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "6ba091ac36df9a801d9760c77d305d4624b899c99b9e4c08050f96f565993803" network for pod "yurt-app-manager-admission-create-t7r89": networkPlugin cni failed to set up pod "yurt-app-manager-admission-create-t7r89_kube-system" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  14m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3c248424d8b88f66af8ec32e1069f0fccb3088b973ff422ff7bd7a45f3c15cb9" network for pod "yurt-app-manager-admission-create-t7r89": networkPlugin cni failed to set up pod "yurt-app-manager-admission-create-t7r89_kube-system" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  14m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "d2d4d27b36d1b337901f016f4fcd2aa53732e4997c9b6320f8643276a70cbb77" network for pod "yurt-app-manager-admission-create-t7r89": networkPlugin cni failed to set up pod "yurt-app-manager-admission-create-t7r89_kube-system" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  14m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3bbc267148810a30d7052e2ab46196a857f915e9c83629b594169bc91e1f2ac9" network for pod "yurt-app-manager-admission-create-t7r89": networkPlugin cni failed to set up pod "yurt-app-manager-admission-create-t7r89_kube-system" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  14m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "6aeca7c0df14ecdf19de771c1e447fd31f56d6e29bf15e51637b3089173128df" network for pod "yurt-app-manager-admission-create-t7r89": networkPlugin cni failed to set up pod "yurt-app-manager-admission-create-t7r89_kube-system" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  14m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c2c74fae125298602e0c0af70470e34c88859290dc17791af1eba28d3039cbb9" network for pod "yurt-app-manager-admission-create-t7r89": networkPlugin cni failed to set up pod "yurt-app-manager-admission-create-t7r89_kube-system" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  14m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "fe2d5642d9001e59686c6afbe4d706bcffbb59e5d82ad8e0b25c51f1998d4035" network for pod "yurt-app-manager-admission-create-t7r89": networkPlugin cni failed to set up pod "yurt-app-manager-admission-create-t7r89_kube-system" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  14m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "d8d5e297f1f700da3653babda29feeb7a1f7eb2e2fd48c4afc18d523c07388d9" network for pod "yurt-app-manager-admission-create-t7r89": networkPlugin cni failed to set up pod "yurt-app-manager-admission-create-t7r89_kube-system" network: open /run/flannel/subnet.env: no such file or directory
  Warning  FailedCreatePodSandBox  14m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "aecbc6a62522ab775a8642bceb4518a69bac3a270ae9141b3a0ca5c65392154e" network for pod "yurt-app-manager-admission-create-t7r89": networkPlugin cni failed to set up pod "yurt-app-manager-admission-create-t7r89_kube-system" network: open /run/flannel/subnet.env: no such file or directory
  Normal   SandboxChanged          9m30s (x264 over 14m)  kubelet            Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  4m31s (x515 over 14m)  kubelet            (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "ef7e52e71b2f5d9857917541dbdef508e4cce09859e22e75aa26eb1cded5b1ec" network for pod "yurt-app-manager-admission-create-t7r89": networkPlugin cni failed to set up pod "yurt-app-manager-admission-create-t7r89_kube-system" network: open /run/flannel/subnet.env: no such file or directory
root@debian:/work/openyurt/_output/local/bin/linux/arm64/charts/yurt-app-manager# 
root@debian:/work/openyurt/_output/local/bin/linux/arm64/charts/yurt-app-manager# kubectl get po -n kube-system | grep yurt-app-manager
yurt-app-manager-admission-create-t7r89   0/1     ContainerCreating   0          19m
root@debian:/work/openyurt/_output/local/bin/linux/arm64/charts/yurt-app-manager# 

**Environment**:
- OpenYurt version: v1.2.0
- Kubernetes version (use `kubectl version`):1.22.10
- OS (e.g: `cat /etc/os-release`):arrch64
- Kernel (e.g. `uname -a`):debain.telpo 5.10.66
- Install tools:
- Others:

**others**

/kind bug

**Comment by batthebee** [comment]
Hi @mica1002, please format your output. It's really hard to read. Thx

**Comment by rambohe-ch** [comment]
@mica1002 controllers and webhooks in yurt-app-manager have been migrated into yurt-manager component in OpenYurt v1.3, and yurt-app-manager will be archived later soon.  so please upgrade yurt-app-manager to yurt-manager component.

by the way, i will close this issue. and you can feel free to reopen this issue if you need to track this problem.
