### ISSUE TITLE
[feature request] rework of helm chart release process 

### ISSUE THREAD

**Issue by batthebee** [openyurtio/openyurt#1276]
**What would you like to be added**:

Currently I find it very difficult to install a specific version of openyurt, especially via helm charts. 

the `openyurt-helm` repository has currently no `1.2.1` released. In the `openyurt` repository the helm version on the master partly points to non-existing images ('yurt-manager'). the helm chart on the tag `1.2.1` is `1.2.0`, same for images . 

I think something has to be done in the release process. In this context we could also discuss whether to switch to oci as helm repo and remove the `openyurt-helm` repo. https://helm.sh/docs/topics/registries/

/kind feature

**Comment by rambohe-ch** [comment]
@batthebee Thank you for raising issue. I am so sorry that you felt confused about the openyurt helm charts. I think that github is also convenient to manage helm charts, but we need to improve the helm release process for OpenYurt.

and @fengshunli will take this work and improve the helm charts release process.

**Comment by fengshunli** [comment]
The version is managed through the released release and tag, chart
  The version of repo1.2.1 has not been updated, see pr https://github.com/openyurtio/openyurt/pull/1280
