### ISSUE TITLE
[Question] Interactive channel like slack available for OpenYurt?

### ISSUE THREAD

**Issue by fujitatomoya** [openyurtio/openyurt#1283]
**What happened**:

Just a question if OpenYurt community has chat channel like slack?

**What you expected to happen**:

It would be more helpful to iterate with community to share information and so on.

**others**
/kind question

**Comment by fujitatomoya** [comment]
CC: @rambohe-ch @Windrow

**Comment by rambohe-ch** [comment]
@fujitatomoya yes, welcome you to join slack OpenYurt channel.
https://join.slack.com/t/openyurt/shared_invite/zt-1q04kn3nl-9UOKBo__Z~Qhcaj4jnHH~g
