### ISSUE TITLE
[BUG] yurtadm failed to Download cni plugin from some ip addresses

### ISSUE THREAD

**Issue by batthebee** [openyurtio/openyurt#1286]
**What happened**:

yurtadm is trying to download the cni plugin. But it seems that the download is blocked from some ip addresses. From my home network the download works, from my cloud provider I run into a timeout. 

```bash
"I0303 23:09:36.315047    1788 kubernetes.go:162] Download cni from:  https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-amd64-v0.8.0.tgz", 
"Error: Get \"https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-amd64-v0.8.0.tgz\": dial tcp 118.31.219.194:443: i/o timeout", "Usage:", "
```

Maybe such dependencies are better served on github.

Apropos github: I am currently looking for the repository from which the cni is built. I would like to build a workaround. Where can I find that? The same applies to the sealer image. Where can I make the adjustments there? Does it make sense to transfer both repos to openyurt? 

Thanks!

**Environment**:
- OpenYurt version: v1.2.1

/kind bug

**Comment by rambohe-ch** [comment]
@batthebee Yurtadm supports to use cni binaries that uses prepared beforehand, and cni binaries should be placed under `/opt/cni/bin` directory.then congfiure yurtadm parameter `--reuse-cni-bin=true` for `yurtadm join` command.

**Comment by batthebee** [comment]
@rambohe-ch   thanks for the workaround. What is the cni needed for at this point? In the docs under manual setup the cni does not appear at all. 

Where can I find the sources? What is it based on?

**Comment by rambohe-ch** [comment]
> @rambohe-ch thanks for the workaround. What is the cni needed for at this point? In the docs under manual setup the cni does not appear at all.
> 
> Where can I find the sources? What is it based on?

@batthebee It seems that tutorial of `yurtadm join` has no info about `--reuse-cni-bin`. @YTGhost would you be able to add `--reuse-cni-bin`  parameter and kubelet/kubeadm binary replacement info into the website docs?
https://openyurt.io/docs/installation/yurtadm-join/

**Comment by YTGhost** [comment]
> > @rambohe-ch thanks for the workaround. What is the cni needed for at this point? In the docs under manual setup the cni does not appear at all.
> > Where can I find the sources? What is it based on?
> 
> @batthebee It seems that tutorial of `yurtadm join` has no info about `--reuse-cni-bin`. @YTGhost would you be able to add `--reuse-cni-bin` parameter and kubelet/kubeadm binary replacement info into the website docs? https://openyurt.io/docs/installation/yurtadm-join/

Of course, I will add documentation as soon as possible

**Comment by YTGhost** [comment]
@rambohe-ch I remember that the cni we are using is specially modified, do we also have to explain it inside the documentation and make the changes public as a repository?

**Comment by rambohe-ch** [comment]
> @rambohe-ch I remember that the cni we are using is specially modified, do we also have to explain it inside the documentation and make the changes public as a repository?

@YTGhost maybe you can add the reference link: https://openyurt.io/docs/user-manuals/network/edge-pod-network/ in the yurtadm doc.
