### ISSUE TITLE
[feature request]improve bootstrap configuration for YurtHub

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1290]
**What would you like to be added**:
A bootstrap token should be passed to yurthub(--join-token parameter) for bootstrapping. sometime token without expire date is used for convenient,  so security problem maybe happen because the bootstrap token is always exist on the edge node.

so i think we can improve bootstrap configuration for yurthub, a bootstrap file instead of bootstrap token is passed into YurtHub, and bootstrap file will be removed after Yurthub bootstrap completed, so bootstrap token can not be leaked on the edge node.

the work we need do as following:
- YurtHub: 
      add a new paramter --boostrap-file, and use bootstrap file to bootstrap YurtHub, and we can keep the original `--join-token` parameter for several versions.

- Yurtadm: 
      - Yurtadm should create a bootstrap file for YurtHub boostrapping, and remove this file after YurtHub bootstrapping completed.
      - add a new sub command for Yurtadm to create a temp bootstrap file for YurtHub when YurtHub need to use bootstrap file to update certificate if certificate expired. on the other hand, the temp bootstrap file also should be removed after certificate is updated.

**Why is this needed**:
A bootstrap token should be passed to yurthub(--join-token parameter) for bootstrapping. sometime token without expire date is used for convenient,  so security problem maybe happen because the bootstrap token is always exist on the edge node.

**others**
/kind feature

**Comment by YTGhost** [comment]
I am interested in this work, can you assign it to me?
