### ISSUE TITLE
[feature request] yurtadm join option to specify secret for private registry

### ISSUE THREAD

**Issue by fujitatomoya** [openyurtio/openyurt#1294]
**What would you like to be added**:

`--registry-secret` option to specify secret to be filled in `/etc/kubernetes/manifests/yurthub.yaml` so that Kuberenetes can pull the image from private registry with this secret.

```bash
yurtadm join --yurthub-image "some.cloud.private.registry.com/openyurt/yurthub:latest" --registry-secret "secrettobewritteninmanifest"
```

**Why is this needed**:

It is likely that user want to guarantee all the container images controlled by them self for production phase from their own registry.
Currently we can only specify the registry but secret. This does not allow the user to pull the image from secured private registry.

**others**
/kind feature

**Comment by fujitatomoya** [comment]
### Implementation Consideration

- extend `addJoinConfigFlags` with `--registry-secret`, in default `None`.
- `YurtJoinData` interface to be extended with `RegistrySecret`.
- If the secret is specified with `yurtadm join --registry-secret`, fill that into static yaml file `yurthub.yaml`
- (the rest will be taken care by kubernetes to pull the image from private registry with specified secret)

**Comment by fujitatomoya** [comment]
off topic from this feature request, but `yurthub:latest` could be the reason for possible problem once image is pushed or updated w/o notice... I saw these issues many times.

**Comment by YTGhost** [comment]
> ### Implementation Consideration
> * extend `addJoinConfigFlags` with `--registry-secret`, in default `None`.
> * `YurtJoinData` interface to be extended with `RegistrySecret`.
> * If the secret is specified with `yurtadm join --registry-secret`, fill that into static yaml file `yurthub.yaml`
> * (the rest will be taken care by kubernetes to pull the image from private registry with specified secret)

I think this requirement is necessary, we need to add a `--registry-secret` flag and fill the value into `imagePullSecrets` in `yurthub.yaml`.

**Comment by fujitatomoya** [comment]
yeah, i mean it is not hard-requirement right away, but better to have this option.

**Comment by YTGhost** [comment]
> off topic from this feature request, but `yurthub:latest` could be the reason for possible problem once image is pushed or updated w/o notice... I saw these issues many times.

Maybe we should set the default value image version of `yurthubImage` to follow the `yurtadm` version? WDYT @rambohe-ch

**Comment by fujitatomoya** [comment]
@rambohe-ch thanks for the information, that looks good to me. I would do review to see the details, appreciate the contribution and feature enhancement!

**Comment by fujitatomoya** [comment]
@rambohe-ch 

having `StaticPod` template makes sense to me, i believe that it should be the way it it to align kubernetes CRD.

AFAIU, user still needs to issue `yurtadm join` after this feature is integrated, right? in that case, the question is how user can specify the `secret`? besides, `StaticPod` spec does not allow to specify the `secret`? (https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/)

> Note: The spec of a static Pod cannot refer to other API objects (e.g., ServiceAccount, ConfigMap, Secret, etc).

**Comment by rambohe-ch** [comment]
> @rambohe-ch
> 
> having `StaticPod` template makes sense to me, i believe that it should be the way it it to align kubernetes CRD.
> 
> AFAIU, user still needs to issue `yurtadm join` after this feature is integrated, right? in that case, the question is how user can specify the `secret`? besides, `StaticPod` spec does not allow to specify the `secret`? (https://kubernetes.io/docs/tasks/configure-pod-container/static-pod/)
> 
> > Note: The spec of a static Pod cannot refer to other API objects (e.g., ServiceAccount, ConfigMap, Secret, etc).

@fujitatomoya sorry, my response had confused you, and i had made a mistake that static pod can not support `imagePullSecrets` field. 

but i think `yurtadm join` can not manage to help `static pod` to support `imagePullSecrets` because this secret can not be passed through to kubelet component.

and for private registry, i suggested that user should configure the runtime to support it. like [$HOME/.docker/config.json](https://docs.docker.com/engine/reference/commandline/login/) for docker runtime.

**Comment by fujitatomoya** [comment]
> but i think yurtadm join can not manage to help static pod to support imagePullSecrets because this secret can not be passed through to kubelet component.

yeah, agree. I believe that `StaticPods` are meant to be controlled by only kubelet but high level controller of kubernetes. that is said that it cannot bind or control the secret from k8s perspective.

> and for private registry, i suggested that user should configure the runtime to support it. like [$HOME/.docker/config.json](https://docs.docker.com/engine/reference/commandline/login/) for docker runtime.

it is doable, setting the appropriate secret for private registry to container runtime address this issue. i think this needs to be well-documented since user might meet the same situation like `where to set the secret?`. and probably passing secret via command line is not really good idea for security?

**Comment by rambohe-ch** [comment]
> > but i think yurtadm join can not manage to help static pod to support imagePullSecrets because this secret can not be passed through to kubelet component.
> 
> yeah, agree. I believe that `StaticPods` are meant to be controlled by only kubelet but high level controller of kubernetes. that is said that it cannot bind or control the secret from k8s perspective.
> 
> > and for private registry, i suggested that user should configure the runtime to support it. like [$HOME/.docker/config.json](https://docs.docker.com/engine/reference/commandline/login/) for docker runtime.
> 
> it is doable, setting the appropriate secret for private registry to container runtime address this issue. i think this needs to be well-documented since user might meet the same situation like `where to set the secret?`. and probably passing secret via command line is not really good idea for security?

@fujitatomoya I will add the solution of using private registry for YurtHub component(static pod) in faq doc.
and i agree that user should configure the private registry for runtime manually.

/assign @rambohe-ch

**Comment by rambohe-ch** [comment]
@fujitatomoya I have updated yurthub faq doc, and added a item: 【12. How to use the yurthub image of the private image registry】
https://openyurt.io/docs/faq/yurthub/

so i think we can close this issue now.

**Comment by fujitatomoya** [comment]
`12. How to use the yurthub image of the private image registry` makes sense to me, thanks!
