### ISSUE TITLE
use yurt-tunnel to connect apiserver and edge node  tunnel-agent failure

### ISSUE THREAD

**Issue by lgy1027** [openyurtio/openyurt#131]
use yurt-tunnel to connect apiserver and edge node  tunnel-agent state is always pending
The version used for k8S is 1.16.9
Setup the yurt-tunnel manually

**Comment by rambohe-ch** [comment]
would you upload your tunnel-agent container logs and kubelet logs?

**Comment by lgy1027** [comment]
It is best to support bare metal operation, the current use of kubeedge live K8S cluster operation will have problems

**Comment by rambohe-ch** [comment]
@lgy1027 This issue is not active over two months, and you can try the yurt-tunnel in OpenYurt v0.5.0. we will close this issue, you can reopen this issue at any time.
