### ISSUE TITLE
[BUG]Image cannot be pulled down

### ISSUE THREAD

**Issue by JiaweiGithub** [openyurtio/openyurt#1311]
Use official documents to install, there are image that cannot be pulled down

**What happened**:
![image](https://user-images.githubusercontent.com/8078735/224920014-5574a754-1811-430a-8ed8-c787f582df80.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@JiaweiGithub yurt-manager component is not available in OpenYurt v1.2, and only latest version is ready at present.

**Comment by JiaweiGithub** [comment]
@rambohe-ch  I used the helm library linked from the official website. The version of the component in it is v1.2. After I changed it to latest, the image pull was successful, but it still failed.
![image](https://user-images.githubusercontent.com/8078735/224950317-3b5a79f4-cf66-46c0-ba50-bd6887359dd1.png)

**Comment by rambohe-ch** [comment]
> @rambohe-ch I used the helm library linked from the official website. The version of the component in it is v1.2. After I changed it to latest, the image pull was successful, but it still failed.
> 
> ![image](https://user-images.githubusercontent.com/8078735/224950876-b738344a-fdc5-48b4-9c0a-3784972030e7.png)

@JiaweiGithub I think you need to use openyurt helm v1.2, the link: https://github.com/openyurtio/openyurt-helm/releases/tag/openyurt-1.2.0
