### ISSUE TITLE
CNCF SIG-Runtime discussion/presentation?

### ISSUE THREAD

**Issue by raravena80** [openyurtio/openyurt#133]
Hello OpenYurt team,

I'm one of the co-chairs of the CNCF SIG-Runtime, and since you are CNCF Sandbox project I think it would be great for you to present/discuss the project in one of our meetings. For example, discuss things such as adoption, architecture, etc.

Let me know if this something you'd be interested in doing. If yes, please feel free to add it to our [agenda](https://bit.ly/cncf-sig-runtime-meeting-notes) or reach out to me (raravena80 at gmail.com)

Thanks!

**Comment by Fei-Guo** [comment]
Sure, I will update your agenda soon.

**Comment by Fei-Guo** [comment]
Added to Nov 5th meeting.
