### ISSUE TITLE
[feature request]support yurthub component work in specified namespace

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1341]
**What would you like to be added**:
yurthub component should be deployed in kube-system namespace. as you known, kube-system namespace is used for K8s components, so some users have requested that yurthub can be deployed in specified namespace.

**Why is this needed**:
improve the deployment flexibility of OpenYurt component.

**others**
/kind feature

**Comment by YTGhost** [comment]
Does this mean we need to add a new flag named `ResourceNamespace` to `yurthub` and set the value to `LeaderElection.ResourceNamespace`? Is there anything else that needs to be changed?

**Comment by rambohe-ch** [comment]
> Does this mean we need to add a new flag named `ResourceNamespace` to `yurthub` and set the value to `LeaderElection.ResourceNamespace`? Is there anything else that needs to be changed?

@YTGhost I think that one component works in a specified namespace, the following two jobs maybe included:
1. the deployment of this component should be improved, the namespace for this component can be specified in the helm values.yaml or command tool(like yurtadm) parameter.
2. improve `kube-system` hard code in the component, and the namespace can be specified as a parameter for the component.

**Comment by YTGhost** [comment]
> > Does this mean we need to add a new flag named `ResourceNamespace` to `yurthub` and set the value to `LeaderElection.ResourceNamespace`? Is there anything else that needs to be changed?
> 
> @YTGhost I think that one component works in a specified namespace, the following two jobs maybe included:
> 
> 1. the deployment of this component should be improved, the namespace for this component can be specified in the helm values.yaml or command tool(like yurtadm) parameter.
> 2. improve `kube-system` hard code in the component, and the namespace can be specified as a parameter for the component.

I see. Maybe I can take this work after migrate the service topology controller.

**Comment by huweihuang** [comment]
may I take this work? @rambohe-ch

**Comment by huweihuang** [comment]
if we set a specified namespace for yurthub and the other openyurt component, What is the appropriate name of the namespace?  can use `openyurt` as default namespace which been set in yurthub.yaml? @rambohe-ch

**Comment by rambohe-ch** [comment]
> if we set a specified namespace for yurthub and the other openyurt component, What is the appropriate name of the namespace? if the user didn't set the specified namespace , can use `openyurt` as default namespace which been set in yurthub.yaml? @rambohe-ch

@huweihuang I think that default namespace should be `kube-system`, so we keep the consistency with the old version.

**Comment by huweihuang** [comment]
ok， if the all openyurt component set a specified namespace, shall we use `openyurt` insteads of `kube-system` as default namespace? @rambohe-ch

**Comment by rambohe-ch** [comment]
> ok， if the all openyurt component set a specified namespace, shall we use `openyurt` insteads of `kube-system` as default namespace? @rambohe-ch

@huweihuang maybe we can use the specified namespace as default namespace, not `openyurt`.
