### ISSUE TITLE
[feature request]support pool-coordinator component work in specified namespace

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1342]
**What would you like to be added:**
pool-coordinator component should be deployed in kube-system namespace. as you known, kube-system namespace is used for K8s components, so some users have requested that OpenYurt components(like yurthub, pool-coordinator) can be deployed in specified namespace.

**Why is this needed:**
improve the deployment flexibility of OpenYurt components.

**others**
/kind feature

**Comment by y-ykcir** [comment]
@rambohe-ch  I want to try this, can you assign it to me?

**Comment by y-ykcir** [comment]
@rambohe-ch It seems that pool-coordinator itself only needs to specify the namespace in the helm. However, the pkg/controller/poolcoordinator use hard code "kube-system" to get or create svc and certs info. Should we add a flag to the yurt controller manager to specify the same namespace or import it as an environment variable?

**Comment by rambohe-ch** [comment]
> @rambohe-ch It seems that pool-coordinator itself only needs to specify the namespace in the helm. However, the pkg/controller/poolcoordinator use hard code "kube-system" to get or create svc and certs info. Should we add a flag to the yurt controller manager to specify the same namespace or import it as an environment variable?

@y-ykcir it's a good idea to add a new parameter for yurt-manager to specify namespace for controllers.
