### ISSUE TITLE
[Question][HELP] Change yurt-manager ClusterRoleBinding name

### ISSUE THREAD

**Issue by kadisi** [openyurtio/openyurt#1350]
**What happened**:

now, in openyurt  helm chart, the name of yurt-manager clusterrolebing is `manager-rolebinding`. 
`manager-rolebinding` is a generic name created by kubebuild, which is prone to name conflicts and cannot be used properly

![image](https://user-images.githubusercontent.com/36974756/229431308-b4f7d025-ab40-4bb5-8d02-6798c98c2446.png)

**What you expected to happen**:

I suggest changing the name `manager-rolebinding` to `manager-yurt-manager-rolebinding`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by YTGhost** [comment]
@kadisi  I see that in creating a test cluster in e2e, the name of ClusterRoleBinding is `yurt-manager-rolebinding`. Perhaps we could also change it to this.
