### ISSUE TITLE
Does the openyurt support Knative?

### ISSUE THREAD

**Issue by yuxiaoba** [openyurtio/openyurt#136]
Can we work on a project which use both knative and openyurt? Any docs on how we can use them together?

**Comment by richard2006** [comment]
Hi @yuxiaoba , why you want to work on a project using both knative and openyurt?  Indeed, we have plan to support knative on openyurt.

**Comment by yuxiaoba** [comment]
@richard2006  Because we would like to delivery functions to data centers' node and edge devices in one cluster.   Can we achieve this goal if we combine Knative and openyurt directly ?

**Comment by richard2006** [comment]
yes @yuxiaoba , you can do this.

**Comment by MIBc** [comment]
As I know, knative activitor will set connection with application and proxy forwarding traffic for application. 
In the scene of edge computing, the network is unstable. Therefore,  knative may be inappropriate in openyurt.
