### ISSUE TITLE
[feature request] support yurt-manager work in specified namespace

### ISSUE THREAD

**Issue by y-ykcir** [openyurtio/openyurt#1361]
**What would you like to be added**:
All controllers and webhooks in yurt-manager can be deployed in specified namespace.

**Why is this needed**:
improve the deployment flexibility of OpenYurt components.

**others**
/kind feature

The current yurt-manager needs to be adapted to the specified namespace by modifying the following:

- [x] Pool-coordinator cert controller
- [x] Gateway controller in raven
- [x] Yurt-manager webhooks
- [x] Other components not yet migrated...

**Comment by rambohe-ch** [comment]
@y-ykcir would you be able to take this work?

**Comment by rambohe-ch** [comment]
@y-ykcir yurt-manager component has been updated recently, would you be able to check all yurt-manager again whether can work in specified namespace or not?

**Comment by y-ykcir** [comment]
> @y-ykcir yurt-manager component has been updated recently, would you be able to check all yurt-manager again whether can work in specified namespace or not?

Sure

**Comment by y-ykcir** [comment]
@rambohe-ch It seems that the newly migrated controllers do not need to be modified to be compatible with the specified namespace, maybe we can close this issue?

**Comment by rambohe-ch** [comment]
> @rambohe-ch It seems that the newly migrated controllers do not need to be modified to be compatible with the specified namespace, maybe we can close this issue?

@y-ykcir would you like to take a test for OpenYurt in specified namespace, and make sure OpenYurt can work in specified namespace?

**Comment by y-ykcir** [comment]
> > @rambohe-ch It seems that the newly migrated controllers do not need to be modified to be compatible with the specified namespace, maybe we can close this issue?
> 
> @y-ykcir would you like to take a test for OpenYurt in specified namespace, and make sure OpenYurt can work in specified namespace?

@rambohe-ch Is it possible to test this thing with Kind on the m1 Mac? Sorry that I currently do not have an available Linux server, it may not be convenient for testing.

**Comment by rambohe-ch** [comment]
> > > @rambohe-ch It seems that the newly migrated controllers do not need to be modified to be compatible with the specified namespace, maybe we can close this issue?
> > 
> > 
> > @y-ykcir would you like to take a test for OpenYurt in specified namespace, and make sure OpenYurt can work in specified namespace?
> 
> @rambohe-ch Is it possible to test this thing with Kind on the m1 Mac? Sorry that I currently do not have an available Linux server, it may not be convenient for testing.

@y-ykcir i think we can not check this feature on Kind, because Kind has not used `yurtadm join` command to add nodes.

**Comment by rambohe-ch** [comment]
@y-ykcir all the work of this issue had been done, so i will close this issue.
