### ISSUE TITLE
边端自治情况下，设备重启后，应用访问api报错

### ISSUE THREAD

**Issue by yinlimi** [openyurtio/openyurt#1369]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@yinlimi Thanks for raising issue. would you be able to upload more info about your problem? like OpenYurt version, and which api can not be connected by the application?

**Comment by yinlimi** [comment]
openyurt 1.2.0版本
在连网的情况下，可以访问
I0413 08:25:14.819682       1 remote.go:130] request: go-http-client list customresourcedefinitions: https://192.168.203.27:6443/apis/apiextensions.k8s.io/v1/customresourcedefinitions?limit=500&resourceVersion=0 with bearer token: eyJhbGciOiJSUzI1NiIsImtpZCI6ImVMYU42a2ZBQkM5ZTJPMGdBMlpjYXBOS2M3N3o2dk8wemtnMV9YRlE0bDQifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzEyOTEwMzAxLCJpYXQiOjE2ODEzNzQzMDEsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJldmlydCIsInBvZCI6eyJuYW1lIjoidmlydC1jb250cm9sbGVyLTY5NWNjOThjNTYtcjljc2ciLCJ1aWQiOiJkZTA3Y2I5Ny02ZjZhLTQ5NGEtYjZmNi04OWQwNGE1MjRmNTIifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6Imt1YmV2aXJ0LWNvbnRyb2xsZXIiLCJ1aWQiOiJkNjdjZWZkMy1kZWZlLTRlMzYtODQyYy1lMWY5ZTgyZDM5ZDkifSwid2FybmFmdGVyIjoxNjgxMzc3OTA4fSwibmJmIjoxNjgxMzc0MzAxLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZXZpcnQ6a3ViZXZpcnQtY29udHJvbGxlciJ9.gVjlCLOeCybA5UHZoOpOfyHi7DyTPupqqTqhitjdNUXOAsuaT3vV5v4udVR2kKMi5eTQ6xPdK1qSK8eaHqPV2ck3zKpCys08LNQcg9T3PQ0lSoPH5okZZmszwlJ1eaOmJfwnhLPOr9LxsMhRuzl5yhzPMesztSFTD1rq4HIdSvd-yRmfunR4v0g9F8QHY68JFLBWtA0tC67dCcP27Tehege6UzT8Hwf3ebX1fteRovr37Q7O4udTHTyolnKEzzC3-KiAfvIntiMMfJsdgz682zstKMBhuyl5V0B-Ceh-MlOQPbWFTYWTbWBgDQwFQqcx6aD2L6WjmaD3GuZXPtbJrg
I0413 08:25:14.822316       1 shared_informer.go:270] caches populated
边端自治重启后，应用访问k8s api报错
W0414 02:51:19.892669    2363 reflector.go:324] pkg/controller/virtinformers.go:331: failed to list *v1.VirtualMachineInstance: can not cache for go-http-client list virtualmachineinstances: /apis/kubevirt.io/v1alpha3/virtualmachineinstances?labelSelector=kubevirt.io%2FnodeName+in+%28i-m6ak5dfy%29&limit=500&resourceVersion=0
E0414 02:51:19.892705    2363 reflector.go:138] pkg/controller/virtinformers.go:331: Failed to watch *v1.VirtualMachineInstance: failed to list *v1.VirtualMachineInstance: can not cache for go-http-client list virtualmachineinstances: /apis/kubevirt.io/v1alpha3/virtualmachineinstances?labelSelector=kubevirt.io%2FnodeName+in+%28i-m6ak5dfy%29&limit=500&resourceVersion=0
W0414 02:51:19.894019    2363 reflector.go:324] pkg/controller/virtinformers.go:331: failed to list *v1.VirtualMachineInstance: can not cache for go-http-client list virtualmachineinstances: /apis/kubevirt.io/v1alpha3/virtualmachineinstances?labelSelector=kubevirt.io%2FmigrationTargetNodeName+in+%28i-m6ak5dfy%29&limit=500&resourceVersion=0

**Comment by rambohe-ch** [comment]
@yinlimi It looks that yurthub has not cached metadata for your clients, so your client can not get metadata from yurthub cache when cloud-edge disconnected.

and you can check the yurthub faq tutorial number 13: https://openyurt.io/zh/docs/faq/yurthub/

**Comment by yinlimi** [comment]
修改yurt-hub-cfg配置cache_agents: '*'，重启了edge节点，发现cache确实多了一些缓存，但是yurt_hub log 有报错
E0414 07:07:55.143773       1 loadbalancer.go:390] lb failed to cache req go-http-client watch virtualmachineinstances: https://192.168.203.27:6443/apis/kubevirt.io/v1alpha3/virtualmachineinstances?allowWatchBookmarks=true&labelSelector=kubevirt.io%2FnodeName+in+%28i-m6ak5dfy%29&resourceVersion=5525869&timeoutSeconds=308&watch=true in local cache, EOF
断网重启edge设备后，应用访问k8s api还是报错

**Comment by rambohe-ch** [comment]
> ![da3e224de693a5a0425ccb575a5043e1](https://user-images.githubusercontent.com/129256128/232416400-28c9315a-91fe-4d2e-9ae1-0ee365f2a627.png) 这里导致请求list失败

@yinlimi Yurthub will return all metadata under `/etc/kubernetes/cache/{componentName}/{resource}` directory for the list request, so list request with the same selectors can be supported to cache because these list requests have the same response.

on the other hand, we also recommend that a client should use sharedInformer to list/watch resource from kube-apiserver, and not use multiple list/watch requests to get one kind of resource.

**Comment by yinlimi** [comment]
谢谢解答
