### ISSUE TITLE
[feature request] support yurtadm init command based on sealer

### ISSUE THREAD

**Issue by YTGhost** [openyurtio/openyurt#1392]
**What would you like to be added**:
OpenYurt is an open-source project in the field of cloud-native computing that enables the extension of Kubernetes clusters to edge devices. However, currently, the OpenYurt cluster can only be installed manually, and we lack a unified installation method for quick and convenient deployment of a high-availability OpenYurt cluster. The [Sealer](https://github.com/sealerio/sealer) project provides a new approach to delivering distributed applications by packaging the Kubernetes cluster and all application dependencies into a single Sealer Image, reducing deployment difficulty and complexity.

There have been some progress in the 2022 ASOC, which can be viewed [here](https://github.com/openyurtio/openyurt/issues/856). However, the implementation is not yet quite refined. For example, the generation of Sealer Image has not been integrated into Openyurt's CI process, and the maintenance of the implemented `yurtadm init` command has been abandoned. Therefore, we need to take up this task anew.

**Why is this needed**:
This feature has the potential to greatly enhance the user-friendliness of Openyurt.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@YTGhost As we discussed in the community meeting, `yurtadm init` command will not be supported in the OpenYurt. and `yurtadm init` command has been removed in the #1537 . so i will close this issue.
