### ISSUE TITLE
[feature request]Support rollback for StaticPod

### ISSUE THREAD

**Issue by xavier-hou** [openyurtio/openyurt#1410]
**What would you like to be added**:
Support CR of `StaticPod`(a kind of workload which represents static pod) to roll back to specific version.

**Why is this needed**:
We can use `kubectl rollout` to roll back some common workloads in K8s, such as `daemonset` and `deployment`. As workload, `StaticPod` also need to support this feature. Currently, we have add some fields relevant to this feature in `StaticPod Spec`.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@xavier-hou Very appreciate for your idea to support rollback feature for StaticPod. i agree with you that rollback is a convenient feature for workloads.
