### ISSUE TITLE
[Discussion]discussion on archiving yurt-app-manager, raven-controller-manager, yurt-app-manager-api 

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1414]
**What would you like to be added**:
As you known, we have migrated controllers, webhooks, and apis from these repos(yurt-app-manager, raven-controller-manager, yurt-app-manager-api ) to yurt-manager component in openyurtio/openyurt repo.

see the [detail information](https://github.com/openyurtio/openyurt/issues/1067) for context.

At present, controllers and webhooks migration almost have been completed, so it is convenient to manage OpenYurt by archiving these repos.

- https://github.com/openyurtio/yurt-app-manager
- https://github.com/openyurtio/raven-controller-manager
- https://github.com/openyurtio/yurt-app-manager-api

**Why is this needed**:
stop pull requests and issue discussion for these repos because these repos will not be maintained.

**others**
/kind feature

**Comment by YTGhost** [comment]
Yes, we should archive these repositories and note in the Readme that we have migrated these components to yurt-manager component in openyurtio/openyurt repo.

**Comment by Congrool** [comment]
LGTM, archiving repo also reduce our work, such as maintaining doc of previous version, links in which will become invalid if we make these repo private.

**Comment by rambohe-ch** [comment]
All these three repos: yurt-app-manager, raven-controller-manager, yurt-app-manager-api have been archived, so i will close this issue.
