### ISSUE TITLE
yurtctl convert --provider minikube timeout

### ISSUE THREAD

**Issue by luhaopei** [openyurtio/openyurt#142]
os:centos 7 k8s:v1.16.0
[bearlu@control-plane amd64]$ ./yurtctl convert --provider minikube
I1115 12:04:28.705547    4730 convert.go:217] mark minikube as the edge-node
I1115 12:04:28.713233    4730 convert.go:217] mark minikube-m02 as the edge-node
I1115 12:04:28.764969    4730 convert.go:285] deploying the yurt-hub and resetting the kubelet service...
E1115 12:06:28.800491    4730 util.go:288] fail to run servant job(yurtctl-servant-convert-minikube): wait for job to be complete timeout
E1115 12:06:28.813800    4730 util.go:288] fail to run servant job(yurtctl-servant-convert-minikube-m02): wait for job to be complete timeout
I1115 12:06:28.813852    4730 convert.go:295] the yurt-hub is deployed

**Comment by charleszheng44** [comment]
will upload the openyurt container image to aliyun registry
