### ISSUE TITLE
unable to get podCIDR，unable to list calico blockaffinity

### ISSUE THREAD

**Issue by succw** [openyurtio/openyurt#1434]
E0508 02:05:48.362747       1 gateway_controller.go:180] "unable to get podCIDR" err="ravenl3-gateway: unable to list calico blockaffinity: no kind is registered for the type v3.BlockAffinityList in scheme \"pkg/runtime/scheme.go:100\"" 
E0508 02:05:48.362782       1 controller.go:317] setup/controller/ravenl3-gateway "msg"="Reconciler error" "error"="ravenl3-gateway: unable to list calico blockaffinity: no kind is registered for the type v3.BlockAffinityList in scheme \"pkg/runtime/scheme.go:100\"" "name"="enterprise-9999" "namespace"="" 

calico: v3.20.0
k8s: v1.23.6

**Comment by luckymrwang** [comment]
`raven-controller-manager` was migrated  from [raven-controller-manager](https://github.com/openyurtio/raven-controller-manager) to [openyurt](https://github.com/openyurtio/openyurt), and the related calico scheme was missing. I will fix it later.
If you want to use `raven-controller-manager`, you can temporarily use [raven-controller-manager](https://github.com/openyurtio/raven-controller-manager) as a replacement for it.
