### ISSUE TITLE
[feature request] provide `--register-node` option for yurtadm

### ISSUE THREAD

**Issue by siredmar** [openyurtio/openyurt#1438]
**What would you like to be added**:
I'd like to have the `--register-node` option for yurtadm join.

**Why is this needed**:
This way it is possible to create a node resource and taint it before the node is connected to the cluster thus preventing the scheduler from placing undesired workload on the node diretcly after the node joined.

See this for reference: https://kubernetes.io/docs/concepts/architecture/nodes/#manual-node-administration

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@siredmar Thanks for raising issue. It seems that `--register-node` parameter is deprecated in kubelet, and it is recommended to set field `registerNode` in KubeletConfiguration. 

At present, `KubeletConfiguration` is supported in yurtadm, so you can configure `KubeletConfiguration` configmap for modifying node registration.

**Comment by rambohe-ch** [comment]
@YTGhost Do you have any other comments?

**Comment by YTGhost** [comment]
> At present, KubeletConfiguration is supported in yurtadm, so you can configure KubeletConfiguration configmap for modifying node registration.

Yes, because `yurtadm join` currently integrates with the `kubeadm` binary and uses the `kubeadm join` command directly, during the kubeadm join run, it will be download the `kubelet-config` Configmap from the cluster and writes it to `/var/lib/kubelet/config.yaml`. So I think you can configure the `kubelet-config` Configmap, in detail, according to this [doc](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/#kubelet-config-k8s-io-v1beta1-KubeletConfiguration), you need to configure the fields `registerWithTaints` and `registerNode`, that should be enough for your needs.

**Comment by siredmar** [comment]
@YTGhost wil it overwrite `/var/lib/kubelet/config.yaml` if it pre-exists before executing `yurtadm join`?

**Comment by YTGhost** [comment]
> @YTGhost wil it overwrite `/var/lib/kubelet/config.yaml` if it pre-exists before executing `yurtadm join`?

Yes, it will overwrite it. You can see the code in [here](https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/phases/kubelet/config.go#L160)

**Comment by huiwq1990** [comment]
@rambohe-ch @YTGhost By the way, how about to expose [kubeadmconfig](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/) to `yurtadm join`, as I want to set `network-plugin` parameter etc.

**Comment by rambohe-ch** [comment]
> @rambohe-ch @YTGhost By the way, how about to expose [kubeadmconfig](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/) to `yurtadm join`, as I want to set `network-plugin` parameter etc.

@YTGhost Do you have any comments about `kubeadm config` for `yurtadm join` command?

**Comment by YTGhost** [comment]
Currently `yurtadm` uses command line arguments to build the kubeadm config file. Do you mean that yurtadm exposes a command line argument to point to the user's own custom kubeadm config file? If the user sets this parameter, then the process of building the kubeadm config file inside yurtadm is skipped.

**Comment by huiwq1990** [comment]
> Currently `yurtadm` uses command line arguments to build the kubeadm config file. Do you mean that yurtadm exposes a command line argument to point to the user's own custom kubeadm config file? If the user sets this parameter, then the process of building the kubeadm config file inside yurtadm is skipped.

yes, yurtadm join paramters could keep too, and overwrite kubeadmconfig file.

**Comment by YTGhost** [comment]
> > Currently `yurtadm` uses command line arguments to build the kubeadm config file. Do you mean that yurtadm exposes a command line argument to point to the user's own custom kubeadm config file? If the user sets this parameter, then the process of building the kubeadm config file inside yurtadm is skipped.
> > @YTGhost yes, yurtadm join paramters could keep too, and overwrite kubeadmconfig file.

I think it is a good idea, WDYT? @rambohe-ch

**Comment by rambohe-ch** [comment]
> > > Currently `yurtadm` uses command line arguments to build the kubeadm config file. Do you mean that yurtadm exposes a command line argument to point to the user's own custom kubeadm config file? If the user sets this parameter, then the process of building the kubeadm config file inside yurtadm is skipped.
> > > @YTGhost yes, yurtadm join paramters could keep too, and overwrite kubeadmconfig file.
> 
> I think it is a good idea, WDYT? @rambohe-ch

@YTGhost agree +1, but i think we also need to add some parameters to kubelet even if when kubeadm config file is specified. for example: `--rotate-certificates=false, --node-labels=openyurt.io/is-edge-worker=true`

**Comment by YTGhost** [comment]
> but i think we also need to add some parameters to kubelet even if when kubeadm config file is specified. for example: --rotate-certificates=false, --node-labels=openyurt.io/is-edge-worker=true

I understand that this doesn't seem to work well, for example the two parameters you mention here, `kubeadm join` doesn't expose the corresponding parameters.

I was thinking that perhaps we could provide a template to the user in which several parameters such as the ones you mention are populated in advance.

For more information on how this template is provided, perhaps we can refer to the `kubeadm config` command. We can create a new `yurtadm config` command and the user can print the default `yurtadm join` configuration by using `yurtadm config print join-defaults`. WDYT? @rambohe-ch

**Comment by rambohe-ch** [comment]
> > but i think we also need to add some parameters to kubelet even if when kubeadm config file is specified. for example: --rotate-certificates=false, --node-labels=openyurt.io/is-edge-worker=true
> 
> I understand that this doesn't seem to work well, for example the two parameters you mention here, `kubeadm join` doesn't expose the corresponding parameters.
> 
> I was thinking that perhaps we could provide a template to the user in which several parameters such as the ones you mention are populated in advance.
> 
> For detail on how this template is provided, perhaps we can refer to the `kubeadm config` command. We can create a new `yurtadm config` command and the user can print the default `yurtadm join` configuration by using `yurtadm config print join-defaults`. WDYT? @rambohe-ch

@YTGhost I think that `yurtadm join` should use `kubeadm-config` configmap instead of adding a new  parameter `--config-file`. so it is not need to add a new command `yurtadm config`.

**Comment by rambohe-ch** [comment]
@huiwq1990 I think we should improve `yurtadm join` command so `kubeadm-config` configmap can be used in the node joining phase. so it is not need to add a parameter to overwrite `kubeadm config` in `yurtadm join` because user can edit `kubeadm-config` configmap directly.

**Comment by rambohe-ch** [comment]
@siredmar @huiwq1990 I think that the problems in this issue have been solved, so i will close this issue.
And you can feel free to reopen this issue or create new issues if you need it.
