### ISSUE TITLE
[OSPP 2023]feat: Automated installation and deployment platform based on dashboard

### ISSUE THREAD

**Issue by luc99hen** [openyurtio/openyurt#1441]
## Motivation
OpenYurt is an open source project in the edge cloud native domain, which aims to simplify the management of distributed edge resources by providing a unified platform for Kubernetes clusters. However, the current installation and deployment process of OpenYurt can be challenging for non-specialists, hindering the adoption of this powerful tool. To address this issue, we want to create an automated platform for the installation and deployment of the OpenYurt based on a dashboard, making it more accessible for users to manage and utilize OpenYurt capabilities.

## Objectives
The primary objectives of this project are to:

1. Develop a one-command solution to install and deploy the OpenYurt Dashboard on a prepared Kubernetes cluster, providing users with the dashboard UI.
2. Allows users to select OpenYurt components for automatic installation and deployment.
3. Enable management and usage of OpenYurt capabilities (e.g., node pool management and node access) through the Dashboard interface.

## Output Requirements

1. Design documentation and code implementation for the installation and deployment automation platform.
2. OpenYurt installation and deployment documentation, to guide users on how to use it to install OpenYurt.

## Related issues
1. https://github.com/openyurtio/yurt-dashboard/issues/41
2. https://summer-ospp.ac.cn/org/prodetail/235fc0263?lang=en&list=pro

**Comment by 401lrx** [comment]
/assign @401lrx
https://github.com/openyurtio/openyurt/pull/1664
