### ISSUE TITLE
[Question]How about rename auto upgrade strategy to AdvancedRollingUpdate

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1450]
**What happened**:
 The newly added upgrade models: auto and ota are convenient way for user upgrade DaemonSet and StaticPod on edge nodes, but the name convention: auto is not easy to understand for users.
 
    - auto: rolling update pods of DaemonSet or StaticPod, but skip pods on NotReady nodes. And when NotReady nodes turn to Ready,  pods on these nodes will be upgraded automatically.

 so i think that `auto` is also a rolling update strategy, but with some advanced features. so how about rename `auto` to `AdvancedRollingUpdate`? i think that new name(AdvancedRollingUpdate) is more understandable for users.

by the way, `ota` upgrade strategy should be upper-cased, so how about rename `ota` to `OTA`?

**What you expected to happen**:
rename newly added upgrade strategy as following:
- auto --> AdvancedRollingUpdate
- ota --> OTA

**How to reproduce it (as minimally and precisely as possible)**:
NA

**Anything else we need to know?**:
NA

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by JameKeal** [comment]
I agree this suggest, the deployment in native kubernetes was use RollingUpdate, Recreate and Custom for it update strategy, and DaemonSet is RollingUpdate and OnDelete, it's straightaway
