### ISSUE TITLE
Fail to upgrade static pod, open /etc/kubernetes/manifests/yurt-hub.yaml: no such file or directory

### ISSUE THREAD

**Issue by succw** [openyurtio/openyurt#1454]
kube-system/yurt-static-pod-upgrade-worker-gw-edge-node-9999-2-78c8d9ff8:upgrade-worker

I0512 08:49:04.665999    3631 upgrade.go:35] FLAG: --kubeconfig=""                                                                                                                        
I0512 08:49:04.666003    3631 upgrade.go:35] FLAG: --manifest="yurt-hub"                                                                                                                  
I0512 08:49:04.666006    3631 upgrade.go:35] FLAG: --mode="auto"                                                                                                                          
I0512 08:49:04.666010    3631 upgrade.go:35] FLAG: --name="yurt-hub-9999-2"                                                                                                  
I0512 08:49:04.666014    3631 upgrade.go:35] FLAG: --namespace="kube-system"                                                                                                              
I0512 08:49:04.666017    3631 upgrade.go:35] FLAG: --timeout="2m0s"                                                                                                                       
I0512 08:49:04.666167    3631 upgrade.go:87] Create upgrade space success                                                                                                                 
I0512 08:49:04.666289    3631 upgrade.go:105] Auto prepare upgrade manifest success                                                                                                       
F0512 08:49:04.666314    3631 upgrade.go:48] Fail to upgrade static pod, open /etc/kubernetes/manifests/yurt-hub.yaml: no such file or directory                                          
goroutine 1 [running]:                                                                                                                                                                    
k8s.io/klog/v2.stacks(0x1)                                                                                                                                                                
    /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1026 +0x8a                                                                                                                                  
k8s.io/klog/v2.(*loggingT).output(0x2025980, 0x3, {0x0, 0x0}, 0xc0007f6d90, 0x0, {0x1928a18?, 0xc0001ff850?}, 0x0?, 0x0)                                                                  
    /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:975 +0x648                                                                                                                                  
k8s.io/klog/v2.(*loggingT).printf(0x0?, 0x0?, {0x0, 0x0}, {0x0, 0x0}, {0x146054a, 0x1e}, {0xc0001ff850, 0x1, ...})                                                                        
    /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:753 +0x1e5                                                                                                                                  
k8s.io/klog/v2.Fatalf(...)                                                                                                                                                                
    /go/pkg/mod/k8s.io/klog/v2@v2.9.0/klog.go:1514                                                                                                                                        
github.com/openyurtio/openyurt/cmd/yurt-node-servant/static-pod-upgrade.NewUpgradeCmd.func1(0xc0007e5800?, {0xc00009c230?, 0x5?, 0x5?})                                                   
    /build/cmd/yurt-node-servant/static-pod-upgrade/upgrade.go:48 +0x26d                                                                                                                  
github.com/spf13/cobra.(*Command).execute(0xc0007e5800, {0xc00009c1e0, 0x5, 0x5})                                                                                                         
    /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847                                                                                                                       
github.com/spf13/cobra.(*Command).ExecuteC(0xc0007e4600)                                                                                                                                  
    /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bc                                                                                                                      
github.com/spf13/cobra.(*Command).Execute(...)                                                                                                                                            
    /go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992                                                                                                                              
main.main()                                                                                                                                                                               
    /build/cmd/yurt-node-servant/node-servant.go:55 +0x428

**Comment by rambohe-ch** [comment]
@succw Thanks for raising issue. would you be able to check what files are under the `/etc/kubernetes/manifests` directory on `9999-2` node?

**Comment by succw** [comment]
It should be yurthub. yaml, not yurt-hub. yaml

**Comment by rambohe-ch** [comment]
@y-ykcir sorry, i will make pull request to fix this bug right away.

**Comment by y-ykcir** [comment]
Ok, it seems my mistake in [here](https://github.com/openyurtio/openyurt/blob/578a91bcf7b05dd4d7b53ba8245b84d5b8f0e02f/pkg/yurtadm/util/yurthub/yurthub.go#LL76C73-L76C73)
