### ISSUE TITLE
[feature request]how about rename StaticPod to StaticSet

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1456]
**What would you like to be added**:
The newly added CRD `StaticPod` is used as a workload for managing static pods on nodes, and this name is very confused for users, because the pods for this workload are called static pod in kubernetes, but the workload is also called `StaticPod`,  so it is very hard to distinguish which `static pod` you are talking about.

I think it is a good idea for us that we can refer to DaemonSet to name `static pod`, so how about rename `StaticPod` to `StaticSet`?

by the way, the name for the configmap that used for storing template of static pod can also be improved as `static-set-{ins.Name}`.

**others**
/kind feature

**Comment by xavier-hou** [comment]
How about rename to `YurtStaticSet`, which is more in line with OpenYurt.

**Comment by rambohe-ch** [comment]
> @rambohe-ch How about rename to `YurtStaticSet`, which is more in line with OpenYurt.

@xavier-hou agree +1, it is a good idea to be consistent with the naming rules of YurtAppSet, YurtAppDaemon CRDs.
