### ISSUE TITLE
[feature request]improve yurthub artifacts installation

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1474]
**What would you like to be added**:
In the tutorial: https://openyurt.io/docs/next/installation/manually-setup#32-install-yurthub-artifacts, if user has not set `kubernetesServerAddr` value in yurthub artifacts installation, `yurtadm join` command should use the correct kubernetes server address to replace `https://127.0.0.1:6443`.

**Why is this needed**:
It is easy for user to forget to set `kubernetesServerAddr` value when install yurthub artifacts, and this will cause the execution of the `yurtadm join` command to fail.

**others**
/kind feature

**Comment by Lan-ce-lot** [comment]
@rambohe-ch I want to try this.
