### ISSUE TITLE
[feature request]support SIGUSR1 signal for yurthub component.

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1475]
**What would you like to be added**:
please use `runtime.Stack` to support SIGUSR1 signal for yurthub somponent.

**Why is this needed**:
In order to improve the efficiency of debugging yurthub when component is blocked.

**others**
/kind feature

**Comment by y-ykcir** [comment]
I'd like to do this.
/assign @y-ykcir

**Comment by rambohe-ch** [comment]
@y-ykcir you can refer to the implementation in containerd, the code is here: https://github.com/containerd/containerd/blob/main/cmd/containerd/command/main.go#L359-L384
