### ISSUE TITLE
[feature request]how about rename pool-coordinator to yurt-coordinator

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1482]
**What would you like to be added**:
Except for the pool-coordinator component, the naming convention for each component is yurt-xxx, like yurt-manager, yurtadm, yurthub, etc. so it is easy for user to understand components in openyurtio/openyurt repo if we rename pool-coordinator to yurt-coordinator.

**Why is this needed**:
Unify the naming rules of each component in openyurtio/openyurt repo, it is more understandable for end users.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@gnunu @JameKeal @Congrool @fujitatomoya WDYT?

**Comment by JameKeal** [comment]
agree, it feels that the components in openyurt should be unified, so the understanding cost is lower, and also for newly added components

**Comment by LaurenceLiZhixin** [comment]
I agree with you.

**Comment by fujitatomoya** [comment]
sgtm, especially `grep`ing the worload based on component name such as `yurt` would be helpful in practice.

**Comment by gnunu** [comment]
agree +1

**Comment by JameKeal** [comment]
If necessary to update, you can assign it to me. @rambohe-ch
