### ISSUE TITLE
kubectl logs and exec Error from server (ServiceUnavailable)

### ISSUE THREAD

**Issue by betterxu** [openyurtio/openyurt#1496]
my k8s cluster has 3 master so ,i build 3 tunnel server
sometimes is normal,sometimes is error when i kubectl logs -f edge pod
Error from server (ServiceUnavailable): the server is currently unable to handle the request ( pods/log yurt-tunnel-agent-gmj6v)
好像只有一个 tunnel server节点能和agent正常通信，其他两个不行，导致有时候正常有时候不正常，我的版本是0.7.1

tunnel server A:
I0524 14:01:51.602414       1 tracereq.go:134] start handling request GET https://:10250/containerLogs/kube-system/yurt-hub-pcz2a245-219/yurt-hub?follow=true, from :1623 to :10250
E0524 14:01:51.602635       1 tunnel.go:74] "currently no tunnels available" err="No backend available"
E0524 14:01:51.602759       1 interceptor.go:136] fail to setup the tunnel: fail to setup TLS handshake through the Tunnel: write unix @->/tmp/interceptor-proxier.sock: write: broken pipe
I0524 14:01:51.602778       1 tracereq.go:138] stop handling request GET https://:10250/containerLogs/kube-system/yurt-hub-pcz2a245-219/yurt-hub?follow=true, request handling lasts 348.086µs
I0524 14:02:15.742039       1 iptables.go:539] dnat ports changed, []
tunnel server B;
I0524 13:21:50.706327       1 tunnel.go:128] "Starting proxy to host" host=":10250" agentID="" connectionID=24
I0524 13:22:04.449080       1 interceptor.go:306] chunked request(https://:10250/containerLogs/cattle-system/cattle-cluster-agent-5b6dd6cb4b-skcfl/cluster-register?follow=true) to agent(:10250) closed by cloud client, context canceled
I0524 13:22:04.449172       1 tracereq.go:138] stop handling request GET https://:10250/containerLogs/cattle-system/cattle-cluster-agent-5b6dd6cb4b-skcfl/cluster-register?follow=true, request handling lasts 13.761047594s
I0524 13:22:04.449343       1 tunnel.go:141] "EOF from host" host=":10250" agentID="219" connID=24
I0524 13:22:04.467224       1 server.go:290] "Remove frontend for agent" agentID="219" connectionID=24

tunnel agent:
I0524 12:53:12.646667       1 client.go:382] "close connection" connectionID=4
I0524 12:53:16.076720       1 client.go:412] received dial request to tcp::10250 with random=6382800227808658932 and connID=5
I0524 12:53:18.021179       1 client.go:382] "close connection" connectionID=5
I0524 12:53:19.185402       1 client.go:412] received dial request to tcp::10250 with random=1598098976185383115 and connID=6
I0524 12:53:21.234001       1 client.go:382] "close connection" connectionID=6
I0524 12:53:21.896569       1 client.go:412] received dial request to tcp:10250 with random=5018949295715050020 and connID=7
I0524 12:53:22.615656       1 client.go:382] "close connection" connectionID=7
I0524 12:53:23.201429       1 client.go:412] received dial request to tcp::10250 with random=2568779411109623071 and connID=8
I0524 12:53:23.839972       1 client.go:382] "close connection" connectionID=8
I0524 12:53:25.149466       1 client.go:412] received dial request to tcp::10250 with random=4893789450120281907 and connID=9
I0524 12:53:26.028641       1 client.go:382] "close connection" connectionID=9
I0524 12:53:26.571570       1 client.go:412] received dial request to tcp::10250 with random=2338498362660772719 and connID=10
I0524 12:53:27.197643       1 client.go:382] "close connection" connectionID=10
I0524 12:53:27.700659       1 client.go:412] received dial request to tcp::10250 with random=7273596521315663110 and connID=11
I0524 12:53:28.274164       1 client.go:382] "close connection" connectionID=11
I0524 12:53:31.374469       1 client.go:412] received dial request to tcp::10250 with random=8121576815539813105 and connID=12
I0524 12:53:32.878201       1 client.go:382] "close connection" connectionID=12
I0524 12:53:33.830782       1 client.go:412] received dial request to tcp::10250 with random=8249030965139585917 and connID=13
I0524 12:53:35.089508       1 client.go:382] "close connection" connectionID=13
I0524 12:53:39.388149       1 client.go:412] received dial request to tcp:10.209.1.227:10250 with random=685213522303989579 and connID=14
I0524 12:53:40.797069       1 client.go:382] "close connection" connectionID=14
I0524 12:53:43.280946       1 client.go:412] received dial request to tcp::10250 with random=6281838661429879825 and connID=15
I0524 12:53:44.500124       1 client.go:382] "close connection" connectionID=15
I0524 12:53:57.498566       1 client.go:412] received dial request to tcp::10250 with random=6735196588112087610 and connID=16
I0524 12:54:00.746214       1 client.go:382] "close connection" connectionID=16
I0524 13:06:26.812926       1 client.go:412] received dial request to tcp::10250 with random=3235237269844622367 and connID=17
I0524 13:06:26.898184       1 client.go:382] "close connection" connectionID=17
I0524 13:06:39.923200       1 client.go:412] received dial request to tcp::10250 with random=8883393020643919152 and connID=18
I0524 13:06:39.989085       1 client.go:464] "connection read EOF" connID=18
I0524 13:06:39.989102       1 client.go:382] "close connection" connectionID=18
I0524 13:15:50.657062       1 client.go:412] received dial request to tcp::10250 with random=5200546064640301018 and connID=19
I0524 13:15:50.743305       1 client.go:382] "close connection" connectionID=19
I0524 13:16:09.877558       1 client.go:412] received dial request to tcp::10250 with random=8935091539206106276 and connID=20
I0524 13:16:09.943233       1 client.go:382] "close connection" connectionID=20
I0524 13:18:15.377662       1 client.go:412] received dial request to tcp::10250 with random=889032155449973530 and connID=21
I0524 13:18:16.832310       1 client.go:382] "close connection" connectionID=21
I0524 13:19:02.581176       1 client.go:412] received dial request to tcp::10250 with random=3108138781323191767 and connID=22
I0524 13:19:04.164844       1 client.go:382] "close connection" connectionID=22
I0524 13:19:06.584591       1 client.go:412] received dial request to tcp::10250 with random=3949956415341892322 and connID=23
I0524 13:19:14.105670       1 client.go:382] "close connection" connectionID=23
I0524 13:21:50.695720       1 client.go:412] received dial request to tcp:10250 with random=6230576165160159969 and connID=24
I0524 13:22:04.456511       1 client.go:382] "close connection" connectionID=24
I0524 14:04:13.602450       1 client.go:412] received dial request to tcp::10250 with random=392908508879011023 and connID=25

**Comment by rambohe-ch** [comment]
@betterxu According to @River-sh's response, you should only deploy one instance of yurt-tunnel-server, please scale down the replicas of yurt-tunnel-server and have a try. 

btw, i will close this issue. and you can feel free to reopen it if you need to do it.

**Comment by betterxu** [comment]
> 

but i have three master,when use kubectl logs command, and tunnel server instance is only one,the apiserver is loadbalance,The other two no tunnlserver masters cannot use rpc tunnel

**Comment by betterxu** [comment]
> tunnel-server does not support multiple instances

but i have three master,when use kubectl logs command, and tunnel server instance is only one,the apiserver is loadbalance,The other two no tunnlserver masters cannot use rpc tunnel
