### ISSUE TITLE
support Public Cloud k8s Distribution Installation Check or doc Recommended List

### ISSUE THREAD

**Issue by xuelangos** [openyurtio/openyurt#1498]
ex:  yurtadm install check list
or
https://openyurt.io/zh/docs/usage-conditions/resource-and-system-requirements
Indicate which public cloud distribution is supported

/kind feature

**Comment by rambohe-ch** [comment]
@xuelangos Thanks for raising issue. i think that OpenYurt is supported in all Public cloud k8s distribution, but you need to adjust the affinity of the components according to the k8s nodes.
