### ISSUE TITLE
[feature request] cleanup "yurt-manager" temporary dir after "local-up-openyurt"

### ISSUE THREAD

**Issue by xavier-hou** [openyurtio/openyurt#1510]
**What would you like to be added**:
Typically, we would like to use `make local-up-openyurt` command to create a local K8s cluster by `kind`.
During the deployment of `yurt-manager` componet, a temporary dir named `yurt-manager` will be created.
https://github.com/openyurtio/openyurt/blob/master/test/e2e/cmd/init/converter.go#L299

**Why is this needed**:
It's better to remove this dir in time, otherwise lots of unnecessary `yurt-manager` will accumulate in project.

**others**
/kind feature

**Comment by Lan-ce-lot** [comment]
I'd like to do this.
/assign @Lan-ce-lot
