### ISSUE TITLE
[feature request] Move account-controller into yurt-manager

### ISSUE THREAD

**Issue by luc99hen** [openyurtio/openyurt#1530]
**What would you like to be added**:
Accout controller is developed for experience center. User information of the platform is stored in the cluster through CRD. Account Controller is responsible for managing the creation and deletion of user accounts and related resources (e.g. namespace, certificates, etc). 

**Why is this needed**:
 It has been a private repo under the organization since developed. It needs to keep up with the version updates of the main repository. Therefore, I suggest to move it into yurt-manager as a controller which is closed by default. 

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@luc99hen I think it's a good idea to migrate `account controller` into yurt-manager, but how about make the following changes:
1. rename `account controller` to `tenant controller`
2. The tenant controller is not started by default in yurt-manager

**Comment by luc99hen** [comment]
> @luc99hen I think it's a good idea to migrate `account controller` into yurt-manager, but how about make the following changes:
> 
> 1. rename `account controller` to `tenant controller`
> 2. The tenant controller is not started by default in yurt-manager

Agree with 2. For the first point, will `tenant` be misleading? It seems like a controller provide multi-tenant ability.

**Comment by rambohe-ch** [comment]
> > @luc99hen I think it's a good idea to migrate `account controller` into yurt-manager, but how about make the following changes:
> > 
> > 1. rename `account controller` to `tenant controller`
> > 2. The tenant controller is not started by default in yurt-manager
> 
> Agree with 2. For the first point, will `tenant` be misleading? It seems like a controller provide multi-tenant ability.

@luc99hen It seems that account and tenant have the same meaning for users in a cluster. but tenant is often used in Kubernetes cluster for multiple users.
