### ISSUE TITLE
[feature request] Remove yurtadm init command

### ISSUE THREAD

**Issue by YTGhost** [openyurtio/openyurt#1535]
**What would you like to be added**:
Remove `yurtadm init` command.

**Why is this needed**:
Since the `yurtadm init` command is no longer maintained and have some problem, it needs to be removed in order not to confuse yurtadm users.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@YTGhost Thank you for raising issue, I agree with you that we can remove yurtadm init command. go ahead.
