### ISSUE TITLE
[feature request] Support yurtadm config command

### ISSUE THREAD

**Issue by YTGhost** [openyurtio/openyurt#1536]
**What would you like to be added**:
Support the `yurtadm config` command to provide the user with the default `JoinConfiguration`.

**Why is this needed**:
As discussed in #1448, we need to give yurtadm join a `--config` option. this requires that we can somehow give the user a default config template, so this requirement wants to give the user a default config template using the new `yurtadm config` command.

The implementation of `yurtadm config` can be refer to `kubeadm config`.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@YTGhost Do you have any progress about this issue?

**Comment by YTGhost** [comment]
> @YTGhost Do you have any progress about this issue?

Sorry for the late reply, I plan to finish it this weekend.

**Comment by rambohe-ch** [comment]
> > @YTGhost Do you have any progress about this issue?
> 
> Sorry for the late reply, I plan to finish it this weekend.

@YTGhost It's a good job, maybe we can include it in release v1.4.
