### ISSUE TITLE
[feature request] Add more information about availability in the status of the yurtappset

### ISSUE THREAD

**Issue by LavenderQAQ** [openyurtio/openyurt#1543]
**What would you like to be added**:
IoT-sig currently deploys PlatformAdmin through yurtappset. We use yurtappset to distribute various components required by edgex framework to multiple nodepools. PlatformAdmin and yurtappset form a many-to-many relationship. But at the same time this causes a problem, when the user is using multiple PlatformAdmin, we need to know the deployment of each PlatformAdmin, and the status provided by the current yurtappset is not satisfied.
For this, we may need some support from yurtappset. We hope yurtappset can output whether the component of a nodepool is ready in status (for example, the component of Beijing nodepool is Ready, and the component of Shanghai nodepool is NotReady).

**Why is this needed**:
Let me take a simple example, suppose there are two PlatformAdmin, one belongs to beijing nodepool and the other belongs to shanghai nodepool, and they need to deploy two components redis and consul respectively. Below is a diagram of their deployment:
<img width="724" alt="image" src="https://github.com/openyurtio/openyurt/assets/33485524/1dc010f4-484b-46f7-95fb-d0e058283a40">
PlatformAdmin also needs to know which components have been successfully deployed, as shown in the following figure:
![image](https://github.com/openyurtio/openyurt/assets/33485524/95abb02c-fbbe-488f-a4de-914b477d0e02)
Next, we assume that the redis of shanghai nodepool suddenly crashes, and then the readyReplicas of the upper yurtappset will become 1. However, since we cannot know from the yurtappset which nodepool's redis failed, so we cannot find PlatformAdmin where deployment failed. At present, the code logic of IoT-sig will cause both PlatformAdmin to become NotReady (in fact, beijing PlatformAdmin is normal), which I think is very unreasonable. A problem with one nodepool component cannot affect the state of another nodepool. This problem also existed in the previous yurt-edgex-manager, see [[BUG] Edgex READYDEPLOYMENT quantity in the case of multiple Edgex instance has a cascading effect](https://github.com/openyurtio/yurt-edgex-manager/issues/103).
<img width="737" alt="image" src="https://github.com/openyurtio/openyurt/assets/33485524/0c8f6648-fac7-44eb-af67-58db1fca4f50">
In addition, when I deploy a new PlatformAdmin, a similar cascading problem occurs, because I don't know which nodepool component is deployed, and all the PlatformAdmin states.
![image](https://github.com/openyurtio/openyurt/assets/33485524/72d6c9db-42fd-4aa9-ad04-4c0455892e10)

**others**
I have considered directly getting the status of the deployment under yurtappset, but this may bring a lot of extra visits to PlatformAdmin, and currently PlatformAdmin does not have any code to control the deployment, I am not inclined to this approach.
/kind feature

**Comment by rambohe-ch** [comment]
@vie-serendipity PTAL

**Comment by vie-serendipity** [comment]
From what I understand, there is a need to contain information about unavailable nodepools in the status of YurtAppSet in case that one nodepool affects another. So one slice in the status of YurtAppSet may be enough to solve this problem, like NotReadyApp []string. Is it necessary to involve some other information?

**Comment by vie-serendipity** [comment]
From what I understand, there is a need to contain information about unavailable nodepools in the status of YurtAppSet in case that one nodepool affects another. So one slice in the status of YurtAppSet may be enough to solve this problem, like NotReadyApp []string. Is it necessary to involve some other information?

**Comment by LavenderQAQ** [comment]
@vie-serendipity  I have some ideas here, and this is now the status field:
```yaml
status:
  ...
  currentRevision: edgex-redis-55d684687
  observedGeneration: 1
  poolReplicas:
    beijing: 1
    shanghai: 2
  readyReplicas: 3
  replicas: 3
  templateType: Deployment
```
This one has a field called `poolReplicas`, and I think it's possible to extend the field of `poolReadyReplicas` and reference the structure of `poolReplicas`. Just like:
```yaml
status:
  ...
  currentRevision: edgex-redis-55d684687
  observedGeneration: 1
  poolReplicas:
    beijing: 1
    shanghai: 2
  poolReadyReplicas:
    beijing: 1
    shanghai: 1
  readyReplicas: 2
  replicas: 3
  templateType: Deployment
```
I think that simply exporting notReady slice may lead to insufficient information in the future. FYI.

**Comment by LavenderQAQ** [comment]
@vie-serendipity Of course, for our current situation, notReady slice is sufficient. You could think about whether you want to export specific quantities.

**Comment by vie-serendipity** [comment]
@LavenderQAQ Given the larger number of nodepools, listing all nodepools may be overloaded. So just focusing on the unavailable nodepools may be better? Is it necessary to show detailed replicas, readyReplicas, and some condition information of unavailable nodepools?

**Comment by LavenderQAQ** [comment]
@vie-serendipity Indeed, for our iot side, just listing notReady is enough for us.

**Comment by LavenderQAQ** [comment]
@vie-serendipity But there seems to be something trouble with the slice structure. If we're using it and we get a slice in the yurtappset and we want to quickly determine if a nodepool is ready, we need to do `O(n)` traversal every time. For more nodepool scenarios, this is actually a relatively large cost.

**Comment by LavenderQAQ** [comment]
@vie-serendipity  Whether this issue can be turned off?

**Comment by vie-serendipity** [comment]
@LavenderQAQ yeah
