### ISSUE TITLE
[feature request]  pool coordinator memory optimizations

### ISSUE THREAD

**Issue by batthebee** [openyurtio/openyurt#1546]
**What would you like to be added**:

I have a node with ubuntu server 22.04 set up as an edge node. I noticed a high memory consumption by openyurt. 

After a few tests I was able to trace the whole thing back to the pool coordinator. 

After joining the node, kubernetes and openyurt need ~170mb memory. Actually a very decent value.

After I created a nodepool for the node, the memory usage increased to ~620MB, an increase of almost 450MB. Mainly the increase was due to the kube-apiserver(>250MB) and etcd(>50MB).

**Why is this needed**:

I would like to use openyurt on nodes with 1GB RAM if possible. Are there any ways/approaches to significantly reduce the memory consumption at least from the kube-apiserver? A reduction would also be great for nodes with 2GB ram, since more is then available for the actual workload.

 I already looked through the arguments and experimented a bit, but found nothing.

**others**
/kind feature

**Comment by batthebee** [comment]
@rambohe-ch Absolutely!

I just need some help from your side. At the moment I am looking for a starting point.  Do you have any documentation on how the pool coordinator works? 
And do you perhaps already have one or the other parameter for optimization in mind?

Thanks!

**Comment by batthebee** [comment]
I have already found the [pool coordinator docs](https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20220307-nodepool-governance-capability.md) . Great Work!

**Comment by batthebee** [comment]
I found that you can also disable the pool coordinator and still continue to work with nodepools. This is enough for my current use case. 

Nevertheless, I would like to try my hand at optimization. Where would you start with this? 

@rambohe-ch some ideas?

**Comment by rambohe-ch** [comment]
> I found that you can also disable the pool coordinator and still continue to work with nodepools. This is enough for my current use case.
> 
> Nevertheless, I would like to try my hand at optimization. Where would you start with this?
> 
> @rambohe-ch some ideas?

@batthebee I think that we can focus on the kube-apiserver component at first, and we can find out the reason where memory is used in kube-apiserver.
1. check the detail logs of kube-apiserver, and find out what data has been posted to kube-apiserver. then we can consider that some requests can be reduced or not in yurthub.
2. we can use `pprof tool of golang` to check memory of kube-apiserver, and find out where memory is used
3. i think that we can configure some parameters of kube-apiserver to control the cache of kube-apiserver, but maybe we need to read the source code of kube-apiserver.

Memory optimization is a challenging task and we can progress step by step to achieve our goals.
