### ISSUE TITLE
[feature request]improve service topology controller by using client.Client instead of kubernetes.Interface

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1559]
**What would you like to be added**:
In service topology controller, `kubernetes.Interface` is used for updating annotations of [endpoints](https://github.com/openyurtio/openyurt/blob/master/pkg/controller/servicetopology/adapter/endpoints_adapter.go#L49), [v1.endpointslices](https://github.com/openyurtio/openyurt/blob/master/pkg/controller/servicetopology/adapter/endpointslicev1_adapter.go#L61), [v1beta1.endpointslices](https://github.com/openyurtio/openyurt/blob/master/pkg/controller/servicetopology/adapter/endpointslicev1beta1_adapter.go#L61).

and it is recommended to use `client.Client` instead of `kubernetes.Interface` to update K8s object in `yurt-manager` controller because controller-runtime is imported by yurt-manager.

**Why is this needed**:
it is recommended to use `client.Client` instead of `kubernetes.Interface` to update K8s object in `yurt-manager` controller because controller-runtime is imported by yurt-manager.

**others**
/kind feature

**Comment by zhy76** [comment]
I want to try this.

**Comment by JameKeal** [comment]
> I want to try this.

Thanks for your participation. /assign @zhy76
