### ISSUE TITLE
Do we plan to push the image to other registry

### ISSUE THREAD

**Issue by vincent-pli** [openyurtio/openyurt#156]
Since the docker hub introduce the rate limit, `deployment` has no pull secret, so be treat as Unauthenticated request, and for Unauthenticated, docker hub will mark it by IP, that's bad for a cluster use a single public IP for internet access.

So, do we have plan to push the image to other registry, like gcr.io or whatever has no such limitation.

**Comment by charleszheng44** [comment]
That could be a problem. But we do not have a plan to hold images in a place other than docker hub and aliyun container registry for now. For the scenario you mentioned, a potential workaround would be pulling the openyurt images and storing them in a private registry or whatever registry that could not throttle back the download rate. Then specifying the image path when running the `yurtctl convert`.

**Comment by rambohe-ch** [comment]
@vincent-pli Thank you for filing issue.
to better use OpenYurt for domestic users, we recently hosted images of OpenYurt on aliyun container registry(ACR). please refer to the link below for details.
https://github.com/alibaba/openyurt/blob/master/docs/tutorial/yurtctl.md#1-failure-due-to-pulling-image-timeout

**Comment by huang12zheng** [comment]
May have nothing to do with the issue, but it's also an idea or sumup.

> a potential workaround would be pulling the openyurt images and storing them in a private 
registry or whatever registry that could not throttle back the download rate

Personally, if there are many nodes, there should be an edge Registry first.
In this context,The image is first delivered from the cloud to the edge Registry, and then the node on the edge retrieves the image from the edge Registry

Of course, I think more of the scene is manually creating edge Registry.  
> pull all images on the node manually or use automation tools such as broadcastjob(from Kruise) in advance.

This is also mentioned in [yurtctl.md](https://github.com/alibaba/openyurt/blob/master/docs/tutorial/yurtctl.md#1-failure-due-to-pulling-image-timeout)
