### ISSUE TITLE
[Question] kubernetes >= 1.24 

### ISSUE THREAD

**Issue by batthebee** [openyurtio/openyurt#1567]
Hi Everybody, 

Kubernetes 1.23 is already deprecated. What is the status for kubernetes versions greater than 1.23? Have you already tried newer versions? Is there a migration planned in the near future? 

Thanks!

**Comment by rambohe-ch** [comment]
@batthebee yes, we plan to check and support K8s v1.24+ in the OpenYurt v1.4.0.
