### ISSUE TITLE
Consider github container registry

### ISSUE THREAD

**Issue by siredmar** [openyurtio/openyurt#1575]
Please consider moving away from docker hub do github container registry (https://github.com/features/packages#pricing)
Pricing is free for public repositories. 
The problem is, that docker has very limited rate limits (https://docs.docker.com/docker-hub/download-rate-limit/#:~:text=Docker%20Hub%20limits%20the%20number,pulls%20per%206%20hour%20period.)

/kind feature

**Comment by rambohe-ch** [comment]
@siredmar It seems that only 500MB free storage for public repository, i think it is not enough for OpenYurt images.

**Comment by siredmar** [comment]
These limits are for private repositories only.

**Comment by rambohe-ch** [comment]
> @rambohe-ch these limits are for private repositories only.

@siredmar ok, i agree with you, and it's a good idea to support github container registry, but we can also keep docker hub for consistency in the next several versions. 

would you like to make a pull request to support github container registry? and you can ping me anytime if need any collaboration from me.

**Comment by siredmar** [comment]
@rambohe-ch see #1578

**Comment by siredmar** [comment]
@rambohe-ch you also need to change the visibility of the packages. If the packages are not linked directly to the repository, you can change this per package. Also you need to change the visibility per package to public.

**Comment by rambohe-ch** [comment]
> @rambohe-ch you also need to change the visibility of the packages. If the packages are not linked directly to the repository, you can change this per package. Also you need to change the visibility per package to public.
> 
> https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility

@siredmar The visibility of packages have been changed to public. and you can find them at: https://github.com/orgs/openyurtio/packages

**Comment by siredmar** [comment]
@rambohe-ch you can also link the packages to their corresponding repositories so that they are visible in the repo.

**Comment by rambohe-ch** [comment]
> https://github.com/orgs/openyurtio/packages

@siredmar done

**Comment by rambohe-ch** [comment]
> @rambohe-ch you can also link the packages to their corresponding repositories so that they are visible in the repo.

@siredmar done

**Comment by siredmar** [comment]
@rambohe-ch very nice! 👍
