### ISSUE TITLE
[BUG] metadata.name is not set and cause staticPod creation to fail

### ISSUE THREAD

**Issue by YTGhost** [openyurtio/openyurt#1589]
**What happened**:
See https://github.com/kubernetes/kubernetes/issues/119135, the `yurthub.yaml` that was created did not set the `metadata.name` field, thus causing the creation to fail.

**What you expected to happen**:
The yurthub static pod can be successfully pulled up.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@YTGhost Would you like to make a pull request to solve this problem?

**Comment by YTGhost** [comment]
@yuanqijing Would you like to fix it?

**Comment by yuanqijing** [comment]
> @yuanqijing Would you like to fix it?

sure, I'd like fix it.

**Comment by rambohe-ch** [comment]
@YTGhost @yuanqijing It seems that this pull request: https://github.com/openyurtio/openyurt/pull/1486 has solved this problem.

**Comment by YTGhost** [comment]
> @YTGhost @yuanqijing It seems that this pull request: #1486 has solved this problem.

Yes, I will close this issue. And I think the chart need to be updated: https://github.com/openyurtio/openyurt-helm, it still 1.3.2.
