### ISSUE TITLE
[OSPP 2024] Build iot system configuration isolation on nodepool

### ISSUE THREAD

**Issue by LavenderQAQ** [openyurtio/openyurt#1597]
**What would you like to be added**:
Provides multiple PlatformAdmin deployment based on the same namespace, and allows users to customize the configuration of a nodepool.

**Why is this needed**:
We gave users the ability to customize iot systems in #1595, but it's currently not isolated enough for nodepool.
This is a very old need, refer to [multi edgex instance support](https://github.com/openyurtio/yurt-edgex-manager/issues/10). OpenYurt extends the concept of nodepools on top of k8s, so an ideal deployment is that users can configure each nodepool iot system independently. With #1435 we can manipulate yurtappset to configure each nodepool individually. And service topology allows us to separate the traffic from each nodepool. With these two capabilities we can take a step closer to idealizing the current deployment model.

_Finally, there is the tricky problem that we cannot split the configuration of services by nodepool (because edgex internal components access the same set of dns). At the moment we don't think there's enough incentive to solve this problem._

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@LavenderQAQ Do you have any progress about this issue?

**Comment by LavenderQAQ** [comment]
@rambohe-ch I am really busy recently. I plan to write a proposal first, which may be after March.

**Comment by WoShiZhangmingyu** [comment]
Hello，I am Zhangmingyu。Please
