### ISSUE TITLE
[feature request] The documentation provides instructions on how to get a bootstrap token.

### ISSUE THREAD

**Issue by xuelangos** [openyurtio/openyurt#1610]
https://openyurt.io/docs/next/installation/yurtadm-join/#1-joining-nodes-from-scratch

/kind feature

**Comment by rambohe-ch** [comment]
@YTGhost PTAL

**Comment by YTGhost** [comment]
Thanks for raising this issue, and yes, I think we should point out how to get the bootstrap token.

**Comment by rambohe-ch** [comment]
@YTGhost Do you have any progress about this issue?

**Comment by YTGhost** [comment]
> @YTGhost Do you have any progress about this issue?

Yes, PTAL https://github.com/openyurtio/openyurt.io/pull/347
