### ISSUE TITLE
[Question]openyurt可以在二进制部署的K8S上应用吗

### ISSUE THREAD

**Issue by Wuzhuangshi** [openyurtio/openyurt#1619]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:云平台，二进制方式部署
- Others:

**others**
/kind question

**Comment by wudazhuang-hash** [comment]
那我在join是的token如何获取，因为二进制生成的是一个[令牌认证文件]bootstrap.kubeconfig，
![image](https://github.com/openyurtio/openyurt/assets/73467002/87768a59-8e8a-4503-979e-a537ae7a177a)
token格式是这样的。我手动创建了一个bootstrap-token 也绑定了rbac，现在权限问题也解决了，只是不知道为什么yurtadm join时没有使用指定的token做为Authorization。

**Comment by rambohe-ch** [comment]
> 那我在join是的token如何获取，因为二进制生成的是一个[令牌认证文件]bootstrap.kubeconfig， ![image](https://user-images.githubusercontent.com/73467002/254539653-87768a59-8e8a-4503-979e-a537ae7a177a.png) token格式是这样的。我手动创建了一个bootstrap-token 也绑定了rbac，现在权限问题也解决了，只是不知道为什么yurtadm join时没有使用指定的token做为Authorization。

@YTGhost how to get bootstrap token, would you like to give some advices?

**Comment by YTGhost** [comment]
@wudazhuang-hash I think the bootstrap token needs to match [a-z0-9]{6}. [a-z0-9]{16} format. See https://kubernetes.io/docs/reference/access-authn-authz/bootstrap-tokens/#token-format

**Comment by rambohe-ch** [comment]
@Wuzhuangshi It seems that your problems have been solved, so i will close this issue. if you have other questions, please feel free to reopen this issue or create new issues.
