### ISSUE TITLE
[Bug] Starting node with no network/internet connection

### ISSUE THREAD

**Issue by siredmar** [openyurtio/openyurt#1649]
**What happened**:
I have a bunch of workload scheduled on the edge node. 
When i restart the edge node and there is no interface up with a valid connection - or in other words, there is no default route, flannel exits `Failed to find any valid interface to use: failed to get default interface: Unable to find default route` and the containers that were present before the restart won't get started.

**What you expected to happen**:
I'd expect that the containers would start even flannel isn't up.

**How to reproduce it (as minimally and precisely as possible)**:
Using flannel as CNI disconnect all connections and perform a reboot. 

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: 1.3.4
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.17", GitCommit:"a7736eaf34d823d7652415337ac0ad06db9167fc", GitTreeState:"clean", BuildDate:"2022-12-08T11:47:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-03-06T21:07:35Z", GoVersion:"go1.16.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Kernel (e.g. `uname -a`): `Linux lizard 5.4.193-5.7.0-devel+git.f78299297185 #1 SMP PREEMPT Mon Jul 11 14:42:03 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux`

**others**
/kind bug

**Comment by rambohe-ch** [comment]
@siredmar Thanks for raising issue. when cloud-edge network offline, if you want to reboot node and recover all pods, besides yurthub cache for kubelet, kube-proxy, flannel, coredns components, you also need to keep pod ip and VTEP for flannel Vxlan. you can reference the tutorial here: https://openyurt.io/docs/user-manuals/network/edge-pod-network

**Comment by siredmar** [comment]
@rambohe-ch i follows the tutorial yesterday. I used the flannel image provided by openyurt. I provisioned the device using yurtadm and let it download the CNI plugins. The tutorial suggests (https://openyurt.io/docs/user-manuals/network/edge-pod-network/#solution-pod-ip-address-kept) that i need a modified version if the CNI plugins. The yurtadm tool downloads these: https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-arm64-v0.8.0.tgz 
I can't seem to find if the patches mentioned in the tutorial are also baked into `cni-plugins-linux-arm64-v0.8.0.tgz`? 
Are these builts done manually? Where can i find the CI for that? 

What i see is that the files in `var/lib/cni/networks/cbr0/` don't look the way the tutorial suggests:
````
$ ls /var/lib/cni/networks/cbr0/
10.244.4.15  10.244.4.16  last_reserved_ip.0  lock
```

**Comment by siredmar** [comment]
@rambohe-ch i'm struggling in building the cni plugins with the provided patches myself. This is from 2019 - currently nearly impossible to build :/

**Comment by siredmar** [comment]
After using the self build CNI plugins with the provided patch and using the openyurt provided flannel image i all pods running again, however coredns won't start. This is my resolv.conf

```
nameserver 8.8.8.8
```

It gives me the message and then restarts:

```
[INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
CoreDNS-1.8.4
linux/arm64, go1.16.4, 053c4d5
[ERROR] plugin/errors: 2 8059800573062957875.2043736685324146137. HINFO: dial udp 8.8.8.8:53: connect: network is unreachable
[INFO] SIGTERM: Shutting down servers then terminating
[INFO] plugin/health: Going into lameduck mode for 5s
```

I need coredns working that node-local service resolution still works. Let's say i have pod A and pod B running on the offline node. The Service B lands on pod B. Pod A must be able to address service B and communicate with pod B - even if the device has no valid network connection and is completely offline. 

Is this use case feasable?

**Comment by siredmar** [comment]
To give a little more insights on the current setup and the state right after provisioning.
Preconditions:
* Node is online and connected
* kube-proxy is modified (https://openyurt.io/docs/user-manuals/network/service-topology#configure-kube-proxy)
* Using `docker.io/openyurt/flannel-edge:v0.14.0-1` for flannel
* Using patched CNI plugins (https://openyurt.io/docs/user-manuals/network/edge-pod-network/#solution-add-mac-address-kept-capability-in-flannel)
start flanneld using `-ip-masq -kube-subnet-mgr --iface=wt0 --iface=eth0 --iface=yurthub-dummy0` (wt0 is a VPN device that connects every node, eth0 is the default interface and yurthub-dummy0 is a fallback if the device is not connected at all)

Flannel is started using this command to create a basic monitoring if the interfaces change. Initially i'm connected with eth0, then the VPN pod configures the `wt0` interface and flannel restarts to use this interface instead. In the offline case where no interface is up and the reboot occurs, then `yurthub-dummy0` shall be used to make flannel start in the first place.

```
/opt/bin/flanneld -ip-masq -kube-subnet-mgr -iface=wt0 -iface=eth0 -iface=yurthub-dummy0 & \
          p=$(ls /sys/class/net); while true; do c=$(ls /sys/class/net); if [ "$p" != "$c" ]; then echo "Network changed!"; '
          sleep 5; pkill -f flanneld; /opt/bin/flanneld -ip-masq -kube-subnet-mgr -iface=wt0 -iface=eth0 \
         -iface=yurthub-dummy0 & p=$c; fi; sleep 5; done
```

So initially when i start the system the flannel.1 device is set to `10.244.6.0/32`. 
```
$ cat /run/flannel/subnet.env
FLANNEL_NETWORK=10.244.0.0/16
FLANNEL_SUBNET=10.244.6.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```

The pods alpine and nginx pods get created in that subnet:

```
$ ls /var/lib/cni/networks/cbr0
10.244.6.2_default_alpine-b5dj6                       last_reserved_ip.0
10.244.6.3_default_nginx-deployment-6c5879b75d-9h4xm  lock
```

After the reboot (all interfaces disconnected) flannel starts up using `yurthub-dummy0`. Flannel however uses another subnet. This prevents the alpine and nginx pod sandbox containers from starting, because they expect another subnet:

```
$ cat /run/flannel/subnet.env
FLANNEL_NETWORK=10.244.0.0/16
FLANNEL_SUBNET=10.244.7.1/24
FLANNEL_MTU=1450
FLANNEL_IPMASQ=true
```

```
docker ps -a
CONTAINER ID   IMAGE                                                           COMMAND                  CREATED                  STATUS                                PORTS     NAMES
73201505192c   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2   "/pause"                 Less than a second ago   Exited (0) Less than a second ago               k8s_POD_nginx-deployment-6c5879b75d-9h4xm_default_3a41c0ed-a7c9-4c63-a30c-6b734c0d309e_485
f747b47a55ad   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2   "/pause"                 Less than a second ago   Exited (0) Less than a second ago               k8s_POD_alpine-b5dj6_default_a30c2ec8-8683-4e90-96a4-e612a2bab1ff_483
```

```
journalctl -u kubelet -f
Aug 15 08:44:25 eagle kubelet[715]: E0815 08:44:25.185033     715 kuberuntime_manager.go:818] "CreatePodSandbox for pod failed" err="rpc error: code = Unknown desc = failed to set up sandbox container \"f747b47a55ad147e9e5ac351acac9c258d583b38f68a489e1e3037be3382e77a\" network for pod \"alpine-b5dj6\": networkPlugin cni failed to set up pod \"alpine-b5dj6_default\" network: failed to delegate add: invalid CIDR address: <nil>" pod="default/alpine-b5dj6"
Aug 15 08:44:25 eagle kubelet[715]: E0815 08:44:25.185185     715 pod_workers.go:918] "Error syncing pod, skipping" err="failed to \"CreatePodSandbox\" for \"alpine-b5dj6_default(a30c2ec8-8683-4e90-96a4-e612a2bab1ff)\" with CreatePodSandboxError: \"Failed to create sandbox for pod \\\"alpine-b5dj6_default(a30c2ec8-8683-4e90-96a4-e612a2bab1ff)\\\": rpc error: code = Unknown desc = failed to set up sandbox container \\\"f747b47a55ad147e9e5ac351acac9c258d583b38f68a489e1e3037be3382e77a\\\" network for pod \\\"alpine-b5dj6\\\": networkPlugin cni failed to set up pod \\\"alpine-b5dj6_default\\\" network: failed to delegate add: invalid CIDR address: <nil>\"" pod="default/alpine-b5dj6" podUID=a30c2ec8-8683-4e90-96a4-e612a2bab1ff
```

So the question is: How to i start flannel with the old configuration?

**Comment by rambohe-ch** [comment]
> @rambohe-ch i follows the tutorial yesterday. I used the flannel image provided by openyurt. I provisioned the device using yurtadm and let it download the CNI plugins. The tutorial suggests (https://openyurt.io/docs/user-manuals/network/edge-pod-network/#solution-pod-ip-address-kept) that i need a modified version if the CNI plugins. The yurtadm tool downloads these: https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-arm64-v0.8.0.tgz I can't seem to find if the patches mentioned in the tutorial are also baked into `cni-plugins-linux-arm64-v0.8.0.tgz`? Are these builts done manually? Where can i find the CI for that?
> 
> What i see is that the files in `var/lib/cni/networks/cbr0/` don't look the way the tutorial suggests:
> 
> ```
> $ ls /var/lib/cni/networks/cbr0/
> 10.244.4.15  10.244.4.16  last_reserved_ip.0  lock
> ```
> ```

@siredmar cni plugins for linux/arm64 has been updated, please have a try the new one: https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-arm64-v0.8.0.tgz

**Comment by rambohe-ch** [comment]
> After using the self build CNI plugins with the provided patch and using the openyurt provided flannel image i all pods running again, however coredns won't start. This is my resolv.conf
> 
> ```
> nameserver 8.8.8.8
> ```
> 
> It gives me the message and then restarts:
> 
> ```
> [INFO] plugin/reload: Running configuration MD5 = db32ca3650231d74073ff4cf814959a7
> CoreDNS-1.8.4
> linux/arm64, go1.16.4, 053c4d5
> [ERROR] plugin/errors: 2 8059800573062957875.2043736685324146137. HINFO: dial udp 8.8.8.8:53: connect: network is unreachable
> [INFO] SIGTERM: Shutting down servers then terminating
> [INFO] plugin/health: Going into lameduck mode for 5s
> ```
> 
> I need coredns working that node-local service resolution still works. Let's say i have pod A and pod B running on the offline node. The Service B lands on pod B. Pod A must be able to address service B and communicate with pod B - even if the device has no valid network connection and is completely offline.
> 
> Is this use case feasable?

@siredmar yes, OpenYurt can perfectly solve this case. it seems that coredns pod has not restarted properly.

**Comment by rambohe-ch** [comment]
> w to i start flannel with the old configuration?

@siredmar would you be able to show me the entire flannel yaml include configmaps?

**Comment by siredmar** [comment]
Also i saw a strange thing: after an offline reboot, the coredns pod tries to run, but crashes and then disappearing forever leaving no traces of existence. Nothing in the docker logs, and only two messages in the kubelet logs

```
Aug 16 13:37:37 eagle kubelet[715]: I0816 13:37:37.427673     715 reconciler.go:225] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-jdqxn\" (UniqueName: \"kubernetes.io/projected/1dc8de44-2fc6-47f8-b4ed-646eb963bb62-kube-api-access-jdqxn\") pod \"coredns-zsfm2\" (UID: \"1dc8de44-2fc6-47f8-b4ed-646eb963bb62\") "
Aug 16 13:37:37 eagle kubelet[715]: I0816 13:37:37.429340     715 reconciler.go:225] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/1dc8de44-2fc6-47f8-b4ed-646eb963bb62-config-volume\") pod \"coredns-zsfm2\" (UID: \"1dc8de44-2fc6-47f8-b4ed-646eb963bb62\") "
```

**Comment by siredmar** [comment]
After changing the  onfiguration of coredns  from this

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata
  name: coredns
  namespace: kube-system

```
to this

```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . 8.8.8.8 {
           max_concurrent 1000
        }
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata
  name: coredns
  namespace: kube-system
```

coredns stays alive. However, service resolution still does not work when offline.

**Comment by rambohe-ch** [comment]
@siredmar Do you have any progress about this issue?

**Comment by siredmar** [comment]
@rambohe-ch yes, indeed. 
I created a dummy interface called `edge0` with a constant IP address (e.g. 192.168.168.1). I told the kubelet to run on that IP address using the --address argument. The flannel instance running on that machine also uses `edge0` via parameter `--iface` and `--public-ip` to the IP address of a VPN interface (called `wt0`) that has a constant IP address beyond reboots. Also i configured iptables in a way that everything kubelet related goes through `edge0`.

So, even if the device reboots offline, the device edge0 is there and flannel starts with the same IP address that got stored in a file. 

To see what is going on, extract this tar-ball and have a look at the scripts.
https://github.com/edgefarm/edgefarm/releases/download/v1.3.0/ubuntu-22.04-edge-node-config.tar.gz

This can be closed now. The same goes for #1660
