### ISSUE TITLE
[BUG] Unpacking the cni-plugins zip for arm64 is abnormal

### ISSUE THREAD

**Issue by YTGhost** [openyurtio/openyurt#1678]
**What happened**:
During the `yurtadm join` process, kubernetes-cni is downloaded and installed to the `/opt/cni/bin` directory. However, when the user's environment is `arm64`, the downloaded package (https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins -linux-arm64-v0.8.0.tgz) is overpacked, which causes cni to end up being unpacked under `/opt/cni/bin/cni-plugin`.

**What you expected to happen**:
The cni binary should be properly extracted to `/opt/cni/bin`.

**How to reproduce it (as minimally and precisely as possible)**:
Executing `yurtadm join` on an arm64 edge machine.

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by YTGhost** [comment]
@rambohe-ch PTAL, I think we should modify the cni-plugins package for arm64 on oss.

**Comment by luc99hen** [comment]
@YTGhost  done
