### ISSUE TITLE
[BUG] Lack of the delete logic of finalizer in yurt-iot-dock

### ISSUE THREAD

**Issue by Pluviophile225** [openyurtio/openyurt#1694]
**What happened**:
Can not delete the device on the openyurt platform. The reason is the finalizer in the device crd.
**What you expected to happen**:
Delete the redundantKubeDevices in the sync time loop.
**How to reproduce it (as minimally and precisely as possible)**:
Create a device and then delete the device. But it can't be deleted in the edgex platform.
**Anything else we need to know?**:
I find the solution and I want to fix this bug.

**Environment**:
- OpenYurt version: master
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by LavenderQAQ** [comment]
This is a problem caused by adding finalizer when moving yurt-device-controller into yurt-manager. The previous version does not have this problem. Welcome to fix it. 👏
