### ISSUE TITLE
failed to call web:443/mutate-apps-openyurt-io-v1alpha1-yurtstaticset?timeout=10s": Service Unavailable

### ISSUE THREAD

**Issue by henry718** [openyurtio/openyurt#1708]
**What happened**: 
Install yurthub artifacts on master. Run `helm upgrade --install yurt-hub -n kube-system --set kubernetesServerAddr=https://1.2.3.4:6443 openyurt/yurthub`  failed.
Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "mutate.apps.v1alpha1.yurtstaticset.openyurt.io": failed to call web:443/mutate-apps-openyurt-io-v1alpha1-yurtstaticset?timeout=10s": Service Unavailable

**What you expected to happen**:
Install yurthub successfully.

**How to reproduce it (as minimally and precisely as possible)**:
Run this command. `helm upgrade --install yurt-hub -n kube-system --set kubernetesServerAddr=https://1.2.3.4:6443 openyurt/yurthub`

**Anything else we need to know?**:
When I used calico for CNI before, the installation was successful. Then reset and change to flannel, failed. 
**Environment**: 
- OpenYurt version: V1.3
- Kubernetes version (use `kubectl version`): v1.22.2
- OS (e.g: `cat /etc/os-release`): Ubuntu-22.04
- Kernel (e.g. `uname -a`): 5.15.0-60-generic
- Install tools: helm 
- Others:
[yurt-manager.log](https://github.com/openyurtio/openyurt/files/12657117/yurt-manager.log)

**others**
/kind question

**Comment by rambohe-ch** [comment]
@henry718 As the detail logs of yurt-manager, it seems yurt-manager have not handled any webhook requests, so i think you should check the dns resolution for domain `web:443` and service traffic is forwarded correctly or not.

**Comment by henry718** [comment]
It seems that there is a problem with the coredns service. I create a busybox on master , and then ping the yurt-manager-webhook-service, it reply that bad address. Is it right? Could you guide me how to debug this issue?
![image](https://github.com/openyurtio/openyurt/assets/110022518/aebf4e17-795a-4103-b23d-03f82bf88912)
![image](https://github.com/openyurtio/openyurt/assets/110022518/59a326dd-5e4b-4aea-ab6d-236cc369fafc)

**Comment by rambohe-ch** [comment]
> It seems that there is a problem with the coredns service. I create a busybox on master , and then ping the yurt-manager-webhook-service, it reply that bad address. Is it right? Could you guide me how to debug this issue? ![image](https://user-images.githubusercontent.com/110022518/269131244-aebf4e17-795a-4103-b23d-03f82bf88912.png) ![image](https://user-images.githubusercontent.com/110022518/269131272-59a326dd-5e4b-4aea-ab6d-236cc369fafc.png)

@henry718 you can use `dig` tool to verify dns resolution. like `dig @10.244.0.2 yurt-manager-webhook-service.kube-system.svc.cluster.local`

then you can access the pod ip of yurt-manager container directly and check the request is handled or not.

**Comment by henry718** [comment]
Thank you, This issue was solved. Just add the kube-system.svc to no_proxy in /etc/kubernetes/manifests/kube-apiserver.yaml .
Because we need to use the proxy to access the Internet. So we should add kube-system.svc to no_proxy.
