### ISSUE TITLE
[feature request]Move in NodeLifeCycle to yurt-manager

### ISSUE THREAD

**Issue by JameKeal** [openyurtio/openyurt#1713]
**What would you like to be added**:
Move in nodelifecycle controller to yurt-manager, and disable it in kube-controller-manager. In the mean time, add some logic on it to process some questions, like pod evict and status updates when node or nodepool is not ready.

**Why is this needed**:
We use webhook and add some controllers to process question at present, we add pod and node webhook, it may be in trouble when webhook not running, and the cluster will not process pod and node. And use webhook increase calling link time, so we need to replace it with a better way.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@JameKeal I agree with your idea to add NodeLifeCycle controller into yurt-manager, and i will take over this work.
