### ISSUE TITLE
Fail to connect the edge pod from cloud master

### ISSUE THREAD

**Issue by henry718** [openyurtio/openyurt#1714]
I have installed the yurt-manager and yurt-hub raven.

**Environment**:
- OpenYurt version: 1.3
- Kubernetes version (use `kubectl version`): V1.22.2
- OS (e.g: `cat /etc/os-release`): ubuntu
- Kernel (e.g. `uname -a`): 5.15.0-60
- Install tools:
- Others:

**others**
/kind question
Network topology
![image](https://github.com/openyurtio/openyurt/assets/110022518/b038db58-0055-406a-943e-341407fa72f0)
log 
[yurtmaster-raven.log](https://github.com/openyurtio/openyurt/files/12681472/yurtmaster-raven.log)

**Comment by YTGhost** [comment]
According to the logs, `gw-lab` hasn't been able to get a public IP, are the nodes in this gateway unable to access the outside?

**Comment by rambohe-ch** [comment]
@henry718 Do you have any progress about this issue?

**Comment by YTGhost** [comment]
> @henry718 Do you have any progress about this issue?

@rambohe-ch This problem was solved after he manually set publicIp, so I think we can close this issue now.

**Comment by henry718** [comment]
Yes, thank you. You can close this issue, it can be solved by setting the public Ip manually.
