### ISSUE TITLE
[feature request] Modify script to add yurt-iot-dock chart build flow

### ISSUE THREAD

**Issue by LavenderQAQ** [openyurtio/openyurt#1718]
**What would you like to be added**:
Encapsulate `kustomize_to_chart.sh` scripts to make the build process available to both yurt-manager and yurt-iot-dock.

**Why is this needed**:
The current crd and build scripts for related resources are customized for yurt-manager, but the yurt-iot-dock will also need to be used in the future (since it comes with three CRDs), so it will need to be revamped.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@LavenderQAQ I think t

**Comment by LavenderQAQ** [comment]
@rambohe-ch Thank you, there needs to be some script modification work.
