### ISSUE TITLE
[BUG] pool coordinator resource key path is wrong for extended custom resources

### ISSUE THREAD

**Issue by qsfang** [openyurtio/openyurt#1728]
**What happened**:
1. kubect edit cm yurt-hub-cfg -n kube-system, add pool_scope_resources
  pool_scope_resources: |
    [{
      "Group":"networking.alibaba.com",
      "Version":"v1",
      "Resource":"ipinstances"
    }]
2. sign in edge node
3. restart yurthub static pod
4. use edge pool-coordinator kubeconfig, kubectl get ipinstance, get nothing

**What you expected to happen**:
cmd `kubectl get ipinstance` get expected result, as ipinstance crd resource is synced from cloud apiserver to edge pool coordinator

**How to reproduce it (as minimally and precisely as possible)**:
1. kubect edit cm yurt-hub-cfg -n kube-system, add pool_scope_resources
  pool_scope_resources: |
    [{
      "Group":"networking.alibaba.com",
      "Version":"v1",
      "Resource":"ipinstances"
    }]
2. create rolebinding, and grant yurt-hub system:nodes with cluster-admin role, just for testing
3. sign in edge node
4. use edge pool-coordinator kubeconfig, kubectl create customresourcedefinition of ipinstances.networking.alibaba.com manually
5. restart yurthub static pod
6. use edge pool-coordinator kubeconfig, kubectl get ipinstance, get nothing

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: 
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@qsfang It looks like that yurt-coordinator has some problems to support crd resource syncing. would you like to debug this problem?
