### ISSUE TITLE
[BUG] yurt-coordinator pod hangs

### ISSUE THREAD

**Issue by simonyangcj** [openyurtio/openyurt#1739]
**What happened**:

Hi team, my yurt-coordinator pod of node-pool hangs due to missing 2 secret yurt-coordinator-dynamic-certs and yurt-coordinator-static-certs

<pre>
$ kubectl get pod -n kube-system yurt-coordinator-beijing-t4stt-98b96b4bb-mx9sd

NAME                                             READY   STATUS              RESTARTS   AGE
yurt-coordinator-beijing-t4stt-98b96b4bb-mx9sd   0/2     ContainerCreating   0          129m
</pre>

<pre>
$ kubectl describe pod  -n kube-system yurt-coordinator-beijing-t4stt-98b96b4bb-mx9sd

...
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  35m (x6 over 116m)     kubelet  Unable to attach or mount volumes: unmounted volumes=[yurt-coordinator-certs], unattached volumes=[kube-api-access-n9rxt etcd-data yurt-coordinator-certs]: timed out waiting for the condition
  Warning  FailedMount  19m (x31 over 123m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[yurt-coordinator-certs], unattached volumes=[yurt-coordinator-certs kube-api-access-n9rxt etcd-data]: timed out waiting for the condition
  Warning  FailedMount  14m (x11 over 128m)    kubelet  Unable to attach or mount volumes: unmounted volumes=[yurt-coordinator-certs], unattached volumes=[etcd-data yurt-coordinator-certs kube-api-access-n9rxt]: timed out waiting for the condition
  Warning  FailedMount  3m57s (x70 over 130m)  kubelet  MountVolume.SetUp failed for volume "yurt-coordinator-certs" : [secret "yurt-coordinator-dynamic-certs" not found, secret "yurt-coordinator-static-certs" not found]

</pre>

**What you expected to happen**:

Yurt-coordinator pod of node-pool can run normally

**How to reproduce it (as minimally and precisely as possible)**:

1. deploy yurt-coordinator with helm
2. create a simple nodepool object

<pre>
apiVersion: apps.openyurt.io/v1beta1
kind: NodePool
metadata:
  name: huzhou
spec:
  type: Edge
</pre>

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: release-1.3
- Kubernetes version (use `kubectl version`): v1.23.6
- OS (e.g: `cat /etc/os-release`): Rocky Linux 8.8 (Green Obsidian)
- Kernel (e.g. `uname -a`): 4.18.0-477.10.1.el8_8.x86_64
- Install tools: helm
- Others:

**others**

many thx:)

/kind bug

**Comment by JameKeal** [comment]
hi there, is your first time to deploy yurt-coordinator? Can you show us the secrets list for yurt-coordintaor.

**Comment by simonyangcj** [comment]
@JameKeal thank you for quick reply. 
Yes, it's my first time deploy openyurt.

<pre>
# yurt-coordinator of YurtAppDaemon
[root@openyurt-center-controller ~]# kubectl get YurtAppDaemon -n kube-system yurt-coordinator -o yaml
apiVersion: apps.openyurt.io/v1alpha1
kind: YurtAppDaemon
metadata:
  annotations:
    meta.helm.sh/release-name: yurt-coordinator
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-10-19T04:13:13Z"
  generation: 1
  labels:
    app.kubernetes.io/instance: yurt-coordinator
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: yurt-coordinator
    app.kubernetes.io/version: 1.3.4
    helm.sh/chart: yurt-coordinator-1.3.4
  name: yurt-coordinator
  namespace: kube-system
  resourceVersion: "934442"
  uid: 7c5a8034-51b9-46c0-922d-69e06a0c327b
spec:
  nodepoolSelector:
    matchLabels:
      openyurt.io/node-pool-type: edge
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: yurt-coordinator
      app.kubernetes.io/name: yurt-coordinator
  workloadTemplate:
    deploymentTemplate:
      metadata:
        creationTimestamp: null
        labels:
          app.kubernetes.io/instance: yurt-coordinator
          app.kubernetes.io/managed-by: Helm
          app.kubernetes.io/name: yurt-coordinator
          app.kubernetes.io/version: 1.3.4
          helm.sh/chart: yurt-coordinator-1.3.4
      spec:
        replicas: 1
        selector:
          matchLabels:
            app.kubernetes.io/instance: yurt-coordinator
            app.kubernetes.io/name: yurt-coordinator
        strategy: {}
        template:
          metadata:
            creationTimestamp: null
            labels:
              app.kubernetes.io/instance: yurt-coordinator
              app.kubernetes.io/managed-by: Helm
              app.kubernetes.io/name: yurt-coordinator
              app.kubernetes.io/version: 1.3.4
              helm.sh/chart: yurt-coordinator-1.3.4
          spec:
            containers:
            - command:
              - kube-apiserver
              - --bind-address=0.0.0.0
              - --allow-privileged=true
              - --anonymous-auth=true
              - --authorization-mode=Node,RBAC
              - --client-ca-file=/etc/kubernetes/pki/ca.crt
              - --enable-admission-plugins=NodeRestriction
              - --enable-bootstrap-token-auth=true
              - --disable-admission-plugins=ServiceAccount
              - --etcd-cafile=/etc/kubernetes/pki/ca.crt
              - --etcd-certfile=/etc/kubernetes/pki/apiserver-etcd-client.crt
              - --etcd-keyfile=/etc/kubernetes/pki/apiserver-etcd-client.key
              - --etcd-servers=https://127.0.0.1:12379
              - --kubelet-client-certificate=/etc/kubernetes/pki/apiserver-kubelet-client.crt
              - --kubelet-client-key=/etc/kubernetes/pki/apiserver-kubelet-client.key
              - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
              - --secure-port=10270
              - --service-account-issuer=https://kubernetes.default.svc.cluster.local
              - --service-account-key-file=/etc/kubernetes/pki/sa.pub
              - --service-account-signing-key-file=/etc/kubernetes/pki/sa.key
              - --service-cluster-ip-range=10.96.0.0/12
              - --tls-cert-file=/etc/kubernetes/pki/apiserver.crt
              - --tls-private-key-file=/etc/kubernetes/pki/apiserver.key
              image: registry.k8s.io/kube-apiserver:v1.22.0
              imagePullPolicy: IfNotPresent
              livenessProbe:
                failureThreshold: 8
                httpGet:
                  host: 127.0.0.1
                  path: /livez
                  port: 10270
                  scheme: HTTPS
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 15
              name: kube-apiserver
              readinessProbe:
                failureThreshold: 3
                httpGet:
                  host: 127.0.0.1
                  path: /readyz
                  port: 10270
                  scheme: HTTPS
                periodSeconds: 1
                successThreshold: 1
                timeoutSeconds: 15
              resources:
                requests:
                  cpu: 250m
              startupProbe:
                failureThreshold: 24
                httpGet:
                  host: 127.0.0.1
                  path: /livez
                  port: 10270
                  scheme: HTTPS
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 15
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /etc/kubernetes/pki
                name: yurt-coordinator-certs
                readOnly: true
            - command:
              - etcd
              - --advertise-client-urls=https://0.0.0.0:12379
              - --listen-client-urls=https://0.0.0.0:12379
              - --cert-file=/etc/kubernetes/pki/etcd-server.crt
              - --client-cert-auth=true
              - --max-txn-ops=102400
              - --data-dir=/var/lib/etcd
              - --max-request-bytes=100000000
              - --key-file=/etc/kubernetes/pki/etcd-server.key
              - --listen-metrics-urls=http://0.0.0.0:12381
              - --snapshot-count=10000
              - --trusted-ca-file=/etc/kubernetes/pki/ca.crt
              image: registry.k8s.io/etcd:3.5.0-0
              imagePullPolicy: IfNotPresent
              name: etcd
              resources:
                limits:
                  cpu: 200m
                  memory: 512Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
              startupProbe:
                failureThreshold: 24
                httpGet:
                  host: 127.0.0.1
                  path: /health
                  port: 12381
                  scheme: HTTP
                initialDelaySeconds: 10
                periodSeconds: 10
                successThreshold: 1
                timeoutSeconds: 15
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
              - mountPath: /var/lib/etcd
                name: etcd-data
              - mountPath: /etc/kubernetes/pki
                name: yurt-coordinator-certs
                readOnly: true
            dnsPolicy: ClusterFirst
            enableServiceLinks: true
            hostNetwork: true
            preemptionPolicy: PreemptLowerPriority
            priority: 2000001000
            priorityClassName: system-node-critical
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext:
              seccompProfile:
                type: RuntimeDefault
            terminationGracePeriodSeconds: 30
            volumes:
            - emptyDir:
                medium: Memory
              name: etcd-data
            - name: yurt-coordinator-certs
              projected:
                defaultMode: 420
                sources:
                - secret:
                    name: yurt-coordinator-dynamic-certs
                - secret:
                    name: yurt-coordinator-static-certs
status:
  collisionCount: 0
  conditions:
  - lastTransitionTime: "2023-10-19T04:13:13Z"
    status: "True"
    type: WorkLoadProvisioned
  - lastTransitionTime: "2023-10-19T04:13:13Z"
    status: "True"
    type: WorkLoadUpdated
  currentRevision: yurt-coordinator-85f9445d64
  nodepools:
  - huzhou
  - beijing
  observedGeneration: 1
  templateType: Deployment
</pre>

<pre>
# full secret list of kube-system
[root@openyurt-center-controller ~]# kubectl get secret -n kube-system
NAME                                             TYPE                                  DATA   AGE
attachdetach-controller-token-bnr6r              kubernetes.io/service-account-token   3      5d23h
bootstrap-signer-token-thj7s                     kubernetes.io/service-account-token   3      5d23h
bootstrap-token-aaynbi                           bootstrap.kubernetes.io/token         6      21h
bootstrap-token-e8md0i                           bootstrap.kubernetes.io/token         6      21h
bootstrap-token-g2a20q                           bootstrap.kubernetes.io/token         6      21h
bootstrap-token-nuq1gf                           bootstrap.kubernetes.io/token         6      22h
bootstrap-token-s5lnq0                           bootstrap.kubernetes.io/token         6      22h
certificate-controller-token-t2mpn               kubernetes.io/service-account-token   3      5d23h
clusterrole-aggregation-controller-token-cqkdf   kubernetes.io/service-account-token   3      5d23h
coredns-token-gl55s                              kubernetes.io/service-account-token   3      5d23h
cronjob-controller-token-kr4fg                   kubernetes.io/service-account-token   3      5d23h
daemon-set-controller-token-tp576                kubernetes.io/service-account-token   3      5d23h
default-token-mh5x6                              kubernetes.io/service-account-token   3      5d23h
deployment-controller-token-v8b96                kubernetes.io/service-account-token   3      5d23h
disruption-controller-token-mjjtd                kubernetes.io/service-account-token   3      5d23h
endpoint-controller-token-rd6gg                  kubernetes.io/service-account-token   3      5d23h
endpointslice-controller-token-bpbx7             kubernetes.io/service-account-token   3      5d23h
endpointslicemirroring-controller-token-fpdzl    kubernetes.io/service-account-token   3      5d23h
ephemeral-volume-controller-token-m7g5x          kubernetes.io/service-account-token   3      5d23h
expand-controller-token-kcgbr                    kubernetes.io/service-account-token   3      5d23h
generic-garbage-collector-token-jkqzg            kubernetes.io/service-account-token   3      5d23h
horizontal-pod-autoscaler-token-4l5jq            kubernetes.io/service-account-token   3      5d23h
job-controller-token-9b4gc                       kubernetes.io/service-account-token   3      5d23h
kube-proxy-token-8lg2c                           kubernetes.io/service-account-token   3      5d23h
namespace-controller-token-fkt7b                 kubernetes.io/service-account-token   3      5d23h
node-controller-token-smbsw                      kubernetes.io/service-account-token   3      5d23h
persistent-volume-binder-token-n4pqq             kubernetes.io/service-account-token   3      5d23h
pod-garbage-collector-token-dg5sq                kubernetes.io/service-account-token   3      5d23h
pool-coordinator-ca-certs                        Opaque                                2      5d23h
pool-coordinator-static-certs                    Opaque                                5      5d23h
pool-coordinator-yurthub-certs                   Opaque                                3      5d23h
pv-protection-controller-token-5rcg2             kubernetes.io/service-account-token   3      5d23h
pvc-protection-controller-token-tpnvz            kubernetes.io/service-account-token   3      5d23h
raven-agent-account-token-krz9n                  kubernetes.io/service-account-token   3      5d22h
raven-agent-secret                               Opaque                                1      5d22h
replicaset-controller-token-br6xn                kubernetes.io/service-account-token   3      5d23h
replication-controller-token-w4vk8               kubernetes.io/service-account-token   3      5d23h
resourcequota-controller-token-4bpzw             kubernetes.io/service-account-token   3      5d23h
root-ca-cert-publisher-token-hwwbj               kubernetes.io/service-account-token   3      5d23h
service-account-controller-token-ffs6f           kubernetes.io/service-account-token   3      5d23h
service-controller-token-xw22k                   kubernetes.io/service-account-token   3      5d23h
sh.helm.release.v1.raven-agent.v1                helm.sh/release.v1                    1      5d22h
sh.helm.release.v1.yurt-coordinator.v1           helm.sh/release.v1                    1      20h
sh.helm.release.v1.yurt-hub.v1                   helm.sh/release.v1                    1      5d23h
sh.helm.release.v1.yurt-manager.v1               helm.sh/release.v1                    1      5d23h
sh.helm.release.v1.yurt-manager.v2               helm.sh/release.v1                    1      20h
sh.helm.release.v1.yurt-manager.v3               helm.sh/release.v1                    1      20h
statefulset-controller-token-ldtkw               kubernetes.io/service-account-token   3      5d23h
token-cleaner-token-4gpks                        kubernetes.io/service-account-token   3      5d23h
ttl-after-finished-controller-token-6mdcb        kubernetes.io/service-account-token   3      5d23h
ttl-controller-token-rn99j                       kubernetes.io/service-account-token   3      5d23h
yurt-manager-token-s6j65                         kubernetes.io/service-account-token   3      20h
yurt-manager-webhook-certs                       Opaque                                6      5d23h
</pre>

**Comment by rambohe-ch** [comment]
@simonyangcj pool-coordinator has been renamed to `yurt-coordinator` at some time, and certificates for yurt-coordinator should be prepared by the yurt-manager component. 

It seems that old version of yurt-manager component has been used, so `pool-coordinator-ca-certs`, `pool-coordinator-static-certs` and `pool-coordinator-yurthub-certs` secrets have been created, so you can upgrade to the latest version for yurt-manager and have a try.

**Comment by simonyangcj** [comment]
thank you very much. I give a try :)
