### ISSUE TITLE
[Question] Why yurtstaticset designed to not directly deploy static pod

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/openyurt#1747]
**What happened**:

If we want to use yurtstaticset, we need to deploy the static pod firstly.

**What you expected to happen**:

After the openyurt kubernetes cluster setup, I want to deploy a new static pod to edge node. If use yurtstaticset to implement, I need to login the edge node, and use yurtadm command to deploy staticpod. Sometime we may do not have permission to login node.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@huiwq1990 Thanks for raising issue. and i want to explain the reasons why yurtstaticset is not designed to deploy static pod directly.

1. As you known, the lifecycle of static pod is managed by kubelet, so if yurtstaticset can deploy static pod directly, the right of managing the lifecycle of static pod should be transferred to yurtstaticset controller on control-plane side.  this means we will change the static pod lifecycle management logic, this would violate OpenYurt's design principles.

2. so we want to keep the static pod lifecycle management on the edge side, and maybe users can manage static pod in the NodePool based on the yurt-coordinator, even cloud-edge network disconnected.

**Comment by rambohe-ch** [comment]
@huiwq1990 by the way,  when you bootstrap your edge node, you can also setup `--static-pods` parameter of `yurtadm join` command to select the static pods that you want to setup.

**Comment by huiwq1990** [comment]
@rambohe-ch If we have many edge nodes, and they are joined to the openyurt clusters. After sometime, we want to add a new staticpod to edge node. It's too consume time and not maintenance-friendly if we execude yurtadm command in edge node.

**Comment by rambohe-ch** [comment]
> @rambohe-ch If we have many edge nodes, and they are joined to the openyurt clusters. After sometime, we want to add a new staticpod to edge node. It's too consume time and not maintenance-friendly if we execude yurtadm command in edge node.

@huiwq1990 I think maybe it is a good idea to implement a new script to run `yurtadm staticpods install` command, and you can use deployment or daemonset to schedule this script  on edge nodes.

**Comment by rambohe-ch** [comment]
@huiwq1990 I think we need to keep the current status for yurtstaticset resource, so i will close this issue at first.
