### ISSUE TITLE
[feature request]fix error log format in cache manager

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1776]
**What would you like to be added**:

As the following code: var `key` is a struct, not a string, so print format is not match.

please change to `key.Key()` to fix it.

https://github.com/openyurtio/openyurt/blob/76a4cfb36a3cdb217d6431b18b06cfd7d8146c34/pkg/yurthub/cachemanager/cache_manager.go#L442-L444

**others**
/kind feature

**Comment by rambohe-ch** [comment]
by the way, at present the error log was printed as following:

```
E1107 14:39:21.863847   12599 cache_manager.go:443] failed to process watch object {%!s(bool=false) 
```

**Comment by NewKeyTo** [comment]
I want to help with this issue
