### ISSUE TITLE
[feature request] Make a video about using openyurt for camera management

### ISSUE THREAD

**Issue by LavenderQAQ** [openyurtio/openyurt#1798]
**What would you like to be added**:
Improve the previous demo about camera management and shoot a full video using OpenYurt v1.4 for camera management.

**Why is this needed**:
Demonstrate the capabilities of the iot part of openyurt.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@LavenderQAQ @gnunu Do you have any progress about this case?

**Comment by jeffrey4l** [comment]
coud you show me the previous demo video? where i can find it ?

**Comment by LavenderQAQ** [comment]
> coud you show me the previous demo video? where i can find it ?

@jeffrey4l We had a demo at the edgex meeting before, but I'm not sure if the video was left at that time. @wangxye Do you still have the demo video?

**Comment by LavenderQAQ** [comment]
> have

@rambohe-ch I thought we could discuss it at the next community meeting. I remember that @gnunu  wanted to release the demo as a file.
