### ISSUE TITLE
[feature request] Use message-bus instead of REST to communicate with EdgeX

### ISSUE THREAD

**Issue by LavenderQAQ** [openyurtio/openyurt#1799]
**What would you like to be added**:
Since MessageBus is now the default inter-communication method for EdgeX, yurt-iot-dock should witch to MessageBus, and remove the actual value update logic for devices.

**Why is this needed**:
Improved device synchronization for yurt-iot-dock

Refer: https://github.com/openyurtio/yurt-device-controller/issues/60

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@LavenderQAQ Do you have any progress about this issue?

**Comment by LavenderQAQ** [comment]
@rambohe-ch It seems that @wangxye has submitted a version of the code in #1955, I will review it.
