### ISSUE TITLE
[feature request]support LB service on edge nodes

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1804]
**What would you like to be added**:
At present, users like to use NodePort service to expose their services on edge nodes, and outside clients need to specify the IP address of the edge node that runs the corresponding edge application, even multiple instances of edge application are available. so edge application service unavailable happens easily because of single point of failure.

so we want to support LB service to solve the single point of failure. outside clients can use the IngressIP of LB service to access the edge application even a part of edge applications are unavailable.

moreover, we need to consider the multiple NodePools. this means when edge applications are scattered across multiple NodePools, LB service can provide access points across multiple NodePools.

**Why is this needed**:
To solve the single point of failure for outside clients access edge applications through NodePort service.

**others**
/kind feature

**Comment by Congrool** [comment]
PR linked: #1816
