### ISSUE TITLE
[feature request] Add optional components for iot platformadmin via cli

### ISSUE THREAD

**Issue by YTGhost** [openyurtio/openyurt#1805]
**What would you like to be added**:
Add optional components for iot Platformadmin via cli (update the `components` field of platformAdmin via cli)

**Why is this needed**:

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@YTGhost Do you have any progress about this issue?

**Comment by YTGhost** [comment]
> @YTGhost Do you have any progress about this issue?

Not yet, still working on https://github.com/openyurtio/openyurt/issues/1862
