### ISSUE TITLE
[feature request]Support K8s v1.24~v1.28

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1806]
**What would you like to be added**:
Even OpenYurt can support K8s v1.24+, but we need to upgrade OpenYurt independencies of k8s.io/xxx. 
At present, OpenYurt depends on the k8s.io/xxx v0.22.3, and we want to upgrade k8s.io/xxx version to v0.28.x,
Moreover, we want to upgrade `local-up-openyurt` command to support K8s v1.24 ~ v1.28 version, for making sure all functions of OpenYurt can work on K8s v1.24 ~ v1.28 clusters.

**Why is this needed**:
normal version upgrade.

**others**
/kind feature

**Comment by Congrool** [comment]
PR linked: #1699

**Comment by siredmar** [comment]
@Congrool @rambohe-ch  anything new about this issue? The linked PR was closed due to inactivity. The supported k8s 1.22 ended EOL in december 2022.

**Comment by rambohe-ch** [comment]
> @Congrool @rambohe-ch anything new about this issue? The linked PR was closed due to inactivity. The supported k8s 1.22 ended EOL in december 2022.

@siredmar I am working on this issue, but have not enough progress now, and i will try my best to make progress in this month.

**Comment by siredmar** [comment]
@rambohe-ch thanks for the update
