### ISSUE TITLE
[Question] Why yurtmanager(raven) doesn't watch changes to BlockAffinity?

### ISSUE THREAD

**Issue by suyuee** [openyurtio/openyurt#1809]
**What happened**:
New pod cidr not updated to gateway nodeinfo
**What you expected to happen**:
If a new BlockAffinity CR is created, the node info should add the pod cird
**How to reproduce it (as minimally and precisely as possible)**:
Simply create new blockaffinity (or have calico do it) and observe the nodeinfo status of gateway, yurtmanager won't automatically reconcile and add the info to the pod
**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@suyuee I think the reason is simply because this feature has not been supported, @luckymrwang do you have any comments?

**Comment by luckymrwang** [comment]
@suyuee Hi, which version the `yurtmanager` you use? And what's the version of the `CR` `gateway` resource, `v1alpha1` or `v1beta1`?

**Comment by suyuee** [comment]
@luckymrwang thanks for looking

I guess for yurtmanager is v1.3.4

for gateway version is `raven.openyurt.io/v1beta1`

**Comment by luckymrwang** [comment]
@suyuee You can use gateway version `raven.openyurt.io/v1alpha1`.  And `v1beta1` has some problems.

**Comment by suyuee** [comment]
@luckymrwang could you elaborate about the problems v1beta1 has, or point me to previous discussions about it?

**Comment by luckymrwang** [comment]
@suyuee I'm sorry, I misunderstood the question. Currently, this feature is indeed not supported.
I will add the feature, and if you are interested, you are welcome to contribute.
