### ISSUE TITLE
[BUG] YurtAppDaemon don't schedule the app into desired nodepool

### ISSUE THREAD

**Issue by luc99hen** [openyurtio/openyurt#1841]
**What happened**:
When I follow the [yurtappdaemon doc](https://openyurt.io/zh/docs/next/user-manuals/workload/yurt-app-daemon) to deploy my apps, the pod are not scheduled into the desired nodepool as expected.

The desired nodepool is `np19b635d8ee844b188ef726a23914a676`. 
![image](https://github.com/openyurtio/openyurt/assets/28707897/e308cb1d-c02c-4def-acec-51ddf841e055)

This nodepool only have one node
![image](https://github.com/openyurtio/openyurt/assets/28707897/802857dc-b565-418e-a60c-e12347bea822)

However the pod is schedule into 
![image](https://github.com/openyurtio/openyurt/assets/28707897/887e93f4-adee-44de-9405-d34c05f65064)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: v1.4
- Kubernetes version (use `kubectl version`):  
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@luc99hen Thank you for raising the issue. would you like to make a pull request to solve this bug?

**Comment by luc99hen** [comment]
I think the problem is from the webhook of yurtappoverrider. I will make a PR to resolve this.
