### ISSUE TITLE
[Question] The yurt-iot-dock image is missing the arm64 version

### ISSUE THREAD

**Issue by HuangYuFe** [openyurtio/openyurt#1842]
**What happened**:
I want to deploy yurt-iot-dock on a Raspberry Pi, but the image architecture is not compatible with arm64
**What you expected to happen**:
I hope to compile a yurt-iot-dock image that is compatible with the arm64 platform
**How to reproduce it (as minimally and precisely as possible)**:
Use the following commands on the ARM64 hardware platform:Use the following commands on the ARM64 hardware platform:
cat <<EOF | kubectl apply -f -
apiVersion: iot.openyurt.io/v1alpha2  
kind: PlatformAdmin  
metadata:  
  name: edgex-sample  
spec:  
  version: levski  
  poolName: beijing
components:
  - name: yurt-iot-dock
EOF
**Anything else we need to know?**:

**Environment**: 
- OpenYurt version:1.4.0
- Kubernetes version (use `kubectl version`):1.22.4
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
![屏幕截图 2023-12-06 113149](https://github.com/openyurtio/openyurt/assets/117882542/74bea23b-b201-4d17-924a-75fad26f712a)

**others**
/kind question

**Comment by YTGhost** [comment]
@LavenderQAQ PTAL

**Comment by LavenderQAQ** [comment]
@HuangYuFe Thank you for your feedback. This issue has been solved in pr #1843, and the corresponding image is also synchronized on dockerhub.
<img width="1295" alt="image" src="https://github.com/openyurtio/openyurt/assets/33485524/542eb979-2288-4dee-87a6-c257d982dc1f">
