### ISSUE TITLE
[Question] cloud-edge network connection not work when openyurt components are deployed in specified namesapce

### ISSUE THREAD

**Issue by tagGeeY** [openyurtio/openyurt#1845]
**What happened**:
I deploy openyurt components in specified namesapce _openyurt_, and join edge node by `yurtadm join --namespace=openyurt ...`, then create nodepool and gateway, but I cannot access pod running on edge nodes from cloud.
But when I redeploy openyurt components in kube-system namespace, access edge pods successfully.

**What you expected to happen**:
Everything works well when openyurt components deployed in specified namespace.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
By browsing yurt-manager logs, when deploying in specified namespace, yurt-manager don't print log in https://github.com/openyurtio/openyurt/blob/c1a47601312502adab12070b8ad42b48494239af/pkg/yurtmanager/controller/raven/gatewaypickup/gateway_pickup_controller.go#L302
It seems that _gateway_pickup_controller_ directly get raven-config info from kube-system namespace. 

**Environment**:
- OpenYurt version: v1.4.0
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: helm
- Others:

**others**
/kind question

**Comment by YTGhost** [comment]
> @YTGhost I think we should search `kube-system` string in the entire project, and check `kube-system` should be improved or not.
> 
> @tagGeeY would you like to take over this work and make openyurt can work in specified namespace?

@rambohe-ch Yes, in addition to the code I marked, I also found that there are many places in the `raven-controller` is still using the `util.WorkingNamespace`, these we have to change, I don't know if this is the case in other controllers.

**Comment by tagGeeY** [comment]
> @YTGhost I think we should search `kube-system` string in the entire project, and check `kube-system` should be improved or not.
> 
> @tagGeeY would you like to take over this work and make openyurt can work in specified namespace?

OK, I'd like to.

**Comment by tagGeeY** [comment]
@YTGhost @rambohe-ch 
I tried to modify codes by setting `util.WorkingNamespace` as `c.ComponentConfig.Generic.WorkingNamespace` in `pkg/yurtmanager/controller/raven`, and execute  
`make docker-build TARGET_PLATFORMS=linux/amd64 REGION=cn WHAT=yurt-manager` to get new yurt-manager image. I redeploy openyurt with the new image, components works normally and the cloud-edge network problem resolved.
But if directly edit deployment yurt-manager to update yurt-manager image, an error occurred: 
![image](https://github.com/openyurtio/openyurt/assets/35259969/abc6fac4-fc82-4569-b6f1-22bd143161e3)

and curiously, when I reedit deployment yurt-manager to restore original image `yurt-manager:v1.4.0`, that error reoccurred.
I tried to search which piece of code caused this problem, but unable to find, maybe it need deeply work.

**Comment by rambohe-ch** [comment]
> @YTGhost @rambohe-ch I tried to modify codes by setting `util.WorkingNamespace` as `c.ComponentConfig.Generic.WorkingNamespace` in `pkg/yurtmanager/controller/raven`, and execute `make docker-build TARGET_PLATFORMS=linux/amd64 REGION=cn WHAT=yurt-manager` to get new yurt-manager image. I redeploy openyurt with the new image, components works normally and the cloud-edge network problem resolved. But if directly edit deployment yurt-manager to update yurt-manager image, an error occurred: ![image](https://private-user-images.githubusercontent.com/35259969/289479293-abc6fac4-fc82-4569-b6f1-22bd143161e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNzM4NzEsIm5iZiI6MTcwMjM3MzU3MSwicGF0aCI6Ii8zNTI1OTk2OS8yODk0NzkyOTMtYWJjNmZhYzQtZmM4Mi00NTY5LWI2ZjEtMjJiZDE0MzE2MWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDA5MzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1ZTNiN2QwNjliY2UyMWEzNWViYjZiM2I1ZTcxZmU3Y2NjNzBhYWMzNGIzZjg2MjZkNmM4MGM1ZmQ2MjY4OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oLO05GJuwU1Rri1vN2s_MQ2T81r9-1DCeen7ztGDV-M)
> 
> and curiously, after I reedit deployment yurt-manager to restore original image `yurt-manager:v1.4.0`, that error reoccurred. I don't know why yurt-manager still watch resources in `kube-system` namespace, and I tried to search which piece of code caused this problem, but unable to find, maybe it need deeply work.

@tagGeeY It seems that `kube-system` hard code is used in the CRD convert definition, like as following:

https://github.com/openyurtio/openyurt/blob/73315d2f75255ba2e9fc894557cfa14b9a13d123/charts/yurt-manager/crds/raven.openyurt.io_gateways.yaml#L327

https://github.com/openyurtio/openyurt/blob/73315d2f75255ba2e9fc894557cfa14b9a13d123/charts/yurt-manager/crds/apps.openyurt.io_nodepools.yaml#L244

**Comment by rambohe-ch** [comment]
@tagGeeY by the way, files under crds directory can not be rendered by helm, so you need to modify these `kube-system` hard code to specified namespace manually before you deploy yurt-manager by helm.

**Comment by tagGeeY** [comment]
> @tagGeeY by the way, files under crds directory can not be rendered by helm, so you need to modify these `kube-system` hard code to specified namespace manually before you deploy yurt-manager by helm.

Thanks, I get it! This question was discussed in https://github.com/helm/helm/issues/8171.

May I update yurt-manager charts accoding to the recommended method in the helm documentation https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts, then the CRDs will be managed in a subchart.

**Comment by rambohe-ch** [comment]
> > @tagGeeY by the way, files under crds directory can not be rendered by helm, so you need to modify these `kube-system` hard code to specified namespace manually before you deploy yurt-manager by helm.
> 
> Thanks, I get it! This question was discussed in [helm/helm#8171](https://github.com/helm/helm/issues/8171).
> 
> May I update yurt-manager charts accoding to the recommended method in the helm documentation https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts, then the CRDs will be managed in a subchart.

@tagGeeY sorry to reply late, i think it is not a good idea to remove `CRDs` yaml files into `template` directory, because we can not make sure `CRDs` are installed before `yurt-manager`.yaml file if we remove them into `template` directory.

maybe we should extract another new chart repo(like named yurt-manager-crds) for managing these `CRDs` yaml files. and then user should install this helm chart before installing yurt-manager chart.

**Comment by rambohe-ch** [comment]
by the way, we need to modify the script `https://github.com/openyurtio/openyurt/blob/master/hack/make-rules/kustomize_to_chart.sh` file and make sure `make manifests` command can generate this new helm chart repo.

**Comment by tagGeeY** [comment]
> @tagGeeY by the way, we need to modify the script `https://github.com/openyurtio/openyurt/blob/master/hack/make-rules/kustomize_to_chart.sh` file and make sure `make manifests` command can generate this new helm chart repo.

Thanks for addintional reply.

**Comment by tagGeeY** [comment]
> > > @tagGeeY by the way, files under crds directory can not be rendered by helm, so you need to modify these `kube-system` hard code to specified namespace manually before you deploy yurt-manager by helm.
> > 
> > 
> > Thanks, I get it! This question was discussed in [helm/helm#8171](https://github.com/helm/helm/issues/8171).
> > May I update yurt-manager charts accoding to the recommended method in the helm documentation https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts, then the CRDs will be managed in a subchart.
> 
> @tagGeeY sorry to reply late, i think it is not a good idea to remove `CRDs` yaml files into `template` directory, because we can not make sure `CRDs` are installed before `yurt-manager`.yaml file if we remove them into `template` directory.
> 
> maybe we should extract another new chart repo(like named yurt-manager-crds) for managing these `CRDs` yaml files. and then user should install this helm chart before installing yurt-manager chart.

No matter. I executed `helm install --dry-run` to confirm, CRDs in subchart are installed before deployments, but I can not make sure your worries will not happend. So I will revoke my modification in yurt-manager chart.

**Comment by rambohe-ch** [comment]
> > > > @tagGeeY by the way, files under crds directory can not be rendered by helm, so you need to modify these `kube-system` hard code to specified namespace manually before you deploy yurt-manager by helm.
> > > 
> > > 
> > > Thanks, I get it! This question was discussed in [helm/helm#8171](https://github.com/helm/helm/issues/8171).
> > > May I update yurt-manager charts accoding to the recommended method in the helm documentation https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-2-separate-charts, then the CRDs will be managed in a subchart.
> > 
> > 
> > @tagGeeY sorry to reply late, i think it is not a good idea to remove `CRDs` yaml files into `template` directory, because we can not make sure `CRDs` are installed before `yurt-manager`.yaml file if we remove them into `template` directory.
> > maybe we should extract another new chart repo(like named yurt-manager-crds) for managing these `CRDs` yaml files. and then user should install this helm chart before installing yurt-manager chart.
> 
> No matter. I executed `helm install --dry-run` to confirm, CRDs in subchart are installed before deployments, but I can not make sure your worries will not happend. So I will revoke my modification in yurt-manager chart.

@tagGeeY Thanks for your response, i think that `helm install` command can not make sure the installation order for yaml files under template directory. and It is possible to install the yaml files in alphabetical order, so `yurt-manager.yaml` is last file that is installed.
