### ISSUE TITLE
[Question] How many devices can be managed at most  through yurt-iot-dock in a k8s cluster?

### ISSUE THREAD

**Issue by zhang943** [openyurtio/openyurt#1858]
**What happened**:

**What you expected to happen**: 
Is there any performance report about yurt-iot-dock and k8s api-server when the number of managed devices increases?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@LavenderQAQ PTAL

**Comment by LavenderQAQ** [comment]
@zhang943 I'm sorry, we haven't done the performance test yet. The number of devices to access should depend on the access capability of edgex, you can check the documentation of edgex. OpenYurt deploys edgex in a distributed manner, and the increase in access capacity is more than offset by the loss of performance on the management side (you can deploy multiple EdgeXs in multiple nodepools). Moreover, cluster scale and data generated by each device are also different, so it is difficult to directly give a definite value.

**Comment by zhang943** [comment]
@LavenderQAQ Thanks.
