### ISSUE TITLE
[BUG] 不是代码的问题，是官网的OpenYurt 体验中心打不开了

### ISSUE THREAD

**Issue by wuyeguo** [openyurtio/openyurt#1859]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

这个还能打开么？

**Comment by luc99hen** [comment]
The OpenYurt Experience Center is currently undergoing architectural upgrades and is not yet open for use.

**Comment by rambohe-ch** [comment]
@wuyeguo at present, openyurt community has no enough time to support OpenYurt Experience Center, so we have temporarily removed OpenYurt Experience Center in the OpenYurt website.

and i will close the issue, and you can feel free to reopen or create new issues if you have any questions.
