### ISSUE TITLE
[Question] 请问端节点如何访问到正确的边节点

### ISSUE THREAD

**Issue by wuyeguo** [openyurtio/openyurt#1860]
**What happened**:
目前正在做类似的技术选型，如果我现在需要做一个服务，部署在边节点，提供图片的的推理服务
那我的端节点在使用[openyurt](https://github.com/openyurtio/openyurt) 的情况下，该如何选择距离自己最近的边节点？
是通过配置？还是需要每次请求的时候判定一下哪个是最近的存活的边节点，然后提交图片请求？

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@wuyeguo Thanks for raising the issue. 
At first i want to conclude your scenario: 
- feature1: you will manage scattered edge nodes in one OpenYurt cluster, and deploy image inference applications on these edge nodes in different regions or cities.
- feature2: then you will expose all image inference applications to external access through the LoadBalancer service of OpenYurt, enabling access from outside the OpenYurt cluster.
- feature3: then all requests from end users should come to one entry point(like gateway service) firstly, then the entry point will forward  the request to the nearest backend image inference service.

above conclusion is correct or not? if the conclusion is correct, OpenYurt can provide the feature1 and feature2, and you need to prepare the feature3 by yourself.

**Comment by wuyeguo** [comment]
谢谢，完整的解析了我的需求。
我的需求是
2. 里面，OpenYurt 是可以有指令自动实现edge nodes上的推理服务直接在本节点对外透出服务的吧？
3. 里面，是否有什么成熟的案例或者文档可以参考？我现在想的是，搞个管理平台，提供一个查询服务，端节点定期轮询距离自己较近的几个节点，然后访问距离自己最近的这样

**Comment by rambohe-ch** [comment]
@wuyeguo Thanks for your reply.

> 2. 里面，OpenYurt 是可以有指令自动实现edge nodes上的推理服务直接在本节点对外透出服务的吧？ 

yes, you can use a LoadBalancer service(LoadBalancerClass="service.openyurt.io/vip") to expose your image inference applications in different regions to outside of OpenYurt cluster. the details of this feature, you can reference link here: https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20231121-high-availability-of-edge-services.md

by the way, this feature is under developing, and will be released in OpenYurt v1.5.

> 3. 里面，是否有什么成熟的案例或者文档可以参考？我现在想的是，搞个管理平台，提供一个查询服务，端节点定期轮询距离自己较近的几个节点，然后访问距离自己最近的这样

i think the simplest solution is to use a commercial DNS service(like https://wanwang.aliyun.com/domain/dns?spm=5176.28508143.J_4VYgf18xNlTAyFFbOuOQe.102.45a6154a040Doi) that provides this feature.

**Comment by wuyeguo** [comment]
太感谢了，想再请问下，openyurt是否可以和Kserve结合使用？如果可以的话，和普通的K8S一样的么？

**Comment by wuyeguo** [comment]
by the way, this feature is under developing, and will be released in OpenYurt v1.5.
OpenYurt v1.5 大约什么时间发布？

**Comment by rambohe-ch** [comment]
> 太感谢了，想再请问下，openyurt是否可以和Kserve结合使用？如果可以的话，和普通的K8S一样的么？

@wuyeguo I think that Kserve can work in OpenYurt cluster smoothly, and welcome you to report problems about Kserve integration.

**Comment by rambohe-ch** [comment]
> > 太感谢了，想再请问下，openyurt是否可以和Kserve结合使用？如果可以的话，和普通的K8S一样的么？
> 
> @wuyeguo I think that Kserve can work in OpenYurt cluster smoothly, and welcome you to report problems about Kserve integration.

@wuyeguo OpenYurt v1.5 is under developing, and we will release it at the end of 2024.2.

**Comment by rambohe-ch** [comment]
@wuyeguo I think we can close this issue now, and you can feel free to reopen or create new issues if you have problem about this case.

**Comment by wuyeguo** [comment]
yes， thans very much
