### ISSUE TITLE
[feature request]improve DaemonSet upgrade models check

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1869]
**What would you like to be added**:
1. we have added two new upgrade models for DaemonSet workload, AdvancedRollingUpdate and OTA. and the definition as following:

https://github.com/openyurtio/openyurt/blob/74b0a474deee7a2305d679c3eeb270fb6245d24b/pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go#L75-L80

2. and only `AdvancedRollingUpdate, OTA` can be accepted when we use it as the following:

https://github.com/openyurtio/openyurt/blob/74b0a474deee7a2305d679c3eeb270fb6245d24b/pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go#L243-L261

3. we want to support more flexible for these upgrade models, for example: `advancedRollingUpdate` with small letter begin, or  `ota` with all small letters. so maybe we can use `strings.ToLower()` to change these upgrade models to entire small letters before models check.

4. we need to improve all places in DaemonPod Updater controller which these new upgrade models are used.

**others**
/kind feature

**Comment by huangchenzhao** [comment]
Hi, @rambohe-ch 
I'm new to openyurt, and I want to try this issue.
