### ISSUE TITLE
[BUG] YurtAppDaemon status currentRevision is not updated when yad change

### ISSUE THREAD

**Issue by luc99hen** [openyurtio/openyurt#1879]
**What happened**:
After editing yurt-app-daemon(yad)'s spec, another controllerRevision(cr) will be created and currentRevision in yad's status should be updated according to the new created cr. Currently, the status will not be updated.

**What you expected to happen**:
yad's status currentRevision is up to date with the latest cr.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: v1.4 
- Kubernetes version (use `kubectl version`): 
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@luc99hen Thanks for raising issue. would you like to make a pull request to fix this problem?

**Comment by luc99hen** [comment]
This is related revision management in the yad controller. I think we can make it a good first issue for the community first. 
If nobody wants to take, I can fix it.

**Comment by huangchenzhao** [comment]
Hi @luc99hen ,

If I'm not wrong, I think it seems that changes will be made in the  following line
https://github.com/openyurtio/openyurt/blob/master/pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go#L203

before invoking function updateStatus, we just need to replace `currentRevision` to `expectedRevision`  to solve this problem.

Let me know if I'm on the right track. I would like to try this issue.

**Comment by luc99hen** [comment]
Yes, I think it's where the problem is. But it may still need further testing and observation. 
Welcome to create your PR to fix this.



> Hi @luc99hen ,
> 
> If I'm not wrong, It seems that changes will be made in the following line https://github.com/openyurtio/openyurt/blob/master/pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go#L203
> 
> before invoking function updateStatus, we just need to replace `currentRevision` to `expectedRevision` to solve this problem.
> 
> I wonder if I'm on the right track. I would like to try this issue.

**Comment by huangchenzhao** [comment]
> Yes, I think it's where the problem is. But it may still need further testing and observation. Welcome to create your PR to fix this.
> 
> > Hi @luc99hen ,
> > If I'm not wrong, It seems that changes will be made in the following line https://github.com/openyurtio/openyurt/blob/master/pkg/yurtmanager/controller/yurtappdaemon/yurtappdaemon_controller.go#L203
> > before invoking function updateStatus, we just need to replace `currentRevision` to `expectedRevision` to solve this problem.
> > I wonder if I'm on the right track. I would like to try this issue.

Thanks for your reply, I have created a new pr to fix this issue.
