### ISSUE TITLE
[Question]当前openyurt支持将手动创建的Kubernetes集群（非阿里ack集群）转换为openyurt集群吗

### ISSUE THREAD

**Issue by seveirbian** [openyurtio/openyurt#188]

**Comment by rambohe-ch** [comment]
@seveirbian yeah, openyurt can convert native kubernetes cluster that provided by any vendor to openyurt cluster. no vendor lock.

**Comment by liangyuanpeng** [comment]
It's will be replace `my kubelet` or not?

> @seveirbian yeah, openyurt can convert native kubernetes cluster that provided by any vendor to openyurt cluster. no vendor lock.

**Comment by rambohe-ch** [comment]
> > @seveirbian yeah, openyurt can convert native kubernetes cluster that provided by any vendor to openyurt cluster. no vendor lock.
> 
> I have a question ,It's will be replace `my kubelet` or not? Thanks.

@liangyuanpeng a good question, openyurt will not replace `kubelet` on the node,  and only adjust the connection destination for `kubelet` from kube-apiserver to yurthub (`127.0.0.1:10261`) , then yurthub will proxy the request from kubelet to kube-apiserver

**Comment by MIBc** [comment]
Your can reference the document https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/manually-setup.md
@seveirbian

**Comment by seveirbian** [comment]
thanks, i've succeed.
