### ISSUE TITLE
[feature request]improve key logs in yurthub component

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1881]
**What would you like to be added**:
There are some tricky logs in yurthub component as following:

> cache_manager.go:650] skip to cache watch event because key({%!s(bool=false)       kubelet/pods.v1.core/kube-system/kube-proxy-7g4dc}) is under processing

The reason is that var `key` is a struct not a string, so `%s` in `klog.Infof` print the above tricky logs. 

so the following code should be modified:

- current: https://github.com/openyurtio/openyurt/blob/9fb701eb8b5d50c97674f441fede8273149fec73/pkg/yurthub/cachemanager/cache_manager.go#L650

- improved:

```
klog.V(2).Infof("skip to cache watch event because key(%s) is under processing", key.Key())
```

by the way, the following lines have the same kind of problems.

https://github.com/openyurtio/openyurt/blob/9fb701eb8b5d50c97674f441fede8273149fec73/pkg/yurthub/cachemanager/cache_manager.go#L630

https://github.com/openyurtio/openyurt/blob/9fb701eb8b5d50c97674f441fede8273149fec73/pkg/yurthub/cachemanager/cache_manager.go#L644

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@wangzihao05 Do you have any progress about this issue?

**Comment by wangzihao05** [comment]
I have understood this issue.The problem is that struct that is supposed to be string is causing the log exception. I have modified part of the code as required.And I will finish and commit later this week.

**Comment by rambohe-ch** [comment]
> I have understood this issue.The problem is that struct that is supposed to be string is causing the log exception. I have modified part of the code as required.And I will finish and commit later this week.

@wangzihao05 Thanks for your kindly response.
 yes,  var `key` is a pointer of a struct, so you need to replace `key` by `key.Key()` only.

**Comment by Congrool** [comment]
Since the pr has been merged, close.

/close
