### ISSUE TITLE
[BUG] clusterrole `yurt-manager-role` in yurt-manager helm chart lacks nodes/status resource

### ISSUE THREAD

**Issue by qclc** [openyurtio/openyurt#1882]
**What happened**:
The clusterrole `yurt-manager-role` in yurt-manager helm chart lacks permissions for nodes/status：
[charts/yurt-app-manager/templates/clusterrole.yaml](https://github.com/openyurtio/openyurt-helm/blob/f0ab5fb10f50dd0c57e50f1f3a7378b72b75f0b3/charts/yurt-app-manager/templates/clusterrole.yaml#L245)
If role of `nodes/status` resource is missing, the operation of yurt-manager to update the node status is prohibited.

**What you expected to happen**:
add `nodes/status` resources in [charts/yurt-app-manager/templates/clusterrole.yaml](https://github.com/openyurtio/openyurt-helm/blob/f0ab5fb10f50dd0c57e50f1f3a7378b72b75f0b3/charts/yurt-app-manager/templates/clusterrole.yaml#L245)
```
- apiGroups:
  - ""
  resources:
  - nodes
  # add this
  - nodes/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
It seems that the helm chart of yurt-manager is automatically generated by openyurt-bot. I haven't found how to add this role in the code yet.

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@qclc Thank you raising the issue. would you like to make a pull request to fix this bug?

**Comment by qclc** [comment]
> @qclc Thank you raising the issue. would you like to make a pull request to fix this bug?
> 
> by the way, which controller in yurt-manager need to update node status?

Ok, the pr has been submitted. This will affect the nodelifecycle-controller of yurt-manager
