### ISSUE TITLE
[BUG] yurtadm join doesn't work: Failed to request cluster-info, forbidden

### ISSUE THREAD

**Issue by thrashwerk** [openyurtio/openyurt#1886]
**What happened**:
yurtadm join doesn't work

**What you expected to happen**:
Node join the cluster

**How to reproduce it (as minimally and precisely as possible)**:
Install OpenYurt control plane components on existing K8s cluster according to https://openyurt.io/docs/installation/manually-setup/
Generate a bootstrap token with kubeadm `kubeadm token create --print-join-command`
Create a separate VM
Install CRI-O on VM
Download yurtadm on VM
Run on VM: `./yurtadm join my-k8s-api.com:443 --token=cari31.z50omwaoegqo9r85 --node-type=edge --discovery-token-unsafe-skip-ca-verification --v=5`

**Anything else we need to know?**:
```
# ./yurtadm join my-k8s-api.com:443 --token=cari31.z50omwaoegqo9r85 --node-type=edge --discovery-token-unsafe-skip-ca-verification --v=5
I1228 14:47:13.821419    3204 token.go:105] [discovery] Created cluster-info discovery client, requesting info from "76-420276-openyurt.mkaas.k1.luxembourg-2.cloud.gcore.dev:443"
I1228 14:47:13.821702    3204 token.go:230] [discovery] kube client is nil, use bootstrap config(&{  {false map[]} map[kubernetes:0xc0000b6b80] map[] map[token-bootstrap-client@kubernetes:0xc000109630] token-bootstrap-client@kubernetes map[]}) to create client
I1228 14:47:14.120510    3204 token.go:243] [discovery] Failed to request cluster-info, will try again: configmaps "cluster-info" is forbidden: User "system:anonymous" cannot get resource "configmaps" in API group "" in the namespace "kube-public"
```

**Environment**:
- OpenYurt version: 1.4.0
- Kubernetes version (use `kubectl version`): 1.28.3
- OS (e.g: `cat /etc/os-release`): Ubuntu 22.04
- Kernel (e.g. `uname -a`): 5.15.0-87-generic
- Install tools: Helm

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@thrashwerk Thanks for raising the issue. from the logs of `yurtadm join`, we can see that there is not enough rights for `system:anonymous` user to get configmap `kube-public/cluster-info`.

in general, The following role/rolebinding rbac settings have already been installed in the cluster after `kubeadm init` completed.

```
# kubectl -n kube-public get rolebinding kubeadm:bootstrap-signer-clusterinfo -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubeadm:bootstrap-signer-clusterinfo
  namespace: kube-public
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubeadm:bootstrap-signer-clusterinfo
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:anonymous

# kubectl -n kube-public get role kubeadm:bootstrap-signer-clusterinfo -o yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubeadm:bootstrap-signer-clusterinfo
  namespace: kube-public
rules:
- apiGroups:
  - ""
  resourceNames:
  - cluster-info
  resources:
  - configmaps
  verbs:
  - get
```

you can apply the above rbac settings to the cluster, and `yurtadm reset` the node, then `yurtadm join` the node agian. please have a try.

**Comment by thrashwerk** [comment]
> there is not enough rights for `system:anonymous` user to get configmap `kube-public/cluster-info`.

Why should any anonymous have these rights or any rights at all? Sounds like a security issue.

Also, the `cluster-info` configmap doesn't exist in my cluster.

**Comment by YTGhost** [comment]
> > there is not enough rights for `system:anonymous` user to get configmap `kube-public/cluster-info`.
> 
> Why should any anonymous have these rights or any rights at all? Sounds like a security issue.
> 
> Also, the `cluster-info` configmap doesn't exist in my cluster.

In fact, the `kube-public` namespace is designed to hold public information, and the main purpose of this `ConfigMap` is to allow users with read-only access to the cluster (e.g. unauthenticated users) to get basic information about the cluster.

I think that maybe some issues with your cluster? This configmap shouldn't be missing.

**Comment by thrashwerk** [comment]
> I think that maybe some issues with your cluster? This configmap shouldn't be missing.

Yes, it's a managed cluster in the cloud, maybe they have some weird setup.

I think we can close this, thanks.
