### ISSUE TITLE
[Question] Raven0 traffic is always broadcasted to all vxlan nodes

### ISSUE THREAD

**Issue by suyuee** [openyurtio/openyurt#1893]
**What happened**: we noticed that all traffic through raven0 is always flooded(broadcast) to all nodes in vxlan. I'm not sure if it's expected, but the `bridge fdb` command shows the mac addresses are always 0; should they be "learnt" and replaced with actual mac address?

```
00:00:00:00:00:00 dev raven0 dst <ip1> self permanent
00:00:00:00:00:00 dev raven0 dst <ip2> self permanent
```

**What you expected to happen**:

raven0 traffic should flood all vxlan nodes.

**How to reproduce it (as minimally and precisely as possible)**:

Nodes A, B, C are in the same raven vxlan; on node A, pings node B; on Node C, tcpdump -i any icmp, and in our environment, we see the ping requests consistently observed on node C

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by suyuee** [comment]
further investigation with `ip -d link show raven0` indicates that, raven0 is marked with nolearning (vxlan attributes learning is false by default). My understanding is flooding traffic is expected behavior? I'd like to learn how production deployment can work with such setup.

**Comment by BSWANG** [comment]
@suyuee fixed in https://github.com/openyurtio/raven/pull/165
