### ISSUE TITLE
[feature request]improve configuration of concurrent daemon pod updater workers

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1907]
**What would you like to be added**:

please refer to pull request #1906 and improve `daemonpodupdater-workers` configuration for daemonpodupdater controller in yurt-manager component.

https://github.com/openyurtio/openyurt/blob/ed209553bdb8ba128771f5fb2c53d74e0dabcd8e/pkg/yurtmanager/controller/daemonpodupdater/daemon_pod_updater_controller.go#L59

**others**
/kind feature

**Comment by huangchenzhao** [comment]
I would like to try this issue
/assign @huangchenzhao
