### ISSUE TITLE
[feature request]improve configuration of concurrent platformadmin workers

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1909]
**What would you like to be added**:

please refer to pull request https://github.com/openyurtio/openyurt/pull/1906 and improve `platformadmin-workers` configuration for platformadmin controller in yurt-manager component.

https://github.com/openyurtio/openyurt/blob/ed209553bdb8ba128771f5fb2c53d74e0dabcd8e/pkg/yurtmanager/controller/platformadmin/platformadmin_controller.go#L58

**others**
/kind feature

**Comment by MundaneImmortal** [comment]
\assign @MundaneImmortal
