### ISSUE TITLE
[feature request]improve configuration of concurrent servicetopology endpointslice workers 

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#1911]
**What would you like to be added**:

please refer to pull request https://github.com/openyurtio/openyurt/pull/1906 and improve `servicetopology-endpointslice-workers` configuration for servicetopology-endpointslice controller in yurt-manager component.

https://github.com/openyurtio/openyurt/blob/ed209553bdb8ba128771f5fb2c53d74e0dabcd8e/pkg/yurtmanager/controller/servicetopology/endpointslice/endpointslice_controller.go#L42

**others**
/kind feature

**Comment by Bharadwajshivam28** [comment]
Hey @rambohe-ch I can take on this but I need some more details and steps to get started as it will be my first issue

**Comment by rambohe-ch** [comment]
@Bharadwajshivam28 Do you have any progress about this issue?

**Comment by YTGhost** [comment]
@rambohe-ch I think we can close it because https://github.com/openyurtio/openyurt/pull/2086 fix it.

**Comment by rambohe-ch** [comment]
> @rambohe-ch I think we can close it because #2086 fix it.

@YTGhost Thank you for your notice, i will close this issue.
