### ISSUE TITLE
 Not able to communicate to edge nodes from cloud node 

### ISSUE THREAD

**Issue by karthik507** [openyurtio/openyurt#1943]
1.We have 3 cloud nodes and 4 edge nodes.
2. we are using containerd on cloud node and docker on the edge node.
3. installed yurt-Manager, yurthub artifacts and raven agent in cloud nodes.
4. After yurtadm join command in the edge node following were not installed automatically  kubectl, and 
kube-proxy , i am not able to communicate from any one cloud node to edge node.
5. openyurt cloud nodes
 kubectl get pod -A | grep yurt
```typescript
kube-system          yurt-hub-edgebox1                                 1/1     Running   3                  3h19m
kube-system          yurt-hub-edgebox2                                 1/1     Running   1                  3h27m
kube-system          yurt-hub-edgebox3                                 1/1     Running   1                  3h25m
kube-system          yurt-hub-edgebox4                                 1/1     Running   1                  3h22m
kube-system          yurt-manager-66895657fc-hnfzb                     1/1     Running   17 (51s ago)       4h36m
``` 

6.Pods running in edgebox
kubectl get pod -A -o wide | grep edgebox1
                     
```typescript
kube-system          kube-ovn-cni-76bcq                                1/1     Running   0                  3h22m             
kube-system          kube-ovn-pinger-chh8p                             1/1     Running   0                  3h22m   
kube-system          kube-proxy-qzpqg                                  1/1     Running   0                  3h22m   
kube-system          multus-9tpch                                      1/1     Running   0                  3h23m   
kube-system          ovs-cni-amd64-hvpvz                               1/1     Running   0                  3h23m   
kube-system          ovs-ovn-hfxrg                                     1/1     Running   0                  3h23m   
kube-system          raven-agent-ds-xfzgx                              1/1     Running   2 (3h22m ago)      3h23m   
kube-system          yurt-hub-edgebox1                                 1/1     Running   3                  3h22m   
``` 

   

Environment:
1.OpenYurt version: v1.4.0
2. Ubuntu 22.04

**Comment by YTGhost** [comment]
@karthik507 Hi, I think I need some more detailed information to help me understand the issue you're encountering. For instance, when you say you're unable to communicate, does it mean you can't use `kubectl get pod` on the cloud node to get information from the edge node? Additionally, I need the logs for `yurt-manager` and `raven-agent`, as I noticed they have restarted a few times.

**Comment by karthik507** [comment]
Yes mI will share the logs , Iam reinstalling yurt components again after it finishes i will send.

**Comment by karthik507** [comment]
> @karthik507 Hi, I think I need some more detailed information to help me understand the issue you're encountering. For instance, when you say you're unable to communicate, does it mean you can't use `kubectl get pod` on the cloud node to get information from the edge node? Additionally, I need the logs for `yurt-manager` and `raven-agent`, as I noticed they have restarted a few times.

Iam able to do kubectl to edgebox pods but not able to ping from cloud node to edge node

**Comment by YTGhost** [comment]
@karthik507 any update?

**Comment by karthik507** [comment]
> @karthik507 any update?

@YTGhost sorry for the delay we will update the logs in few minutes.

**Comment by karthik507** [comment]
@YTGhost please refer the below file for the logs

[ravenagent logs.txt](https://github.com/openyurtio/openyurt/files/14161229/ravenagent.logs.txt)
[yurthub logs.txt](https://github.com/openyurtio/openyurt/files/14161230/yurthub.logs.txt)
[yurtmanager logs.txt](https://github.com/openyurtio/openyurt/files/14161232/yurtmanager.logs.txt)

when we try to get pod logs of yurthub running in edgebox from cloud machine, we get the below error
Error from server: Get "https://192.168.102.30:10250/containerLogs/kube-system/yurt-hub-edgebox1/yurt-hub": dial tcp 192.168.102.30:10250: i/o timeout

**Comment by karthik507** [comment]
@YTGhost any updates ?

**Comment by YTGhost** [comment]
> @YTGhost any updates ?

Sorry, busy on my work. @River-sh Can you help?
