### ISSUE TITLE
slack channel is not working 

### ISSUE THREAD

**Issue by karthik507** [openyurtio/openyurt#1944]
Link to join openyurt slack channel not working please check it, showing link is no active.

**Comment by YTGhost** [comment]
@karthik507 have a try: https://join.slack.com/t/openyurt/shared_invite/zt-2bptiyzuv-oDDlfdLwS0AuxSyD4cq4eA

**Comment by karthik507** [comment]
Thank you

**Comment by aravindgpd** [comment]
@YTGhost 
not able join the channel from above link , can you help

**Comment by aravindgpd** [comment]
Thank you @YTGhost

**Comment by rambohe-ch** [comment]
@karthik507 Would you like to make a pull request to update the slack link in the readme?

- The following slack link will not be expired.
https://join.slack.com/t/openyurt/shared_invite/zt-2ajsy47br-jl~zjumRsCAE~BlPRRsIvg

**Comment by karthik507** [comment]
> @karthik507 Would you like to make a pull request to update the slack link in the readme?
> 
> * The following slack link will not be expired.
>   https://join.slack.com/t/openyurt/shared_invite/zt-2ajsy47br-jl~zjumRsCAE~BlPRRsIvg

okay
