### ISSUE TITLE
[Question] SVC timeout for application running in edgenode

### ISSUE THREAD

**Issue by aravindgpd** [openyurtio/openyurt#1960]
**What happened**:
we have a five node cluster, 3 master node and 2 worker node ( edgebox). And currently we are maintaining 2 node pools ( one nodepool with all cloud nodes and other nodepool with all the edge nodes)
```
kubectl get np
NAME      TYPE    READYNODES   NOTREADYNODES   AGE
cloud     Cloud   3            0               19d
edgebox   Edge    2            0               4h12m

```
we have following gateway , were both the edgeboxs have separate gateway.
```
 kubectl get gw
NAME          AGE
gw-cloud      19d
gw-edgebox    3h45m
gw-edgebox4   3h18m

```
we installed longhorn application as part of the setup. the pods running in edgeboxs constantly going into crashbackloop because of below error
```
 msg="Error starting CSI manager: Failed to initialize Longhorn API client: Get \"http://longhorn-backend.longhorn-system.svc.cluster.local:9500/v1\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" func=app.CSICommand.func1 file="csi.go:37"

 all the pods associated to the longhorn-backend service is up.
```
Please help us on the configuration to solve the above issue.

OpenYurt version: 1.4.0
Kubernetes version (use kubectl version): 1.22.0
OS (e.g: cat /etc/os-release): Ubuntu 20.04.5 LTS ( Focal Fossa)
Kernel (e.g. uname -a): 5.4.0-170-generic
Install tools:
Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@aravindgpd Thanks for raising the issue. sorry to response lately. 

Would you have any progress about this issue? It seems the network communication between pods maybe unreachable.
