### ISSUE TITLE
[feature request] Enhancement about tweaks of yurtappset

### ISSUE THREAD

**Issue by vie-serendipity** [openyurtio/openyurt#1970]
**What would you like to be added**:
Add {{nodepool}} to replace the specified nodepool, users can batch inject configmap and secret that match the naming rules.

**Why is this needed**:
There may be different configmaps for different nodepools, and the user may need to write tweaks one by one. After joining {{nodepool}}, the user can bulk write by regularly naming the configmap and secret, like configmap-xxx (xxx represents the detailed name of nodepool).

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@vie-serendipity It's a good idea to use {{nodepool}} to match multiple nodepools, as it allows users to easily perform batch configurations at the nodepool level.

I think we should make the definition more clearly, so how about use {{nodepool-name}} to replace {{nodepool}}?

**Comment by vie-serendipity** [comment]
@rambohe-ch Good idea.
