### ISSUE TITLE
[BUG] yurt-iot-dock v1.4.1 doesn't match the edgex v3.1.0

### ISSUE THREAD

**Issue by 24sama** [openyurtio/openyurt#1992]
**What happened**:
When I deploy yurt-iot-dock v1.4.1, I fount it doesn't match the edgex v3.1.0.

<img width="1268" alt="image" src="https://github.com/openyurtio/openyurt/assets/43993589/e1ab9ab9-4a02-4c54-8e20-2cb03ab29497">

And I see the code logic of the release-v1.4 branch and v1.4.1 tag, which all don't contain the "napa".
https://github.com/openyurtio/openyurt/blob/cb2055bc5ba04b202900eaeeda3437eea1192626/pkg/yurtiotdock/clients/edgex-foundry/edgexobject.go#L44-L69

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@zyjhtangtang @LavenderQAQ PTAL

**Comment by LavenderQAQ** [comment]
@24sama Thank you for raising this issue. In fact, this should already be supported. We just need to add the napa case. Could you submit a pr to help fix this?

**Comment by 24sama** [comment]
@LavenderQAQ Got it, and I found this PR: 
https://github.com/openyurtio/openyurt/pull/1850
Maybe we can cherry-pick this PR into release-v1.4

Another question, if I build the yurt-iot-dock from release-v1.4 source code, Is it will miss some feature or bugfix PR which is compared to official v1.4.1 version?

**Comment by LavenderQAQ** [comment]
@24sama When 1.4 was released, there was no napa release yet. This is a more recent version that we support, and we can fix it directly on master.

**Comment by 24sama** [comment]
Thanks @LavenderQAQ , so it means there is only a master branch that supports napa release. And how soon is the official plan to release a new version with napa support? Just like this, we can checkout a new release branch that includes all master PR, and can build it from the release branch.

**Comment by rambohe-ch** [comment]
> Thanks @LavenderQAQ , so it means there is only a master branch that supports napa release. And how soon is the official plan to release a new version with napa support? Just like this, we can checkout a new release branch that includes all master PR, and can build it from the release branch.

@24sama we plan to release OpenYurt v1.5 in the middle of April, please stay in tune.
