### ISSUE TITLE
 e2e failed in prepare_autonomy_tests

### ISSUE THREAD

**Issue by vie-serendipity** [openyurtio/openyurt#1999]
#### Which jobs are failing:
```plain-text
+ kubectl wait --for=condition=Ready pod/yurt-e2e-test-nginx-openyurt-e2e-test-worker --timeout=240s
Error from server (NotFound): pods "yurt-e2e-test-nginx-openyurt-e2e-test-worker" not found
make: *** [Makefile:114: e2e-tests] Error 1
Error: Process completed with exit code 2.
```
#### Reason for failure:
Unknown
#### labels

/kind failing-test

**Comment by vie-serendipity** [comment]
@Congrool I notice e2e failed in https://github.com/openyurtio/openyurt/pull/1996 too. And it seems fine for now after rerun. Will it work if it keeps rerun or is there any way to work?

**Comment by Congrool** [comment]
I guess it failed for bad performance of github action, which may timeout. If more failures occur, at that time, we have to figure out the reason. Currently, just rerun.
