### ISSUE TITLE
[feature request] Concurrent Rolling Upgrades between Node Pools

### ISSUE THREAD

**Issue by chunhui1012** [openyurtio/openyurt#2008]
**What would you like to be added**:
A service deployed across multiple node pools， perform rolling upgrades based on node pools 。

rolling upgrades with nodepool selecter

**Why is this needed**:
to increase parallelism and reduce upgrade time.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@chunhui1012 If you use YurtAppSet to deploy applications across NodePools, you can use the `tweaks` feature in `YurtAppSet` to perform gray upgrade for applications.

the proposal of `YurtAppSet` is here: https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20240102-upgrade-yurtappset-to-v1beta1.md

and the tutorial docs of `YurtAppSet` is under writing by @luc99hen
