### ISSUE TITLE
[Question] kube-apiserver output failed to list and watch apps.openyurt.io

### ISSUE THREAD

**Issue by cuiHL** [openyurtio/openyurt#2012]
I got this error from api-server, yurt-app-manager 0.6, openyurt 1.1
![image](https://github.com/openyurtio/openyurt/assets/26169306/85063807-51d3-4431-a1b2-6d70c1a8f604)

how did I resolve it?

**Comment by rambohe-ch** [comment]
@cuiHL Thank you for raising the issue.

It seems that kube-apiserver can not access the `yurt-app-manager-webhook.kube-sysystem.svc` service and timeout happened.

There are some suggestions for debugging the above problem:
1. dns resolution for `yurt-app-manager-webhook.kube-sysystem.svc` is correct or not?
2. the request for `yurt-app-manager-webhook.kube-sysystem.svc:443` can be forwarded to `yurt-manager` pod or not?
3. yurt-manager pod is listening the correct address or not?
