### ISSUE TITLE
[vote] name the edge load balancer agent: seeking suggestion for name

### ISSUE THREAD

**Issue by wangxye** [openyurtio/openyurt#2023]
**What would you like to be added**:
The Edge Load Balancing Agent is designed to support load balancing of edge nodes in the node pooling dimension, which is deployed in each node to route request traffic forwarding for services in the node pooling dimension with virtual IPs via Keepalived. 

Specifically, in the deployment of load balancing services for edge nodes, it lists/watches the creation, update, and deletion of the poolservice, and for the virtual router ID (VRID) assigned by the load balancing controller to modify the configuration of the Keepalived on the specified node within the node pool.

We invite suggestions for a new name for the edge load balancer agent. 
Please feel free to provide a suitable name in response to this issue.

**Comment by gnunu** [comment]
If the LB feature is named LBSet, the class name can be named after their implementation. In this case, Keepalived.

**Comment by vie-serendipity** [comment]
YurtAlived, alive represents keepalived, d represents daemonset.

**Comment by rambohe-ch** [comment]
how about name this new component as `YurtVIPBroker`?

The name implies that the component acts as a broker for VIPs within the OpenYurt, ensuring that their allocation, release, and synchronization are handled properly, facilitating high availability and consistent service networking.
