### ISSUE TITLE
[Question] failed to convert error=no kind YurtappSet is registered for version "apps.openyurt.io/v1beta1"

### ISSUE THREAD

**Issue by cuiHL** [openyurtio/openyurt#2035]
**What happened**:
When I create the yurtappset object, I get the following error
![image](https://github.com/openyurtio/openyurt/assets/26169306/e55cea02-b40e-4d17-82c3-47a5209ff498)

**What you expected to happen**:
How can I solve this?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:1.4
- yurt-manager:1.4.0
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by cuiHL** [comment]
I solve it

**Comment by rambohe-ch** [comment]
@cuiHL Yes, v1beta1 YurtAppSet is not supported in OpenYurt v1.4
