### ISSUE TITLE
[feature request] Add nodepool flag when joining node with yurtadm

### ISSUE THREAD

**Issue by luc99hen** [openyurtio/openyurt#2041]
**What would you like to be added**:
Add a nodepool flag to yurtadm join command, yurtadm join --nodepool=xxxx

**Why is this needed**:
Currently, joining nodes and subsequently labeling them with the nodepool label is a tedious process. The nodepool label is crucial for numerous OpenYurt features pertaining to nodepool management. We can combine those two steps into one with this feature. Additionally, we can mandate the --nodepool flag for yurtadm join command.

**others**
/kind feature

**Comment by YTGhost** [comment]
Has this issue already been resolved by https://github.com/openyurtio/openyurt/pull/1402?

**Comment by luc99hen** [comment]
@YTGhost  Thanks for your notification. 

You are right, this is a completed task.
