### ISSUE TITLE
If my cloud is down and i want to manage the pods in the nodepool in the edge then how should i setup the kubectl?

### ISSUE THREAD

**Issue by Nitish-CONSORT** [openyurtio/openyurt#2062]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@Nitish-CONSORT Thanks for raising the issue. what kind of operations do you want to manage the pods in the edge when cloud is down?

Any changes to the pod in the edge will be overwritten by the pods in the cloud after cloud recovered.

**Comment by Nitish-CONSORT** [comment]
I am not able to enter in pod by "kubectl exec" command, and also not able to "apply" and "delete" pods if cloud is in down state.

**Comment by rambohe-ch** [comment]
@Nitish-CONSORT There are no activities on this issue for a long time, so i will close this issue.
You can feel free to reopen this issue or create new issues if needed.
