### ISSUE TITLE
[BUG]An abnormal status occurs in an EdgeX application deployed through openyurt-manger

### ISSUE THREAD

**Issue by HuangYuFe** [openyurtio/openyurt#2072]
**What happened**:
When I created a node pool using YurtIotDock in the openyurt project, I added an edge server node to the node pool. I then created an EdgeX service using PlatformAdmin and plugged in a Modbus sensor for data monitoring. At first the whole system worked fine：
![屏幕截图 2024-06-06 160259](https://github.com/openyurtio/openyurt/assets/117882542/ae32a5a2-c15b-4aef-b2f0-05efddd8666c)

but after a week I noticed that the service was abnormal。The number of EdgeX services in the cluster is starting to increase abnormally and is already running out of hardware resources：
![屏幕截图 2024-06-06 154951](https://github.com/openyurtio/openyurt/assets/117882542/93d1ee56-497d-4689-8cfe-7107797d5d19)
After I checked the status of the service, it prompted "Podetnodhard Conditien: [Disco Presul]."
![屏幕截图 2024-06-06 155146](https://github.com/openyurtio/openyurt/assets/117882542/da354b7d-c3f7-49b1-9601-77064dd887d4)
![屏幕截图 2024-06-06 155225](https://github.com/openyurtio/openyurt/assets/117882542/9960d404-8335-4063-91d5-2d04705d50a9)

**What you expected to happen**:
Under normal circumstances, EdgeX applications should continue to work after deployment
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:1.4.0 
- Kubernetes version (use `kubectl version`):1.22.4
- OS (e.g: `cat /etc/os-release`):Debian GNU/Linux 11 (bullseye)
- Kernel (e.g. `uname -a`):Linux version 5.10.110 
- Install tools:helm
- Others:Hardware platform RK3588

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@LavenderQAQ PTAL

**Comment by LavenderQAQ** [comment]
@HuangYuFe I don't have that problem repeated here. I saw a lot of evicted Pods in your picture. I guess your network environment is not very stable. Do you have yurthub deployed? In platformadmin's logic, no new copies are actively deployed, and the number of copies is always 1.

**Comment by HuangYuFe** [comment]
Yes, I didn't deploy yurthub in the cluster, I'll try this method.
