### ISSUE TITLE
Enhance the test coverage for both yurt-manager and yurthub to exceed 65% utilizing the capabilities of Tongyi Lingma's tool.

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#2082]
## Motivation
The current test coverage for the yurt-manager and yurthub modules in the OpenYurt project is as follows:

- yurt-manager: 53%
- yurthub: 58%

The coverage details can be checked on [Codecov](https://app.codecov.io/gh/openyurtio/openyurt/tree/master/pkg).

## Objectives

The primary goal of this task is to enhance test coverage for the specified modules using Tongyi Lingma's testing tools. The target is to increase the test coverage to exceed 65% for each module. The modules in focus are:

- yurt-manager: [GitHub - yurt-manager](https://github.com/openyurtio/openyurt/tree/master/pkg/yurtmanager)
- yurthub: [GitHub - yurthub](https://github.com/openyurtio/openyurt/tree/master/pkg/yurthub)

## Related Issues

For more context on the tools and methodologies that may be employed in this task, refer to the following competition and its resources:

[2024 Tianchi Cloud Native Programming Challenge - Track 3](https://tianchi.aliyun.com/competition/entrance/532215/information?spm=a2c22.12281976.0.0.41ab3f64DqbK3c)

**Comment by urlyy** [comment]
Hi, I'd like to take this. But I wonder how can I get my codecov result on https://app.codecov.io/ ?

**Comment by rambohe-ch** [comment]
> Hi, I'd like to take this. But I wonder how can I get my codecov result on https://app.codecov.io/ ?

@urlyy welcome you to contribute this issue. you can view the coverage on codecov link: https://app.codecov.io/gh/openyurtio/openyurt/tree/master/pkg

by the way, you can also check the coverage locally by executing command `go test -v -coverprofile=coerage.out ./...`.

**Comment by urlyy** [comment]
I have started coding and tested several files, but now having difficulty mocking the `ctrl.Manager`. Are there some common ways you use ? Or maybe I ignore the way have existed in openyurt? Althogh I have found some solutions in website, I don't familiar with k8s's api and don't know if you accept them. Looking forward to your reply.
