### ISSUE TITLE
[BUG] edge node CNI is not functioning correctly 

### ISSUE THREAD

**Issue by ayewwww** [openyurtio/openyurt#2084]
![微信图片_20240621150017](https://github.com/openyurtio/openyurt/assets/59998764/94415337-030f-4c3e-bd64-121128d1dda8)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@ayewwww Thank you for raising the issue. It seems that calico cni plugin has not worked correctly because `get pods csi-node-driver-pgmml` failed. I need more information to know that this error has relationship with OpenYurt or not.
