### ISSUE TITLE
helm repo add openyurt https://openyurtio.github.io/openyurt-helm  error 

### ISSUE THREAD

**Issue by hanlovecode** [openyurtio/openyurt#2109]
再使用helm添加镜像仓库时出现错误，但是添加其他的仓库是正常的 所以应该是openyurt的镜像仓库可能哪里的配置出现了错误

当前的helm版本为：
[root@node1 ~]# helm version
version.BuildInfo{Version:"v3.14.4", GitCommit:"81c902a123462fd4052bc5e9aa9c513c4c8fc142", GitTreeState:"clean", GoVersion:"go1.21.9"}

添加仓库时的具体错误为：
[root@node1 ~]# helm repo add openyurt https://openyurtio.github.io/openyurt-helm
Error: looks like "https://openyurtio.github.io/openyurt-helm" is not a valid chart repository or cannot be reached: Get "https://openyurtio.github.io/openyurt-helm/index.yaml": read tcp 192.168.130.121:47358->185.199.109.153:443: read: connection reset by peer
[root@node1 ~]# helm repo add stable http://mirror.azure.cn/kubernetes/charts
"stable" has been added to your repositories
[root@node1 ~]#

**Comment by rambohe-ch** [comment]
@hanlovecode Thank you for raising the issue. 
From the logs, It seems that there is a problem in your network that causing the openyurt-helm repo can not be added.

In my network environment, openyurt-helm repo has been added successfully as following:

```
MacBook-Pro:~ rambohe$ helm repo add openyurt-helm  https://openyurtio.github.io/openyurt-helm
"openyurt-helm" has been added to your repositories
```

by the way, repo: `https://openyurtio.github.io/charts` is recommended to use from OpenYurt v1.5.0, please enjoy it.

**Comment by rambohe-ch** [comment]
@hanlovecode I think that the problem of this issue has been solved, so i will close this issue.
