### ISSUE TITLE
[Question] Should pods in one edge node be able to communicate pods in other edge nodes?

### ISSUE THREAD

**Issue by ttzeng** [openyurtio/openyurt#213]
**What happened**:
I have the following setup to mimic two edge nodes at different locations, and as you can see in below log, edge nodes are on different sub-nets.
```
$ kubectl get no -o wide
NAME           STATUS   ROLES    AGE     VERSION    INTERNAL-IP      EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
nuc7i5bnh      Ready    master   5d      v1.18.15   192.168.1.116    <none>        Ubuntu 18.04.5 LTS   5.4.0-65-generic   docker://19.3.6
sharkbay-vm1   Ready    <none>   4d18h   v1.18.15   192.168.122.75   <none>        Ubuntu 18.04.5 LTS   5.4.0-65-generic   docker://19.3.6
ttzeng-vm1     Ready    <none>   5d      v1.18.15   192.168.123.35   <none>        Ubuntu 18.04.5 LTS   5.4.0-65-generic   docker://19.3.6
```

I tried to deploy pods to each nodes (including the master node), it seems pods in an edge node can't communicate pods in other nodes:
```
$ kubectl get po -o wide
NAME             READY   STATUS    RESTARTS   AGE     IP              NODE           NOMINATED NODE   READINESS GATES
test-po          1/1     Running   0          47m     172.16.162.68   ttzeng-vm1     <none>           <none>
test-po-master   1/1     Running   0          3m35s   172.16.202.75   nuc7i5bnh      <none>           <none>
test1-po         1/1     Running   0          8m41s   172.16.4.68     sharkbay-vm1   <none>           <none>
```

Run the edge pod from the master node reveals the yurt server/agent have the tunnel set up for the communications:
```
$ kubectl exec test-po -- ifconfig
eth0      Link encap:Ethernet  HWaddr AE:AD:A5:90:91:32
          inet addr:172.16.162.68  Bcast:0.0.0.0  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1440  Metric:1
          RX packets:11225 errors:0 dropped:0 overruns:0 frame:0
          TX packets:20592 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1089142 (1.0 MiB)  TX bytes:2006326 (1.9 MiB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)
```

But I can't ping the address of pods on other nodes (including the master node):
```
$ kubectl exec test-po -- ping 172.16.4.68
^C
```

**What you expected to happen**:
I think in the [Kubernetes networking model](https://kubernetes.io/docs/concepts/cluster-administration/networking/#the-kubernetes-network-model), pods on a node should be able to communicate with other pods in a cluster, so should the Yurt agent or some mechanism should set up NAT rules to route packets targeting for other pods?

**Comment by rambohe-ch** [comment]
@ttzeng Thank you for filing issue.
network communication in OpenYurt can be divided into two kinds:
1.  communication between cloud and edge(we also call this as north-south traffic)
2. communication between edge nodes or between pods on different nodes(we also call this east-west traffic)

and yurt-tunnel-server/yurt-tunnel-agent is responsible for the first kind communication(north-south traffic), so your first command `kubectl exec test-po -- ifconfig` has worked.

then the second kind communication,  currently OpenYurt and K8s are in line, so You can use container network solutions like Flannel/Calico on the basis that the physical network between nodes can be connected. 
and the reason of your second command `kubectl exec test-po -- ping 172.16.4.68` failure is that the physical network between edge nodes is not connected.

**Comment by ttzeng** [comment]
@rambohe-ch , thanks for the explanation! Yes, we have Calico CNI installed, but it looks like different subnets are assigned to two edge nodes (as they behind firewalls), so I think pods on different nodes should communicate through the tunnel, as they are still in the same cluster per k8s networking model, isn't it?

Do you have plans to extend the yurt tunnel or other mechanism to support the east-west traffic? or we are thinking to leverage the [SD-EWAN](https://github.com/akraino-edge-stack/icn-sdwan) in ICN project for usages with east-west traffic, how do you think?

**Comment by rambohe-ch** [comment]
> @rambohe-ch , thanks for the explanation! Yes, we have Calico CNI installed, but it looks like different subnets are assigned to two edge nodes (as they behind firewalls), so I think pods on different nodes should communicate through the tunnel, as they are still in the same cluster per k8s networking model, isn't it?

I think the need for connectivity between pods will vary from edge scenario to edge scenario. If in scenario that use `NodePool`, pods in different `NodePool` may not need to connect each other. of course, there are some edge scenario that pods in different physical place,  They need to communicate with each other for transferring data or something else.
 
> Do you have plans to extend the yurt tunnel or other mechanism to support the east-west traffic? or we are thinking to leverage the [SD-EWAN](https://github.com/akraino-edge-stack/icn-sdwan) in ICN project for usages with east-west traffic, how do you think?

Currently we have no plans to extend yurt-tunnel or other mechanism to support east-west traffic. and the OpenYurt roadmap is here: https://github.com/alibaba/openyurt/blob/master/docs/roadmap.md.
@wenjun93  FYI. leverage the SD-EWAN to support east-west traffic, do you have any comments?

@ttzeng If you can leverage the SD-EWAN  based on OpenYurt, I think the work will be welcome.

**Comment by wenjun93** [comment]
@ttzeng currently we have the ability of inter-nodes/pods communication in our commercial product, which is also based on openyurt. We leveraged alibaba cloud's network infrastructure and SDN solution for edge-to-cloud, edge-to-edge traffic, looked at the SD-EWAN solution and yes there are something in common, we can discuss it :)
