### ISSUE TITLE
[Question] Does YurtHub not support update or patch pod status request when network offline?

### ISSUE THREAD

**Issue by obitoquilt** [openyurtio/openyurt#2137]
**What happened**:

I deploy `daemonset` coredns. In the edge node, the coredns (hostnetwork=true) is connected to yurthub with `127.0.0.1:10268`. It works when the network offline. 

But when the edge node is rebooted, the workload ip is changed and `kubelet` launches `patch` pod status operation. The yurthub seems to be not performing a patch for this request.

In case of `update` or `patch`, the yurthub just queries object, not modifies them.
```golang
func (cm *cacheManager) QueryCache(req *http.Request) (runtime.Object, error) {
	ctx := req.Context()
	info, ok := apirequest.RequestInfoFrom(ctx)
	if !ok || info == nil || info.Resource == "" {
		return nil, fmt.Errorf("could not get request info for request %s", util.ReqString(req))
	}
	if !info.IsResourceRequest {
		return nil, fmt.Errorf("could not QueryCache for getting non-resource request %s", util.ReqString(req))
	}

	switch info.Verb {
	case "list":
		return cm.queryListObject(req)
	case "get", "patch", "update":
		return cm.queryOneObject(req)
	default:
		return nil, fmt.Errorf("could not QueryCache, unsupported verb %s of request %s", info.Verb, util.ReqString(req))
	}
}
```

**What you expected to happen**:

In this case, kube proxy which watches endpoint or endpointslice doesn't work well when networkoffline and the node is rebooted ?
Thanks for any help.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: v1.5.0
- Kubernetes version (use `kubectl version`): v1.27.4
- OS (e.g: `cat /etc/os-release`): linux/centos
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by obitoquilt** [comment]
cilium supports `delegated-plugin` ipam mode, so it can use `host-local` ipam to manage ip address.

**Comment by rambohe-ch** [comment]
> cilium supports `delegated-plugin` ipam mode, so it can use `host-local` ipam to manage ip address.

@obitoquilt It's a good job, then cilium can work correctly when network offline.
