### ISSUE TITLE
[BUG]  edge  Yurthub  restart

### ISSUE THREAD

**Issue by a516664625** [openyurtio/openyurt#2150]
**What happened**:
Yurthub is continuously restarting on my nodes, causing connectivity and functionality issues. The pod logs show it exiting and restarting in a loop. The following logs are observed frequently:
Additionally, there are error logs indicating certificate issues or connectivity problems:

I0913 08:48:56.168228       1 cache_manager.go:447] get bookmark with rv 44792 for kubelet watch pods
I0913 08:48:59.872330       1 health_checker.go:197] exit normally in health check loop.
I0913 08:48:59.872345       1 network.go:66] exit network manager run goroutine normally
I0913 08:48:59.872407       1 start.go:207] hub agent exited
I0913 08:48:59.872538       1 secure_serving.go:311] Stopped listening on 127.0.0.1:10267

**What you expected to happen**:
Yurthub should remain stable and continue running without restarting, allowing it to function as expected.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
<img width="1916" alt="image" src="https://github.com/user-attachments/assets/fbf95797-98a9-462d-825e-c0168635745d">

/kind bug

**Comment by zyjhtangtang** [comment]
Yurthub received a signal that the process exited. You need to check the logs of kubelet and runtime.
