### ISSUE TITLE
openyurt security self-assessment

### ISSUE THREAD

**Issue by rochaporto** [openyurtio/openyurt#2184]
**What would you like to be added**:

Please fill up the security self assessment for the CNCF incubation process.

You can find all [information here](https://tag-security.cncf.io/community/assessments/guide/self-assessment/). Please open a PR to the TAG-Security repository, you can find examples from other projects [here](https://github.com/cncf/tag-security/tree/67039eb2f63e60d5f82911d2a6197c86a3fa9545/community/assessments/projects).

**Why is this needed**:

This is a step part of the new process for CNCF incubation.

**others**
/kind feature

**Comment by vie-serendipity** [comment]
@rochaporto We have drafted an OpenYurt self-assessment. Welcome any feedback you may have.
https://github.com/cncf/tag-security/pull/1422

**Comment by rochaporto** [comment]
> @rochaporto We have drafted an OpenYurt self-assessment. Welcome any feedback you may have. [cncf/tag-security#1422](https://github.com/cncf/tag-security/pull/1422)

Thanks!

**Comment by vie-serendipity** [comment]
Thanks.
