### ISSUE TITLE
register for the openssf best practices badge

### ISSUE THREAD

**Issue by rochaporto** [openyurtio/openyurt#2185]
**What would you like to be added**:

Register and fill in for the OpenSSF best practices badge, [documented here](https://www.bestpractices.dev/en).

You can find examples from existing projects [here](https://www.bestpractices.dev/en/projects).

**Why is this needed**:

The badge is now part of the new CNCF incubation process.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@rochaporto I updated openyurt project status in openssf best practices, and made `Tiered` more than 100%, then got    passing badge.

The reference link is here: https://www.bestpractices.dev/en/projects?q=openyurt

**Comment by rochaporto** [comment]
Excellent thanks @rambohe-ch . I think we can close this ticket.
