### ISSUE TITLE
[Question] clarify email for reporting security vulnerabilities

### ISSUE THREAD

**Issue by rochaporto** [openyurtio/openyurt#2186]
**What happened**:

Currently the [SECURITY.md](https://github.com/openyurtio/openyurt/blob/master/SECURITY.md) points to [kubernetes-security@service.aliyun.com](kubernetes-security@service.aliyun.com) to report security vulnerabilities.

The documentation indicates all maintainers should be reached by these reports. Please clarify how this is the case, or update the target email appropriately if this was an oversight.

**What you expected to happen**:

The email relies on `service.aliyun.com`, i would expect it to reach an email behind `openyurt.io`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@rochaporto The email address for reporting security vulnerabilities is modified to [security@mail.openyurt.io](security@mail.openyurt.io). and the new mail will be distributed to all maintainers.

The related pull request is #2214

**Comment by rochaporto** [comment]
Excellent thanks @rambohe-ch . From my side we can close this issue.
