### ISSUE TITLE
[BUG] inconsistent contributors guide between github repo and website

### ISSUE THREAD

**Issue by rochaporto** [openyurtio/openyurt#2187]
**What happened**:

The information for contributes is not consistent across the github repository and the website.
* [github repo](https://github.com/openyurtio/openyurt/blob/master/CONTRIBUTING.md)
* [website](https://openyurt.io/docs/developer-manuals/how-to-contribute)

The github repo version includes a link to how to report security vulnerabilities, but this information is not available in the version on the website. Please consider making these two documents consistent.

**What you expected to happen**:

The contributors guide should be consistent across the github repo and project website.

**How to reproduce it (as minimally and precisely as possible)**:

Not relevant.

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@rochaporto The documents of `how to contribute to OpenYurt` has been upgraded. and the related pull request is:
#2210 
https://github.com/openyurtio/openyurt.io/pull/493

Very appreciated maintainer @YTGhost for fixing this case.

**Comment by rambohe-ch** [comment]
@rochaporto I think this issue has been fixed by @YTGhost , so I will close this issue. Please feel free to reopen or create new issue if you have any other questions.
