### ISSUE TITLE
[feature request] document integrations with other CNCF and non-CNCF projects

### ISSUE THREAD

**Issue by rochaporto** [openyurtio/openyurt#2189]
**What would you like to be added**:

The existing [architecture document](https://openyurt.io/docs/core-concepts/architecture/) describes well the different project components.

This request is to add an additional section listing the existing integrations with other projects. If you need an example of what the goal is, you can check [this example](https://wasmcloud.com/docs/integrations/).

**Why is this needed**:

Documenting explicitly the existing integrations with other projects will help end users in their process of adopting the project.

**others**
/kind feature

**Comment by luckymrwang** [comment]
@rochaporto Hi, the integrations with other projects have been added. [Integrations List](https://openyurt.io/docs/integrations/)

**Comment by rochaporto** [comment]
Excellent, thanks @luckymrwang . Let's close this.

**Comment by rambohe-ch** [comment]
@luckymrwang Very appreciated for your update for integrations.
