### ISSUE TITLE
[Question] YurtAppSet tweaks.patches error: doc is missing path: "/metadata/labels/test": missing value

### ISSUE THREAD

**Issue by shyer** [openyurtio/openyurt#2202]
**What happened**:
https://openyurt.io/zh/docs/next/user-manuals/workload/yurt-app-set#%E5%88%9B%E5%BB%BA-yurtappset
`kubectl create -f yurtappset_test.yaml`

> Error from server (Forbidden): error when creating "yurtappset_test.yaml": admission webhook "vyurtappset.kb.io" denied the request: add operation does not apply: doc is missing path: "/metadata/labels/test": missing value

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
https://github.com/evanphx/json-patch/issues/138
https://github.com/KusionStack/kusion/pull/1274/files

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@vie-serendipity PTAL
