### ISSUE TITLE
[feature request] add ACLs to code in repositories

### ISSUE THREAD

**Issue by rochaporto** [openyurtio/openyurt#2223]
**What would you like to be added**:

Access control to multiple areas in the repository. Something based on [CODEOWNERS](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners) would be a good example.

Examples of usage in CNCF projects:
https://github.com/dapr/dapr/blob/master/CODEOWNERS
https://github.com/argoproj/argo-cd/blob/master/CODEOWNERS

**Why is this needed**:

This is a requirement for the incubation in the CNCF, see [this PR](https://github.com/cncf/toc/pull/797).

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@rochaporto Thank you for raising the issue.

1. I have posted a pull request to add CODEOWNERS file for openyurt. and add openyurt-maintainers team as codeowners currently. https://github.com/openyurtio/openyurt/pull/2224

2. then I opened a issue to keep improving the codeowners during incubation. https://github.com/openyurtio/openyurt/issues/2225

**Comment by rochaporto** [comment]
Excellent, thanks @rambohe-ch . Very quick action!

We can close this one as well.
