### ISSUE TITLE
[BUG] The manually setup document should include the service account creation & binding section.

### ISSUE THREAD

**Issue by yixingjia** [openyurtio/openyurt#226]
When setup Openyurt following the manual document, the yurt controller manager will not startup properly due the the privileges issue. It should include the  service account creation & binding sections. 
The tunnel server setup also have the same issue.

**Comment by rambohe-ch** [comment]
@yixingjia Thank you for taking over the work to improve OpenYurt manual setup document.
and now yurtctl tool can setup OpenYurt correctly, How about improve manual setup document according to yurtctl implementation?

**Comment by yixingjia** [comment]
Yes, I plan to extract the account creation & binding yaml to the setup folder and update the document accordingly.

**Comment by rambohe-ch** [comment]
> Yes, I plan to extract the account creation & binding yaml to the setup folder and update the document accordingly.

@yixingjia +1, It's good to extract the account creation & binding yaml to the setup folder.

**Comment by yixingjia** [comment]
Just find that @DrmagicE  already add the service account part to the yurt-controller-manager.yaml with commit efed1a60dc6d59abbf2dcb689014832c87f22ba1. So we can close this issue know.
