### ISSUE TITLE
Add support for the conversion between kind cluster and OpenYurt cluster.

### ISSUE THREAD

**Issue by Peeknut** [openyurtio/openyurt#230]
OpenYurt supports the conversion between the OpenYurt cluster and the Kubernetes cluster created by minikube, kubeadm, and ack. It may be necessary to add support for the conversion between kind cluster and OpenYurt cluster.

**Comment by rambohe-ch** [comment]
@Peeknut +1 It's a good idea to support kind cluster conversion. Would you take over the work for kind cluster conversion?

**Comment by Peeknut** [comment]
> @Peeknut +1 It's a good idea to support kind cluster conversion. Would you take over the work for kind cluster conversion?

👌

**Comment by yixingjia** [comment]
Looking forward for this new feature!
