### ISSUE TITLE
[Question]When k8s cluster is converted to edge cluster, node still on the cloud. How can I add edge nodes to the edge cluster？

### ISSUE THREAD

**Issue by yongxingMa** [openyurtio/openyurt#239]
When k8s cluster is converted to edge cluster, node still on the cloud. How can I add edge nodes to the edge cluster？

**Comment by charleszheng44** [comment]
Thanks for filing the issue. What did you mean "the node still on the cloud"? Could you check if the target node contain the label `openyurt.io/is-edge-worker: true`?

**Comment by smart33690** [comment]
> Thanks for filing the issue. What did you mean "the node still on the cloud"? Could you check if the target node contain the label `openyurt.io/is-edge-worker: true`?

Thanks for your reply. I want to know what new edge nodes need to do to join the cluster？

**Comment by charleszheng44** [comment]
If you want to add new edge nodes to the OpenYurt cluster, i.e., converting an existing cloud node to an edge node, you can try out the subcommand `yurtctl edgenode -e <edge-node-1>,<edge-node-2>`. Please let us know if it does not work.

**Comment by smart33690** [comment]
> If you want to add new edge nodes to the OpenYurt cluster, i.e., converting an existing cloud node to an edge node, you can try out the subcommand `yurtctl edgenode -e <edge-node-1>,<edge-node-2>`. Please let us know if it does not work.

Sorry，I want to add new edge nodes to OpenYurt cluster， instead of converting existing cloud nodes into edge nodes。

**Comment by rambohe-ch** [comment]
> > If you want to add new edge nodes to the OpenYurt cluster, i.e., converting an existing cloud node to an edge node, you can try out the subcommand `yurtctl edgenode -e <edge-node-1>,<edge-node-2>`. Please let us know if it does not work.
> 
> Sorry，I want to add new edge nodes to OpenYurt cluster， instead of converting existing cloud nodes into edge nodes。

At present,  OpenYurt has no ability to add new node as OpenYurt edge node, and you should add node to cluster like joining node to kubernetes at first then convert node into edge node.

btw: we will add the ability to add new node to OpenYurt cluster soon.  @zyjhtangtang do you have any comments?

**Comment by rambohe-ch** [comment]
@yongxingMa I think that `yurtctl join` in OpenYurt v0.5.0 can meet your requirements. so i will close this issue.
/close
