### ISSUE TITLE
[Question]Slack link is not active

### ISSUE THREAD

**Issue by zc2638** [openyurtio/openyurt#241]
**What happened**:
Slack link is not active
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rambohe-ch** [comment]
@zc2638 Thank you for filing issue. I'm going to update the slack info.

**Comment by zc2638** [comment]
I can not sign in, please  check the settings.
thanks.

**Comment by zc2638** [comment]
@rambohe-ch
