### ISSUE TITLE
How to establish communication between master node pod and edge node pod? How to establish communication between edge node pod and edge node pod?

### ISSUE THREAD

**Issue by yanyhui** [openyurtio/openyurt#246]
How does the pod of the master node establish communication with the pod of the edge node? How does the master node's apisever establish communication with the edge node pod? How does the edge node pod establish communication with the edge node pod?

**Comment by charleszheng44** [comment]
@yanyhui thanks for filing the issue. Following are answers to your questions. Please let me know if they are not clear

> How does the pod of the master node establish communication with the pod of the edge node?

If the master node and edge nodes are located in different isolated network regions, then the pod on the master node would not be able to talk to pods on edge nodes. However, if users run `kubectl logs/exec`, the request will be redirected from the APIServer (assume the APIServer is running as pod on the master node) to pods on edge nodes using YurtTunnel. 

> How does the master node's apisever establish communication with the edge node pod?

There are two kinds of traffics between the apiserver and the pod on edge nodes
1. traffic initiated by apiserver, e.g., kubectl log/exec, this kind of traffic will go through the YurtTunnel
2. traffic initiated by pods on edge nodes, e.g., a controller pod that will list resources, this kind of traffic requires the APIServer to listen at an address that can be accessed by pods

> How does the edge node pod establish communication with the edge node pod?

If the pods are located in different isolated network regions, then they can't communicate with each other. If the pods are located in the same network region, pods will be able to talk to each other as they do in the original Kubernetes.

**Comment by yanyhui** [comment]
@charleszheng44 
Thanks.That's great.
