### ISSUE TITLE
After the user's HTTP request arrives at the edge node through the yurtturnnel, how to access the specific service?

### ISSUE THREAD

**Issue by yanyhui** [openyurtio/openyurt#247]
The principle of edge computing is that the master node establishes a long-term connection with the kubelet of the edge node through the yurtturnnel. However, the HTTP request arrives at the edge node through the yurtturnnel, and the specific service needs to be accessed through the Kube proxy in the edge node. The problem is that the master node apiserver does not establish a connection with the Kube proxy of the edge node, so how can the HTTP request access the specific service in the edge node?

**Comment by rambohe-ch** [comment]
@yanyhui Thank you for filing issue. 
1. yurt-tunnel is used by monitor or maintenance traffic like kubectl logs/exec, prometheus etc.
2. And i'd like to verify the meaning of user's HTTP request through yurt-tunnel to access specific service. why access the specific service through yurt-tunnel? does kube-apiserver proxies service?

**Comment by yanyhui** [comment]
@rambohe-ch  Thank you for zhe answer.
What I want to know is how the HTTP request goes to the specific service in the edge node? The kubelet of edge node can only create or delete pod, it can't process the HTTP request transferred from the master node; in the original k8s cluster, the way to process the HTTP request and access the service is that the Kube proxy of the child node will register and establish communication in the apiserver of the master node, and process the HTTP request through the Kube proxy of the child node to access the specific service

**Comment by rambohe-ch** [comment]
> @rambohe-ch Thank you for zhe answer.
> What I want to know is how the HTTP request goes to the specific service in the edge node? The kubelet of edge node can only create or delete pod, it can't process the HTTP request transferred from the master node; in the original k8s cluster, the way to process the HTTP request and access the service is that the Kube proxy of the child node will register and establish communication in the apiserver of the master node, and process the HTTP request through the Kube proxy of the child node to access the specific service

@yanyhui  Thank you for your kind response. 
you can access specific service with service NodePort from master node through yurt-tunnel.  and you can have a try.

ps:  please add the port dnat rule setting in yurt-tunnel-server-cfg configmap before access service NodePort, and the detail info you can dive into the code here: https://github.com/openyurtio/openyurt/blob/master/pkg/yurttunnel/iptables/iptables.go#L203

**Comment by yanyhui** [comment]
@rambohe-ch 
Thanks.
