### ISSUE TITLE
[Question] pods "yurt-hub-minikube" not found

### ISSUE THREAD

**Issue by BeWaterMyFriend7** [openyurtio/openyurt#251]
' When I follow the tutorial steps `_output/bin/yurtctl convert --provider minikube` to arrange the edge nodes, the following occurs

_I0406 16:40:27.289204   79287 convert.go:443] kube-public/cluster-info configmap already exists, skip to prepare it
I0406 16:40:27.289299   79287 convert.go:332] deploying the yurt-hub and resetting the kubelet service...
E0406 16:40:27.500283   79287 util.go:316] **fail to run servant job(yurtctl-servant-convert-minikube): jobs.batch "yurtctl-servant-convert-minikube" already exists**
I0406 16:40:27.500326   79287 convert.go:349] the yurt-hub is deployed_

It doesn't seem to matter, so I ignored her continuing to type`kubectl get deploy yurt-controller-manager -n kube-system`,it's OK.

_NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
yurt-controller-manager   0/1     1            0           16s_

But when I type `kubectl get po yurt-hub-minikube -n kube-system`, the errors occurs:

**Error from server (NotFound): pods "yurt-hub-minikube" not found**

I have tried many methods, including reinstalling openyurt and restarting the minikube environment, but to no avail. 
Hope you can help me, thank you!

**Environment**:
- Kubernetes version (use `kubectl version`):1.16.2
- Ubuntu18.04
- Go 1.13.10

**Comment by DreamEagle0** [comment]
You may read this issue #250, I think our problems may be the same. 
First, you can show us more information by running `kubectl get all -n kube-system`. 
Besides, if you need to revert the failed openyurt totally, try running `yurtctl revert` and delete all failed jobs manully, i.e. `kubectl delete jobs --all -n kube-system`

**Comment by DreamEagle0** [comment]
> fail to run servant job(yurtctl-servant-convert-minikube): jobs.batch "yurtctl-servant-convert-minikube" already exists

This means last time you deployed openyurt the jobs didn't complete.

**Comment by BeWaterMyFriend7** [comment]
> You may read this issue #250, I think our problems may be the same.
> First, you can show us more information by running `kubectl get all -n kube-system`.
> Besides, if you need to revert the failed openyurt totally, try running `yurtctl revert` and delete all failed jobs manully, i.e. `kubectl delete jobs --all -n kube-system`

OK, Thank you very much.I have tried your methods .After typing`yurtctl revert` and `kubectl delete jobs --all -n kube-system`, I typed `_output/bin/yurtctl convert --provider minikube`, and the following occurs:

>I0407 09:21:29.249607   25566 convert.go:443] kube-public/cluster-info configmap already exists, skip to prepare it
>I0407 09:21:29.249683   25566 convert.go:332] deploying the yurt-hub and resetting the kubelet service...
>E0407 09:23:29.325060   25566 util.go:316] **fail to run servant job(yurtctl-servant-convert-minikube): wait for job to be complete timeout**
>I0407 09:23:29.326093   25566 convert.go:349] the yurt-hub is deployed

more details


![图片](https://user-images.githubusercontent.com/49580332/113797465-e9907300-9783-11eb-8f30-8822036cce60.png)

**Comment by DreamEagle0** [comment]
@BeWaterMyFriend7 Yes, so it should be same problem. Actually, you did not read the whold issue。  The official yurtctl-servant image lacks yurtctl in its `/usr/local/bin/` path. You need to build a new yurtctl-servant image, like below: 
```Dockerfile
FROM registry.cn-hangzhou.aliyuncs.com/openyurt/yurtctl-servant
COPY yurtctl /usr/local/bin/yurtctl
COPY yurtctl /var/tmp/yurtctl
```
The Dockerfile should be put in the same directory of yurtctl binary.  Actually, the third line in the Dockerfile should be able to omitted, but I do it just in case.
Following steps:
1. push the image you just build to your local registry or docker hub as you like.
2. Using `yurtctl convert` by specifically define `--yurtctl-servant-image your_image:tag`，it should works.
3. When you want to use `yurtctl revert`, you should do the same thing like step 2.

**Comment by BeWaterMyFriend7** [comment]
> @BeWaterMyFriend7 Yes, so it should be same problem. Actually, you did not read the whold issue. The official yurtctl-servant image lacks yurtctl in its `/usr/local/bin/` path. You need to build a new yurtctl-servant image, like below:
> 
> ```dockerfile
> FROM registry.cn-hangzhou.aliyuncs.com/openyurt/yurtctl-servant
> COPY yurtctl /usr/local/bin/yurtctl
> COPY yurtctl /var/tmp/yurtctl
> ```
> 
> The Dockerfile should be put in the same directory of yurtctl binary. Actually, the third line in the Dockerfile should be able to be omitted, but I do it just in case.
> Following steps:
> 
>     1. push the image you just build to your local registry or docker hub as you like.
> 
>     2. Using `yurtctl convert` by specifically define `--yurtctl-servant-image your_image:tag`，it should works.
> 
>     3. When you want to use `yurtctl revert`, you should do the same thing like step 2.

Thank you very much.But I'm a new here,I can't fully understand what you mean. More details are shown below.

![图片](https://user-images.githubusercontent.com/49580332/113804864-f74cf500-9791-11eb-935e-4b48509735d9.png)

**Comment by DreamEagle0** [comment]
@BeWaterMyFriend7 Well, it's just some docker commands...
1. You can just rename the Dockerfile to exactly `Dockerfile`, and run `docker build -t new_servant .` (don't lose the last dot `.`), then a new image will be built.
2. push it to dockerhub registry by `docker push <your_username>/new_servant`. (Change the `<your_username>` here to your dockerhub username). 
  - More at: [https://docs.docker.com/docker-hub](https://docs.docker.com/docker-hub/) (Step 3 just need to run `docker login`.) 
3. `yurtctl convert --provider minikube --yurtctl-servant-image <your_username>/new_servant:lastet`

**Comment by DreamEagle0** [comment]
If you are using a x86-64 machine, you may simply use my image. 
`yurtctl convert --provider minikube --yurtctl-servant-image dreameagle/yurtctl-servant:latest`

**Comment by DreamEagle0** [comment]
@BeWaterMyFriend7  If you are using a x86-64 machine, you may simply use my image. 
`yurtctl convert --provider minikube --yurtctl-servant-image dreameagle/yurtctl-servant:latest`
