### ISSUE TITLE
[BUG] Internal error occurred: failed calling webhook "mnodepool.kb.io"

### ISSUE THREAD

**Issue by yang-zhang-edge** [openyurtio/openyurt#254]
**Following the official tutorial concering about yurt-app-manager hereby https://gitee.com/mirrors/openyurt/blob/master/docs/tutorial/yurt-app-manager.md, I failed to create NodePool resource. To be precise, when try to apply the example config demonstrated within the mentioned link, I got error as below:
[root@cloud-master opt]# kubectl apply -f nodepool.yml                             
Error from server (InternalError): error when creating "nodepool.yml": Internal error occurred: failed calling webhook "mnodepool.kb.io": Post https://yurt-app-webhook-service.kube-system.svc:443/mutate-apps-openyurt-io-v1alpha1-nodepool?timeout=30s: context deadline exceeded**:

**Since the K8S cluster provided by kubeadm has already been transformed to openyurt cluster, nodepool resource should be crated successfully**:

**Following the above official tutorial, after initializing openyurt cluster from kubeadm managed K8S and installing yurt-app-manager operator, execute the below command:
cat <<EOF | kubectl apply -f -
apiVersion: apps.openyurt.io/v1alpha1
kind: NodePool
metadata:
  name: Pool-A
spec:
  type: Edge
  annotations:
    apps.openyurt.io/example: test-Pool-A
  labels:
    apps.openyurt.io/example: test-Pool-A
  taints:
  \- key: apps.openyurt.io/example
    value: test-Pool-A
    effect: NoSchedule
EOF**:

**Yurt-app-manager pod has already been running normally:
[root@cloud-master opt]# kubectl get pod -n kube-system |grep yurt-app        
yurt-app-manager-6bf675f789-dnxdv          1/1     Running   0          62m**:

**Environment**:
- OpenYurt version: 0.3.0
- Kubernetes version (use `kubectl version`): 1.18.0
- OS (e.g: `cat /etc/os-release`): centos7.4
- Kernel (e.g. `uname -a`): 3.10.0-693.el7.x86_64
- Install tools:
- Others:

**Comment by rambohe-ch** [comment]
@yang-zhang-edge Thank you for filing issue.

@kadisi  Would you take a look the problem of yurt-app-manager?

**Comment by kadisi** [comment]
@yang-zhang-edge 

yurt-app-manager has been removed to new [repo](https://github.com/openyurtio/yurt-app-manager).

you can follow this tutorial:

1. clone yurt-app-manger code
```
# cd $GOPATH/src/github.com/openyurtio
# git clone git@github.com:openyurtio/yurt-app-manager.git

# cd  yurt-app-manager
```
2. push yurt-app-manager to your private registy ， for example

```
make push REPO=registry.cn-your-registry.com/edge-kubernetes
```
if REPO value is assigned  `registry.cn-your-registry.com/edge-kubernetes`， the `make push` command will eventually build an image named `registry.cn-your-registry.com/edge-kubernetes/yurt-app-manager:{git commit id}` and push it into your  private repository. and `make push` command will also create a file named `yurt-app-manager.yaml` in `_output/yamls` dir.

3.  install `nodepool` and `uniteddeployment` controller
```
kubectl apply -f _output/yamls/yurt-app-manager.yaml
```

**Comment by rambohe-ch** [comment]
@yang-zhang-edge we will close this issue because not active over two months, if you have any other questions about `yurt-app-manager`, please raise a new issue.
