### ISSUE TITLE
Does this project support the edge computing scenarios of master cluster and edge sub cluster?

### ISSUE THREAD

**Issue by yanyhui** [openyurtio/openyurt#256]
In the edge computing scenario, there may be a master cluster deployed in the cloud and an edge cluster deployed at the edge, and the networks of these two clusters are not connected. 
1. But I want to manage the edge cluster through the master cluster. Can openyurt support this situation? The cloud is not a master node, and the edge is not a follower node, but both the cloud and the edge are clusters, and the edge cluster should be managed by the cloud cluster.
2. If this kind of nanotube between clusters is supported, I would like to know how to realize this kind of business function?

**Comment by charleszheng44** [comment]
We current doesn’t support sub-cluster.

**Comment by yanyhui** [comment]
@charleszheng44  thanks for zhe answer.
