### ISSUE TITLE
In the high availability scenario, when an agent in a network region hangs up, how to ensure the connectivity with cloud nodes?

### ISSUE THREAD

**Issue by yanyhui** [openyurtio/openyurt#257]
In the high availability scenario, two edge nodes of the cluster are in a physical network region. In theory, the network agent only needs to configure one agent. The problem is that if the node where the agent is located hangs up, the two nodes will not work. In this case, how can we ensure high availability?

**Comment by yanyhui** [comment]
@charleszheng44  How can openyurt ensure high availability of agents in edge network region?

**Comment by rambohe-ch** [comment]
@yanyhui Thank you for filing issue.
> In the high availability scenario, two edge nodes of the cluster are in a physical network region. In theory, the network agent only needs to configure one agent. The problem is that if the node where the agent is located hangs up, the two nodes will not work. In this case, how can we ensure high availability?

would you can describe more info about the network agent? the network agent is the workload pod or some other agent?

**Comment by yanyhui** [comment]
@rambohe-ch   
Error has been reported after executing the make what=cmd/yurtctl command,The error is **_pkg/yurthub/util/util_test.go:37:4: call to (*T).Fatalf from a non-test goroutine
make: *** [vet] Error 2_**
![image](https://user-images.githubusercontent.com/33149983/114669877-fccbb180-9d34-11eb-8d75-77693c0dca64.png)

**Comment by yanyhui** [comment]
@rambohe-ch 
How to connect to the edge node if the agent in yurtunnel is down? The problem is how to realize the high availability of agent. The server in yurttunnel is highly available through multiple server copies. If one server is broken, it will automatically switch to other servers. Then the agent is broken?

**Comment by charleszheng44** [comment]
@yanyhui you can set up multiple agents per network region.

**Comment by felix0080** [comment]
守护进程，进程监控，如果真的跑不起来，那可能是其他问题
