### ISSUE TITLE
[feature request] Support RKE ?

### ISSUE THREAD

**Issue by AnyISalIn** [openyurtio/openyurt#259]
the RKE is a popular Kubernetes engine,   Do you guys plan to support RKE?

**What would you like to be added**:

support convert RKE to yurt cluster.

**Why is this needed**:

**Comment by charleszheng44** [comment]
Hi @AnyISalIn, If RKE is fully compatible with upstream Kubernetes (support all upstream features and workloads), then OpenYurt should be able to work with it out of the box. If RKE changes some of the upstream features, then we would not consider supporting it.

**Comment by AnyISalIn** [comment]
> Hi @AnyISalIn, If RKE is fully compatible with upstream Kubernetes (support all upstream features and workloads), then OpenYurt should be able to work with it out of the box. If RKE changes some of the upstream features, then we would not consider supporting it.

Thanks, I'll try to test OpenYurt on RKE.

**Comment by charleszheng44** [comment]
Great. Please keep us posted about your progress. 😄  

I will close this issue for now but feel free to reopen it or create a new one if you run into any issue.
