### ISSUE TITLE
Should we consider edgenode crash in autonomy scenario?

### ISSUE THREAD

**Issue by DreamEagle0** [openyurtio/openyurt#260]
When cloud nodes cannot connect to a edge node, there are 2 scenarios:  
1. network disconnection 
2. edge node crashes. 

Consider the second scenario. When a edge node crashes, the pod in the edge node will not be evicted.  In this case, the service of the pod will keep unavailable? Is there any way to fix this?

**Comment by rambohe-ch** [comment]
@DreamEagle0 Thank you for filing issue.

> When cloud nodes cannot connect to a edge node, there are 2 scenarios:
> 
> 1. network disconnection
> 2. edge node crashes.
> 
> Consider the second scenario. When a edge node crashes, the pod in the edge node will not be evicted. In this case, the service of the pod will keep unavailable? Is there any way to fix this?

We plan to solve the above scenario 2 in the next version(v0.4.0) or the next two version(v0.5.0), the name of the feature is: Support autonomy feature in node pool level. 
and you can refer to the roadmap: https://github.com/openyurtio/openyurt/blob/master/docs/roadmap.md

**Comment by DreamEagle0** [comment]
@rambohe-ch Thank you for your kind explanation.
