### ISSUE TITLE
[BUG] Issues of RKE

### ISSUE THREAD

**Issue by AnyISalIn** [openyurtio/openyurt#261]
**What happened**:
Hi @charleszheng44, I've already tried to deploy [OpenYurt on RKE](https://github.com/openyurtio/openyurt/issues/259) and it doesn't work. 

1. Kubelet of RKE is containerization, OpenYurt only to control Kubelet service of systemd.
2. Kubelet of RKE communication apiserver based local Nginx container that Nginx listens 127.0.0.1:6443 and reverse proxy real address of apiserver.
3. The static pod directory needs to exposed manually.

**Environment**:
- OpenYurt version: master branch
- Kubernetes version (use `kubectl version`): 1.20
- OS (e.g: `cat /etc/os-release`): CentOS 7.6
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by charleszheng44** [comment]
Hi, @AnyISalIn Thanks for your update. It looks like RKE has a specific system setup for Kubernetes components. Currently, supporting distros other than upstream Kubernetes is not on our road map. But you are welcome to add an extra mode to the `yurtctl` that can make OpenYurt work with RKE, and we can discuss it at the bi-weekly community meeting. 

For the three issues, 

> 1. Kubelet of RKE is containerization, OpenYurt only to control Kubelet service of systems.

A potential solution will be, change the Kubelet workload configuration to make it reconnect to the YurtHub pod

> 2. Kubelet of RKE communication apiserver based local Nginx container that Nginx listens 127.0.0.1:6443 and reverse proxy real address of apiserver.

I think this setting can influence how YurtHub connects to the apiserver. A potential solution will be to let the YurtHub connect to the apiserver through the Ngnix. 

> 3. The static pod directory needs to exposed manually.

I don't quite understand this issue. Can you elaborate a little bit.

**Comment by AnyISalIn** [comment]
@charleszheng44 Thanks for your great suggestions, It seems to works. but RKE needs to manage Kubelet's lifecycle, If we were changed the configuration of Kubelet and when the RKE cluster was changed, It probably re-generated and makes YurtHub not working.

Can we run a container in the worker node and redirect APIServer traffic to YurtHub? Such as the DNAT rule generator.

**Comment by charleszheng44** [comment]
Yes. I think a sidecar container could be a potential solution. 👍🏼

**Comment by AnyISalIn** [comment]
> Yes. I think a sidecar container could be a potential solution. 👍🏼

Thanks, I'll try it on my RKE Cluster.

**Comment by charleszheng44** [comment]
@AnyISalIn I will close this issue for now. Feel free to reopen or submit new issues if you have any questions.
