### ISSUE TITLE
Error report in creating pod of yurt tunnel agent

### ISSUE THREAD

**Issue by yanyhui** [openyurtio/openyurt#262]
_Next, we can set up the yurt-tunnel-agent. Like before, we add a label to the edge node, which allows the yurt-tunnel-agent to be run on the edge node:
kubectl label nodes minikube-m02 openyurt.io/edge-enable-reverseTunnel-client=true
And, apply the yurt-tunnel-agent yaml:
kubectl apply -f config/setup/yurt-tunnel-agent.yaml_    

After the above execution manually, the pod of the cluster is always in the state of crashloopbackoff, and the log is not printed directly when viewing the log through kubectl logs.

**Comment by rambohe-ch** [comment]
@yanyhui Thank you for filing issue.

> _Next, we can set up the yurt-tunnel-agent. Like before, we add a label to the edge node, which allows the yurt-tunnel-agent to be run on the edge node: kubectl label nodes minikube-m02 openyurt.io/edge-enable-reverseTunnel-client=true And, apply the yurt-tunnel-agent yaml: kubectl apply -f config/setup/yurt-tunnel-agent.yaml_

The new label for yurt-tunnel-agent is `openyurt.io/is-edge-worker=true`.
and the detail of deploy yurt-tunnel, you can refer to the docs: https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/yurt-tunnel.md

**Comment by yanyhui** [comment]
@rambohe-ch  Thank you for zhe answer.But the actual operation is totally not right with what you said, _**https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/yurt-tunnel.md**_ It can be determined from this address that the code is in the master version, and the node should be labeled _**kubectl label nodes minicube-m02 openyurt.io/is -Edge worker = true**_, then _**kubectl apply - f  config/setup/yurt-tunnel- agent.yaml**_ is executed After execution, the following effect appears, and no pod is created, because creating pod requires the label in the figure below **_openyurt.io/edge -enable-reverseTunnel-client=true_**
[image](https://user-images.githubusercontent.com/33149983/115132571-1110f680-a034-11eb-9ca9-c4ab0004c88f.png),

When I label the edge node openyurt.io/edge -After enable reversechannel client = true, the pod is created, but it is always CrashLoopBackOff, as shown in the following figure
![image](https://user-images.githubusercontent.com/33149983/115132646-9a282d80-a034-11eb-9a22-6618c1a096b5.png)，
Check the log and execute the command **_kubectl describe Pod - n Kube system yurt-tunnel-agent-nt7w4_**，
Can you give me some suggestions and solutions? Is there a problem with the version of the code master? Do you need to change to version 0.3.0?

**Comment by rambohe-ch** [comment]
@yanyhui Thank you for uploading the detail info. 
Would you upload the logs of yurt-tunnel-agent container? you can login the minicube-m02 node, and execute the command `docker logs {yurt-tunnel-agent-container-id}`  to get the logs.

by the way, you can use the code of master branch.

**Comment by rambohe-ch** [comment]
@yanyhui would you make a pull request for updating the label from `openyurt.io/edge-enable-reverseTunnel-client` to `openyurt.io/is-edge-worker=true` in the following yaml file.
- config/setup/yurt-tunnel- agent.yaml
- config/yaml-template/yurt-tunnel- agent.yaml

**Comment by rambohe-ch** [comment]
@yanyhui If it's convenient for you, you can join openyurt community  dingding group.
and you can get QR code here: https://github.com/openyurtio/openyurt#contact
