### ISSUE TITLE
coredns 无法连接127.0.0.1:10261

### ISSUE THREAD

**Issue by yingjianjian** [openyurtio/openyurt#263]
**What would you like to be added**:
coredns 无法连接127.0.0.1:10261

**Why is this needed**:
yurthub 是否可以新增一个网卡用于容器内部连接10261端口

**Comment by rambohe-ch** [comment]
@yingjianjian Thank you for filing issue.

> **What would you like to be added**:
> coredns 无法连接127.0.0.1:10261

If coredns wants to access the address 127.0.0.1:10261, you should deploy coredns with `hostNetwork=true` at present.

> **Why is this needed**:
> yurthub 是否可以新增一个网卡用于容器内部连接10261端口

I think it's a good idea to add a network interface for accessing the address 127.0.0.1:10261 by container. and we can implement the feature in the next version.

**Comment by yingjianjian** [comment]
> @yingjianjian感谢您提交问题。
> 
> > **您想添加什么**：
> > coredns无法连接127.0.0.1:10261
> 
> 如果coredns要访问地址127.0.0.1:10261，则应`hostNetwork=true`在当前位置部署coredns 。
> 
> > **为什么需**
> > 要这样做：yurthub是否可以添加一个网卡用于容器内部连接10261端口
> 
> 我认为添加一个网络接口以通过容器访问地址127.0.0.1:10261是一个好主意。我们可以在下一版本中实现该功能。

嗯 是的。目前我是通过hostNetwork去解决的。 但是不是所有场景都适用hostNetwork，我这边也在修改yurthub的源码，新增一个虚拟网卡去解决

**Comment by rambohe-ch** [comment]
@yingjianjian If it's convenient for you, you can join openyurt community dingding group.
and you can get QR code here: https://github.com/openyurtio/openyurt#contact

**Comment by rambohe-ch** [comment]
> > 我认为添加一个网络接口以通过容器访问地址127.0.0.1:10261是一个好主意。我们可以在下一版本中实现该功能。
> 
> 嗯 是的。目前我是通过hostNetwork去解决的。 但是不是所有场景都适用hostNetwork，我这边也在修改yurthub的源码，新增一个虚拟网卡去解决

@yingjianjian we will add a dummy type network interface on the node for accessing yurt-hub from container. and the dummy interface address is: `169.254.2.1`.  and you can configure the dummy interface address in the yurt-hub parameter.

**Comment by rambohe-ch** [comment]
@yingjianjian dummy type network interface has been fixed in pr[#289](https://github.com/openyurtio/openyurt/pull/289)
