### ISSUE TITLE
[Refact] Migrate yurt-app-manager to openyurtio/yurt-app-manager

### ISSUE THREAD

**Issue by charleszheng44** [openyurtio/openyurt#280]
Since we have migrated yurt-app-manager to independent repos (`openyurtio/yurt-app-manager` and `openyurtio/yurt-app-manager-api`), we should remove legacy codes from this repository and migrate docs related to the yurt-app-manager to the `openyurtio/yurt-app-manager`.

@rambohe-ch @Fei-Guo  what do you think?

**Comment by Fei-Guo** [comment]
Yes, we should.
