### ISSUE TITLE
[Help Wanted]perfect  yurt-app-manager totural  

### ISSUE THREAD

**Issue by kadisi** [openyurtio/openyurt#286]
**What happened**:

yurt-app-manager add  add patch feature for uniteddeployment , the [toturial](https://github.com/openyurtio/yurt-app-manager/blob/master/docs/yurt-app-manager-dev-tutorial.md) is older , need to  perfect it.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yanyhui** [comment]
@kadisi  please assign to me.

**Comment by kadisi** [comment]
> @kadisi please assign to me.

@yanyhui perfect, welcome
