### ISSUE TITLE
Installation takes very long

### ISSUE THREAD

**Issue by lukonjun** [openyurtio/openyurt#292]
Hi, I just installed yurtctl following the instructions in the README
```bash
git clone https://github.com/openyurtio/openyurt.git
cd openyurt/
make WHAT=cmd/yurtctl
```
The installation was successful, however it took very long (10 min on a cloud VM with 2GBRAM and 2 CPUs), and several test where run. 
Is there a way to increase the speed of the installation?

**Comment by Fei-Guo** [comment]
It could be due to the size of the VM. Did you enable host swapping and is it possible that memory is swapped during the installation?

**Comment by neo502721** [comment]
try set goproxy 

export GOPROXY=https://goproxy.io,https://goproxy.cn

**Comment by lukonjun** [comment]
Hi Guys, thanks for your help,
@Fei-Guo host swapping is not enabled, also only a small part of the RAM is used, peaking at 200mb
@neo502721 i set the proxy, and compared it to an installation where the proxy was set, however both took the same. 

Even though i now took a better performing VM, the installation process still took 6 mins (3 mins test i dont know how to skip :D). 
Maybe this is the expected time and the only thing to speed this up is to provide a compiled binary?

**Comment by neo502721** [comment]
you can skip test use  `make build WHAT=cmd/yurtctl`

**Comment by neo502721** [comment]
> try set goproxy
> 
> export GOPROXY=https://goproxy.io,https://goproxy.cn

sorry, I thought you were in China，goproxy may not work for you.
it took 3min to build all binary on my VM (4core16G) with  test run.
