### ISSUE TITLE
[Question]when openyurt can support 1.19+?

### ISSUE THREAD

**Issue by yudar1024** [openyurtio/openyurt#297]
we use k8s 1.19 and above, but in docs, openyurt only support less then 1.14, when openyurt can support 1.19+?

**Comment by charleszheng44** [comment]
Hi @yudar1024, we won't support 1.19 for the next release.  

We have not run OpenYurt with Kubernetes 1.19 in production environments yet, but I have used OpenYurt with Kubernetes 1.19 locally for a while and everything looks just fine. If you don't mind, you can try out running OpenYurt with 1.19.

**Comment by yanyhui** [comment]
@yudar1024 ，Thank you for filing issue.
We have verified that we have supported version 1.20.I can help you modify the local code to achieve.
