### ISSUE TITLE
The new node join cluster is directly converted to openyurt.

### ISSUE THREAD

**Issue by yanyhui** [openyurtio/openyurt#301]
The new node join cluster is directly converted to openyurt without manual conversion to openyurt.

**Comment by rambohe-ch** [comment]
@yanyhui  thank you for filing issue.
I think it's a good idea to join node into openyurt cluster directly without conversion. and maybe we can add this feature in the next version(v0.5.0)
@zyjhtangtang would you have any comments?

**Comment by yanyhui** [comment]
I think cloud node and edge node need to be handled separately.

**Comment by yanyhui** [comment]
> @yanyhui thank you for filing issue.
> I think it's a good idea to join node into openyurt cluster directly without conversion. and maybe we can add this feature in the next version(v0.5.0)
> @zyjhtangtang would you have any comments?

I think cloud node and edge node need to be handled separately.

**Comment by zyjhtangtang** [comment]
> @yanyhui thank you for filing issue.
> I think it's a good idea to join node into openyurt cluster directly without conversion. and maybe we can add this feature in the next version(v0.5.0)
> @zyjhtangtang would you have any comments?



> @yanyhui thank you for filing issue.
> I think it's a good idea to join node into openyurt cluster directly without conversion. and maybe we can add this feature in the next version(v0.5.0)
> @zyjhtangtang would you have any comments?

Approval, we will provide a tool for OpenYurt cluster creation and node access in the next version (v0.5.0).

**Comment by felix0080** [comment]
good idea

**Comment by rambohe-ch** [comment]
yurtctl init/join command for this feature has been released in OpenYurt v0.5.0, so close this issue.
