### ISSUE TITLE
[Question] openyurt是如何保证edge端与云端网络断连时，节点pod不被迁移的

### ISSUE THREAD

**Issue by fanzetian** [openyurtio/openyurt#305]
看了下superedge是通过域内节点health check vote机制和kubelet上报作为节点禁止pod调度或者pod驱逐的依据，从而保证edge与云端断连pod不被驱逐；openyurt的yurt controller manager是通过什么机制保证在这种只是与云端网络断连但是域内节点间网络正常的场景下pod不驱逐的？

**Comment by Fei-Guo** [comment]
We change the node controller to avoid evicting Pods that run on nodes in "autonomy" mode. It is suboptimal since the remote node can be truly unavailable (crash for instance). We may improve this aspect later.
