### ISSUE TITLE
Verify whether openyurt supports k8s cluster of version 1.20.

### ISSUE THREAD

**Issue by yanyhui** [openyurtio/openyurt#327]
Through manual deployment of openyurt environment verification, openyurt supports k8s cluster of version 1.20.

**Comment by rambohe-ch** [comment]
@yanyhui Thank you for verifying OpenYurt.
how about add the version info of OpenYurt and some verify results or logs?

**Comment by yanyhui** [comment]
Yurtctl also supports version 1.20.
