### ISSUE TITLE
[feature request] Should an Operator be good to turn vanilla k8s cluster to OpenYurt one?

### ISSUE THREAD

**Issue by gnunu** [openyurtio/openyurt#328]
**What would you like to be added**:
An easy way (for user) to do k8s to OpenYurt tranlsation, automatically and thoroughly.

**Why is this needed**:
Sounds an Operator can do this tedious job. This Operator would watch the changes of cluster and do translation or update if needed.

**others**
Sounds not so easy to do, but it will be good to devops. Anyway, Operator is for automation of doing tedious things.

/kind feature

**Comment by rambohe-ch** [comment]
@gnunu Very appreciate for your issue.

It's a good idea to make an Operator to take over cluster translation. and the plan to settle it, i think we can discuss this issue on OpenYurt community meeting and add feedback here. we also welcome you to participate in OpenYurt community meeting  on June 2, 2021 11:00～12:00(Beijing time)

the detail info of community info: https://github.com/openyurtio/openyurt#meeting

**Comment by gnunu** [comment]
Thanks. The merits to do OpenYurt translation by an Operator is it's a general, automatic and close-loop way in terms of taking care of nodes entering and leaving. I can do some expewriments for getting more details to chat in the meeting.
