### ISSUE TITLE
[Question] Does OpenYurt have a formal code style requirement?

### ISSUE THREAD

**Issue by zzguang** [openyurtio/openyurt#330]
**What happened**:
I am not sure whether OpenYurt has a formal code style requirement, which may include:
1. function name definition rule
2. limitation of max characters every line
3. code comments format
4. patch comments format
5. ...
**What you expected to happen**:
If no clear requirement for OpenYurt by now, I think it's better to clarify it so that different contributors can follow the unified code style rule. Forming the consistent code style may be beneficial to the code readability and maintainability of the whole project.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@zzguang Very appreciate for your issue.  
OpenYurt community does not have a detailed code style at present, but code of pull request will be verified by golang native rule(`golangci-lint run --out-format=github-actions --disable-all  -E deadcode -E gofmt -E goimports -E ineffassign -E misspell -E vet --timeout=15m` in github action)

and If you have a good code style to contribute to OpenYurt, we will be more than happy to do so.

**Comment by zzguang** [comment]
Okay, let's follow the golang native rule firstly, if we find it's not enough yet, we can discuss it in future to figure out an unified code style, thanks!
