### ISSUE TITLE
[Question]Why does yurthub store cached data like this? 

### ISSUE THREAD

**Issue by xmwilldo** [openyurtio/openyurt#331]
**What happened**:
When the component on the edge node is connected to yurthub, the data it needs will be cached on the edge node, like this：
![image](https://user-images.githubusercontent.com/16560252/120458870-3bdbc200-c3ca-11eb-938e-f4d27d85a34b.png)

**What you expected to happen**:
If this is the case, the same data of different components cannot be shared, and duplicate data will be generated. Why do you design this way?
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by qclc** [comment]
I think this design mainly plays a role in resource isolation. Each component can only get the resources in its own folder, and each component folder will only save the content that the component can get. If the resource is placed in the public directory, when making a list request, unauthorized resources may be obtained.

**Comment by rambohe-ch** [comment]
@xmwilldo Thank you for filing issue.
1. First of all, the isolated data cache is relatively easy to implement. if cache data is shared by all of components, yurthub will become complicated.
2. And then, cache data on node only includes the meta data, and the duplicated data is not so much.

so compared to more storage consumption, we chose a isolated cache for easier implementation. and maybe in the future we will consider optimizing current cache.

**Comment by MIBc** [comment]
How about the `get` performance if there are a lot of resource in cache?
