### ISSUE TITLE
[Question] How to request for an account for OpenYurt Channel on Slack?

### ISSUE THREAD

**Issue by Windrow** [openyurtio/openyurt#333]
**What happened**:  
A link to Slack is provided in README, but I haven't seen how to register an account to sign in OpenYurt Channel.  
Also, QR code for Dingtalk Group is out of date. Is it abandoned?  

**What you expected to happen**:  
Register an account and sign in the channel.  

**How to reproduce it (as minimally and precisely as possible)**:  
[channel](https://openyurt.slack.com/)  

/kind question

**Comment by qclc** [comment]
@Windrow Thanks for reminding. The latest PR has updated the invite connection, you can enter the openyurt slack workspace through this connection #332 , and Dingtalk Group number is 31993519, you can search that number to join the Openyurt  Community Group.
