### ISSUE TITLE
[Question]complete yurthub configuration error

### ISSUE THREAD

**Issue by zf930530** [openyurtio/openyurt#338]
Get an error while deploy yurthub: complete yurthub configuration error, only https scheme is supported for server address(http://127.0.0.1:10261)

**Environment**:
- OpenYurt version:0.4.0
- Kubernetes version (use `kubectl version`):v1.16.9
- OS (e.g: `cat /etc/os-release`):CentOS 7.4
- Kernel (e.g. `uname -a`):3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:_output/bin/yurtctl convert --provider kubeadm

**Comment by rambohe-ch** [comment]
@zf930530 Thank you for filing issue.
Would you provide complete log information about `yurtctl convert` command?

**Comment by zf930530** [comment]
[root@xxxxx openyurt]# _output/bin/yurtctl convert --provider kubeadm
I0607 09:33:04.401518   25284 convert.go:461] kube-public/cluster-info configmap already exists, skip to prepare it
I0607 09:33:04.401604   25284 convert.go:348] deploying the yurt-hub and resetting the kubelet service...
E0607 09:35:04.442528   25284 util.go:318] fail to run servant job(yurtctl-servant-convert-100009-w-z4-1-1): wait for job to be complete timeout
E0607 09:35:04.442530   25284 util.go:318] fail to run servant job(yurtctl-servant-convert-100009-m-hh-1-2): wait for job to be complete timeout
E0607 09:35:04.444701   25284 util.go:318] fail to run servant job(yurtctl-servant-convert-100009-w-z4-1-2): wait for job to be complete timeout
E0607 09:35:04.487936   25284 util.go:318] fail to run servant job(yurtctl-servant-convert-100009-m-hh-1-1): wait for job to be complete timeout
E0607 09:35:04.488676   25284 util.go:318] fail to run servant job(yurtctl-servant-convert-100009-m-hh-1-3): wait for job to be complete timeout
I0607 09:35:04.488700   25284 convert.go:372] the yurt-hub is deployed

**Comment by zf930530** [comment]
> @zf930530 Thank you for filing issue.
> Would you provide complete log information about `yurtctl convert` command?
[root@xxxxx openyurt]# _output/bin/yurtctl convert --provider kubeadm
I0607 09:33:04.401518 25284 convert.go:461] kube-public/cluster-info configmap already exists, skip to prepare it
I0607 09:33:04.401604 25284 convert.go:348] deploying the yurt-hub and resetting the kubelet service...
E0607 09:35:04.442528 25284 util.go:318] fail to run servant job(yurtctl-servant-convert-100009-w-z4-1-1): wait for job to be complete timeout
E0607 09:35:04.442530 25284 util.go:318] fail to run servant job(yurtctl-servant-convert-100009-m-hh-1-2): wait for job to be complete timeout
E0607 09:35:04.444701 25284 util.go:318] fail to run servant job(yurtctl-servant-convert-100009-w-z4-1-2): wait for job to be complete timeout
E0607 09:35:04.487936 25284 util.go:318] fail to run servant job(yurtctl-servant-convert-100009-m-hh-1-1): wait for job to be complete timeout
E0607 09:35:04.488676 25284 util.go:318] fail to run servant job(yurtctl-servant-convert-100009-m-hh-1-3): wait for job to be complete timeout
I0607 09:35:04.488700 25284 convert.go:372] the yurt-hub is deployed

**Comment by zf930530** [comment]
> @zf930530 Thank you for filing issue.
> Would you provide complete log information about `yurtctl convert` command?

The configuration file looks weird
config file:/etc/kubernetes/manifests/yurt-hub.yaml

  containers:
  - name: yurt-hub
    image: openyurt/yurthub:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: hub-dir
      mountPath: /var/lib/yurthub
    - name: kubernetes
      mountPath: /etc/kubernetes
    command:
    - yurthub
    - --v=2
    - --server-addr=http://127.0.0.1:10261
    - --node-name=$(NODE_NAME)
    - --join-token=41o26o.uzbyhk672dlbxjqs

But in config/setup/yurthub.yaml,it's
  containers:
  - name: yurt-hub
    image: openyurt/yurthub:latest
    imagePullPolicy: Always
    volumeMounts:
    - name: kubernetes
      mountPath: /etc/kubernetes
    - name: pki
      mountPath: /etc/kubernetes/pki
    - name: pem-dir
      mountPath: /var/lib/kubelet/pki
    command:
    - yurthub
    - --v=2
    - --server-addr=https://__kubernetes_service_host__:__kubernetes_service_port_https__
    - --node-name=$(NODE_NAME)
