### ISSUE TITLE
[feature request]metadata cache path can be configured

### ISSUE THREAD

**Issue by luckymrwang** [openyurtio/openyurt#343]
**What would you like to be added**:
The k8s's resource metadata are saved to the fixed path `/etc/kubernetes/cache/`.  I think that it's better to change it according to bootstrap parameter.

**Why is this needed**:
Maybe some user want to save metadata to specified path. 

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@luckymrwang Very appreciate for your issue.
It's a good idea to add a parameter for changing root dir of cache in yurthub.
agree + 1

**Comment by rambohe-ch** [comment]
@luckymrwang Would you like to take over to add this parameter in yurthub?

**Comment by luckymrwang** [comment]
> @luckymrwang Would you like to take over to add this parameter in yurthub?

I am willing to do it. I will create a pr and push the code later.
