### ISSUE TITLE
[Question] Need a tutorial / manual of feature `Device Manager`

### ISSUE THREAD

**Issue by gaofeng1973** [openyurtio/openyurt#344]
What happened:
I saw that in OpenYurt 0.4.0 that the road map already support the `Device Manager`. but I only found the following https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20210310-edge-device-management.md proposal doc on this topic. I would like to try this feature with EdgeX foundry . 

What you expected to happen:
Need a tutorial / manual of feature `Device Manager`

How to reproduce it (as minimally and precisely as possible):
N/A

/kind question

**Comment by charleszheng44** [comment]
@gaofeng1973 Thanks for filing the issue. The DeviceManager is still under development. We will add the manual once the feature is ready.

**Comment by rambohe-ch** [comment]
@gaofeng1973 `DeviceManager` has been released in OpenYurt v0.5.0, the repo is here: https://github.com/openyurtio/yurt-device-controller
