### ISSUE TITLE
[BUG][tunnel server]After yurt revert,iptables remained

### ISSUE THREAD

**Issue by zf930530** [openyurtio/openyurt#345]
**What happened**: revert a k8s cluster with tunnel server, iptables with tunnel server does not be removed.

**What you expected to happen**: iptables with tunnel server will be removed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: 0.4.0
- Kubernetes version (use `kubectl version`): 1.16.9
- OS (e.g: `cat /etc/os-release`): centos 7.4
- Kernel (e.g. `uname -a`): 
Linux 100178-m-iz-1-1 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
1.yurtctl convert --provider kubeadm --cloud-nodes xxxxx --deploy-yurttunnel
2.yurtctl revert
- Others:
Output of run yurtctl revert:
I0609 16:19:51.437100 20116 revert.go:162] label openyurt.io/is-edge-worker is removed
I0609 16:19:51.447503 20116 revert.go:172] yurt controller manager is removed
I0609 16:19:51.455485 20116 revert.go:182] serviceaccount for yurt controller manager is removed
I0609 16:19:51.466377 20116 revert.go:192] clusterrole for yurt controller manager is removed
I0609 16:19:51.473353 20116 revert.go:202] clusterrolebinding for yurt controller manager is removed
I0609 16:19:51.618861 20116 revert.go:239] clusterrolebinding system:controller:node-controller is created
I0609 16:20:21.664607 20116 util.go:321] servant job(yurtctl-servant-revert-100178-w-ib-2) has succeeded
I0609 16:20:21.665480 20116 util.go:321] servant job(yurtctl-servant-revert-100178-w-ib-1) has succeeded
I0609 16:20:21.665507 20116 revert.go:253] yurt-hub is removed, kubelet service is reset

After yurt revert,iptables remained: iptables -t nat -nvL
Chain TUNNEL-PORT (1 references)
pkts bytes target prot opt in out source destination
0 0 TUNNEL-PORT-10255 tcp -- * * 0.0.0.0/0 0.0.0.0/0 tcp dpt:10255 /* jump to port 10255 /
5 300 TUNNEL-PORT-10250 tcp -- * * 0.0.0.0/0 0.0.0.0/0 tcp dpt:10250 / jump to port 10250 */

Chain TUNNEL-PORT-10250 (1 references)
pkts bytes target prot opt in out source destination
0 0 RETURN tcp -- * * 0.0.0.0/0 127.0.0.1 /* return request to access node directly / tcp dpt:10250
0 0 RETURN tcp -- * * 0.0.0.0/0 192.168.0.6 / return request to access node directly / tcp dpt:10250
0 0 RETURN tcp -- * * 0.0.0.0/0 192.168.0.4 / return request to access node directly / tcp dpt:10250
0 0 RETURN tcp -- * * 0.0.0.0/0 192.168.0.5 / return request to access node directly / tcp dpt:10250
5 300 DNAT tcp -- * * 0.0.0.0/0 0.0.0.0/0 / dnat to tunnel for access node */ tcp dpt:10250 to:192.168.0.4:10263

Chain TUNNEL-PORT-10255 (1 references)
pkts bytes target prot opt in out source destination
0 0 RETURN tcp -- * * 0.0.0.0/0 127.0.0.1 /* return request to access node directly / tcp dpt:10255
0 0 RETURN tcp -- * * 0.0.0.0/0 192.168.0.6 / return request to access node directly / tcp dpt:10255
0 0 RETURN tcp -- * * 0.0.0.0/0 192.168.0.4 / return request to access node directly / tcp dpt:10255
0 0 RETURN tcp -- * * 0.0.0.0/0 192.168.0.5 / return request to access node directly / tcp dpt:10255
0 0 DNAT tcp -- * * 0.0.0.0/0 0.0.0.0/0 / dnat to tunnel for access node */ tcp dpt:10255 to:192.168.0.4:10264

/kind bug

**Comment by Peeknut** [comment]
Related issues are mentioned in the issue #337, and pr #346.
Suggestions for amendments are welcome. :)

**Comment by yanyhui** [comment]
@zf930530 Thank you for putting forward this bug. I also encountered this problem.
The reason for our analysis is that the iptables rule was not deleted when yurtctl revert was executed. We are dealing with it and plan to deal with it in the near future.
