### ISSUE TITLE
[Question]Questions about clusterrolebinding system:controller:node-controller being deleted.

### ISSUE THREAD

**Issue by zf930530** [openyurtio/openyurt#347]
Why was the clusterrolebinding system:controller:node-controller removed when the cluster converted to a yurt cluster?

**What happened**:
After all worker nodes convert to yurt cluster,the deployment(or daemonset) is no longer working, and pods are not automatically deleted or created when deployments are deleted or created.
**What you expected to happen**:
Deployment or DaemonSet can work properly.

**How to reproduce it (as minimally and precisely as possible)**:
Convert all worker nodes to edge node,then create a deployment or daemonset.

**Anything else we need to know?**:
Error log from kube-controller-manager
I0610 07:06:02.361899       1 controllermanager.go:534] Started "deployment"
I0610 07:06:02.361975       1 deployment_controller.go:152] Starting deployment controller
I0610 07:06:02.361984       1 shared_informer.go:197] Waiting for caches to sync for deployment
I0610 07:06:02.511994       1 node_ipam_controller.go:94] Sending events to api server.
E0610 07:06:12.513705       1 cidr_allocator.go:119] Failed to list all nodes: nodes is forbidden: User "system:serviceaccount:kube-system:node-controller" cannot list resource "nodes" in API group "" at the cluster scope
E0610 07:06:22.513180       1 cidr_allocator.go:119] Failed to list all nodes: nodes is forbidden: User "system:serviceaccount:kube-system:node-controller" cannot list resource "nodes" in API group "" at the cluster scope
E0610 07:06:32.513491       1 cidr_allocator.go:119] Failed to list all nodes: nodes is forbidden: User "system:serviceaccount:kube-system:node-controller" cannot list resource "nodes" in API group "" at the cluster scope
E0610 07:06:42.513064       1 cidr_allocator.go:119] Failed to list all nodes: nodes is forbidden: User "system:serviceaccount:kube-system:node-controller" cannot list resource "nodes" in API group "" at the cluster scope
E0610 07:06:52.513406       1 cidr_allocator.go:119] Failed to list all nodes: nodes is forbidden: User "system:serviceaccount:kube-system:node-controller" cannot list resource "nodes" in API group "" at the cluster scope
E0610 07:07:02.513283       1 cidr_allocator.go:119] Failed to list all nodes: nodes is forbidden: User "system:serviceaccount:kube-system:node-controller" cannot list resource "nodes" in API group "" at the cluster scope
E0610 07:07:12.513321       1 cidr_allocator.go:119] Failed to list all nodes: nodes is forbidden: User "system:serviceaccount:kube-system:node-controller" cannot list resource "nodes" in API group "" at the cluster scope
E0610 07:07:22.513216       1 cidr_allocator.go:119] Failed to list all nodes: nodes is forbidden: User "system:serviceaccount:kube-system:node-controller" cannot list resource "nodes" in API group "" at the cluster scope
E0610 07:07:32.513258       1 cidr_allocator.go:119] Failed to list all nodes: nodes is forbidden: User "system:serviceaccount:kube-system:node-controller" cannot list resource "nodes" in API group "" at the cluster scope

**Environment**:
- OpenYurt version: 0.4.0
- Kubernetes version (use `kubectl version`): 1.16.9
- OS (e.g: `cat /etc/os-release`): centos 7.4
- Kernel (e.g. `uname -a`):
Linux 100178-m-iz-1-1 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
yurtctl convert --provider kubeadm --cloud-nodes xxxxx --deploy-yurttunnel

**others**
/kind question

**Comment by zf930530** [comment]
[all_resource.txt](https://github.com/openyurtio/openyurt/files/6629314/all_resource.txt)
[kube-controller-manager.log](https://github.com/openyurtio/openyurt/files/6629315/kube-controller-manager.log)
[yurt-controller-manager-7d4f7df99f-6dhhn.log](https://github.com/openyurtio/openyurt/files/6629316/yurt-controller-manager-7d4f7df99f-6dhhn.log)
[yurt-hub-100178-w-ib-1.log](https://github.com/openyurtio/openyurt/files/6629317/yurt-hub-100178-w-ib-1.log)
[yurt-hub-100178-w-ib-2.log](https://github.com/openyurtio/openyurt/files/6629318/yurt-hub-100178-w-ib-2.log)

All logs and k8s resources.

**Comment by Peeknut** [comment]
Can a deplyment/daemonset be created? If the deployment/daemonset can be created, but the corresponding pod is not created, can you check again whether the node yurthub and kubelet are running normally?

**Comment by zf930530** [comment]
Deplyment/daemonset can be created and yurthub/kubelet on edgenode running normally.

**Comment by Peeknut** [comment]
I think there is a problem with `kube-controller-manager` itself. 

Compared with my local log: 
[kube-controller-manager.log](https://github.com/openyurtio/openyurt/files/6638117/kube-controller-manager.log)
In `kube-controller-manager`, `deployment`, `daemonset`, `replicationcontroller`, etc. are not started, so `deployment` and `daemonset` cannot be created normally.

When using `yurtctl convert` to convert, `kube-controller-manager` will have relevant information, such as:


```
I0605 05:55:35.207513       1 event.go:278] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"yurt-controller-manager", UID:"c80e17e5-c391-4709-b0f3-a865d4cc5509", APIVersion:"apps/v1", ResourceVersion:"179630", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set yurt-controller-manager-7895f68dcd to 1
I0605 05:55:35.610048       1 event.go:278] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"yurt-controller-manager-7895f68dcd", UID:"0b44eed2-8102-4297-94eb-b9edfd1ffae2", APIVersion:"apps/v1", ResourceVersion:"179631", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: yurt-controller-manager-7895f68dcd-bfwd9
I0605 05:58:27.203591       1 event.go:278] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"yurt-controller-manager", UID:"40277314-2c50-4939-b1be-0f13d0773cf6", APIVersion:"apps/v1", ResourceVersion:"180128", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set yurt-controller-manager-7895f68dcd to 1
I0605 05:58:27.395109       1 event.go:278] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"yurt-controller-manager-7895f68dcd", UID:"d613c763-e2b8-4ce0-a089-b2c602393f26", APIVersion:"apps/v1", ResourceVersion:"180129", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: yurt-controller-manager-7895f68dcd-h8g5r
I0605 06:02:41.413224       1 event.go:278] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"yurt-controller-manager", UID:"57786fde-a6b3-4ea7-b2e1-215fa84de1a6", APIVersion:"apps/v1", ResourceVersion:"180860", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set yurt-controller-manager-7895f68dcd to 1
I0605 06:02:41.527252       1 event.go:278] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"yurt-controller-manager-7895f68dcd", UID:"74f4e2cb-0051-4868-bdca-dc1ad29a6890", APIVersion:"apps/v1", ResourceVersion:"180861", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: yurt-controller-manager-7895f68dcd-sh2k7
I0605 06:02:42.397113       1 event.go:278] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"kube-system", Name:"yurt-tunnel-server", UID:"89730853-49a1-4997-8145-69ad6b9f61ae", APIVersion:"apps/v1", ResourceVersion:"180891", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set yurt-tunnel-server-58dbdd6d9c to 1
I0605 06:02:42.518417       1 event.go:278] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"kube-system", Name:"yurt-tunnel-server-58dbdd6d9c", UID:"19706e0c-d510-40c2-a573-86f2d9964945", APIVersion:"apps/v1", ResourceVersion:"180893", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: yurt-tunnel-server-58dbdd6d9c-n2jh2
I0605 06:02:42.558769       1 event.go:278] Event(v1.ObjectReference{Kind:"DaemonSet", Namespace:"kube-system", Name:"yurt-tunnel-agent", UID:"dad68414-0e88-45ec-a44f-b4abebbd4bda", APIVersion:"apps/v1", ResourceVersion:"180894", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: yurt-tunnel-agent-7cwdm
I0605 06:02:43.124305       1 event.go:278] Event(v1.ObjectReference{Kind:"Job", Namespace:"kube-system", Name:"yurtctl-servant-convert-n80", UID:"bf4b0a97-f26f-4896-be38-56666b68938f", APIVersion:"batch/v1", ResourceVersion:"180910", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: yurtctl-servant-convert-n80-2v8mf
```
And it doesn't appear in your log. Maybe there is a problem with `kube-controller-manager` before using `yurtctl convert`.

You can use `yurtctl revert` to convert the cluster back, check `kube-controller-manager`, and then run `yurtctl convert`.

**Comment by Peeknut** [comment]
In addition, clusterrolebinding `system:controller:node-controller` is deleted to turn off the `nodelifecycle` function in `kube-controller-manager` and use `yurt-controller-manager` to replace it, so edge node autonomy can be achieved.

**Comment by zf930530** [comment]
NAME                                               READY   STATUS    RESTARTS   AGE
kube-controller-manager-100178-m-iz-1-1            1/1     Running   234        6d15h
kube-controller-manager-100178-m-iz-1-2            1/1     Running   224        6d15h
kube-controller-manager-100178-m-iz-1-3            1/1     Running   237        6d15h


I found that in my environment, the kube-controller-manager seems to go into an infinite reboot state after the k8s cluster is transformed into a Yurt cluster.As you can see, it has been restarted more than 200 times.What are the possible reasons? Is there some ability to repair Yurt cluster itself after kube-controller-manager been rebooted?

**Comment by Peeknut** [comment]
I think the reason should be the same as you said:

The kube-controller-manager restarted for the first time because the leader changed, and then restarted continuously because of the lack of clusterrolebinding `system:controller:node-controller`.



Now there is no related ability to be repaired Yurt cluster itself. If you want to fix the current problem, you can try:

1) Re-create clusterrolebinding `system:controller:node-controller`,

2) Modify `/etc/kubernetes/manifests/kube-controller-manager.yaml` on all leader nodes, the original option looks like `--controllers=*,bootstrapsigner,tokencleaner`, to disable
the nodelifecycle controller, change the option to `--controllers=*,bootstrapsigner,tokencleaner,-nodelifecycle`.

**Comment by Peeknut** [comment]
In addition, if you have suggestions for code improvement, welcome to submit pr to fix the problem. :)
