### ISSUE TITLE
yurthub can not running successfully when cert-mgr-mode set to "kubelet"

### ISSUE THREAD

**Issue by lclxg** [openyurtio/openyurt#348]
the value of "cert-mgr-node" is hubslef in defalut， I want to test kubelet mode , so modify the yurhub.yml and add environment variable  cert-mgr-node=kubelet，but the yurthub pod can not  running  with the error “panic: runtime error: invalid memory address or nil pointer dereference”

**What you expected to happen**: the yurthub running correctly  with kubelet cert-mgr-mode

**How to reproduce it (as minimally and precisely as possible)**:modify the yurhub.yml and add environment variable  cert-mgr-node=kubelet

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: 0.4
- Kubernetes version (use `kubectl version`): 1.20
- OS (e.g: `cat /etc/os-release`): centos 8.3
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@lclxg Thank you for filing issue.
Would you upload the detail log of yurthub?

**Comment by qclc** [comment]
@lclxg Thanks for reporting the bug. This error occurred in the process of using kubelet.conf to obtain *rest.Config, I will fix it.
