### ISSUE TITLE
[Feature Request]pkg/yurthub/storage/factory/factory.go file is unnecessary

### ISSUE THREAD

**Issue by mauricewei** [openyurtio/openyurt#355]
**What would you like to be added**:
When i view the yurthub code,I find the pkg/yurthub/storage/factory/factory.go file is unnecessary.
For code simplicity, can we remove this file ? 
And when other fuction need create a default backend storage directory, we can Just call func disk.NewDiskStorage("") ?

**Why is this needed**:
For code simplicity

**others**
/kind feature

This issue may be fix after [pull request](https://github.com/openyurtio/openyurt/pull/349)

**Comment by luckymrwang** [comment]
The code may be changed in the [pull request](https://github.com/openyurtio/openyurt/pull/349)

**Comment by mauricewei** [comment]
> The code may be changed in the [pull request](https://github.com/openyurtio/openyurt/pull/349)

Maybe give this fix to me？

**Comment by rambohe-ch** [comment]
@mauricewei Thank you for filing issue.
I think it's need to keep `factory.go` for `factory.go` is used for creating storage for cache container metadata. in the meantime it's convenient to add other kind storage in the future.

by the way, other functions call `disk.NewDiskStorage("")` is used to store yurthub internal info on local disk, and i think it's not conflict with `factory.go`

**Comment by mauricewei** [comment]
@rambohe-ch Agreen with
