### ISSUE TITLE
[Question]The yurtctl binary file build in macOs can't execute on centos7

### ISSUE THREAD

**Issue by mauricewei** [openyurtio/openyurt#356]
**What happened**:
When i build yurtctl binary file in my macbook:
```shell
➜  openyurt git:(master) ✗ make WHAT=cmd/yurtctl
```
And then i copy the file to my test environment(centos7 operating system)
I try to convert my k8s cluster use this binary file, some error happend:
```shell
[maurice@lab-openyurt ~]$ yurtctl  convert --provider  minikube
-bash: /usr/bin/yurtctl: cannot execute binary file
```
When i build binary file in centos operating system it works.
READEME is not any reminder content about this problem.

**What you expected to happen**:
Readme docment should reminder users to avoid this problem.

**How to reproduce it (as minimally and precisely as possible)**:
The same as *What happened* section

**Anything else we need to know?**:
Is there a nessary that perfect the README to remind users to avoid this problem?

**Environment**:
- OpenYurt version: master
- Kubernetes version (use `kubectl version`): v1.16.7
- OS (e.g: `cat /etc/os-release`): centos7/macOs
- Kernel (e.g. `uname -a`):Linux lab-openyurt 3.10.0-1062.4.3.el7.x86_64 #1 SMP Wed Nov 13 23:58:53 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: minikube
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@mauricewei Would you like to take over this problem and fix it?

**Comment by mauricewei** [comment]
@rambohe-ch I am willing to fix it and commit pull request later
