### ISSUE TITLE
[Question]Listen protocol of yurthub is `http`, why not https

### ISSUE THREAD

**Issue by luckymrwang** [openyurtio/openyurt#361]
**What happened**:
The current listen protocol of yurthub is `http`, why not https?

**What you expected to happen**:
calico, kube-proxy and so on accessed apiserver using `https` by default. If they use yurthub will do many change.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
What's the original purpose to use http?

**Environment**:
- OpenYurt version: v0.4.0
- Kubernetes version (use `kubectl version`): v1.20
- OS (e.g: `cat /etc/os-release`): centos7
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by qclc** [comment]
At present, the communication between yurthub and kube-apiserver uses https, and the communication between local components (such as kube-proxy, calico/flannel) and yurthub is http. Since the communication between yurthub and internal components occurs locally, the original design was http

**Comment by qclc** [comment]
At present, the communication between yurthub and kube-apiserver uses `https`, and the communication between local components (such as kube-proxy, calico/flannel) and yurthub is `http`. 

- Original purpose:  I think it's the communication between yurthub and internal components occurs locally, so the original design was http.
- For network components, openyurt currently uses flannel by default, just configure the startup parameters of flannel to the listening address of yurthub to use flannel normally.

**Comment by qclc** [comment]
@rambohe-ch Hi, Does openyurt currently consider replacing the local communication with `https` to adapt to the components that use https communication by default?

**Comment by rambohe-ch** [comment]
@luckymrwang Thank you for your question.
To be frankly, the original purpose of using `http` more simpler. and `https` is more useful and smoothly for edge workload to  access yurthub. Would you like to take over to support https for yurthub?

**Comment by luckymrwang** [comment]
> At present, the communication between yurthub and kube-apiserver uses `https`, and the communication between local components (such as kube-proxy, calico/flannel) and yurthub is `http`.
> 
> * Original purpose:  I think it's the communication between yurthub and internal components occurs locally, so the original design was http.
> * For network components, openyurt currently uses flannel by default, just configure the startup parameters of flannel to the listening address of yurthub to use flannel normally.

@qclc  I got it. Thanks for your replay.

**Comment by luckymrwang** [comment]
> Would you like to

Yes, I'd like to do it.

**Comment by luckymrwang** [comment]
> @luckymrwang Thank you for your question.
> To be frankly, the original purpose of using `http` more simpler. and `https` is more useful and smoothly for edge workload to access yurthub. Would you like to take over to support https for yurthub?

@rambohe-ch Yes, I'd like to do it.
