### ISSUE TITLE
[REQUEST Membership]: New membership  for Peeknut: reviewer of openyurtio/openyurt

### ISSUE THREAD

**Issue by Peeknut** [openyurtio/openyurt#362]
## GitHub Username

Peeknut

## Membership I'm requesting

reviewer

## Sponsors

rambohe-ch

## List of contributions 

- PRs reviewed:

  openyurtio/openyurt#352

  openyurtio/openyurt#336

  openyurtio/openyurt#323

  openyurtio/openyurt#306

- PRs authored:

  openyurtio/openyurt#346

  openyurtio/openyurt#317

  openyurtio/openyurt#234

  openyurtio/openyurt#220

  openyurtio/openyurt#206

**Comment by rambohe-ch** [comment]
agree +1
@Peeknut have contributed some valuable pull requests and review comments to OpenYurt. I think @Peeknut will contribute more to OpenYurt when she becomes a Reviewer, so i like to support the reviewer request.

**Comment by kadisi** [comment]
agree +1

**Comment by Fei-Guo** [comment]
+1

**Comment by yixingjia** [comment]
+1

**Comment by rambohe-ch** [comment]
@Peeknut Congratulations on becoming a Reviewer for the OpenYurt project, I will approve the pull request #363 and then close this issue.
