### ISSUE TITLE
[BUG] Unable to re-convert the cluster after executing yurtctl revert.

### ISSUE THREAD

**Issue by DrmagicE** [openyurtio/openyurt#376]
**What happened**:
I ran `yurtctl convert` to convert the cluster to yurt cluster. As I forgot to pass `--kubeadm-conf-path` flag and the default value is not suitable for my environment, I stop `yurtctl convert` by ctrl+C and then ran `yurtctl revert` to revert it. 
After the revert process was done, I ran `yurtctl convert --kubeadm-conf-path=xxx` again, but got the following error: 
```
CustomResourceDefinition/uniteddeployments.apps.openyurt.io createdF0702 10:31:15.497317    8410 convert.go:103] fail to convert kubernetes to yurt: fail to deploy the yurt-app-manager: fail to create the secret/yurt-app-webhook-certs: secrets "yurt-app-webhook-certs" already exists
```
I have to remove some resources manually before `yurtctl convert`.  

Should `yurtctl revert` be responsible for these cleanups?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: 
master branch (https://github.com/openyurtio/openyurt/commit/9426d63ddd3ac7a3a837fc61f847f88a9ee76bf2)
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.20", GitCommit:"1f3e19b7beb1cc0110255668c4238ed63dadb7ad", GitTreeState:"clean", BuildDate:"2021-06-16T12:51:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by Peeknut** [comment]
Yes,  `yurtctl revert` responsible for `yurt-app-manager` cleanups is still being updated, which is handled by @yanyhui.

**Comment by rambohe-ch** [comment]
@Peeknut Would you take over this issue and fix the kube-controller-manager setting?

**Comment by Peeknut** [comment]
> @Peeknut Would you take over this issue and fix the kube-controller-manager setting?

OK

**Comment by Peeknut** [comment]
> @Peeknut Would you take over this issue and fix the kube-controller-manager setting?

ok
