### ISSUE TITLE
[Question]How to collect metrics of edgenode by metrics-server and yurt-tunnel-server?

### ISSUE THREAD

**Issue by zf930530** [openyurtio/openyurt#379]
**What happened**:
Execute: kubectl top node
[root@xxx]# kubectl top node
NAME              CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%     
m-iz-1-1           100m         5%     2277Mi          76%         
m-iz-1-2           131m         7%     2248Mi          75%         
m-iz-1-3           104m         5%     2424Mi          81%         
w-ib-1               39m          2%     1762Mi          54%         
w-ib-2               57m          3%     1808Mi          56%         
w-ib-3     unknown                      unknown               unknown               unknown               
w-ib-4     unknown                           unknown               unknown               unknown 

metrics-server cannot collect metrics from edge nodes.
**What you expected to happen**:
Metrics-server can collect metrics info from edge nodes.

Is it possible for metrics-server to collect metrics from edge nodes via yurt-tunnel-server? How should I configure it?

**Environment**:
- OpenYurt version: 0.4.0
- Kubernetes version (use `kubectl version`): 1.16.9
- OS (e.g: `cat /etc/os-release`): Centos7.4

**others**
/kind question

**Comment by rambohe-ch** [comment]
@zf930530 Thank you for filing issue.
Metrics-server and yurt-tunnel-server have run on same node?

and you want to dive into the details of yurt-tunnel, you can read the link here: https://mp.weixin.qq.com/s/QVrygAyq01AWbvgj1ihBEQ
