### ISSUE TITLE
[BUG] default yurt-tunnel-agent.yaml is invalid if chose  manual install openyurt 

### ISSUE THREAD

**Issue by konghui** [openyurtio/openyurt#382]
**What happened**:
`yurt-tunnel-agent` can't connect to `kube-apiserver` and yurt-tunnel-agent display has not permission to list/watch/create resources. 
**What you expected to happen**:
yurt-tunnel-agent can start correctly.
**How to reproduce it (as minimally and precisely as possible)**:
`kubectl apply -f config/setup/yurt-tunnel-agent.yaml`
**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@kong Thank you for filing issue.
Would you be able to upload the detail logs of yurt-tunnel-agent?
