### ISSUE TITLE
[feature request] Openyurt does not support k8s-1.19 version, but our product use k8s-1.19 version, we need openyurt supporting k8s-1.19 version, thanks a lot!

### ISSUE THREAD

**Issue by dingsihua** [openyurtio/openyurt#385]
https://github.com/openyurtio/openyurt/blob/02a5cfb4f9f0c9e1757457068e7a58d4de1321f4/pkg/yurtctl/util/kubernetes/util.go#L84

**Comment by rambohe-ch** [comment]
@dingsihua Thank you for filing issue.
I think that openyurt components can work with kubernetes v1.19 version , but we have not checked kubernetes v1.19 carefully,  so version v1.19 is not added into supported version list. maybe you can revise the `ValidServerVersions` and add v1.19, then make up a new yurtctl tool and run convertion.

**Comment by rambohe-ch** [comment]
@dingsihua Would you make a pull request to revise the `supported version list` and add v1.19

**Comment by rambohe-ch** [comment]
@dingsihua I think k8s v1.19 is already supported by yurtctl tool.
