### ISSUE TITLE
[BUG]How `yurtctl convert` can better close the `nodelifecycle controller` (`kube-controller-manager`)?

### ISSUE THREAD

**Issue by Peeknut** [openyurtio/openyurt#391]
**What happened**:
When excuting the command `yurtctl convert`,  the clusterrolebinding `system:controller:node-controller` will be deleted to turn off the `nodelifecycle controller` (in `kube-controller-manager`).
However, the flowing questions will appear afterwards:
- Other controllers using clusterrolebinding `system:controller:node-controller` can't work normally.
  eg: issue: https://github.com/openyurtio/openyurt/issues/380
- In a high availability scenario, when kube-controller-manager changes the leader, kube-controller-manager can't start successfully because of lack of clusterrolebinding `system:controller:node-controller` .
  Issue: https://github.com/openyurtio/openyurt/issues/347

**What you expected to happen**:
`yurtctl convert`  doesn't  turn off `nodelifecycle controller` by deleting clusterrolebinding `system:controller:node-controller`. And it can support the high availability of `kube-controller-manager`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
*Solutions currently proposed:*
When executing `yurtctl convert`, 1) If `kube-controller-manager` is deployed through static file `/etc/kubernetes/manifests/kube-controller-manager.yaml`: Create jobs for all candidates to modify this file to turn off `nodelifecycle controller` . 2) If `kube-controller-manager` is not deployed through a static file: Modify `kube-controller-manager` template directly.
*And this scheme has the following problems:*
If the kube-controller-manager is not deployed through a static file (/etc/kubernetes/manifests/), modify `kube-controller-manager` template directly will lead to the runtime template is inconsistent with the user's local yaml file.

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind bug

**Comment by Peeknut** [comment]
If there are better solutions or suggestions, comments are welcome :)

**Comment by rambohe-ch** [comment]
@Peeknut Thank you filing issue.
We also need to add some tutorial document to introduce how to modify `kube-controller-manager` setting manually by user.
