### ISSUE TITLE
[yurt tunnel]welcome add unit testcases for yurt-tunnel components.

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#416]
**What would you like to be added**:
To add unit test cases for yurt-tunnel is a good way to understand specified components.
welcome to add test case for any small or big functions.

**Why is this needed**:
improve the reliability of yurt-tunnel.

**others**
/kind feature

**Comment by YRXING** [comment]
I am studying the yurt tunnel source code. I will write some test cases.

**Comment by rambohe-ch** [comment]
> I am studying the yurt tunnel source code. I will write some test cases.

@YRXING Very appreciate for your positivity. If you have any questions, we can discuss here or at the slack.
