### ISSUE TITLE
[refactor]extract the certificate manager of yurthub and yurt-tunnel as util functions.

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#419]
**What would you like to be added**:
Both yurthub and yurt-tunnel have certificate manager, we can unify the certificate manager as util functions.

**Why is this needed**:
reduce the complexity of OpenYurt project.

**others**
/kind feature

**Comment by ke-jobs** [comment]
I would like to take over this.

**Comment by Congrool** [comment]
I'd like take over it.
/assign
