### ISSUE TITLE
[yurthub]improve list/watch node pool resource in serviceTopology filter.

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#421]
**What would you like to be added**:
Improve list/watch node pool resource, only list/watch the node pool instance which the edge node belongs to.

**Why is this needed**:
In order to reduce the network traffic between cloud and edge.

**others**
/kind feature

**Comment by neo502721** [comment]
hi@rambohe-ch, I am trying add TweakListOptions to the Openyurt SharedInformer. But the LabelSelector confulse me. Is the edge nodepool's lable is "default-edge-nodepool=true"?

**Comment by rambohe-ch** [comment]
> hi@rambohe-ch, I am trying add TweakListOptions to the Openyurt SharedInformer. But the LabelSelector confulse me. Is the edge nodepool's lable is "default-edge-nodepool=true"?

@neo502721 you can get nodePool name from node labels "apps.openyurt.io/nodepool", and you can reference the code here: https://github.com/openyurtio/openyurt/blob/master/pkg/yurthub/filter/servicetopology/handler.go#L167

and you need to add TweakListOptions to the NodePool SharedInformer after node has synced.

**Comment by rambohe-ch** [comment]
> hi@rambohe-ch, I am trying add TweakListOptions to the Openyurt SharedInformer. But the LabelSelector confulse me. Is the edge nodepool's lable is "default-edge-nodepool=true"?

@neo502721 How about define the new parameter name of yurthub is `--nodepool-name`?

**Comment by neo502721** [comment]
> > hi@rambohe-ch, I am trying add TweakListOptions to the Openyurt SharedInformer. But the LabelSelector confulse me. Is the edge nodepool's lable is "default-edge-nodepool=true"?
> 
> @neo502721 How about define the new parameter name of yurthub is `--nodepool-name`?

Do you means add a new parameter named `nodepool-name` to yurthub  in the convert process?

**Comment by rambohe-ch** [comment]
> > > hi@rambohe-ch, I am trying add TweakListOptions to the Openyurt SharedInformer. But the LabelSelector confulse me. Is the edge nodepool's lable is "default-edge-nodepool=true"?
> > 
> > 
> > @neo502721 How about define the new parameter name of yurthub is `--nodepool-name`?
> 
> Do you means add a new parameter named `nodepool-name` to yurthub in the convert process?

Only add `nodepool-name` parameter for yurthub and optimize nodepool list/watch in serviceTopology in yurthub. 
I think that we can keep the yurtctl without modification.

**Comment by rambohe-ch** [comment]
> hi@rambohe-ch, I am trying add TweakListOptions to the Openyurt SharedInformer. But the LabelSelector confulse me. Is the edge nodepool's lable is "default-edge-nodepool=true"?

@neo502721 LabelSelector can be set as `--labelSelector=metadata.name={nodePool-name}` and you can get nodePoolName from yurthub startup parameter.
