### ISSUE TITLE
[yurtctl] Disable the nodelifecycle-controller if kube-controller-manager deployed in other ways except static pod

### ISSUE THREAD

**Issue by Peeknut** [openyurtio/openyurt#424]
**Background:**
OpenYurt uses the `nodelifecycle-controller` in `yurt-app-manager ` to replace it in `kube-controller-manager` to manage the node life cycle to achieve edge autonomy. Therefore, we need to close the `nodelifecycle-controller` in kube-controller-manager.

**What would you like to be added**:
When kube-controller-manager is not deployed as a static pod, `yurtctl convert/revert` can automatically close the nodelifecycle controller in kube-controller-manger. So OpenYurt cluster created by yurtctl can run normally and support the high availability of `kube-controller-manager`.

**Why is this needed**:
Currently yurtctl only supports automatic shutdown of the `nodelifecycle-controller` if kube-controller-manager is deployed as a static pod. If the user deploys in other ways, yurtctl cannot automatically close the nodelifecycle controller.

**others**
/kind enhancement

**Comment by eightzero** [comment]
Is that wrong? 

> When kube-controller-manager is not deployed as a static pod

**Comment by Peeknut** [comment]
Do you mean that the kube-controller-manager will not be deployed in other ways?

**Comment by eightzero** [comment]
yeah, I don’t know what other ways mean :laughing:

**Comment by Peeknut** [comment]
Since kcm runs as a pod, its deployment method is the same as that of a normal Pod. For example, it can be run directly with `kubectl apply pod.yaml`. Of course, this is rare.

In addition, we may need to consider the high availability of kcm. Because the conversion(yurtctl convert/revert) will only run once, only the nodelife-controller of the leader at the time of conversion will be modified. When the leader is changed, its kube-controller-manager.yaml file remains unchanged, that is, the nodelife-controller is not closed.

**Comment by eightzero** [comment]
may I have a try

**Comment by Peeknut** [comment]
Yes, of course.

**Comment by eightzero** [comment]
Do you have some suggestions about how to patch a normal pod with golang

**Comment by Peeknut** [comment]
If you have the clientSet(*kubernetes.Clientset), just use `clientSet.CoreV1().Pods("kube-system").Patch()` to patch pod.
And you can refer to using `kubeutil.GenClientSet`(`openyurt/pkg/yurtctl/util/kubernetes/util.go`)  to generate `clientSet`  in yurtctl.

**Comment by eightzero** [comment]
Does this meet your expectations?

```
// 4. disable node-controller
	ok, _ := enutil.FileExists(co.PodMainfestPath + "/kube-controller-manager.yaml")
	if ok {
		// static pod
		if err = kubeutil.RunServantJobs(co.clientSet, func(nodeName string) (*batchv1.Job, error) {
			ctx := map[string]string{
				"node_servant_image": co.NodeServantImage,
				"pod_manifest_path":  co.PodMainfestPath,
			}
			return kubeutil.RenderServantJob("disable", ctx, nodeName)
		}, kcmNodeNames); err != nil {
			return fmt.Errorf("fail to run DisableNodeControllerJobs: %s", err)
		}
	} else {
		// normal pod
		patchFmt := `{"spec":{"containers":[{"command":["--controllers=-nodelifecycle,*,bootstrapsigner,tokencleaner"]}]}}`
		podList, err := kubeutil.FilterPodWithSubStr(co.clientSet, "kube-controller-manager")
		if err != nil {
			klog.Error("get normal kube-controller-manager pod fail")
		}
		for _, pod := range podList.Items {
			co.clientSet.CoreV1().Pods("kube-system").Patch(context.TODO(), pod.Name, types.StrategicMergePatchType, []byte(patchFmt), metav1.PatchOptions{})
		}
	}
```

**Comment by Peeknut** [comment]
yurtctl is a binary which can be executed on non-master nodes, the following method may not be very appropriate to distinguish static pods from normal pods.

> ok, _ := enutil.FileExists(co.PodMainfestPath + "/kube-controller-manager.yaml")

**Comment by Peeknut** [comment]
How about submitting a pr so that others can review it?
