### ISSUE TITLE
[Feature] Introduces one basic implementation of an OpenYurt Operator

### ISSUE THREAD

**Issue by SataQiu** [openyurtio/openyurt#427]
**What happened**:
Recently, I implemented a basic OpenYurt Operator https://github.com/SataQiu/openyurt-operator
It satisfies most of our previous proposal https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20210722-yurtcluster-operator.md, but some things are not quite the same. 

The CRD defined in: https://github.com/SataQiu/openyurt-operator/blob/master/api/v1alpha1/yurtcluster_types.go

Currently, its main functions include：
- Deploy yurt components including yurt-controller-manager, yurt-app-manager, yurt-tunnel and yurthub
- Adjust the number of tunnel-server Pod and boot args to ensure all the kube-apiserver node has a tunnel server Pod
- Convert a node to an edge node based on the node label `openyurt.io/is-edge-worker=true`
- Revert a node to a normal node based on the node label `openyurt.io/is-edge-worker=false`
- Deploy node-local-dns to provide local DNS resolution

Next to do:
- Support upgrade operations
- Handle configuration of logging and monitoring components
- Something else to do

**What you expected to happen**:
Can we take it as a reference implementation and further refine it to implement the final OpenYurt Operator?
Can we bring it to the OpenYurt community?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by SataQiu** [comment]
Ref: #328

**Comment by gnunu** [comment]
so amazing to know that an implementation rolled out so quickly! 
@SataQiu,
as @rambohe-ch suggested in DingTalk group, I think it's good to merge the code to Openyurt repo, how do you think?
