### ISSUE TITLE
[BUG]yurtctl convert command line option --yurt-app-manager-image not in effect

### ISSUE THREAD

**Issue by zf930530** [openyurtio/openyurt#428]
yurtctl convert --enable-app-manager --yurt-app-manager-image xxxxxx
yurtctl convert command line option --yurt-app-manager-image not in effect.
Line 654 and line 666 in pkg/yurtctl/constants/yurt-app-manager-tmpl.go is not defined as template variable.
**others**

/kind bug

**Comment by rambohe-ch** [comment]
@zf930530 Thank you for filing issue.
Would you like to take over to solve this bug?

**Comment by rambohe-ch** [comment]
@yanyhui Do you have any comments?
