### ISSUE TITLE
[Vote] About the naming of UnitedDaemonset

### ISSUE THREAD

**Issue by kadisi** [openyurtio/openyurt#433]
**What happened**:

Recently we are working on a proposal for UnitedDaemonset ,however, the naming of UnitedDaemonset maybe lead to some misunderstandings ( ref #422 ).  So we need to revisit this naming problem。

**What you expected to happen**:

Here are two names for your vote：

- UnitedDaemonset
   UnitedDaemonset follows the previous definition of UnitedDeployment。

- NodePoolDaemonset
   NodePoolDaemonset focuses more on the node pool concept

Welcome to vote！！！

**others**
/kind question

**Comment by huangyuqi** [comment]
UnitedDaemonset +1

**Comment by rambohe-ch** [comment]
@kadisi I think that other names are welcome.

**Comment by zzguang** [comment]
Echo to @Fei-Guo to define the names from the app level, which seems to be a higher level abstraction.
What's more, it makes the native service template support becomes to be more reasonable than before.
To cover the close relationship between the app and the nodepool, I recommend another candidate for your reference:
    UnitedDeployment -> NodePoolAppSet
    UnitedDaemonSet -> NodePoolAppDaemon

**Comment by rambohe-ch** [comment]
@Fei-Guo @zzguang In my opinion, compared with `YurtAppSet` and `YurtAppDaemon`, `NodePoolAppSet` and `NodePoolAppDaemon` are more likely to accept by end users.
so `NodePoolAppSet` and `NodePoolAppDaemon` +1

**Comment by kadisi** [comment]
UnitedDaemonset

**Comment by kadisi** [comment]
UnitedDaemonset
UnitedDeployment

or

UnitedDeployment->NodePoolDeployment
UnitedDaemonset->NodePoolDaemonset

or

UnitedDeployment-> YurtPlacement
UnitedDaemonSet-> YurtDaemon

or

UnitedDeployment-> YurtAppSet
UnitedDaemonSet-> YurtAppDaemon

or

UnitedDeployment -> NodePoolAppSet
UnitedDaemonSet -> NodePoolAppDaemon

**Comment by kadisi** [comment]
After community discussion, we finally decided to name `UnitedDaemonset` to `YurtAppDaemon`.
In the future we will name `UnitedDeployment` to `YurtAppSet`.

UnitedDeployment -> YurtAppSet
UnitedDaemonSet -> YurtAppDaemon

If the community students have new ideas, welcome to participate in the discussion。

**Comment by zzguang** [comment]
By my understanding, the scope of YurtAppDaemon is bigger than NodePoolAppDaemon, not sure whether the assumption below makes sense:
We know that not all the edge nodes are definitely located in a nodepool,  if yurt-app-manager will extend its scope to handle app disposal to these scattered edge nodes in future, the corresponding component may be named as "NodeAppDaemon", and current "NodePoolAppDaemon" can leave some space for it. 
Otherwise, If yurt-app-manager will focus on nodepool all the way, "YurtAppDaemon" seems to be the better choice.

**Comment by rambohe-ch** [comment]
> By my understanding, the scope of YurtAppDaemon is bigger than NodePoolAppDaemon, not sure whether the assumption below makes sense:
> We know that not all the edge nodes are definitely located in a nodepool, if yurt-app-manager will extend its scope to handle app disposal to these scattered edge nodes in future, the corresponding component may be named as "NodeAppDaemon", and current "NodePoolAppDaemon" can leave some space for it.
> Otherwise, If yurt-app-manager will focus on nodepool all the way, "YurtAppDaemon" seems to be the better choice.

In openyurt cluster，nodes(include edge nodes and cloud nodes) must be belong to one NodePool, if no NodePool is specified, default NodePool will be used.

**Comment by kadisi** [comment]
> In openyurt cluster，nodes(include edge nodes and cloud nodes) must be belong to one NodePool, if no NodePool is specified, default NodePool will be used.


@zzguang @rambohe-ch  So this needs to be reinterpreted,It is recommended that users place nodes in the same region in the same node pool and that all nodes have their own node pool. It's easy to manage。  But this is not a constraint。
