### ISSUE TITLE
[Question] Can multi edge nodes in same region share one tunnel agent?

### ISSUE THREAD

**Issue by tiezhuoyu** [openyurtio/openyurt#436]
/kind question

Hi, I found a document 'https://blog.csdn.net/yunqiinsight/article/details/109637353' about tunnel tech of openyurt.
![图片](https://user-images.githubusercontent.com/25275281/130979941-90a22ebe-4d9e-426b-bf00-fbe8bb5a5b30.png)
Does it mean that several edge nodes in the same region share one tunnel agent, and we do not need to execute a tunnel agent for each edge node?  If so, is there any tutorial to show how to configure tunnel agent or kubelet? Thank you.

**Comment by Baoqiang-Zhang** [comment]
Good question, I'm also looking for this feature.
