### ISSUE TITLE
[Question] Are all messages transmitted through the tunnel?  

### ISSUE THREAD

**Issue by tiezhuoyu** [openyurtio/openyurt#439]
/kind question
Are all messages transmitted through the unnel?  Or just part of them such as logs and exec message? Thank you.

**Comment by rambohe-ch** [comment]
@tiezhuoyu Thank you for filing issue.
The traffic from [cloud node](https://github.com/openyurtio/openyurt/blob/master/docs/proposals/00_openyurt-glossary.md#cloudnode) to edge nodes will be transmitted through yurt-tunnel.  for example, the traffic for `kubectl logs/exec/port-forward` or `metrics-server/prometheus` collect metrics of edge nodes.

**Comment by tiezhuoyu** [comment]
> @tiezhuoyu Thank you for filing issue.
> The traffic from [cloud node](https://github.com/openyurtio/openyurt/blob/master/docs/proposals/00_openyurt-glossary.md#cloudnode) to edge nodes will be transmitted through yurt-tunnel. for example, the traffic for `kubectl logs/exec/port-forward` or `metrics-server/prometheus` collect metrics of edge nodes.

i got it, thanks!
