### ISSUE TITLE
[BUG]Yurthub return tunnel-server-service endpoint to kube-proxy on edge node

### ISSUE THREAD

**Issue by zf930530** [openyurtio/openyurt#447]
**What happened**:
Config x-tunnel-server-service as a LoadBalancer service, then edge node start the kube-proxy service with option --master=http://127.0.0.1:10261. Yurthub return endpoints of x-tunnel-server-service to kube-proxy, and kube-proxy write endpoints info to ipvs.The tunnel-agent cannot communicate with the tunnel-server because of the DNAT of the ipvs rule.
**What you expected to happen**:
Yurthub should not return information about tunnel-server-service to kube-proxy, so that the tunnel-agent of the edge node can communicate through the EXTERNAL-IP(LoadBalancer IP) of the tunnel-server-service.

**How to reproduce it (as minimally and precisely as possible)**:
Service x-tunnel-server-svc set as a LoadBalancer service.
Kube-proxy on edge node start in ipvs model and config master=localyurthub.
Excute command "ipvsadm -Ln | grep LoadBalancerIP -5" on edge node,check that the EXTERNAL-IP of the x-tunnel-server-svc has been configed by kube-proxy.
Tunnel-agent cloud not connect to tunnel-server via x-tunnel-server-svc EXTERNAL-IP because that traffic accessing the EXTERNAL-IP is DNATted to an intranet endpoint that is not accessible by the network.

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:v0.4.1
- Kubernetes version (use `kubectl version`):v1.16.9

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@zf930530 Thank you for filing issue.
we have made a pull request to solve this problem. and you may dive deeper into the solution here: https://github.com/openyurtio/openyurt/pull/440

**Comment by zf930530** [comment]
> @zf930530 Thank you for filing issue.
> we have made a pull request to solve this problem. and you may dive deeper into the solution here: #440

Also find error log in yurthub like: 
pkg/yurthub/filter/masterservice/handler.go:105
I0902 15:31:47.866823 49140 serializer.go:199] schema.GroupVersionResource{Group:"apps.openyurt.io", Version:"v1alpha1", Resource:"nodepools"} is not found in client-go runtime scheme
Looks that an error occured when decoding nodepool type into run-time type.

**Comment by rambohe-ch** [comment]
> > @zf930530 Thank you for filing issue.
> > we have made a pull request to solve this problem. and you may dive deeper into the solution here: #440
> 
> Also find error log in yurthub like:
> pkg/yurthub/filter/masterservice/handler.go:105
> I0902 15:31:47.866823 49140 serializer.go:199] schema.GroupVersionResource{Group:"apps.openyurt.io", Version:"v1alpha1", Resource:"nodepools"} is not found in client-go runtime scheme
> Looks that an error occured when decoding nodepool type into run-time type.

@zf930530 `MasterService` filter can only handle service resource that list/watch by kubelet, you can dive deeper into the code here: https://github.com/openyurtio/openyurt/blob/master/pkg/yurthub/filter/masterservice/filter.go#L45

So i can not confirm that the above error can happen on yurthub, Would you can provide the detailed yurthub version info?

**Comment by zf930530** [comment]
> > > @zf930530 Thank you for filing issue.
> > > we have made a pull request to solve this problem. and you may dive deeper into the solution here: #440
> > 
> > 
> > Also find error log in yurthub like:
> > pkg/yurthub/filter/masterservice/handler.go:105
> > I0902 15:31:47.866823 49140 serializer.go:199] schema.GroupVersionResource{Group:"apps.openyurt.io", Version:"v1alpha1", Resource:"nodepools"} is not found in client-go runtime scheme
> > Looks that an error occured when decoding nodepool type into run-time type.
> 
> @zf930530 `MasterService` filter can only handle service resource that list/watch by kubelet, you can dive deeper into the code here: https://github.com/openyurtio/openyurt/blob/master/pkg/yurthub/filter/masterservice/filter.go#L45
> 
> So i can not confirm that the above error can happen on yurthub, Would you can provide the detailed yurthub version info?

After adding the watch, get and list permissions to system:node for noodpools, this error appears in the log.
yurt version is v0.4.1

**Comment by rambohe-ch** [comment]
> > > > @zf930530 Thank you for filing issue.
> > > > we have made a pull request to solve this problem. and you may dive deeper into the solution here: #440
> > > 
> > > 
> > > Also find error log in yurthub like:
> > > pkg/yurthub/filter/masterservice/handler.go:105
> > > I0902 15:31:47.866823 49140 serializer.go:199] schema.GroupVersionResource{Group:"apps.openyurt.io", Version:"v1alpha1", Resource:"nodepools"} is not found in client-go runtime scheme
> > > Looks that an error occured when decoding nodepool type into run-time type.
> > 
> > 
> > @zf930530 `MasterService` filter can only handle service resource that list/watch by kubelet, you can dive deeper into the code here: https://github.com/openyurtio/openyurt/blob/master/pkg/yurthub/filter/masterservice/filter.go#L45
> > So i can not confirm that the above error can happen on yurthub, Would you can provide the detailed yurthub version info?
> 
> After adding the watch, get and list permissions to system:node for noodpools, this error appears in the log.
> yurt version is v0.4.1

@zf930530 NodePool list/watch rbac rights are missed for yurthub, you need add the rbac rights to group `system:nodes` manually to solve the problem.

**Comment by rambohe-ch** [comment]
@zf930530 OpenYurt v0.5.0 has been released, and pods on edge nodes can access kube-apiserver through yurthub defaultly.

so we will close this issue.
