### ISSUE TITLE
[Question] Should  Yurthub also be deployed  on the cloud side?

### ISSUE THREAD

**Issue by DrmagicE** [openyurtio/openyurt#450]
The data-filtering framework is implemented by Yurthub. The cloud side also needs this feature in order to learn the ”service topology“ to keep service traffic in-bound within the cloud-side.

For example,  the endpoints of the CoreDNS service on the cloud side must be filtered, so the pods on the cloud side can access the DNS service correctly.

/kind question

**Comment by rambohe-ch** [comment]
@DrmagicE Thank you for filing issue.
I agree with you that yurthub should also be deployed on the cloud nodes. 
Would you like to take over this work and fix it?

**Comment by DrmagicE** [comment]
@rambohe-ch No problem. I will fix it.

**Comment by DrmagicE** [comment]
Since the answer is clear now and the related feature has been implemented in https://github.com/openyurtio/openyurt/pull/483 .
I think we can close this issue.
