### ISSUE TITLE
Eliminate dependency on k8s.io/kubernetes

### ISSUE THREAD

**Issue by SataQiu** [openyurtio/openyurt#453]
https://github.com/kubernetes/kubernetes#to-start-using-k8s

> Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries is not supported.

Relying directly on `k8s.io/kubernetes` didn't seem like a good idea, which made our project difficult to upgrade and maintain. I propose that eliminate dependency on `k8s.io/kubernetes`. 

This is likely to be a long-term task.

**Comment by rambohe-ch** [comment]
@SataQiu Thank you for filing issue.
It's a good idea to cleanup dependency on `k8s.io/kubernetes` in openyurt. and would you like to take over this work?

**Comment by SataQiu** [comment]
@rambohe-ch 
I'd like to help with this.  
It seems a big job, and more contributors are welcome!
/kind good-first-issue

**Comment by rambohe-ch** [comment]
> @rambohe-ch
> I'd like to help with this.
> It seems a big job, and more contributors are welcome!
> /kind good-first-issue

@SataQiu It seems that `yurt-controller-manager`, `yurtctl`, `yurt-tunnel` have imported `k8s.io/kubernetes`, we can cleanup the dependency from `yurt-tunnel` --> `yurtctl` --> `yurt-controller-manager`.

**Comment by rambohe-ch** [comment]
This issue is divided into issue #548 #549 #550 #551 , so this issue can be closed now.
