### ISSUE TITLE
[feature request] Create STATIC_POD_PATH dir if not exists

### ISSUE THREAD

**Issue by adamzhoul** [openyurtio/openyurt#460]
**What would you like to be added**:
     
   When deploying yurtHub during RunConvertEdgeNode(), programs return when PodMainfestPath dir not exists.

https://github.com/openyurtio/openyurt/blob/47a88eab0a1450c90901e8c42c3ec88099602aea/pkg/yurtctl/cmd/convert/edgenode.go#L251

https://github.com/openyurtio/openyurt/blob/47a88eab0a1450c90901e8c42c3ec88099602aea/pkg/yurtctl/cmd/convert/edgenode.go#L338

   What if we create that dir?

**Why is this needed**:

   the static path may not always be created during installing ( yurtctl join not create that dir when i execute )
   we don't know how users add the edge node in the first place.

   1. exits always leads to bad expirence
   2. dir missing is not a big deal if the user makes sure that's the right path.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@adamzhoul Because `PodManifestPath` will be used by kubelet component, so i think that `PodManifestPath` should be managed by `kubelet` instead of yurtctl. if yurtctl create new dir for `PodManifestPath` that kubelet does not use it, the new manifest dir can not work for static pod.

by the way, @Peeknut Do you have any comments for this feature request?

**Comment by adamzhoul** [comment]
@rambohe-ch  yes you are right, it's should not be yurtctl's responsbility.

But, what to do with the bad experience ?  well, I encountered this.

follow the logic,  yurtctl should get static path from kubelet config  instead of --params.

1. if the user passes the right dir. but dir does not exist, they have to create it themself, and they will.
2. if the user passes the wrong dir.  
    2.1 if the dir exists. yurtctl success, but kubelet does nothing. the user feels the program doesn't work but has no error log.    
    2.2 if the dir does not exist.  yurtctl exists with an error log. everyone happy.

besides, who is responsible for dir creation? kubelet ? kubeadm ?

**Comment by Peeknut** [comment]
Yes, maybe yurtctl get static path from kubelet config is better. As different nodes maybe has different kubelet staticPodPath, this cannot be handled by passing in parameters.
And after yurtctl get the staticPodPath, it can be created if it does not exist.

**Comment by Peeknut** [comment]
By the way, would you want to take over this issue and fix it?

**Comment by adamzhoul** [comment]
> By the way, would you want to take over this issue and fix it?

sure.
