### ISSUE TITLE
[Question] Develop Guide Help

### ISSUE THREAD

**Issue by ghost** [openyurtio/openyurt#467]
What is the development testing process for openyurt? As a new developer, I'm not sure how I should test it quickly after I've modified the code for openyurt. Of course I can test by replacing the image in the openyurt cluster, but that's too slow. Does openyurt have scripts that similar to kubeedge [local-up-kubeedge.sh](https://github.com/kubeedge/kubeedge/blob/master/hack/local-up-kubeedge.sh) and [e2e](https://github.com/kubeedge/kubeedge/tree/master/tests/e2e) , and you can use the script to compile the entire openyurt to pull up a new cluster and do  test suits? And we can also use github action to run automated e2e tests to make sure that the code doesn't introduce other bug, [link](https://github.com/kubeedge/kubeedge/runs/3575044532?check_suite_focus=true).

**Comment by rambohe-ch** [comment]
@ke-jobs Thank you for raising this issue.
At present, OpenYurt has some [e2e test cases](https://github.com/openyurtio/openyurt/blob/master/test/e2e/e2e.go) but it's not enough, and have not integrated with github action. Would you have interested in taking over this problem and fix it?

**Comment by ke-jobs** [comment]
https://github.com/openyurtio/openyurt/issues/410

**Comment by ke-jobs** [comment]
I'm a new openyurt developer and I'm not familiar with openyurt yet. This work can be done later when I am familiar with it. Or by someone else who is already familiar with the project.

**Comment by Congrool** [comment]
I'd like to intergrate e2e tests with github action.

**Comment by rambohe-ch** [comment]
@Congrool Would you like to apply OpenYurt community member? you can add me as sponsor and here is an apply example: https://github.com/openyurtio/community/issues/25

**Comment by Congrool** [comment]
> @Congrool Would you like to apply OpenYurt community member? you can add me as sponsor and here is an apply example: [openyurtio/community#25](https://github.com/openyurtio/community/issues/25)

@rambohe-ch Thanks for your invitation.
I'd like to apply for the membership after finishing this work.

**Comment by rambohe-ch** [comment]
> > @Congrool Would you like to apply OpenYurt community member? you can add me as sponsor and here is an apply example: [openyurtio/community#25](https://github.com/openyurtio/community/issues/25)
> 
> @rambohe-ch Thanks for your invitation.
> I'd like to apply for the membership after finishing this work.

@Congrool ok, looking forward to completing this feature.

**Comment by Congrool** [comment]
The work is almost finished. Now we are waiting for #484 .
