### ISSUE TITLE
[feature request] Add command-line option for YurtHub to disable local cache and GC

### ISSUE THREAD

**Issue by DrmagicE** [openyurtio/openyurt#476]
**What would you like to be added**:
Add command-line option for YurtHub to disable local cache and GC. 

**Why is this needed**:
Base on this discussion https://github.com/openyurtio/openyurt/issues/450, the YurtHub should also be deployed on the cloud side. 
When deploying on the cloud side, caching apiserver response and the garbage collector is no longer needed, so we should provides an option to disable them.

There are some reasonable options here:
* --working-mode=cloud  or
* --disable-disk-cache=false
* ..

Any advice?

**others**
/kind feature

**Comment by zzguang** [comment]
In case that yurthub may extend other features for edge nodes in future, I think "--working-mode" is more reasonable.

**Comment by rambohe-ch** [comment]
@DrmagicE It's make sense to me that add a new parameter for yurthub to specify where yurthub is working, edge or cloud. 
--working-mode=cloud/edge (default value: edge) <-- agree +1

**Comment by rambohe-ch** [comment]
By the way, besides gc and cache feature, other features like `discardcloudservice` filter, some `request handler` of yurthub can also be disabled. so `--work-mode` mode maybe more reasonable.

**Comment by DrmagicE** [comment]
@rambohe-ch @zzguang Thanks for your advice. I think "--working-mode" is better. I will take over this issue.
