### ISSUE TITLE
[feature request]add hack script to check license header for newly created files.

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#478]
**What would you like to be added**:
1. add hack script to check newly created files that license header missed or not.
2. revise github actions to include this hack script.

**Why is this needed**:
Based on the hack script and github action, license header of newly created files in pull requests can be checked automatically and improve review efficiency.

**others**
/kind feature

**Comment by lonelyCZ** [comment]
@rambohe-ch 
Hi, I want to try to take this issue.

**Comment by rambohe-ch** [comment]
> @rambohe-ch
> Hi, I want to try to take this issue.

@lonelyCZ Very appreciate for taking over this feature.

/assign @lonelyCZ

**Comment by lonelyCZ** [comment]
@rambohe-ch 
There are not license header in following file. Do we need to add license header to them?
```
./pkg/controller/apis/config/types.go
./pkg/yurtctl/constants/yurt-app-manager-tmpl.go
./pkg/yurthub/healthchecker/node_lease_test.go
./pkg/yurthub/kubernetes/rest/config_test.go
./pkg/yurthub/network/dummyif_test.go
./pkg/yurthub/network/dummyif_unsupported.go

./hack/make-rules/build-e2e.sh
./hack/make-rules/generate_client.sh
./hack/make-rules/genyaml.sh
```

**Comment by rambohe-ch** [comment]
> @rambohe-ch
> There are not license header in following file. Do we need to add license header to them?
> 
> ```
> ./pkg/controller/apis/config/types.go
> ./pkg/yurtctl/constants/yurt-app-manager-tmpl.go
> ./pkg/yurthub/healthchecker/node_lease_test.go
> ./pkg/yurthub/kubernetes/rest/config_test.go
> ./pkg/yurthub/network/dummyif_test.go
> ./pkg/yurthub/network/dummyif_unsupported.go
> 
> ./hack/make-rules/build-e2e.sh
> ./hack/make-rules/generate_client.sh
> ./hack/make-rules/genyaml.sh
> ```

@lonelyCZ yes ,and you can make a new pull request to fix these files.
