### ISSUE TITLE
Openyurt is an Alibaba project or a CFCF Sandbox project ？

### ISSUE THREAD

**Issue by zilin00** [openyurtio/openyurt#480]
I personally remember openyurt as a CNCF Sandbox project, but it contains too many Alibaba elements, such as **3434 aliyun keywords**...

![image](https://user-images.githubusercontent.com/90911101/133785097-3315e438-372b-48b9-849a-32276bcc1c19.png)

**How could this be a CNCF Sandbox project? ? ?**

@caniszczyk @amye @lizrice @JustinCappos @dankohn @edsiper

**Comment by rambohe-ch** [comment]
> **How could this be a CNCF Sandbox project? ? ?**
> 
> @caniszczyk @amye @lizrice @JustinCappos @dankohn @edsiper

@zilin00 Thank you for raising issue, but i think it's just a kidding.

1. maybe you are not a golang developer,  `aliyun golang sdk` has been imported in OpenYurt, so you can get so many results by searching `aliyun` keyword in your local vendor directory(which are not in OpenYurt upstream project). btw: if you have interest, you can also search many other company names as keywords in OpenYurt.

2. we can search `aliyun` keywords in OpenYurt and get 37 results in three places including:
   - image repo at here(https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/yurtctl.md#1-failure-due-to-pulling-image-timeout): it's just easy to try OpenYurt for domestic user who can not get images from dockerhub(of course,  OpenYurt official images are hosted on dockerhub)
   - e2e testcase: just use aliyun as one sample environment
   - help docs
  
![image](https://user-images.githubusercontent.com/57081505/133791426-642c4cd3-755f-47a0-b931-2576be3839f2.png)

**Comment by liangyuanpeng** [comment]
I juse do the same thing in kubernetes,Amazing...

![image](https://user-images.githubusercontent.com/28711504/133802618-4eea845d-8138-415d-ba35-00bbfb4dfd91.png)

**Comment by zilin00** [comment]
Sorry, it is not helpful to start a war between your two families. I close the issues. However, Opwnyurt still needs to optimize this point, and try to minimize the elements of your own home.
