### ISSUE TITLE
[feature request] Add a script to startup openyurt cluster in single machine

### ISSUE THREAD

**Issue by ke-jobs** [openyurtio/openyurt#481]
**What would you like to be added**:
 Add a script to startup openyurt cluster in a single machine.

**Why is this needed**:
If we can startup openyurt on one machine (use kind or docker to simulate multiple nodes directly), we can quickly verify our code and do e2e tests.

**others**
/kind feature

**Comment by ke-jobs** [comment]
I would close this issue, if https://github.com/openyurtio/openyurt/issues/467 would complete this feature.

**Comment by rambohe-ch** [comment]
> I would close this issue, if #467 will complete this feature.

@ke-jobs ok, #467 will follow this feature, so we can close this issue.

**Comment by ke-jobs** [comment]
ok
