### ISSUE TITLE
[feature request] idempotent when execute yurtctl convert or yurtctl revert

### ISSUE THREAD

**Issue by adamzhoul** [openyurtio/openyurt#485]
**What would you like to be added**:

whenever we execute `yurtctl convert` or `yurtctl revert`
no matter how many times we execute (same command) 

it shall succeed, has no side effect.

**Why is this needed**:

 reduce user mind pressure when try and execute 
 try yurtctl with different params when last is wrong and failed, without execute `yurtctl revert` and delete failed k8s job manually.

**others**
/kind feature

for example:

     yurtctl-disable-node-controller  using sed, multiple execute leads to multiple `-nodelifecycle`
`nsenter -t 1 -m -u -n -i -- sed -i 's/--controllers=/--controllers=-nodelifecycle,/g' {{.pod_manifest_path}}/kube-controller-manager.yaml`

    manually delete k8s job when last is failed.

**Comment by rambohe-ch** [comment]
@adamzhoul Thank you for raising issue.

when user want to convert a native k8s cluster to OpenYurt, `yurtctl convert/revert` is not a cloud native solution. so another solution(add an yurtcluster operator) has been raised by @gnunu and @SataQiu .  you can reference the following issues and docs:

- https://github.com/openyurtio/openyurt/issues/328
- https://github.com/openyurtio/openyurt/issues/427
- https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20210722-yurtcluster-operator.md

and we are looking forward to `YurtCluster` operator ready.

**Comment by adamzhoul** [comment]
operator is certainly a better solution.
