### ISSUE TITLE
[BUG] redundant  code

### ISSUE THREAD

**Issue by adamzhoul** [openyurtio/openyurt#486]
https://github.com/openyurtio/openyurt/blob/797c43d730a11a6cd9bd491f3d3838917e2a49cb/pkg/yurtctl/cmd/convert/edgenode.go#L275

https://github.com/openyurtio/openyurt/blob/797c43d730a11a6cd9bd491f3d3838917e2a49cb/pkg/yurtctl/cmd/convert/edgenode.go#L282

![image](https://user-images.githubusercontent.com/7430439/134270682-d5ea05c2-81d9-469a-8eb3-4a264aca3cc5.png)

**Comment by rambohe-ch** [comment]
@adamzhoul  Thank you for raising issue.
At present, both `yurtctl convert` and `yurtctl revert` are recommended to use for experiencing OpenYurt. and would you be able to add a pull request to fix this duplicated code?

**Comment by adamzhoul** [comment]
sure
