### ISSUE TITLE
[Question] Why not check is-edge-worker==true

### ISSUE THREAD

**Issue by adamzhoul** [openyurtio/openyurt#488]
![image](https://user-images.githubusercontent.com/7430439/134278417-999c02b3-bf43-4282-a9d3-b0d82e218c7d.png)

https://github.com/openyurtio/openyurt/blob/797c43d730a11a6cd9bd491f3d3838917e2a49cb/pkg/yurtctl/cmd/convert/edgenode.go#L191

what if labed  "openyurt.io/is-edge-worker：true" ：
```

			v, ok := node.Labels[projectinfo.GetEdgeWorkerLabelKey()]
			if !ok {
				edgeNodeNames = append(edgeNodeNames, node.GetName())
			}else if v == "true“ {
                               	edgeNodeNames = append(edgeNodeNames, node.GetName())
                         }


```

similarity  question at：

https://github.com/openyurtio/openyurt/blob/797c43d730a11a6cd9bd491f3d3838917e2a49cb/pkg/yurtctl/cmd/convert/edgenode.go#L247

**Comment by rambohe-ch** [comment]
@Peeknut Do you have any comments?

**Comment by Peeknut** [comment]
I think if the node has the label  "openyurt.io/is-edge-worker：true", it doesn't need to do the convert, because it's already a yurt node.

**Comment by adamzhoul** [comment]
got it.
thanks
