### ISSUE TITLE
[feature request]  DeployYurthubSetting, not delete when revert

### ISSUE THREAD

**Issue by adamzhoul** [openyurtio/openyurt#489]
https://github.com/openyurtio/openyurt/blob/797c43d730a11a6cd9bd491f3d3838917e2a49cb/pkg/yurtctl/cmd/convert/convert.go#L382
`yurtctl convert `: run function DeployYurthubSetting , create `yurt-hub ClusterRole ClusterRoleBinding` 

Howevert, `yurtctl revert` won't delete them.

**Comment by rambohe-ch** [comment]
@adamzhoul I think it's a miss, and  welcome you to add `DeleteYurthubSetting` in `yurtctl revert`.

**Comment by adamzhoul** [comment]
ok
