### ISSUE TITLE
[feature request] tunnel agent supports proxy application requests from edge to cloud

### ISSUE THREAD

**Issue by SataQiu** [openyurtio/openyurt#497]
**What would you like to be added**:
Tunnel agent supports proxy application requests from edge to the cloud.

**Why is this needed**:
Currently, the openyurt tunnel component can only proxy the requests to access edge nodes from cloud nodes.
Applications on edge nodes can access cloud services only through public IP and port, and this increases the complexity of network configuration in edge computing scenarios. 
If the openyurt tunnel agent can proxy edge-to-cloud requests, it will greatly simplify the complexity of the data path between cloud and edge.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@SataQiu Thank you for raising this issue.
At present, yurt-tunnel is used to proxy monitor traffic for cloud-to-edge, I think this feature that will update yurt-tunnel ability. It's need to discuss this feature at OpenYurt community meeting, and get more feedback from community.

**Comment by SataQiu** [comment]
https://github.com/kubernetes-sigs/apiserver-network-proxy/issues/171
