### ISSUE TITLE
[feature request] Do we miss delete all resource for yurt-app-manager

### ISSUE THREAD

**Issue by adamzhoul** [openyurtio/openyurt#499]
see `DeployYurtAppManager` when `yurtctl convert`
https://github.com/openyurtio/openyurt/blob/c50a8d03158082fd6519f38e266107a9ea2904d9/pkg/yurtctl/util/kubernetes/apply_addons.go#L60

it does:

    1. create CRD:                                  nodepool uniteddeployment
    2. create Role:                                 yurt-app-leader-election-role
    3. create ClusterRole:                          yurt-app-manager-role
    4. create RoleBinding:                          yurt-app-leader-election-rolebinding
    5. create ClusterRoleBinding:                   yurt-app-manager-rolebinding
    6. create secret:                               yurt-app-webhook-certs
    7. create service:                              yurt-app-webhook-service
    8. create deployment:                           yurt-app-manager
    9. create MutatingWebhookConfiguration:         yurt-app-mutating-webhook-configuration
    10. create ValidatingWebhookConfiguration:      yurt-app-validating-webhook-configuration
 
but can't find any delete in `yurtctl revert`  

besides： 
https://github.com/openyurtio/openyurt/blob/c50a8d03158082fd6519f38e266107a9ea2904d9/pkg/yurtctl/cmd/revert/revert.go#L178 

    why not put remove `yurt-controller-manager` resource in a function in apply_addons.go 
    so deploy /delete can put together.
   

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@adamzhoul Thank you for raising issue.
In fact, @yanyhui has made a pull request for this feature: https://github.com/openyurtio/openyurt/pull/393, and some errors and comments have been not fixed.
