### ISSUE TITLE
[Question] Master node in internal network

### ISSUE THREAD

**Issue by tiezhuoyu** [openyurtio/openyurt#501]
**What happened**:
Hi, we want to deploy master node in an internal network where edge nodes cannot directly access master node. 

For example, master node ip w.x.y.z, gate way ip l.m.n.o, edge node ip a.b.c.d. Mapping w.x.y.z:6443 (apiserver port) to l.m.n.o:5555. Later, edge node a.b.c.d will execute with command join l.m.n.o:5555. 

![图片](https://user-images.githubusercontent.com/25275281/134796579-b0403a55-ad3c-4d7c-9c43-99cd13eda128.png)

What ports of openyurt componoent (such as port 10262, tunnel-server) need to be mapped?

Thanks!

**What you expected to happen**:
Openyurt components work properly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:v0.4.0
- Kubernetes version (use `kubectl version`):v1.18.2
- OS (e.g: `cat /etc/os-release`):Centos7.6 & Ubuntu20.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@tiezhuoyu Thank you for raising issue.

> 
> What ports of openyurt componoent (such as port 10262, tunnel-server) need to be mapped?
> 
The type of tunnel-server service `x-tunnel-server-svc` is NodePort, and the port is fixed as 31008(and you can modify as you want in service template), so you can map one port on gateway to {nodeIP:31008}.
