### ISSUE TITLE
[feature request] set job template imagePullPolicy to Always from IfNotPresent

### ISSUE THREAD

**Issue by adamzhoul** [openyurtio/openyurt#505]
**What would you like to be added**:

    imagePullPolicy: Always

now is:
https://github.com/openyurtio/openyurt/blob/095cc4c91d85e05f3dedcfa4ccb6ffd8a7305e93/pkg/yurtctl/constants/constants.go#L269

**Why is this needed**:

the default image is: 
       
     docker.io/openyurt/xxxx:latest

  IfNotPresent leads to never be updated while it should.

**Problem I meet**:

    crictl  images
    docker.io/openyurt/yurtctl-servant               latest               e1ec131fa6cc2       15.2MB

images left before. It’s not been build with the latest code. 
I can’t remember which day I run `yurtctl convert` and downloaded the image.
And it contains a bug but is fixed by https://github.com/openyurtio/openyurt/pull/490

In short：
 
 1. duplicated code  leads to bug :
 
 ```
2021-09-28T06:05:04.16277Z stderr F I0928 06:05:04.154963  198728 edgenode.go:263] mark openyurt-worker2 as the edge-node
2021-09-28T06:05:04.2673512Z stderr F I0928 06:05:04.266359  198728 edgenode.go:274] open the openyurt-worker2 autonomous
2021-09-28T06:05:04.3142398Z stderr F I0928 06:05:04.305542  198728 edgenode.go:281] open the openyurt-worker2 autonomous
2021-09-28T06:05:04.3908907Z stderr F F0928 06:05:04.379338  198728 edgenode.go:83] fail to convert the kubernetes node to a yurt node: Operation cannot be fulfilled on nodes "openyurt-worker2": the object has been modified; please apply your changes to the latest version and try again
```
2.  pod exists with error.  restart for ever with error

```
kubectl logs -f yurtctl-servant-convert-openyurt-worker2-x4fhp -n kube-system
F0928 06:44:12.296154  203920 edgenode.go:83] fail to convert the kubernetes node to a yurt node: Cannot do the convert, the worker node: openyurt-worker2 is not a Kubernetes node.
```

3.  convert job failed. leaves pod restart forever.

PS:  
locating the error log is very difficult since the job pod restarts many many times.
can we return true here?
https://github.com/openyurtio/openyurt/blob/095cc4c91d85e05f3dedcfa4ccb6ffd8a7305e93/pkg/yurtctl/cmd/convert/edgenode.go#L246-L250

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@adamzhoul Thank you for raising issue.
The reason of `imagePullPolicy=IfNotPresent` is: pods on edge nodes can restart successfully when edge nodes can not connect public network. If user wants to use latest images , it's recommended to pull images manually.

**Comment by adamzhoul** [comment]
@rambohe-ch  thanks for the reply.
