### ISSUE TITLE
[BUG]Avoid using different version of yurt-tunnel-agent and yurt-tunnel-server, when deploying with yurtctl

### ISSUE THREAD

**Issue by Congrool** [openyurtio/openyurt#511]
When deploying yurt-tunnel with yurtctl, we will set `imagePullPolicy: IfNotPresent` for [yurt-tunnel-agent](https://github.com/openyurtio/openyurt/blob/master/pkg/yurtctl/constants/yurt-tunnel-agent-tmpl.go#L49) and `imagePullPolicy: Always` for [yurt-tunnel-server](https://github.com/openyurtio/openyurt/blob/master/pkg/yurtctl/constants/yurt-tunnel-server-tmpl.go#201). It possibly makes users use local old version of yurt-tunnel-agent and the latest version of yurt-tunnel-server which may cause potential problems.  

I think it's better to set same `imagePullPolicy` for yurt-tunnel-agent and yurt-tunnel-server.

/kind bug

**Comment by rambohe-ch** [comment]
@Congrool Thank you for raising issue.
As i have replied in this issue: https://github.com/openyurtio/openyurt/issues/505, we need to set `imagePullPolicy` to `IfNotPresent` for yurt-tunnel-agent pod restart on edge nodes. and keep  `imagePullPolicy` of yurt-tunnel-agent as the same as yurt-tunnel-agent maybe make sense.  so i agree with this issue.
