### ISSUE TITLE
images should support multiarch

### ISSUE THREAD

**Issue by lwmqwer** [openyurtio/openyurt#521]
When I user yurtctl convert  cluster which has edgex node is arm64.
The kube-proxy is replace to registry.aliyuncs.com/k8sxio/kube-proxy:v1.18.10
And this is not multiarch support, the proxy is crash.

**Comment by rambohe-ch** [comment]
@lwmqwer Thank you for raising issue.
OpenYurt components support multiarch, and kube-proxy is k8s core component, maybe you need to find arm64 image from k8s community or other cloud providers(like registry.cn-hangzhou.aliyuncs.com/acs/kube-proxy:v1.18.8-aliyun.1)
