### ISSUE TITLE
[Question] How to proxy requests from cloud to pod (not hostNetwork) on edge?

### ISSUE THREAD

**Issue by tiezhuoyu** [openyurtio/openyurt#522]
**What happened**:
Hi, i want to know if it is possible to proxy requests from cloud to pods (not hostNetwork mod) on edge? I found issue [issue#138](https://github.com/openyurtio/openyurt/issues/138), but it works on hostNetwork mod. 

Thanks!

**What you expected to happen**:
For example, pod1(192.168.0.5) on cloud node, and pod2(192.168.4.5) on edge node.
If it is possible pod1 send reqeust like 'GET http://192.168.4.5:80' ?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: v0.5.0
- Kubernetes version (use `kubectl version`): v1.18.2
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: yurtctl init & yurtctl join
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@tiezhuoyu Thank you for raising this issue.
Proxy request from cloud to edge pods(not hostnetwork) is not supported at present as @DrmagicE has replied. and Would you be able to describe the detail scenario about this requirement?

**Comment by DrmagicE** [comment]
@rambohe-ch Yes, I'll try it.

**Comment by lujinda** [comment]
We are designing a solution that connects the edge and the edge, and the edge and the cloud network. The general idea is to use IPSec (or other) to connect to each data center, and then use IPSec to send the traffic of the Pod in one data center to other data centers. Plan to integrate with openyurt. The plan hopes that the intrusion to the Pod is small enough.

**Comment by rambohe-ch** [comment]
@tiezhuoyu Pods(not hostNetwork) connection across public network will be solved by [raven](https://github.com/openyurtio/raven),  also you can dive into the proposal: https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20211123-enhancement-of-cluster-networking.md

and we will close this issue, and you reopen or create a new issue if you have any other questions.

**Comment by tiezhuoyu** [comment]
@rambohe-ch that's a greate work 👍
