### ISSUE TITLE
[Discussion] Extend the capabilities of YurtTunnel to forward not only O&M and monitoring traffic from cloud to edge

### ISSUE THREAD

**Issue by DrmagicE** [openyurtio/openyurt#527]
The YurtTunnel was originally designed to deal with the challenges of O&M and monitoring traffic in edge scenarios. 
In this context, YurtTunnel can :
1. handle the traffic to kubelet (to port 10250) on edge nodes through the tunnel by default ; 
2. and handle the traffic to `hostNetwork` pod and `localhost` on edge nodes with a little configuration. 

By these two fundamental features, users can execute kubectl exec/logs to edge nodes and scrap metric from exporters on edge nodes, but it does not provide us a convenient way to forward other kinds of traffic from cloud to edge.

Although building a general purpose proxy may not be the goal of Yurttunnel, I am wondering if we can extend the capabilities of Yurttunnel to forward not only O&M and monitoring traffic. (see aslo https://github.com/openyurtio/openyurt/issues/522)

For example,  we can add more features to YurtTunnel to support these cases:
1. the cloud components can use service DNS to request services on edge nodes; 
2. and use PodIP to request pods on edge nodes.

Here are some rough designs:

For case 1, we can maintain a special zone in CoreDNS using `file` plugin, (for example: `.openyurt.tunnel`), all domains belong to the zone will have an A record that holds the yurttunnel server service IP.  The DNS name in this zone will follow such schema: `<service_name>.<namespace>.<nodepool_name>.openyurt.tunnel`. The components on the cloud side can use this schema to request specific services on specific nodepool.  With this method, the user can manage their services in the service topology way, which is provided by data-filtering framework, which means the user do not need to create additional unique service per nodepool.

For case 2, we can list watch all pods that do not belong to `podCIDR` of the cloud side,   and then add them to DNAT rule according to the `yurt-tunnel-server-cfg` configmap configuration.

Not sure if we should do this, I would like to hear your opinion. Welcome to discuss.

/kind design

**Comment by rambohe-ch** [comment]
@tiezhuoyu You have mentioned that proxy request from cloud to edge through yurt-tunnel in issue: https://github.com/openyurtio/openyurt/issues/522. Do you have any comments about these two features? and these features can satisfy your requirements?

**Comment by DrmagicE** [comment]
> @DrmagicE If we use iptables rule to solve the case2, then client pods(the pod sends request) need to work on the same node with yurt-tunnel-server pod.

Yes, and I believe this is a common issue in YurtTunnel DNAT mode. If the client is using IP to connect to the edge, it cannot take advantage of DNS.

**Comment by rambohe-ch** [comment]
> > @DrmagicE If we use iptables rule to solve the case2, then client pods(the pod sends request) need to work on the same node with yurt-tunnel-server pod.
> 
> Yes, and I believe this is a common issue in YurtTunnel DNAT mode. Unless we implement a controller (run as daemonset in every cloud node) to set the DNAT rule in every cloud node.

@DrmagicE Ok, I got it. maybe end user need to accept this constraint at the beginning.

**Comment by tiezhuoyu** [comment]
with pod IP, and the request as follow: 
![image](https://user-images.githubusercontent.com/25275281/138254340-2ef49e4e-f012-4cf9-9ff2-e693e520cd75.png)

**Comment by DrmagicE** [comment]
> @DrmagicE Very appreciate for improving yurt-tunnel. and would you be able to add some background information about these two features?

In edge scenario, the edge node may not be accessible through the public network. For example, the edge node is a laptop in your room, a traffic light on the road, etc. 
It is reasonable to have a central application which often deployed in the cloud and need to request the services on the edge, by service name or by pod IP.

If the YurtTunnel can satisfy this kind of requirement, the users will not need to find another solution.

**Comment by rambohe-ch** [comment]
A new edge network project named `Raven` has been launched in OpenYurt community. and the feature requests in this issue will be implemented in the new project.
