### ISSUE TITLE
[feature request]Remove k8s.io/kubernetes dependency for yurt-controller-manager

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#549]
**What would you like to be added**:
Yurt-controller-manager have imported k8s.io/kubernetes, you can search `k8s.io/kubernetes` in `cmd/yurt-controller-manager` and `pkg/controller` directory. and based on Issue #453, we need to remove k8s.io/kubernetes dependency.

**Why is this needed**:
From kubernetes introduction: https://github.com/kubernetes/kubernetes#to-start-using-k8s

> To use Kubernetes code as a library in other applications, see the list of published components. Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries is not supported.

**others**
/kind feature

**Comment by hzliangbin** [comment]
@rambohe-ch hi, what should I do is to  replace k8s.io/kubernetes with [dependencies listed here](https://github.com/kubernetes/kubernetes/blob/master/staging/README.md) .  right?

**Comment by rambohe-ch** [comment]
> @rambohe-ch hi, what should I do is to replace k8s.io/kubernetes with [dependencies listed here](https://github.com/kubernetes/kubernetes/blob/master/staging/README.md) . right?

@hzliangbin yes, we can use `k8s.io/kube-controller-manager` directly for `yurt-controller-manager`.

**Comment by rambohe-ch** [comment]
@hzliangbin Would you be able to update progress about this issue?

**Comment by hzliangbin** [comment]
> @hzliangbin Would you be able to update progress about this issue?

so sorry for being late, i will open a pr in a day or two.

**Comment by rambohe-ch** [comment]
> @rambohe-ch
> 
> so sorry for being late, i will open a pr in a day or two.

@hzliangbin Thanks for your feedback. 
I'am very sorry, other community member had taken over this issue and he will make a pull request today.  how about to review the pull request as reviewer?

**Comment by hzliangbin** [comment]
> > @rambohe-ch
> > so sorry for being late, i will open a pr in a day or two.
> 
> @hzliangbin Thanks for your feedback. I'am very sorry, other community member had taken over this issue and he will make a pull request today. how about to review the pull request as reviewer?

@rambohe-ch I'd love to, but I am a new bird to openyurt so I'm afraid that I can't give a hand.
