### ISSUE TITLE
[feature request]Remove k8s.io/kubernetes dependency for yurtctl

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#550]
**What would you like to be added**:
Yurtctl have imported k8s.io/kubernetes, you can search `k8s.io/kubernetes` in `pkg/yurtctl` directory. and based on Issue #453, we need to remove k8s.io/kubernetes dependency.

**Why is this needed**:
From kubernetes introduction: https://github.com/kubernetes/kubernetes#to-start-using-k8s

> To use Kubernetes code as a library in other applications, see the list of published components. Use of the k8s.io/kubernetes module or k8s.io/kubernetes/... packages as libraries is not supported.

**others**
/kind feature

**Comment by Peeknut** [comment]
`yurtctl join`, `yurtctl init` reuses a lot of code in `kubeadm`, and it takes a lot of work to delete dependencies directly and rewriting the code. How about download and use the kubeadm binary file directly in yurtctl?

**Comment by rambohe-ch** [comment]
> it takes a lot of work to delete dependencies directly and rewriting the code. How about download and use the kubeadm binary file directly in yurtctl?

@Peeknut It's a good idea to use kubeadm binary directly. agree +1

**Comment by villanel** [comment]
There are two parts to be replaced here,`kubelet`and`kubeadm`, I will try to use use the kubeadm binary file directly.

**Comment by villanel** [comment]
There are two parts to be replaced here,`kubelet` and `kubeadm`, I will try to use the kubeadm binary file directly.

**Comment by rambohe-ch** [comment]
> There are two parts to be replaced here,`kubelet` and `kubeadm`, I will try to use the kubeadm binary file directly.

@villanel Thank you for your reply. Do you have any progress of this enhancement? 
and we want to solve this feature in these days, then we can go ahead to update OpenYurt other dependencies.

**Comment by villanel** [comment]
@rambohe-ch Thank you for your help, I will finish this part as soon as possible.

**Comment by villanel** [comment]
@rambohe-ch It seems `kubeadm` binary file has many test cases and unused code, should we keep these?

**Comment by rambohe-ch** [comment]
> @rambohe-ch It seems `kubeadm` binary file has many test cases and unused code, should we keep these?

@villanel we can download `kubeadm` binary like download other components(eg: kubelet), and use the downloaded `kubeadm` binary by `cmd.exec`.
