### ISSUE TITLE
When yurtctl revert executes yurtappmanager to delete automatically, no crd resource error is reported.

### ISSUE THREAD

**Issue by yanyhui** [openyurtio/openyurt#557]
**What happened**:
If yurtappmanager is not deployed and yurtctl revert is executed, a notfound error will be reported when yurtappmanager is deleted.
**What you expected to happen**:

A not found error occurred
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@yanyhui Would you be able to take over and fix this bug?
