### ISSUE TITLE
[Question]Timeout when join the node into the openyurt cluster.

### ISSUE THREAD

**Issue by littletiger123** [openyurtio/openyurt#565]
**What happened**:
I am a new one to use openyurt. When I use **yurtctl**  to  install the openyurt cluster, I fail to join the node into the master.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Here is the command I used
```
./yurtctl join 192.168.100.204:6443 --token z5r7g5.mlfntm1tke1vrmwh     --discovery-token-ca-cert-hash sha256:7d565f0f1931b8db5106849abd55313b416bcf1c2be55e2aafdaa2d6fcd23bd2  --node-type=edge-node
```

Here is the log

```
W1109 23:22:19.558285   29375 join.go:213] [preflight] WARNING: JoinControlPane.controlPlane settings will be ignored when control-plane flag is not set.
Error: error execution phase initialize: couldn't validate the identity of the API Server: Get https://192.168.100.204:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

Also, the token is not expired. Here is the commnad and the output:

```
kubeadm token list
TOKEN                     TTL         EXPIRES                     USAGES                   DESCRIPTION                                                EXTRA GROUPS
z5r7g5.mlfntm1tke1vrmwh   13h         2021-11-10T22:56:29+08:00   authentication,signing   The default bootstrap token generated by 'kubeadm init'.   system:bootstrappers:kubeadm:default-node-token
```

There is the pod run in the master node :
```
kubectl get pod -A
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   controlplane-slave204                      4/4     Running   0          10h
kube-system   coredns-546565776c-mw2l9                   1/1     Running   0          10h
kube-system   coredns-546565776c-q89tx                   1/1     Running   0          10h
kube-system   kube-flannel-ds-55jl9                      1/1     Running   0          10h
kube-system   kube-proxy-xg78z                           1/1     Running   0          10h
kube-system   yurt-app-manager-75b7f76546-59799          1/1     Running   0          10h
kube-system   yurt-app-manager-75b7f76546-js5b5          1/1     Running   0          10h
kube-system   yurt-controller-manager-697877d548-fwq76   1/1     Running   0          10h
kube-system   yurt-tunnel-server-65db8dc68c-kscd2        1/1     Running   0          10h
```
Thanks a lot.

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@littletiger123 Thank you for raising issue.

@zyjhtangtang Would you be able to rely this issue?
/assign @zyjhtangtang

**Comment by zyjhtangtang** [comment]
You can execute this command on the edge node to test the network. `curl -k https://192.168.100.204:6443/healthz` @littletiger123

**Comment by littletiger123** [comment]
> You can execute this command on the edge node to test the network. `curl -k https://192.168.100.204:6443/healthz` @littletiger123

Hi，it may not work
```
curl -k https://192.168.100.204:6443/healthz
curl: (56) Proxy CONNECT aborted
```
I  used the command ` curl  -k https://192.168.100.204:6443/api/v1/namespaces/kube-public/configmaps/cluster-info?timeout=10s ` it worked on the master while not working on the edge. 
Also, I tried `telnet 192.168.100.204 6443` , it worked on the edge.

**Comment by littletiger123** [comment]
I have fixed the problem, thanks. Maybe we can improve the `yurtctl join` command to add the argument which is the path of the `kubernetes-node-linux-amd64.tar.gz`.

**Comment by rambohe-ch** [comment]
> I have fixed the problem, thanks. Maybe we can improve the `yurtctl join` command to add the argument which is the path of the `kubernetes-node-linux-amd64.tar.gz`.

@littletiger123 would you like to introduce the detail info about `yurtctl join` improvement?

**Comment by littletiger123** [comment]
> > I have fixed the problem, thanks. Maybe we can improve the `yurtctl join` command to add the argument which is the path of the `kubernetes-node-linux-amd64.tar.gz`.
> 
> @littletiger123 would you like to introduce the detail info about `yurtctl join` improvement?

I tried many times for the command. It always download `the kubernetes-node-linux-amd64.tar.gz`. Maybe we can download once and we can use the argument added for the local path of `the kubernetes-node-linux-amd64.tar.gz.`

**Comment by littletiger123** [comment]
> > I have fixed the problem, thanks. Maybe we can improve the `yurtctl join` command to add the argument which is the path of the `kubernetes-node-linux-amd64.tar.gz`.
> 
> @littletiger123 would you like to introduce the detail info about `yurtctl join` improvement?

I tried many times for the command. It always download the `kubernetes-node-linux-amd64.tar.gz`. Maybe we can download once and we can use the argument added for the local path of the `kubernetes-node-linux-amd64.tar.gz`.

**Comment by rambohe-ch** [comment]
> > > I have fixed the problem, thanks. Maybe we can improve the `yurtctl join` command to add the argument which is the path of the `kubernetes-node-linux-amd64.tar.gz`.
> > 
> > 
> > @littletiger123 would you like to introduce the detail info about `yurtctl join` improvement?
> 
> I tried many times for the command. It always download the `kubernetes-node-linux-amd64.tar.gz`. Maybe we can download once and we can use the argument added for the local path of the `kubernetes-node-linux-amd64.tar.gz`.

@littletiger123 Thanks for feedback. but how to verify local `kubernetes-node-linux-amd64.tar.gz` is the newest file?
