### ISSUE TITLE
[BUG] yurt revert forget clean job of yurtctl-servant-convert

### ISSUE THREAD

**Issue by hhstu** [openyurtio/openyurt#566]
**What happened**:

find  job of yurtctl-servant-convert exit after yurt revert 

```bash
[root@RJYF-T-210 ~]# kubectl  get  job    -n kube-system
NAME                                 COMPLETIONS   DURATION   AGE
yurtctl-servant-convert-rjyf-t-208   1/1           113s       33m

we will get an exit error when next convert   
####
fail to run servant job(yurtctl-servant-convert-rjyf-t-208): jobs.batch "yurtctl-servant-convert-rjyf-t-208" already exists

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by Peeknut** [comment]
Does convert job run successfully? If convert job run successfully, the job will be deleted.

**Comment by hhstu** [comment]
@Peeknut  I  have know what happend,  see this https://github.com/openyurtio/openyurt/issues/567#issue-1049444727 , timeout
