### ISSUE TITLE
[feature request]CheckServantJobPeriod may be too short

### ISSUE THREAD

**Issue by hhstu** [openyurtio/openyurt#567]
**What would you like to be added**:

default CheckServantJobPeriod = time.Second * 10 

my job Completed whis  2m15s, we can give a param of CheckServantJobPeriod when yurtctl convert
```bash
pod:

kube-system   yurtctl-servant-convert-rjyf-t-208-2dr7z    0/1     Completed   0          2m15s

err:

E1110 13:31:25.091769   20214 util.go:489] fail to run servant job(yurtctl-servant-convert-rjyf-t-208): wait for job to be complete timeout
```
**Why is this needed**:

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@hhstu Thank you for raising issue.
Timeout of servant job is defined by `WaitServantJobTimeout = time.Minute * 2` as 2 minutes. I think it's good idea to add a parameter to specify timeout for servant job, plus we can extended fixed 2 minutes to fixed 5 minutes.

@adamzhoul Do you have any comments?

**Comment by hhstu** [comment]
please let me do it if need

**Comment by rambohe-ch** [comment]
> please let me do it if need

@hhstu Thanks for your feedback. i will assign this issue to you. 
/assign @hhstu

**Comment by adamzhoul** [comment]
it's reasonable to add 
since pull images take time,  time is unpredictable

**Comment by adamzhoul** [comment]
the problem right now is when job timeout

1. job may succeed in fact, means everything has been done right to the node
2. node will node be labeled 
3. k8s job will not be deleted

so, if users want to fix it, they have to 
1. run `yurtctl reset`
2. manual delete job
3. run `yurtctl convert` again (this time image has already been pulled)
this is a bad experience.

so, if we add the params, 
this problem may still exist since users never realized to set that param at the beginning, and it's useless the second time
fixed to 5 minutes may be more helpful.
add params is useful for users who are familiar 

what do you say @hhstu  @rambohe-ch

**Comment by hhstu** [comment]
agree, more that  force  delete job can code in `yurtctl revert ` when users want to reset.  what do you say @adamzhoul 

For Chinese：

同意。另外 job timeout 后用户想要 reset，delete job这个动作可以编码到 `yurtctl revert ` 中而不是用户手动做，`yurtctl revert ` 应该是一个全部清理的操作

**Comment by adamzhoul** [comment]
agree

**Comment by rambohe-ch** [comment]
> the problem right now is when job timeout
> 
> 1. job may succeed in fact, means everything has been done right to the node
> 2. node will node be labeled
> 3. k8s job will not be deleted
> 
> so, if users want to fix it, they have to
> 
> 1. run `yurtctl reset`
> 2. manual delete job
> 3. run `yurtctl convert` again (this time image has already been pulled)
> 
> this is a bad experience.
> 
> so, if we add the params, this problem may still exist since users never realized to set that param at the beginning, and it's useless the second time fixed to 5 minutes may be more helpful. add params is useful for users who are familiar
> 
> what do you say @hhstu @rambohe-ch

@adamzhoul agree +1

@hhstu so optimization includes the following work:
1. WaitServantJobTimeout: 2m --> 5m
2. add a servant job timeout parameter  for `yurtctl convert`
3. `yurtctl revert` will remove the remained servant job forcely.
