### ISSUE TITLE
[feature request] Discard param system-architecture  of yurtctl  convert 

### ISSUE THREAD

**Issue by hhstu** [openyurtio/openyurt#571]
**What would you like to be added**:

Discard param system-architecture  of yurtctl  convert 

**Why is this needed**:

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@hhstu Thank you for raising issue.
Would you be able to collect the info where `system-architecture` is used, and if `system-architecture` is removed, is it going to affect those places?

**Comment by hhstu** [comment]
look at this pr:  https://github.com/openyurtio/openyurt/pull/435 just used by nodeSelector @rambohe-ch

**Comment by rambohe-ch** [comment]
> look at this pr: #435 just used by nodeSelector @rambohe-ch

@hhstu Thanks for your feedback, how about add the detail info about `system-architecture` in the issue message?
