### ISSUE TITLE
[Discussion] How about deprecating kubelet certificate management mode (Yurthub shares certificates with Kubelet) in future releases？

### ISSUE THREAD

**Issue by qclc** [openyurtio/openyurt#573]
**What would you like to be discussed**:

1. In future versions, yurthub and kubelet shared certificate mode will be removed and the related interface will be deprecated.
2. At the same time, in the process of using the current OpenYurt version, the system prompts the user that the certificate sharing with kubelet is no longer supported in the later version.

**Why is this needed**:
1. **Certificate rotation problem may occur when Yurthub shares certificates with Kubelet**：
When Yurthub shares a certificate with Kubelet, if the Kubelet certificate expires during the cloud-side disconnection, yurthub that shares the kubelet certificate will also not work. In this case, Kubelet cannot update the node certificate through Yurthub. For this reason, Yurthub proposes its own certificate management mode, `hubself` (The related PR is [here]( https://github.com/openyurtio/openyurt/pull/120)).

2. **In ordinary use, users are not aware of the option to share with kubelet certificates**:
At present, the default certificate mode of Yurthub is `hubself` mode, which is also the certificate management mode recommended by the community. From the perspective of users, when using yurtctl to convert Kubernetes cluster or nodes, adding nodes to OpenYurt cluster, the `hubself` certificate management mode is used default. Users are not aware of the kubelet sharing mode unless they manually deploy or change Yurthub.

Due to the above two main reasons, and in order to avoid users' confusion about these two modes, can we gradually stop the maintenance and support of the mode of Yurthub sharing kubelet certificate, and delete this mode in the future version?

**Comment by rambohe-ch** [comment]
@qclc Thank you for raising issue.
There are literally no users using `kubelet` mode, so i agree with you that remove `kubelet` certificate mode from yurthub.

**Comment by rambohe-ch** [comment]
@qclc would you can take over and remove kubelet mode from yurthub?

**Comment by qclc** [comment]
> @qclc would you can take over and remove kubelet mode from yurthub?

Yes, I am willing to take over and remove kubelet mode from yurthub.
