### ISSUE TITLE
[feature request]  deploy coredns daemonset  on every edge nodes if necessary

### ISSUE THREAD

**Issue by hhstu** [openyurtio/openyurt#584]
**What would you like to be added**:

**Why is this needed**:

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@hhstu Thank you for raising issue.
In fact, we are using DemonSet to deploy coredns on our production cluster. and we will update to use `YurtAppDaemon` to deploy coredns in later version. 

and about `YurtAppDaemon`, you can reference the following links:
- https://github.com/openyurtio/openyurt/blob/master/docs/enhancements/20210729-yurtappdaemon.md
- https://github.com/openyurtio/yurt-app-manager/pull/27
