### ISSUE TITLE
[Question] How to use the service topology function in openyurt ?

### ISSUE THREAD

**Issue by windydayc** [openyurtio/openyurt#590]
**What happened**:
I notice that the service topology function has already implemented [here](https://github.com/openyurtio/openyurt/blob/f5f0adf6c9fc1b71898af29c21ad2faaf37a0ece/pkg/yurthub/filter/servicetopology/handler.go#L34) , but it does not work when I tested the following operation. 

My test scenario is roughly as shown below (the cloud node is omitted),  I have added openyurt.io/topologyKeys='kubernetes.io/zone' annotation to the service svc-hostname. However, when I go into pod5 and execute "curl svc-hostname:80" several times, I still see the hostname output from pod1 to pod4. This annotation doesn't seem to work.

![image](https://user-images.githubusercontent.com/43909149/141755827-ecf01f3f-e9c8-42e2-92cb-0f3cca3284a8.png)

I don't see any documentation about service topology function in the OpenYurt repository. Maybe is there anything wrong with what I did above ?

**What you expected to happen**:
Because pod5 is in nodepool hangzhou, when I go into pod5 and execute "curl svc-hostname:80" several times, only pod1 and pod2 that reside in hangzhou nodepool should reply.

**How to reproduce it (as minimally and precisely as possible)**:
As the picture shown above.

**Anything else we need to know?**:
I have added the feature gates to enable the kubernetes  ServiceTopology feature.
I have tested [serviceTopology feature in the kubernetes native API](https://kubernetes.io/docs/concepts/services-networking/service-topology/#examples) and it works.

**Environment**:
- OpenYurt version: v0.5.0
- Kubernetes version (use `kubectl version`): v1.18.19, created by kind v0.11.1
- OS (e.g: `cat /etc/os-release`):  Ubuntu 21.04
- Kernel (e.g. `uname -a`): Linux kind-control-plane 5.11.0-40-generic # 44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**others**
/kind question

**Comment by windydayc** [comment]
@rambohe-ch

**Comment by DrmagicE** [comment]
@windydayc Hi, thanks for raising the issue.
To use the service topology, the `kube-proxy` needs to be configured to connect to Yurthub instead of the API server. 
If your `kube-proxy` configuration specifies a kubeconfig path,  you can comment the `kubeconfig` line then restart the `kube-proxy` and it should work.

For example: 
```
$ kubectl edit cm -n kube-system kube-proxy 
apiVersion: v1
data:
  config.conf: |-
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    bindAddress: 0.0.0.0
    featureGates: # enable EndpointSliceProxying feature gate.
      EndpointSliceProxying: true
    clientConnection:
      acceptContentTypes: ""
      burst: 0
      contentType: ""
      #kubeconfig: /var/lib/kube-proxy/kubeconfig.conf # <- comment this line.
      qps: 0
    clusterCIDR: 10.244.0.0/16
    configSyncPeriod: 0s
```

**Comment by windydayc** [comment]
@DrmagicE Thanks. I do what you said and it works. As for this serviceTopology function, I haven't seen any documents about this, do you mind if I add a document about this through a pr?

**Comment by rambohe-ch** [comment]
> @DrmagicE Thanks. I do what you said and it works. As for this service topology function, I haven't seen any documents in this repo, do you mind if I add a document about this through a pr?

@windydayc Very appreciate the idea that add document for service topology.

**Comment by windydayc** [comment]
@rambohe-ch  Thanks. 
/assign @windydayc

**Comment by rambohe-ch** [comment]
@windydayc In OpenYurt, service topology function is carried by `Data Filter Framework` in Yurthub component, so kube-proxy is needed to access kube-apiserver through yurthub in order to enable service topology function.

**Comment by windydayc** [comment]
> @windydayc In OpenYurt, service topology function is carried by `Data Filter Framework` in Yurthub component, so kube-proxy is needed to access kube-apiserver through yurthub in order to enable service topology function.

Well. Thank you. Next, I will try to learn more about Yurthub.

**Comment by rambohe-ch** [comment]
> > @windydayc In OpenYurt, service topology function is carried by `Data Filter Framework` in Yurthub component, so kube-proxy is needed to access kube-apiserver through yurthub in order to enable service topology function.
> 
> Well. Thank you. Next, I will try to learn more about Yurthub.

@windydayc I'd like to give some reference for diving info `Data Filter Framework`
- Proposal: https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20210720-data-filtering-framework.md
- Code: https://github.com/openyurtio/openyurt/tree/master/pkg/yurthub/filter

and three filters have been implemented in Yurthub: servicetopology, masterservice, discardcloudservice

**Comment by windydayc** [comment]
@rambohe-ch  Thank you so much. It's been very helpful. Thanks for the guidance.
