### ISSUE TITLE
[feature request] Add an option to "yurtctl join" to enable "node autonomy" automatically.

### ISSUE THREAD

**Issue by DrmagicE** [openyurtio/openyurt#597]
**What would you like to be added**:
Currently, if the user wants to enable node autonomy for a new node joined by `yurtctl join`. The user had to call `yurtctl markautonomous` after `yurtctl join`, which is inconvenient.

I think the whole process can be simplified by adding an option to `yurtctl join` to enable ”node autonomy“ automatically.

**Why is this needed**:

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@DrmagicE It's a good idea to add parameter for `yurtctl join` for marking autonomous. @zyjhtangtang Do you have any comments?

**Comment by zyjhtangtang** [comment]
Thanks @DrmagicE , I agree. Can you submit a PR to  add this parameter.

**Comment by DrmagicE** [comment]
@zyjhtangtang Hi, I would like to, but I am afraid I had to finish some jobs in hands (https://github.com/openyurtio/openyurt/issues/546 and https://github.com/openyurtio/openyurt/issues/527) before starting this one. 
@rambohe-ch How about we label this issue as a good-first issue?

**Comment by rambohe-ch** [comment]
> @zyjhtangtang Hi, I would like to, but I am afraid I had to finish some jobs in hands (#546 and #527) before starting this one. @rambohe-ch How about we label this issue as a good-first issue?

@DrmagicE done

**Comment by adamzhoul** [comment]
I am working on https://github.com/openyurtio/openyurt/issues/545 
I can pick up this by the way 

/assign @adamzhoul
