### ISSUE TITLE
[Question] What's the relation between pod and nodepool?

### ISSUE THREAD

**Issue by windydayc** [openyurtio/openyurt#618]
**What happened**:
I noticed that only pod1 created using unitedDeployment has the `apps.openyurt.io/pool-name` label. Pod2 I created just using `kubectl run` does not have this label. If pod2 is scheduled to node1, and suppose node1 belongs to beijing nodepool (node1 has the label `apps.openyurt.io/nodepool=beijing`), does that mean pod2 belongs to beijing nodepool?  Although pod2 does not have the `apps.openyurt.io/pool-name label`.

Does the nodepool to which a pod belongs have any relation with the pod's `apps.openyurt.io/pool-name` label ? Or does the nodepool of a pod depends only on the nodepool of its node? If the latter, what does the `apps.openyurt.io/pool-name` label do?

**others**
/kind question

**Comment by rambohe-ch** [comment]
@windydayc Thank you for raising issue. I think that pod should decouple with nodePool, and `apps.openyurt.io/pool-name` label function,  @kadisi Do you have any comments?

**Comment by kadisi** [comment]
@windydayc ,thanks for your issue, please view  proposal about nodepool, https://github.com/openyurtio/openyurt/pull/173

**Comment by windydayc** [comment]
> @windydayc ,thanks for your issue, please view proposal about nodepool, #173

I've seen this, but it doesn't say what the pod's label `apps.openyurt.io/pool-name` does.
