### ISSUE TITLE
[feature request]add `yurtctl precheck` command for reducing `yurtctl convert` failure.

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#619]
**What would you like to be added**:
Add a new command named `yurtctl precheck` for checking the K8s cluster can be converted to OpenYurt cluster or not. 
so users can run `yurtctl precheck` before `yurtctl convert` and verify the K8s cluster is ready for converting.

And the check items maybe include:
1. all nodes are ready or not
2. nodes have been converted to OpenYurt node
3. `kubeadm-conf-path` file exists on edge node or not
4. `kubadm.envs` file exists on edge node or not
5. `kube-apiserver` address can be resolved on edge node or not
6. and other items that need to check

**Why is this needed**:
Before run `yurtctl convert`, users execute `yurtctl precheck` and check the K8s cluster is ready to convert to OpenYurt cluster, so this command will reduce `yurtctl convert` failure and improve the OpenYurt usage experience.

**others**
/kind feature

**Comment by Peeknut** [comment]
Maybe it can split into two parts, check in cloud (such as 1, 2) and check in edge (such as 3, 4, 5). And the check in edge can realized by issuing job and calling node-servant.

And I want to take over it. Does anyone else want to do it with me？

**Comment by adamzhoul** [comment]
if use job, can we get the job pod log and print?
and if the job failed,  we can print the error and delete the job.

a failed job like `convert` always stops users from retrying again.

**Comment by rambohe-ch** [comment]
> if use job, can we get the job pod log and print? and if the job failed, we can print the error and delete the job.
> 
> a failed job like `convert` always stops users from retrying again.

@Peeknut I think that suggestion from @adamzhoul is a good idea, if precheck command failed, error message should be shown to end user.

**Comment by Peeknut** [comment]
Thanks for the suggestion, I will consider this.

**Comment by Congrool** [comment]
Hi, how about intergrating the work of precheck into convert. Thus, users can just use one command `yurtctl convert` to precheck and then convert nodes if no error in precheck.  It's something like the preflight in `kubeadm init`.  
> Maybe it can split into two parts, check in cloud (such as 1, 2) and check in edge (such as 3, 4, 5). And the check in edge can realized by issuing job and calling node-servant.  

And we can distinguish cloud nodes and edge nodes with `cloudnodes` and `edgenodes` subcommand and do different work for them.

**Comment by rambohe-ch** [comment]
> Hi, how about intergrating the work of precheck into convert. Thus, users can just use one command `yurtctl convert` to precheck and then convert nodes if no error in precheck. It's something like the preflight in `kubeadm init`.
> 
> > Maybe it can split into two parts, check in cloud (such as 1, 2) and check in edge (such as 3, 4, 5). And the check in edge can realized by issuing job and calling node-servant.
> 
> And we can distinguish cloud nodes and edge nodes with `cloudnodes` and `edgenodes` subcommand and do different work for them.

@Peeknut FYI

**Comment by Peeknut** [comment]
> Hi, how about intergrating the work of precheck into convert. Thus, users can just use one command `yurtctl convert` to precheck and then convert nodes if no error in precheck. It's something like the preflight in `kubeadm init`.
> 
> > Maybe it can split into two parts, check in cloud (such as 1, 2) and check in edge (such as 3, 4, 5). And the check in edge can realized by issuing job and calling node-servant.
> 
> And we can distinguish cloud nodes and edge nodes with `cloudnodes` and `edgenodes` subcommand and do different work for them.

Yes, the steps of yurtctl convert can be divided into prefilghtcheck and conversion, just like kubeadm init and node-servant
