### ISSUE TITLE
[feature request]

### ISSUE THREAD

**Issue by luckymrwang** [openyurtio/openyurt#623]
**What would you like to be added**:
Yurthub supports 'healthz' and 'metrics' currently. Can it add the ability to support pprof debugging?

**Why is this needed**:
pprof debugging

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@luckymrwang Thank you for raising issue.
Pprof debugging is supported in Yurthub, and you can try `curl http://127.0.0.1:10267/debug/pprof/`.

**Comment by luckymrwang** [comment]
> @luckymrwang Thank you for raising issue. Pprof debugging is supported in Yurthub, and you can try `curl http://127.0.0.1:10267/debug/pprof/`.

Thanks for your reply. It can supported pprof debugging, I have found it. I will close this issue.
