### ISSUE TITLE
[feature request] Support proxy cluster inner services (such as tunnel-server) through kube-apiserver

### ISSUE THREAD

**Issue by SataQiu** [openyurtio/openyurt#625]
**What would you like to be added**:
Currently, the `tunnel-server` service needs to be exposed through the public IP and public port so that the `tunnel-agent` can establish a connection with the server. However, this would require the users to expose additional public ports in addition to `kube-apiserver` service.  As we have more edge services that need to connect to the cloud, the number of open public ports will continue to grow and be difficult to maintain.

As we know, `kube-apiserver` can act as a gateway proxy for services within the cluster.  Even if the service is completely network isolated, you can still access it via `kube-apiserver`. You can look into more about `kube-apiserver` gateway capabilities by trying to use ['kubectl port-forward'](https://kubernetes.io/zh/docs/tasks/access-application-cluster/port-forward-access-application-cluster/) command. 

Thus, it is easy to have an idea: can we make `tunnel-agent` connect to `tunnel-server` via `kube-apiserver` rather than expose another public IP and port?  The network topology should look something like this：

![image](https://user-images.githubusercontent.com/9354727/143188104-6d303f5c-e156-42c9-8ef9-7af57c499078.png)

We can provide a sidecar for `tunnel-agent` (of course it can also be completely part of `tunnel-agent`). The sidecar initializes the Pod network by establishing a connection to `kube-apiserver`, just like `kubectl port-forward` does. Then, the `tunnel-agent` can connect to the `tunnel-server` by accessing the local address instead of the public address. 

The advantage is that only one public address needs to be exposed in the cloud, simplifying network configuration. The downside, of course, is that it may increase the pressure on `kube-apiserver`.

What do you think?

**Why is this needed**:

**others**
/kind feature

**Comment by DrmagicE** [comment]
@SataQiu Hi, maybe I didn't understand the problem correctly.  CMIIW,  what `kubectl port-forward` do is to listen on a ip:port and forward the traffic from it to another ip:port.  After reading [this post](https://prefetch.net/blog/2018/02/03/how-the-kubectl-port-forward-command-works/), I think it is using "socat" under the hood, so it seems the apiserver is not responsible for the data forwarding. Moreover, is that possible to reuse the 6443 port of the apiserver and use it to serve tunnel-server?

**Comment by BSWANG** [comment]
The `port-forward` is based on `kubelet` `exec` API, which need APIServer direct access to `kubelet` `10250` port. But the central `APIServer` cannot access `kubelet`@edge without `tunnel`.

**Comment by BSWANG** [comment]
@SataQiu IMO, The `port-forward` mechanism is too long, is not stable for production usage. May be cause connection or goroutine leak on edge weak-connection environment.

**Comment by SataQiu** [comment]
@DrmagicE @BSWANG
Thanks for your feedback!

If you look at [telepresence](https://github.com/telepresenceio/telepresence), it already has a similar capability.

But we are thinking about the whole reconstruction of the tunnel part, and we will adopt a better way to achieve cloud-edge and edge-edge network connection.

Just close this issue now. 

/close

**Comment by rambohe-ch** [comment]
@SataQiu I am afraid the following two potential problems:
1. Both control traffic and monitor traffic go through kube-apiserver, It will increase the load on the kube-apiserver, leading to more kube-apiserver crash.
2. If monitor failure happened, it's hard to found root reason for the failure because long traffic path.
