### ISSUE TITLE
[Question] Deal with CoreDNS configuration in YurtCluster operator

### ISSUE THREAD

**Issue by SataQiu** [openyurtio/openyurt#626]
**What happened**:
According to the [proposal](https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20210722-yurtcluster-operator.md), the YurtCluster Operator has been able to complete the node convert tasks based on the user's declaration. However, node convert alone is not enough to make a cluster to be a production-usable edge cluster. A very important thing is the DNS resolution of edge nodes. 

Traditionally, we typically deployed a CoreDNS Pod on each node. That should work, but the resource usage is high and the load on `kube-apiserver` is high. Therefore, we proposed the concept of NodePool. In theory, nodes within each NodePool can communicate directly with each other using IP addresses. Therefore, deploying only one CoreDNS Pod per NodePool allows edge nodes to properly resolve DNS.  But deploying CoreDNS based on NodePool brings additional problems. 

My questions are:
1. When and who will create NodePool for the OpenYurt cluster?  
2. Do we want to automate the CoreDNS configuration? Through the YurtCluster Operator or the yurt-app-Manager?

Any suggestions are welcome！

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by adamzhoul** [comment]
I have a problem:
for now, if `coreDNS` is not deployed in edge, how will a pod visit a service?  DNS search traffic can reach cloud pod?
if `coreDNS` does not have a public IP?

and,  even `coreDNS` is deployed at the edge node pool level. 
can it cache the data, and respond well even when connecting to the cloud is broken?

**Comment by rambohe-ch** [comment]
@SataQiu I think that CoreDNS should be deployed by YurtAppDaemon, and then add a tutorial for end user how to handle CoreDNS deployement.

**Comment by rambohe-ch** [comment]
> I have a problem: for now, if `coreDNS` is not deployed in edge, how will a pod visit a service? DNS search traffic can reach cloud pod? if `coreDNS` does not have a public IP?
> 
> and, even `coreDNS` is deployed at the edge node pool level. can it cache the data, and respond well even when connecting to the cloud is broken?

@adamzhoul we need to configure service topology in NodePool for CoreDNS service, so dns traffic can only forward to CoreDNS endpoints in NodePool. and CoreDNS can access kube-apiserver through yurthub, so cache of yurthub can be used by CoreDNS when cloud-edge network disconnected.

**Comment by adamzhoul** [comment]
1. is this complicated for the end-user? any tutorial here I can figure out myself, thanks.
2. is one node one `coreDNS` pod or one `nodePool` one `coreDNS` pod?
3. if `nodepool` level, is this mean we have to create a`nodepool` before we can have `coreDNS` deploy to edge.

**Comment by rambohe-ch** [comment]
@adamzhoul 

> 1. is this complicated for the end-user? any tutorial here I can figure out myself, thanks.

I think that end user just exec command like `kubectl apply -f  coredns-yad` for deploying coredns. it 's not so complicated.

> 2. is one node one `coreDNS` pod or one `nodePool` one `coreDNS` pod?

one or two CoreDNS pod per NodePool, and end user can configure the replicas as desired.

> 3. if `nodepool` level, is this mean we have to create a`nodepool` before we can have `coreDNS` deploy to edge.

yes,  nodePool need to prepared. and one node must belong to one NodePool.

**Comment by adamzhoul** [comment]
thanks

**Comment by adamzhoul** [comment]
where can I find coredns-yad ?

**Comment by rambohe-ch** [comment]
> where can I find coredns-yad ?

@adamzhoul YurtAppDaemon is developing, coredns-yad.yaml will be ready after `YurtAppDaemon` ready.

**Comment by rambohe-ch** [comment]
@SataQiu based on the discussion of issue #846, YurtCluster will be used for status detection, error alarm, etc. but not OpenYurt cluster installation. so we can close issue.
