### ISSUE TITLE
[BUG] http2: invalid Upgrade request header: ["spdy/3.1"]

### ISSUE THREAD

**Issue by DrmagicE** [openyurtio/openyurt#638]
**What happened**:
Yurthub is unable to forward exec requests.  Here is the error logs:

kubectl error log:
```
[root@worker-2 ~]# kubectl exec -it nginx -- bash
Error from server:
[root@worker-2 ~]#
```

Yurthub error log:
```
I1130 01:28:20.301594       1 util.go:228] start proxying: post /api/v1/namespaces/default/pods/nginx/exec?command=bash&container=nginx&stdin=true&stdout=true&tty=true, in flight requests: 61
I1130 01:28:20.301739       1 remote.go:188] remote proxy error handler: kubectl create pods: https://172.16.0.3:6443/api/v1/namespaces/default/pods/nginx/exec?command=bash&container=nginx&stdin=true&stdout=true&tty=true, http2: invalid Upgrade request header: ["spdy/3.1"]
```

**What you expected to happen**:
Yurthub can forward exec requests.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I think this is because there are some compatible issues between spdy and HTTP/2. When serving spdy, we have to disable HTTP2 transport. 

A possible solution: https://github.com/pomerium/pomerium/pull/2134/files

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@DrmagicE Thank you for raising issue.
Maybe it's convenient for end user to use `kubectl exec` through yurthub. @DrmagicE Would you like to take over and fix this feature?

**Comment by DrmagicE** [comment]
@rambohe-ch Yes, I would like to. Cause I need to finish some jobs in hand before starting this one, I would like to leave this issue unassigned. Other contributors are very welcome.

**Comment by rambohe-ch** [comment]
> @rambohe-ch Yes, I would like to. Cause I need to finish some jobs in hand before starting this one, I would like to leave this issue unassigned. Other contributors are very welcome.

@DrmagicE ok, i got it.

**Comment by DrmagicE** [comment]
Solve by #673. closed
