### ISSUE TITLE
[Question]Failed to convert openyurt

### ISSUE THREAD

**Issue by hxcGit** [openyurtio/openyurt#648]
**What happened**:
When I used `_output/bin/yurtctl convert --provider kubeadm --cloud-nodes k8s-master` to converted my machine from k8s to openyurt, an error happened. It failed to run servant job(yurtctl-disable-node-controller-k8s-master): wait for job to be complete timeout, and then I checked the pods status, I found I failed to pull image "openyurt/node-servant:latest".
```
root@k8s-master:~/openyurt# _output/bin/yurtctl convert --provider kubeadm --cloud-nodes k8s-master
I1202 06:31:14.415321   11275 convert.go:366] mark k8s-master as the cloud-node
E1202 06:33:15.611715   11275 util.go:540] fail to run servant job(yurtctl-disable-node-controller-k8s-master): wait for job to be complete timeout
I1202 06:33:15.611831   11275 convert.go:403] complete disabling node-controller
I1202 06:33:15.616105   11275 convert.go:504] kube-public/cluster-info configmap already exists, skip to prepare it
I1202 06:33:15.639371   11275 convert.go:480] deploying the yurt-hub and resetting the kubelet service on cloud nodes
E1202 06:35:14.575951   11275 util.go:540] fail to run servant job(node-servant-convert-k8s-master): wait for job to be complete timeout
I1202 06:35:14.576566   11275 convert.go:485] complete deploying yurt-hub on cloud nodes
```

```
kubectl get pod -A -o wide |grep master|grep yurt
kube-system   yurt-controller-manager-6c95788bf-zpkcr            1/1     Running            0          4m8s    192.168.86.181   k8s-master   <none>           <none>
kube-system   yurtctl-disable-node-controller-k8s-master-xnw4p   0/1     ErrImagePull       0          4m8s    192.168.86.181   k8s-master   <none>           <none>
```

```
Events:
kubectl describe pods yurtctl-disable-node-controller-k8s-master-xnw4p -n kube-system

  Type     Reason   Age                    From                 Message
  ----     ------   ----                   ----                 -------
  Normal   Pulling  3m19s (x4 over 6m28s)  kubelet, k8s-master  Pulling image "openyurt/node-servant:latest"
  Warning  Failed   2m44s (x4 over 5m52s)  kubelet, k8s-master  Failed to pull image "openyurt/node-servant:latest": rpc error: code = Unknown desc = Error response from daemon: pull access denied for openyurt/node-servant, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed   2m44s (x4 over 5m52s)  kubelet, k8s-master  Error: ErrImagePull
  Normal   BackOff  2m30s (x6 over 5m51s)  kubelet, k8s-master  Back-off pulling image "openyurt/node-servant:latest"
  Warning  Failed   86s (x11 over 5m51s)   kubelet, k8s-master  Error: ImagePullBackOff
```

```
root@k8s-master:~/openyurt# docker pull openyurt/node-servant
Using default tag: latest
Error response from daemon: pull access denied for openyurt/node-servant, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```
My questions are:
1. Is there anything wrong with my operation?
2. Where should I pull this image?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):1.18.0
- OS (e.g: `cat /etc/os-release`):ubuntu20.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by Congrool** [comment]
Hi, maybe you can find the solution in the troubleshooting [here](https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/yurtctl.md#Troubleshooting).

**Comment by hxcGit** [comment]
> Really appreciate that. However, I don't find `node-servant-image` in this troubleshooting, and I guess maybe i can use `registry.cn-hangzhou.aliyuncs.com/openyurt/node-servant:latest`,but this still doesn't work.  The question is i can pull other images like `openyurt/yurtctl-servant`、`openyurt/yurt-controller-manager` and so on, except for `openyurt/node-servant`. 



> Hi, maybe you can find the solution in the troubleshooting [here](https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/yurtctl.md#Troubleshooting).

**Comment by adamzhoul** [comment]
did we build the node-servant image and upload it?
@rambohe-ch

**Comment by rambohe-ch** [comment]
> did we build the node-servant image and upload it? @rambohe-ch
> 
> target: "openyurt/node-servant:latest" , docker.io not registry.cn-hangzhou.aliyuncs.com

@hxcGit @adamzhoul sorry, i will upload node-servant image soon later.

**Comment by hxcGit** [comment]
> > did we build the node-servant image and upload it? @rambohe-ch
> > target: "openyurt/node-servant:latest" , docker.io not registry.cn-hangzhou.aliyuncs.com
> 
> @hxcGit @adamzhoul sorry, i will upload node-servant image soon later.

Thanks a lot for your reply. @adamzhoul @rambohe-ch I will try this later.

**Comment by rambohe-ch** [comment]
> > > did we build the node-servant image and upload it? @rambohe-ch
> > > target: "openyurt/node-servant:latest" , docker.io not registry.cn-hangzhou.aliyuncs.com
> > 
> > 
> > @hxcGit @adamzhoul sorry, i will upload node-servant image soon later.
> 
> Thanks a lot for your reply. @adamzhoul @rambohe-ch I will try this later.

@hxcGit node-servant:latest image uploaded, please enjoy yourself.

**Comment by hxcGit** [comment]
Thank you again. I can convert cluster successfully now. @rambohe-ch
