### ISSUE TITLE
[feature request] use sealer to install OpenYurt cluster

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#656]
**What would you like to be added**:
In order to improve the experience of using OpenYurt, how about to use sealer(https://github.com/alibaba/sealer) to install OpenYurt cluster?  and then  we can use sealer to replace `yurtctl init`.

**Why is this needed**:
End user can easily experience OpenYurt in different environments.

**others**
/kind feature

**Comment by cuisongliu** [comment]
need write Kubefile  + plugin customize openyurt cluster

1 Kubefile add app-manager ,tunnel-agent,tunnel-server
2. plugin before install  add yurthub static pod 
3. plugins after install replace kubelet conf

**Comment by Peeknut** [comment]
Maybe we can keep `yurtctl init` and refactor `yurtctl init` to call sealer, which is more user-friendly as users only need to learn how to use `yurtctl` rather than sealer.

And how about creating an issue about this (refactor `yurtctl init`)?

**Comment by rambohe-ch** [comment]
> Maybe we can keep `yurtctl init` and refactor `yurtctl init` to call sealer, which is more user-friendly as users only need to learn how to use `yurtctl` rather than sealer.
> 
> And how about creating an issue about this (refactor `yurtctl init`)?

@Peeknut agree +1
