### ISSUE TITLE
[Question] How tunnel handle connections

### ISSUE THREAD

**Issue by adamzhoul** [openyurtio/openyurt#659]
after reading: https://openyurt.io/blog/Build-side-efficient-collaborative-network

I have some questions: 

 if we have n tunnel-agent pods and m tunnel-server pods
 does each `tunnel-agent` has m connections and each `tunnel-server` has n connections?
 isn't this too complicated for agents and too many connections for agents and servers?

 has the problem the article comes up  been fixed?
 > what if a new agent hasn't connected to all server, how can we make sure apiServer traffic can be forward to that agent?
> we put svcIP in host configmap, right ?

**Comment by YRXING** [comment]
If we have n tunnel-agent and m tunnel-server, then there will be m*n grpc connections. Deploying multiple tunnel servers can solve the single point problem .
if a new agent hasn't connected to all server, the traffic may not reach the tunnel agent. This is indeed a problem at the start of a new agent.
the api-server traffic will be forward tunnel-server firstly( through two ways: DNAT/DNS ), then it's the proxy server's responsibility to select the right tunnel agent (parse the http header's host filed)  and forward to it.

**Comment by rambohe-ch** [comment]
> after reading: https://openyurt.io/blog/Build-side-efficient-collaborative-network
> 
> I have some questions:
> 
> if we have n tunnel-agent pods and m tunnel-server pods does each `tunnel-agent` has m connections and each `tunnel-server` has n connections? isn't this too complicated for agents and too many connections for agents and servers?
> 
> has the problem the article comes up been fixed?
> 
> > what if a new agent hasn't connected to all server, how can we make sure apiServer traffic can be forward to that agent?
> > we put svcIP in host configmap, right ?

@adamzhoul we will try to solve this problem in new edge network proposal, you can reference here: https://github.com/openyurtio/openyurt/pull/637

**Comment by adamzhoul** [comment]
that's great
