### ISSUE TITLE
[Vote] About the naming of the networking project.

### ISSUE THREAD

**Issue by DrmagicE** [openyurtio/openyurt#663]
Hi, dear community:

As we are going to develop a new networking project to enhance the networking capabilities of OpenYurt. (proposal link https://github.com/openyurtio/openyurt/pull/637).

We are looking forward to your advice on the project naming. Here are some candidates:
* lite-vpn 
* NetEdge
* FusionNet
* FiberLink
* Cobweb
* Pigeon
* Magpie
* Wormhole
* Raven
* Over-connector
* Hypernet
* Roaming
* PodNet

Welcome to vote! Other names are very welcome too.

**Comment by rambohe-ch** [comment]
@DrmagicE I think we need to promote a name for the new project without including `yurt`. and i will add the candidates that discussed in dingding group.

**Comment by DrmagicE** [comment]
@rambohe-ch got it, I have updated the candidates.

**Comment by michaeldotmike** [comment]
NetEdge +1

**Comment by rambohe-ch** [comment]
Raven +1

**Comment by BlakeChiang4** [comment]
Raven +1

**Comment by DrmagicE** [comment]
Wormhole + 1

**Comment by h3ar7dump** [comment]
Hypernet + 1

**Comment by sayicui** [comment]
lite-vpn

**Comment by Congrool** [comment]
Raven +1

**Comment by windydayc** [comment]
Raven +1

**Comment by vincent-pli** [comment]
Raven +1

**Comment by cishidai** [comment]
Wormhole +1

**Comment by JameKeal** [comment]
NetEdge +1

**Comment by YRXING** [comment]
Pigeon、Cobweb  +1

**Comment by nancliu** [comment]
Wormhole+1

**Comment by zhuyaguang** [comment]
Raven +1

**Comment by jzwlqx** [comment]
Wormhole +1

**Comment by donychen1134** [comment]
NetEdge +1

**Comment by Peeknut** [comment]
Hypernet+1

**Comment by xionglihdfs** [comment]
LongEdge

**Comment by yixingjia** [comment]
Will this be a separate project or just a component of OpenYurt?

**Comment by charleszheng44** [comment]
Wormhole +1

**Comment by rambohe-ch** [comment]
> Will this be a separate project or just a component of OpenYurt?

@yixingjia This new edge network project will be new repo under openyurtio org.

**Comment by SataQiu** [comment]
FiberLink、HyperNet +1

**Comment by luckymrwang** [comment]
Raven +1

**Comment by rambohe-ch** [comment]
Thank you everybody for voting. 
now it is the closing time of voting, and voting result as following(only list the former three names):
- Raven:  7
- Wormhole: 5
-  Hypernet: 3

so OpenYurt community will use `Raven` as name for edge networking project.
