### ISSUE TITLE
[BUG] The function of SetSELinux is unuseful.

### ISSUE THREAD

**Issue by chenyufeifei** [openyurtio/openyurt#676]
**What happened**:
It will enter a function of doing nothing when we call selinux.SetDisabled.
https://github.com/openyurtio/openyurt/blob/master/pkg/yurtctl/util/system/util.go#L72-L77
![image](https://user-images.githubusercontent.com/94742032/145832272-04a5847e-793b-4723-9dfa-c115832df648.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@zyjhtangtang Do you have any comments?

**Comment by windydayc** [comment]
We can see the selinux.SetDisabled() method is in "github.com/opencontainers/selinux/go-selinux" package.
While in "github.com/opencontainers/selinux/go-selinux" package you can see two almost the same file selinux_linux.go and selinux_stub.go, Both files have selinux.setDisabled() in them, and both are in the selinux package. You'll find the +build command on the first line, which is the syntax for golang conditional compilation.
Therefore, which selinux.setDisabled() method to use when compiling depends on your operating system.

```golang
// github.com/openyurtio/openyurt/pkg/yurtctl/util/system/util.go

import (
	"github.com/opencontainers/selinux/go-selinux"
    ...
)

// setSELinux turn off the node selinux.
func SetSELinux() error {
	klog.Info("Disabling SELinux.")
	selinux.SetDisabled()
	return nil
}
```

```golang
// github.com/opencontainers/selinux/go-selinux/selinux_linux.go

// +build selinux,linux

package selinux

// SetDisabled disables selinux support for the package
func SetDisabled() {
	state.setEnable(false)
}
```

```golang
// github.com/opencontainers/selinux/go-selinux/selinux_stub.go

// +build !selinux

package selinux

// SetDisabled disables selinux support for the package
func SetDisabled() {
	return
}
```

**Comment by windydayc** [comment]
For more about conditional compilation, you can refer to: [Learn golang's conditional compilation](https://programmer.help/blogs/learn-golang-s-conditional-compilation.html)

**Comment by chenyufeifei** [comment]
> ```go
> +build selinux,linux
> ```

But when we click the function in linux, it will jumb to selinux_stub.go. If we upgrade selinux package, it will jumb to selinux_linux.go. So the package should have error。

**Comment by windydayc** [comment]
Maybe you disabled the selinux in your operating system. You can use `getenforce` command in terminal to check it. One possible reason is that selinux is generally disabled when build a k8s cluster.

**Comment by chenyufeifei** [comment]
> Maybe you disabled the selinux in your operating system. You can use `getenforce` command in terminal to check it. One possible reason is that selinux is generally disabled when building a k8s cluster.
> 
> ```shell
> # Disabled means SELinux is not working.
> $ getenforce
> Disabled
> ```

You can test it.
It is missing a space
![image](https://user-images.githubusercontent.com/94742032/145991551-49042b33-6db6-4cd3-a279-3fc149fbc2f6.png)
If I add a space, it is ok
![image](https://user-images.githubusercontent.com/94742032/145991659-2d2d15de-90a0-48da-9669-cadda8da732e.png)

**Comment by windydayc** [comment]
Here Comma-separated logic represents AND, and does not need a white space. 
For example,  (linux AND 386) OR (darwin AND (NOT cgo))
```golang
// +build linux,386 darwin,!cgo
```

**Comment by windydayc** [comment]
Your system disabled selinux, so it will `// +build !selinux` in `selinux_stub.go`.

**Comment by windydayc** [comment]
Maybe you should figure out the grammar of golang's conditional compilation first.

**Comment by chenyufeifei** [comment]
The selinux isn't a deufalt condition，so we shoud add a tag selinux in build the project.  
But not now. @ windydayc  @ rambohe-ch

**Comment by rambohe-ch** [comment]
> The selinux isn't a deufalt condition，so we shoud add a tag selinux in build the project. But not now. @windydayc @rambohe-ch

@chenyufeifei Would you like to give more detail info that how to add a selinux tag for building yurtctl?

**Comment by chenyufeifei** [comment]
> > The selinux isn't a deufalt condition，so we shoud add a tag selinux in build the project. But not now. @windydayc @rambohe-ch
> 
> @chenyufeifei Would you like to give more detail info that how to add a selinux tag for building yurtctl?

The selinux_linux.go has multiple compilation conditions: `// +build selinux,linux`, it should meet conditions both selinux and linux。But the condition of `selinux` is not automatically recognized。
If we need to use selinux_linux.go, we should using `go build -tags selinux xxxx.go`.

**Comment by rambohe-ch** [comment]
> > > The selinux isn't a deufalt condition，so we shoud add a tag selinux in build the project. But not now. @windydayc @rambohe-ch
> > 
> > 
> > @chenyufeifei Would you like to give more detail info that how to add a selinux tag for building yurtctl?
> 
> The selinux_linux.go has multiple compilation conditions: `// +build selinux,linux`, it should meet conditions both selinux and linux。But the condition of `selinux` is not automatically recognized。 If we need to use selinux_linux.go, we should using `go build -tags selinux xxxx.go`.

@chenyufeifei Thanks for your feedback. I agree with you that add selinux tag for building yurtctl component.
