### ISSUE TITLE
[feature request] enable `yurtctl convert` to support k8s v1.19 and 1.21

### ISSUE THREAD

**Issue by Congrool** [openyurtio/openyurt#677]
**What would you like to be added**:
Currently, yurtctl convert and revert command cannot support kubernetes v1.19 and v1.21. We should support them. I've run the kubernetes conformance tests based on both two k8s versions, and all cases passed. It's time to enable yurtctl to support v1.19 and v1.21.  

Here are the test results.  
**v1.19**
![image](https://user-images.githubusercontent.com/32788286/145933495-1d0193df-81f9-4510-bed5-fce9cc842f30.png)

**v1.21**
![image](https://user-images.githubusercontent.com/32788286/145933592-97647e01-e9ab-46c8-8b84-d70baf09a68d.png)

**others**
/kind feature

**Comment by Congrool** [comment]
Some test details
Openyurt components included:
1. yurthub
2. yurt-tunnel
3. yurt-controller-manager

OpenYurt commit: 61f8a76

deployed with command:
```
yurtctl convert -c master -t --provider kubeadm \
  --kubeadm-conf-path /usr/lib/systemd/system/kubelet.service.d/10-kubeadm.conf \
  --node-servant-image openyurt/node-servant:v0.5.0-amd64-61f8a76  \
  --yurt-controller-manager-image openyurt/yurt-controller-manager:v0.5.0-amd64-61f8a76 \
  --yurt-tunnel-agent-image openyurt/yurt-tunnel-agent:v0.5.0-amd64-61f8a76 \
  --yurt-tunnel-server-image openyurt/yurt-tunnel-server:v0.5.0-amd64-61f8a76 \
  --yurthub-image openyurt/yurthub:v0.5.0-amd64-61f8a76
```

k8s version: v1.19.13, v1.21.7

**Comment by rambohe-ch** [comment]
@Congrool It's a good job that add conformance test for OpenYurt. and i agree with you that add v1.19 and v1.21 version support.
