### ISSUE TITLE
[feature request] Yurthub data filtering framework optimization

### ISSUE THREAD

**Issue by zzguang** [openyurtio/openyurt#699]
**What would you like to be added**:
Current yurthub data filtering framework has some limitations, such as:
1. It hardcoded the components and the resources/verbs, which is not convenient to reuse the same resource filtering for different components.
2. One component can only filter one resource, which can not meet the requirements for some components.
So it seems the current implementation needs to be optimized to be a more generic way:
1. Implement the different resources filtering in the core framework
2. Define the components and resources/verbs map in a configurable way, e.g. configmap
3. Implementing it through webhook may be another option

**Why is this needed**:
1. One resource filtering can be reused by multiple components
2. One component can filter multiple resources conveniently, especially for the components which needs to cache data locally by yurthub, filtering to cache the resources only it requires can reduce the storage burden of the Edge device.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@zzguang Very appreciate for your consideration. components and verbs in filter are used by `filter.Approve` only, so it's a good idea to extract resource filters for sharing by multi components.

**Comment by rambohe-ch** [comment]
@zzguang would you like to take over this feature?

**Comment by zzguang** [comment]
> @zzguang would you like to take over this feature?
@rambohe-ch I am not sure when I will have time to optimize it by now, we are making plan for 2022 and some important issues need to be figured out firstly, then we will define the priorities of them. If some others are interested in this feature, you can assign it to them, otherwise, I can take a look at it in future.
