### ISSUE TITLE
Openyurt why not choose k3s/k8s cluster as a edge ?

### ISSUE THREAD

**Issue by jmpcyc** [openyurtio/openyurt#70]
In openyurt we can chose a node as a edge. But in our case, we want to choose k3s cluster as a edge because of we master a lot of cluster in county.  K3s cluster register itself as a k8s node. In cloud, we use nodeselector  to deploy pods to edge. And we want to use  AdmissionWebhook to proxy read write to edge. Is it good more than openyurt？

**Comment by charleszheng44** [comment]
@jmpcyc thanks for filing the issue. I don't quite understand your question.

**Comment by charleszheng44** [comment]
@jmpcyc thanks for filing the issue. I don't quite understand your question. 

Which one do you mean,
Does OpenYurt support adding a k3s cluster as an edge node? 
Or
Why choose OpenYurt over k3s?

**Comment by rambohe-ch** [comment]
@jmpcyc thank you for sharing your experience.
use the central k8s to manage a mass of edge k8s clusters in openyurt is also under consideration, and edge k8s cluster components are pods of central k8s. 

and would you explain how K3s cluster register itself as a k8s node?
