### ISSUE TITLE
[BUG]downloading cni failed when joining arm64 node

### ISSUE THREAD

**Issue by ChengyangDu** [openyurtio/openyurt#707]
**What happened**:
I0106 16:34:24.975456   19047 util.go:764] Download cni from: https://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-arm64-v0.8.0.tgz
Error: error execution phase initialize: Server return non-200 status: 404 Not Found

**What you expected to happen**:
download success

**How to reproduce it (as minimally and precisely as possible)**:
join arm64 node

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: v0.5.0
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-aliyun.1", GitCommit:"40ad569", GitTreeState:"", BuildDate:"2021-06-28T04:01:44Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-aliyun.1", GitCommit:"792b9c9", GitTreeState:"", BuildDate:"2021-07-19T10:33:37Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g: `cat /etoc/os-release`): NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`): Linux nx-desktop 4.9.253-tegra #1 SMP PREEMPT Mon Jul 26 12:19:28 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
- Install tools: YurtCluster Operator 
- Others:

**others**

/kind bug

**Comment by zyjhtangtang** [comment]
The cni of the arm64 architecture is already available for download. 
http://aliacs-edge-k8s-cn-hangzhou.oss-cn-hangzhou.aliyuncs.com/public/pkg/openyurt/cni/v0.8.0/cni-plugins-linux-arm64-v0.8.0.tgz
