### ISSUE TITLE
[best practice]kubeflow works at edge through openyurt

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#713]
**What would you like to be added**:
1. Verify kubeflow works at edge through openyurt
2. Come to the conclusion that what's the best practice for kubeflow at edge.
3. Solve the problems in openyurt that cause kubeflow not to work.

**Why is this needed**:
Theres are more and more requirements for AI at edge, some end user have question that the best practice of kubeflow at edge.

**others**
/kind feature

**Comment by duanjia85** [comment]
I'm interested in kubeflow, I'll take over this task with pleasure

**Comment by rambohe-ch** [comment]
This issue has been added as project in ASOC 2022, the detail info is here: https://github.com/openyurtio/openyurt/issues/855

so i will close this issue.
