### ISSUE TITLE
[feature request]Deploy different versions of the same application to different stand-alone nodes

### ISSUE THREAD

**Issue by expwdx** [openyurtio/openyurt#715]
**What would you like to be added**:
To deploy different versions of the same application to different stand-alone nodes. These nodes may be located in different locations in the same farm or in different farms.

**Why is this needed**:
- In our edge scenario, there are many stand-alone deployed edge servers, which are distributed in different farms and floors. Based on the different scale of the farm, the number of such single node servers installed in a farm ranges from 1 to hundreds.
- Multiple applications are deployed on a single node. Because of business requirements, these applications often need to deploy different versions of the same application on different nodes. These nodes may be in the same farm or in different farms.

**others**
/kind feature

**Comment by Congrool** [comment]
I think `yurt-app-manager` has implemented this feature.
You can find more details at https://github.com/openyurtio/yurt-app-manager

**Comment by rambohe-ch** [comment]
@expwdx Thanks for raising issue.
As @Congrool reply, the UnitedDeployment workload likes to satisfy your requirements.

**Comment by expwdx** [comment]
@Congrool @rambohe-ch Thanks for the suggestion.
Do you mean only one node in a NodePool? I will try...

**Comment by rambohe-ch** [comment]
> @Congrool @rambohe-ch Thanks for reply. Do you mean only one node in a NodePool? I will try...

@expwdx nodes that connect with each other through intranet can be put into the same NodePool.

**Comment by expwdx** [comment]
> > @Congrool @rambohe-ch Thanks for reply. Do you mean only one node in a NodePool? I will try...
> 
> @expwdx nodes that connect with each other through intranet can be put into the same NodePool.

Ok, I see
