### ISSUE TITLE
[feature request]  add regular expression  supprot for config ‘cache-agent‘ of yurthub  

### ISSUE THREAD

**Issue by hhstu** [openyurtio/openyurt#722]
**What would you like to be added**:

**Why is this needed**:

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@hhstu Very appreciate for raising this issue. I agree with you that add regular expression for cache-agents fields, like `cache-agents=*` means all responses will be cached.

**Comment by rambohe-ch** [comment]
@hhstu Would you like to take over the feature and make a pull request?
