### ISSUE TITLE
[Question] Managing identical software on many edge devices

### ISSUE THREAD

**Issue by batthebee** [openyurtio/openyurt#729]
Let's assume we have many edge devices that perform the same task. The identical software stack is to be installed on all these devices.

The software stack consists of different components (pods) that should communicate with each other. It is important that the components only communicate with each other within their node.

Q1: How do I do the "identical" rollout of the stack to each node? This could be solved e.g. over a DaemonSet.

Q2: How do I make sure that the components only talk to each other within their node? Something like services would be ideal here, but ensuring that if a pod is available on the same node, it is also used. Alternatively, you could set up a local service discovery yourself, but this bypasses all k8s mechanisms.

Do you have any idea how to implement something like this?

**Comment by DrmagicE** [comment]
For Q1, as you said, DaemonSet could solve the problem.

For Q2, I think the Service Topology feature is what you are looking for. With Service Topology enabled, you can still use a 
single kubernetes service to expose your service and Openyurt will do the rest for you.

For more information, you can refer to this tutorial: https://github.com/openyurtio/openyurt/blob/master/docs/tutorial/service-topology.md

**Comment by rambohe-ch** [comment]
@batthebee For question2, you can also reference docs as following:
https://openyurt.io/docs/user-manuals/network/service-topology
https://openyurt.io/zh/docs/user-manuals/network/service-topology/
