### ISSUE TITLE
[feature request]provide flannel image and cni binary for edge network

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#731]
**What would you like to be added**:
In order to adapt for edge network, flannel and cni need some improvement. and user docs is here: https://openyurt.io/zh/docs/user-manuals/network/edge-pod-network/

so how about provide flannel image and cni binary for end user directly instead of building image and binary by user-self?

**Why is this needed**:
If improved flannel image and cni binary can be provided by openyurt community, i think it can definitely improve efficiency of user using OpenYurt.

**others**
/kind feature

**Comment by yingjianjian** [comment]
fix #https://github.com/openyurtio/openyurt.io/pull/80
