### ISSUE TITLE
[Question]yurtingrees fails to deploy ingress-nginx-controller

### ISSUE THREAD

**Issue by yingjianjian** [openyurtio/openyurt#732]
**What happened**:
When I was doing yurtingress, I found that ingress-nginx-controller could not be deployed. The main reason was that ingress-nginx-controller did not have the tolerance of node-role.openyurt.io/edge:NoSchedule. What I am not sure about is yurtcluster-operater. Remove Taints when deploying or add corresponding tolerance when deploying ingress-nginx-controller
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version: v0.6.0
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by zzguang** [comment]
Thanks @yingjianjian for filing this issue.
After confirmation with @SataQiu, when users convert a K8S cluster to an OpenYurt cluster by YurtCluster operator, all the edge nodes will be added a taint of "node-role.openyurt.io/edge:NoSchedule" for a production requirement,  which seems need to be optimized to keep consistent with other ways of OpenYurt cluster creation. 
From the YurtIngress aspect, I think it needs to add the related tolerances as well to ensure the nginx ingress controller can be orchestrated to nodepools successfully in such conditions.
