### ISSUE TITLE
[feature request]Rename UnitedDeployment to YurtAppSet

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#735]
**What would you like to be added**:
Rename UnitedDeployment to YurtAppSet.

**Why is this needed**:
From discussion from this issue: https://github.com/openyurtio/openyurt/issues/433, UnitedDeployment should be renamed as YurtAppSet.

**others**
/kind feature

**Comment by moyuduo** [comment]
Hello, i am a new comer of openyurt project, i have been watching this project for months, now i want to resolve this simple issue to learn openyurt project  gradually and becoming a contributor of openyurt project, is this ok?

**Comment by rambohe-ch** [comment]
> Hello, i am a new comer of openyurt project, i have been watching this project for months, now i want to resolve this simple issue to learn openyurt project gradually and becoming a contributor of openyurt project, is this ok?

@moyuduo welcome you to contribute to OpenYurt. if you need to any help, please me know in any way.
/assign @moyuduo

**Comment by moyuduo** [comment]
> > Hello, i am a new comer of openyurt project, i have been watching this project for months, now i want to resolve this simple issue to learn openyurt project gradually and becoming a contributor of openyurt project, is this ok?
> 
> @moyuduo welcome you to contribute to OpenYurt. if you need to any help, please me know in any way. /assign @moyuduo

I note that yurt-app-manager has alerdy remove from [openyurt](https://github.com/openyurtio/openyurt) into [yurt-app-manager repo](https://github.com/openyurtio/yurt-app-manager),  should i fork the latter and create pull request to this repo?

**Comment by rambohe-ch** [comment]
> > > Hello, i am a new comer of openyurt project, i have been watching this project for months, now i want to resolve this simple issue to learn openyurt project gradually and becoming a contributor of openyurt project, is this ok?
> > 
> > 
> > @moyuduo welcome you to contribute to OpenYurt. if you need to any help, please me know in any way. /assign @moyuduo
> 
> I note that yurt-app-manager has alerdy remove from [openyurt](https://github.com/openyurtio/openyurt) into [yurt-app-manager repo](https://github.com/openyurtio/yurt-app-manager), should i fork the latter and create pull request to this repo?

@moyuduo sorry to feedback late, please make a rename pull request in `openyurtio/yurt-app-manager` repo.

**Comment by rambohe-ch** [comment]
@zzguang @kadisi how about make a pull request of renaming UnitedDeployment to YurtAppSet in `openyurtio/yurt-app-manager` repo?

**Comment by moyuduo** [comment]
> > > > Hello, i am a new comer of openyurt project, i have been watching this project for months, now i want to resolve this simple issue to learn openyurt project gradually and becoming a contributor of openyurt project, is this ok?
> > > 
> > > 
> > > @moyuduo welcome you to contribute to OpenYurt. if you need to any help, please me know in any way. /assign @moyuduo
> > 
> > 
> > I note that yurt-app-manager has alerdy remove from [openyurt](https://github.com/openyurtio/openyurt) into [yurt-app-manager repo](https://github.com/openyurtio/yurt-app-manager), should i fork the latter and create pull request to this repo?
> 
> @moyuduo sorry to feedback late, please make a rename pull request in `openyurtio/yurt-app-manager` repo.

ok, i have some question that i forked yurt-app-manager to my own namespace and i forget to resync the latest code, when i realize that i have alerdy finish rename, so now the git flow as follow.
```shell
[root@centos72 yurt-app-manager]# git log --graph --oneline
*   ca18d81 (HEAD -> feature/rename_uniteddeployment_to_yurtappset) Merge branch 'master' into feature/rename_uniteddeployment_to_yurtappset
|\  
| * 5dc7d07 (origin/master, origin/HEAD, master) ingress: add nodepool edge node taints tolerations (#38)
| * 4eb0982 ingress: update yurtingress tutorial link (#37)
| * 2288a2e add 0.5.0 relase and all_in_one yaml (#35)
| * 3fa127c update README to add YurtAppDaemon and YurtIngress (#34)
| * aa6e57b ingress: fix YurtIngress CR status update error (#33)
| * 82f3c34 Initialize capabilities to support enabling containers[*].securityContext.privileged for UnitedDeployment (#26)
| * 457ddb5 Add YurtIngress operator implementation (#32)
| * 783b1be use https[s] proxy in docker for release build if necessary (#28)
| * 9046f0f hotfix: Lables fix to Annotations (#29)
| * 613e42d yurt-app-manager support YurtAppDaemon CRD (#27)
* | 8384768 feature: rename UnitedDeployment to YurtAppSet
|/  
* ab2a014 Fix yurt-app-manager deployment fail due to nodeSelector and tolerance mismatch (#25)
```
i  note that openyurt require single commit each pr, so how can i rebase `8384768 ` and `ca18d81 ` into one commit

**Comment by zzguang** [comment]
> @zzguang @kadisi how about make a pull request of renaming UnitedDeployment to YurtAppSet in `openyurtio/yurt-app-manager` repo?

Sure, welcome for the contribution about it.

**Comment by zzguang** [comment]
> > > > > Hello, i am a new comer of openyurt project, i have been watching this project for months, now i want to resolve this simple issue to learn openyurt project gradually and becoming a contributor of openyurt project, is this ok?
> > > > 
> > > > 
> > > > @moyuduo welcome you to contribute to OpenYurt. if you need to any help, please me know in any way. /assign @moyuduo
> > > 
> > > 
> > > I note that yurt-app-manager has alerdy remove from [openyurt](https://github.com/openyurtio/openyurt) into [yurt-app-manager repo](https://github.com/openyurtio/yurt-app-manager), should i fork the latter and create pull request to this repo?
> > 
> > 
> > @moyuduo sorry to feedback late, please make a rename pull request in `openyurtio/yurt-app-manager` repo.
> 
> ok, i have some question that i forked yurt-app-manager to my own namespace and i forget to resync the latest code, when i realize that i have alerdy finish rename, so now the git flow as follow.
> 
> ```shell
> [root@centos72 yurt-app-manager]# git log --graph --oneline
> *   ca18d81 (HEAD -> feature/rename_uniteddeployment_to_yurtappset) Merge branch 'master' into feature/rename_uniteddeployment_to_yurtappset
> |\  
> | * 5dc7d07 (origin/master, origin/HEAD, master) ingress: add nodepool edge node taints tolerations (#38)
> | * 4eb0982 ingress: update yurtingress tutorial link (#37)
> | * 2288a2e add 0.5.0 relase and all_in_one yaml (#35)
> | * 3fa127c update README to add YurtAppDaemon and YurtIngress (#34)
> | * aa6e57b ingress: fix YurtIngress CR status update error (#33)
> | * 82f3c34 Initialize capabilities to support enabling containers[*].securityContext.privileged for UnitedDeployment (#26)
> | * 457ddb5 Add YurtIngress operator implementation (#32)
> | * 783b1be use https[s] proxy in docker for release build if necessary (#28)
> | * 9046f0f hotfix: Lables fix to Annotations (#29)
> | * 613e42d yurt-app-manager support YurtAppDaemon CRD (#27)
> * | 8384768 feature: rename UnitedDeployment to YurtAppSet
> |/  
> * ab2a014 Fix yurt-app-manager deployment fail due to nodeSelector and tolerance mismatch (#25)
> ```
> 
> i note that openyurt require single commit each pr, so how can i rebase `8384768 ` and `ca18d81 ` into one commit

@moyuduo , welcome for your contribution to yurt-app-manager, some suggestions about your question:
1. Your PR should base on the latest upstream source code, which aims to avoid the code conflict for merging. So you need firstly pull the latest source code then add your commit "8384768" basing on it, if any code conflict, you need to fix it.
2.  One PR can contain one or several commits, so after you add commit "8384768",  you can add commit "ca18d81" base on it, then submit a PR including both of them. Also you can merge commit "8384768" and "ca18d81" into one then submit a PR including the merged commit.

**Comment by hxcGit** [comment]
Is anyone working on this issue right now? If no one is, I want to take it.

**Comment by rambohe-ch** [comment]
> Is anyone working on this issue right now? If no one is, I want to take it.

@hxcGit This issue is still idle, welcome you to take it.

**Comment by hxcGit** [comment]
@rambohe-ch Currently I think three repos (openyurt, yurt-app-manager and openyurt.io) need to make relevant changes, right?

**Comment by rambohe-ch** [comment]
> @rambohe-ch Currently I think three repos (openyurt, yurt-app-manager and openyurt.io) need to make relevant changes, right?

@hxcGit yes, please post your pull requests.
