### ISSUE TITLE
[BUG] Cannot join  OpenYurt slack channel

### ISSUE THREAD

**Issue by benjaminhuo** [openyurtio/openyurt#744]
**What happened**:
Cannot join slack channel below in the README.md with error "This link is no longer active"
https://join.slack.com/t/openyurt/shared_invite/zt-10dxeg3v9-PRApjbfTWN6G3sIIHan2kA

/kind bug

**Comment by rambohe-ch** [comment]
@benjaminhuo Thank you for your reminding, i will update slack link soon.
