### ISSUE TITLE
[feature request]support domain name certs for yurt-tunnel-server and agent

### ISSUE THREAD

**Issue by shao77622** [openyurtio/openyurt#745]
**What would you like to be added**:
yurt-tunnel-server uses --cert-ips for customized endpoints like loadbalancer, but doesn't support domain name.

**Why is this needed**:
in cloud computing environment, loadbalancer ips may changed or lost , and the domain name should be better.

**others**
I have tested this case, --cert-ips does not support domain names.
/kind feature

**Comment by Congrool** [comment]
@shao77622 
Does `--cert-dns-names` work in your case?

**Comment by rambohe-ch** [comment]
@shao77622 Thank you for raising issue. I think we can consider to support this feature in raven.
@Congrool Do you have any comments about this issue?

**Comment by Congrool** [comment]
@rambohe-ch @shao77622 
If I don't miss the point, we want to add a dns name (provided by the cloud provider) into the certificate of tunnel-server so that the tunnel-agent can use this dns name to connect to the server. In my mind, we can do this through setting the `--cert-dns-names` option of tunne-server and the `--tunnelserver-addr=${serverdns}` option of tunnel-agent.

**Comment by rambohe-ch** [comment]
> @rambohe-ch @shao77622 If I don't miss the point, we want to add a dns name (provided by the cloud provider) into the certificate of tunnel-server so that the tunnel-agent can use this dns name to connect to the server. In my mind, we can do this through setting the `--cert-dns-names` option of tunne-server and the `--tunnelserver-addr=${serverdns}` option of tunnel-agent.

@shao77622 would you like to have a try by following comments from @Congrool ?

**Comment by shao77622** [comment]
> > @rambohe-ch @shao77622 If I don't miss the point, we want to add a dns name (provided by the cloud provider) into the certificate of tunnel-server so that the tunnel-agent can use this dns name to connect to the server. In my mind, we can do this through setting the `--cert-dns-names` option of tunne-server and the `--tunnelserver-addr=${serverdns}` option of tunnel-agent.
> 
> @shao77622 would you like to have a try by following comments from @Congrool ?

It worked!  thank you!
