### ISSUE TITLE
[Docs]Translate docs/introduction.md to EN

### ISSUE THREAD

**Issue by Peeknut** [openyurtio/openyurt#752]
### The docs link you want to translate

zh: https://github.com/openyurtio/openyurt.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/version-v0.6.0/introduction.md

### Target language

en: https://github.com/openyurtio/openyurt.io/blob/master/versioned_docs/version-v0.6.0/introduction.md

**Note**：The images in the documentation are stored at https://github.com/openyurtio/openyurt.io/tree/master/static/img

If you have any questions, please refer to [[README.md](https://github.com/openyurtio/openyurt.io#readme)].

**Comment by Peeknut** [comment]
Since version 0.6.0 is the same as the current documentation, the following article also needs to be translated.

### The docs link you want to translate

zh: https://github.com/openyurtio/openyurt.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/current/introduction.md

### Target language

en: https://github.com/openyurtio/openyurt.io/blob/master/docs/introduction.md

**Comment by rambohe-ch** [comment]
introduction doc translation is fixed by https://github.com/openyurtio/openyurt.io/pull/124
