### ISSUE TITLE
[Docs]Translate docs/user-manuals/monitoring/prometheus.md to EN

### ISSUE THREAD

**Issue by qclc** [openyurtio/openyurt#753]
### The docs link you want to translate 

zh (original file): https://github.com/openyurtio/openyurt.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/version-v0.6.0/user-manuals/monitoring/prometheus.md

### Target language

The files in the following directories need to be replaced with the English version:

en: https://github.com/openyurtio/openyurt.io/blob/master/versioned_docs/version-v0.6.0/user-manuals/monitoring/prometheus.md

**Note**：The images in the documentation are stored at https://github.com/openyurtio/openyurt.io/tree/master/static/img

If you have any questions about how to add or update docs, please refer to [README.md](https://github.com/openyurtio/openyurt.io#readme).

**Comment by qclc** [comment]
Since version 0.6.0 is the same as the current documentation, the following article also needs to be translated.

### The docs link you want to translate 

zh (original file): https://github.com/openyurtio/openyurt.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/current/user-manuals/monitoring/prometheus.md

### Target language

The files in the following directories need to be replaced with the English version:

en: https://github.com/openyurtio/openyurt.io/blob/master/docs/user-manuals/monitoring/prometheus.md

**Comment by rambohe-ch** [comment]
prometheus tutorial doc translation is fixed by https://github.com/openyurtio/openyurt.io/pull/140
