### ISSUE TITLE
[Docs] Translate docs/installation/yurtctl-convert-revert.md to EN

### ISSUE THREAD

**Issue by Peeknut** [openyurtio/openyurt#757]
### The docs link you want to translate

zh: https://github.com/openyurtio/openyurt.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/version-v0.6.0/installation/yurtctl-convert-revert.md

### Target language

en: https://github.com/openyurtio/openyurt.io/blob/master/versioned_docs/version-v0.6.0/installation/yurtctl-convert-revert.md

**Note**：The images in the documentation are stored at https://github.com/openyurtio/openyurt.io/tree/master/static/img/docs/installation

If you have any questions, please refer to [[README.md](https://github.com/openyurtio/openyurt.io#readme)].

**Comment by rambohe-ch** [comment]
yurtctl convert/revert command has been deprecated. so tutorial for them is removed.
