### ISSUE TITLE
[Docs] Translate docs/core-concepts/yurt-controller-manager.md to EN

### ISSUE THREAD

**Issue by Peeknut** [openyurtio/openyurt#759]
### The docs link you want to translate

zh: https://github.com/openyurtio/openyurt.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/version-v0.6.0/core-concepts/yurt-controller-manager.md

### Target language

en: https://github.com/openyurtio/openyurt.io/blob/master/versioned_docs/version-v0.6.0/core-concepts/yurt-controller-manager.md

**Note**: The images in the documentation are stored at https://github.com/openyurtio/openyurt.io/tree/master/static/img/docs/core-concepts

If you have any questions, please refer to [[README.md](https://github.com/openyurtio/openyurt.io#readme)].

**Comment by Peeknut** [comment]
Since version 0.6.0 is the same as the current documentation, the following article also needs to be translated.

### The docs link you want to translate

zh: https://github.com/openyurtio/openyurt.io/blob/master/i18n/zh/docusaurus-plugin-content-docs/current/core-concepts/yurt-controller-manager.md

### Target language

en: https://github.com/openyurtio/openyurt.io/blob/master/docs/core-concepts/yurt-controller-manager.md

**Comment by rambohe-ch** [comment]
yurt-controller-manager doc translation is fixed by https://github.com/openyurtio/openyurt.io/pull/127
