### ISSUE TITLE
[feature request]`NodePool Governance Capability`: add `pool-coordinator-certificate` controller 

### ISSUE THREAD

**Issue by Peeknut** [openyurtio/openyurt#774]
**What would you like to be added**:
According to `NodePool governance capability` proposed in the proposal, we need to add some controllers on the cloud:
- pool-coordinator-certificate controller: is used to prepare certificates for pool-coordinator component on edge nodes.
- pool-coordinator controller: is used to manage nodes in terms of delegated node leases.

and these controllers will be integrated into `yurt-controller-manager` component, and this issue is used for tracking `pool-coordinator-certificate` controller.

pool-coordinator-certificate controller can be described as:
1. prepare the client certificate to access the kubelet for pool-coordinator in NodePool, save the certificate in secret and mounts it to pool-coordinator. Note that all pool-coordinator can share this client certificate.
2. prepare the https server tls certificate for receiving requests from yurthub in NodePool, save the certificate in secret and mounts it to pool-coordinator. Note that all pool-coordinator can share this server certificate.
3. prepare kubeconfig client certificate for kubectl tool that get/list resources in pool-coordinator in NodePool, save the certificate in secret with the same name as NodePool.

- Note that the tls server certificate should include the pool-coordinator service clusterIP and the nodeIP of node that hosted the pool-coordinator pod.
- kubeconfig for users to access pool-coordinator. The server address in kubeconfig is set to https://{nodeIP}:10270. In addition, the client certificate authority in kubeconfig should be restricted.
- When the pool-coordinator is rebuilt, spirit-controller will clean up and rebuild the tls server certificate.

 **Notes**: For details, please refer to the proposal: https://github.com/openyurtio/openyurt/pull/772

**Why is this needed**:
As mentioned in the proposal(https://github.com/openyurtio/openyurt/pull/772), pool-coordinator-certificate controller is responsible for managing the certificates of pool-coordinator.

**others**
/kind feature

**Comment by Peeknut** [comment]
The controller is mainly divided into three parts:
(1) prepare: resources are needed to prepare pool-coordinator and yurthub, including certificate for pool-coordinator to access kubelet, client certificate and permissions for yurthub to forward node-lease, etc.
**Progress:** Done

(2) reconcile pool-coordinator: monitor the pool-coordinator resource and operate the corresponding YurtAppSet according to the action.
**Progress:** Partial development work completed
**Problem:** All pool-coordinators in the proposal share a YurtAppSet. If a new pool-coordinator is added, only the NodePool information needs to be updated. But the problem is that using the same YurtAppSet, if you want to configure the pool-coordinator differently, you need to update the Patch field of the YurtAppSet. If the pool-coordinator expands the field later, the Patch field may undergo more modifications. And, the same is true for the additions, deletions and modifications of the pool-coordinator. Is it easier to maintain a YurtAppSet bound to each pool-coordinator?

(3) reconcile YurtAppSet: Monitor YurtAppSet resources to ensure the normal operation of pool-coordinator.
**Progress:** No development started yet

**Comment by luc99hen** [comment]
In response to the adjustments of pool-coordinator component, the role of `pool-coordinator-controller` has been adjusted as following: 
1. Initialize
- block until the YurtAppDaemon CRDs are ready.
- prepares the client certificate to access the kubelet for pool-coordinator, saves the certificate in secret (shared certificate)

2. Reconcile 
- When pool-spirit is scheduled, controller prepares the tls server certificate for pool-coordinator, saves the certificate in secret and mounts it to pool-spirit. We make one single tls server certificate for each pool-spirit which only includes the pool-spirit service clusterIP.
- controller generates kubeconfig for users to access pool-spirit. The server address in kubeconfig is set to https://{nodeIP}:10270. In addition, the client certificate authority in kubeconfig should be restricted.
- When the pool-coordinator is rebuilt, spirit-controller will clean up and rebuild the tls server certificate.

**Comment by rambohe-ch** [comment]
> * We make one single tls server certificate for each pool-spirit which only includes the pool-spirit service clusterIP.
@luc99hen I think it's good idea to add dns names(like pool-coordinator-svc, pool-coordinator-svc.kube-system, pool-coordinator-svc.kube-system.svc, pool-coordinator-svc.kube-system.svc.cluster.local) into tls server certificate.
