### ISSUE TITLE
[feature request]`NodePool Governance Capability`: Add component `pool-coordinator` 

### ISSUE THREAD

**Issue by Peeknut** [openyurtio/openyurt#777]
**What would you like to be added**:
pool-coordinator uses apiserver and etcd in a pod mode, and etcd needs to use memory storage. Its life cycle is controlled by YurtAppDaemon, and helm charts of `pool-coordinator` will be prepared . So the following work needs to be done:

Before implementation, the following tests are required：
- When there are many resources in the NodePool (500 Nodes, 1k Pods), whether etcd, which stores resources in memory, can work normally.
- When there are many resources in the NodePool (500 Nodes, 1k Pods), whether the node's leader election through etcd can work normally.

You can try to build an etcd with data stored in memory in the following ways: https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/demo.md

If there is a problem with the test, please comment and discuss. If there is no problem with the test, in order to implement pool-coordinator, the following work needs to be done:

- After pool-coordinator starts, it is required to prepare clusterrolebinding associated with view rights in the kube-apiserver. This ensures that kubectl tool in NodePool can successfully get/list data using kubeconfig certificate.
- Provide the image of pool-coordinator and related documents for deploying pool-coordinator.

 **Notes**: For details, please refer to the proposal: https://github.com/openyurtio/openyurt/pull/772

**Why is this needed**:
As mentioned in the proposal(https://github.com/openyurtio/openyurt/pull/772), pool-coordinator provides operation and maintenance functions and autonomous functions for NodePool. It is the core component.

**others**
/kind feature

**Comment by donychen1134** [comment]
"You can try to build an etcd with data stored in memory in the following ways: https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/demo.md"
Whether this doc link is wrong? I can't find any "build an etcd with data stored in memory" information in the web page.
Maybe I can use the follow way to let etcd data store in memory:
  volumes:
  - emptyDir:
      medium: Memory
    name: etcd-data

**Comment by rambohe-ch** [comment]
> "You can try to build an etcd with data stored in memory in the following ways: https://github.com/kubernetes-sigs/cluster-api-provider-nested/blob/main/virtualcluster/doc/demo.md" Whether this doc link is wrong? I can't find any "build an etcd with data stored in memory" information in the web page. Maybe I can use the follow way to let etcd data store in memory:
> 
> ```
>   volumes:
>   - emptyDir:
>       medium: Memory
>     name: etcd-data
> ```

@donychen1134 yes, use emptyDir volume for etcd data.
