### ISSUE TITLE
[vote] the name of component that provide governance ability in nodepool.

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#786]
**What would you like to be added**:
In the [proposal](https://github.com/openyurtio/openyurt/pull/772), a new component(named pool-spirit) will be added in the edge NodePool. the new component mainly provides the following ability:
- To store metadata for NodePool as a kv storage
- To provide a distributed lock for leader electing.
- To use native kubernetes API to provide these above two abilities.

For these abilities, the name `pool-spirit` maybe make end user confused, so OpenYurt community have decided to rename the new component. all candidate names as following: 
- pool-spirit: 节点池精灵
- pool-coordinator: 节点池协调器
- pool-linker: 节点池连接器
- pool-fort: 大本营
- sheepdog：牧羊犬
- yurt-minister: yurt主持
- shepherd：牧羊人
- hive: 蜂巢
- pool-harbor: 节点池港口

please select your favourite name and reply this issue. 

btw: other names for new component are also welcome.

**Comment by iutx** [comment]
sheepdog+1

**Comment by rambohe-ch** [comment]
sheepdog +1

**Comment by njucjc** [comment]
sheepdog +1

**Comment by zzguang** [comment]
yurt-minister

**Comment by leejean-wq** [comment]
pool-coordinator+1

**Comment by zyjhtangtang** [comment]
sheepdog +1

**Comment by donychen1134** [comment]
pool-coordinator +1

**Comment by luc99hen** [comment]
sheepdog +1

**Comment by ujnzxw** [comment]
shepherd +1
In my opinion, "shepherd" is a better name than "sheepdog". 
The role of a Shepherd is a leader flock of sheep and manage them. A shepherd is a person who tends, herds, feeds, or guards flocks of sheep
But the primary role of a sheepdog is to assist the shepherd. The sheepdog assists the shepherd with gathering and handling the sheep.
[Be a Shepherd Not a Sheepdog](https://medium.com/@tkbeyond/be-a-shepherd-not-a-sheepdog-de515747233b#:~:text=The%20sheepdog%20isn't%20a,gathering%20and%20handling%20the%20sheep.)

**Comment by Congrool** [comment]
sheepdog +1
@ujnzxw 
From my perspective, sheepdogs are not only responsible for guarding sheep but also moving, managing and controling sheep. We can see that on [wiki](https://en.wikipedia.org/wiki/Sheep_dog#:~:text=A%20sheep%20dog%20or%20sheepdog,control%20sheep%20and%20other%20livestock.).

> But the primary role of a sheepdog is to assist the shepherd.

I totally agree the opinion, and that is one of the reasons I prefer "sheepdog". Because this new component is used for nodepool-level autonomy when there're some nodes(sheep) offline. It will not replace the API Server(shepherd) at the cloud, which has stronger capability and manages the whole cluster, and only serve as an assistance.

**Comment by windydayc** [comment]
yurt-minister +1

**Comment by ujnzxw** [comment]
> sheepdog +1 @ujnzxw From my perspective, sheepdogs are not only responsible for guarding sheep but also moving, managing and controling sheep. We can see that on [wiki](https://en.wikipedia.org/wiki/Sheep_dog#:~:text=A%20sheep%20dog%20or%20sheepdog,control%20sheep%20and%20other%20livestock.).
> 
> > But the primary role of a sheepdog is to assist the shepherd.
> 
> I totally agree the opinion, and that is one of the reasons I prefer "sheepdog". Because this new component is used for nodepool-level autonomy when there're some nodes(sheep) offline. It will not replace the API Server(shepherd) at the cloud, which has stronger capability and manages the whole cluster, and only serve as an assistance.

Thanks for your reply.
Based on my understanding, the project name is "OpenYurt", shepherd belongs to Yurt, API Server is the higher-level component than Yurt, we can call it "government", maybe. 
Generally, one shepherd can only manage one flock of sheep at the same time, and the shepherd manages the sheep(edge nodes) far away from the Yurt. The shepherd can work standalone(autonomy), but the sheepdog cannot.  And the sheepdog has no ability to determine which sheep is the HEAD of flocks of sheep(To provide a distributed lock for leader electing).

Maybe I have some misunderstanding about the project name or the role of this new component. 
Anyway, either name is OK to me:)

**Comment by rambohe-ch** [comment]
> > sheepdog +1 @ujnzxw From my perspective, sheepdogs are not only responsible for guarding sheep but also moving, managing and controling sheep. We can see that on [wiki](https://en.wikipedia.org/wiki/Sheep_dog#:~:text=A%20sheep%20dog%20or%20sheepdog,control%20sheep%20and%20other%20livestock.).
> > > But the primary role of a sheepdog is to assist the shepherd.
> > 
> > 
> > I totally agree the opinion, and that is one of the reasons I prefer "sheepdog". Because this new component is used for nodepool-level autonomy when there're some nodes(sheep) offline. It will not replace the API Server(shepherd) at the cloud, which has stronger capability and manages the whole cluster, and only serve as an assistance.
> 
> Thanks for your reply. Based on my understanding, the project name is "OpenYurt", shepherd belongs to Yurt, API Server is the higher-level component than Yurt, we can call it "government", maybe. Generally, one shepherd can only manage one flock of sheep at the same time, and the shepherd manages the sheep(edge nodes) far away from the Yurt. The shepherd can work standalone(autonomy), but the sheepdog cannot. And the sheepdog has no ability to determine which sheep is the HEAD of flocks of sheep(To provide a distributed lock for leader electing).
> 
> Maybe I have some misunderstanding about the project name or the role of this new component. Anyway, either name is OK to me:)

@ujnzxw Very appreciate for your reply. we will keep this vote until 4.1(Friday) and wait for more discussion and vote.
According to the voting rules, we will finally choose the name with the most votes.

**Comment by dongzl** [comment]
pool-coordinator +1

**Comment by qclc** [comment]
pool-coordinator +1

**Comment by GLTSC** [comment]
shepherd +1

**Comment by cishidai** [comment]
pool-coordinator + 1

**Comment by h3ar7dump** [comment]
new proposal: 
hive

**Comment by JcJinChen** [comment]
pool-coordinator + 1

**Comment by Fei-Guo** [comment]
pool-coordinator +1  or new proposal: pool-harbor

**Comment by lorrielau** [comment]
sheepdog+1

**Comment by showeriszero** [comment]
yurt-minister+1

**Comment by DrmagicE** [comment]
pool-coordinator + 1

**Comment by rambohe-ch** [comment]
more than 20 people have already voted, and the top three names are:
- pool-coordinator  8votes
- sheepdog 7votes
- yurt-minister 3votes

so according to the voting rules, `pool-coordinator` becomes the name for the new component in NodePool.
