### ISSUE TITLE
[feature request]  Update yurt-app-manager-api  repo

### ISSUE THREAD

**Issue by Fei-Guo** [openyurtio/openyurt#797]
**What would you like to be added**:

The  yurt-app-manager-api  repo should be updated with the latest API changes.

**Why is this needed**:

The users that import this repo will get confused for any API changes in the main repo.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@Fei-Guo Ok, I will update `yurt-app-manager-api` repo with the new API definition.

**Comment by kadisi** [comment]
https://github.com/openyurtio/yurt-app-manager-api/pull/1
