### ISSUE TITLE
[BUG] DockerHub YurtAppManager Image Architecture Error

### ISSUE THREAD

**Issue by JameKeal** [openyurtio/openyurt#812]
**What happened**:
When I download openyurt/yurt-app-manager:latest@sha256:5280d56b463575fbe1682de1726347eb33021e5ab37d09a2528a9b39f649acf1 image, I want to get arm64 image, but the result is amd64.

![1650509546333_4C17AC8D-84F4-4b37-8964-F4204FF366A7](https://user-images.githubusercontent.com/70508195/164363794-a4c932c3-6f4a-4198-9932-56f2d34d4a26.png)

![2572f032de8ef370a4b2d0bcaa8ea84](https://user-images.githubusercontent.com/70508195/164364141-74a9d23a-c4d0-441e-b511-315d165722ba.png)

**What you expected to happen**:
All yurt images is correct wheather server architecture, not merely yurt-app-manager

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
@JameKeal This problem has been solved by the pull request: https://github.com/openyurtio/yurt-app-manager/pull/61
