### ISSUE TITLE
[feature request] support chart repo

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/openyurt#824]
**What would you like to be added**:

Create a new github repository, and use it store helm charts. We could reference other projects, like [argo](https://github.com/argoproj/argo-helm) and [prometheus](https://github.com/prometheus-community/helm-charts)

**Why is this needed**:

Currently we need clone yurtcluster-operator, then helm install it. It's not convenient.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
> **What would you like to be added**:
> 
> Create a new github repository, and use it store helm charts. We could reference other projects, like [argo](https://github.com/argoproj/argo-helm) and [prometheus](https://github.com/prometheus-community/helm-charts)
> 
> **Why is this needed**:
> 
> Currently we need clone yurtcluster-operator, then helm install it. It's not convenient.
> 
> **others** /kind feature

@huiwq1990 It's a good idea to create a new repo(like openyurt-helm) for storing helm charts of all of OpenYurt components. and i will fix it.

**Comment by rambohe-ch** [comment]
@huiwq1990 done. https://github.com/openyurtio/openyurt-helm

**Comment by rambohe-ch** [comment]
Fixes by #905
