### ISSUE TITLE
[Question] Does OpenYurt support Istio?

### ISSUE THREAD

**Issue by FengGaoCSC** [openyurtio/openyurt#835]
Does OpenYurt support Isito service mesh  ?

Regards

**others**
/kind question

**Comment by rambohe-ch** [comment]
@FengGaoCSC Very appreciate you for raising issue. Istio will soon be supported in OpenYurt smoothly. we have launched a new project [raven](https://github.com/openyurtio/raven) to solve the network requirements that needed by istio.

**Comment by FengGaoCSC** [comment]
@rambohe-ch  very thanks,  I got it

**Comment by rambohe-ch** [comment]
> @rambohe-ch very thanks, I got it

@FengGaoCSC OpenYurt Community Group ID: 31993519, welcome you to join into the group by dingding software.

**Comment by FengGaoCSC** [comment]
> > @rambohe-ch very thanks, I got it
> 
> @FengGaoCSC OpenYurt Community Group ID: 31993519, welcome you to join into the group by dingding software.

thanks I will join now

**Comment by rambohe-ch** [comment]
@FengGaoCSC we have raised a project in 2022 ASOC for intergating istio with OpenYurt. detail info is here: https://github.com/openyurtio/openyurt/issues/855

so i will close this issue and you can reopen it you need.
