### ISSUE TITLE
[feature request] Add addon subcommand to deploy openyurt component

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/openyurt#837]
**What would you like to be added**:

1) all charts store in repo `https://github.com/openyurtio/openyurt-helm`
2) add subcommand addon, which can deploy yurt-app-manager, yurt-edgex-manager and so on;
The addon can call `helm install` to deploy instance.

**Why is this needed**:

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@huiwq1990 It's a good idea to add a subcommand for installing addons. and we will prepare all of addons' helm charts in the next version(OpenYurt v0.8.0)

**Comment by rambohe-ch** [comment]
@Congrool Do you have any comments?

**Comment by rambohe-ch** [comment]
@huiwq1990 As we have discussed in this issue #846 , and we will not add subcommand for deploying OpenYurt components. so i will go to close this issue.
