### ISSUE TITLE
[Question] Should yurt-controller-manager deploy as Daemonset or static pod on control plane?

### ISSUE THREAD

**Issue by DrmagicE** [openyurtio/openyurt#845]
**What happened**:
yurtctl/yurtadm use 1 replicas `Deployment` to deploy  `yurt-controller-manager`.  Under such circumstances, if the node where `yurt-controller-manager` deployed shutdowns, the node won't turn into NotReady state, so the `yurt-controller-manager` won't be re scheduled which may cause issues.

**What you expected to happen**:
As the `yurt-controller-manager` is a replacement of the NodeLifecycleController in `kube-controller-manager`, which is usually
deployed as a static pod on each control plane node.

Maybe the `yurt-controller-manager` should follow the same deployment way (Daemonset or static pod)? 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@DrmagicE Thanks for raising the issue. At present we can use deployment.replicas=2 in order to make the ycm high availbility.

btw: we are now reforming ycm, remove NodeLifeCycle controller from ycm and put NodeLifeCycle controller back to kcm.
issue reference link: https://github.com/openyurtio/openyurt/issues/776

**Comment by DrmagicE** [comment]
@rambohe-ch Thanks for your quick response. I would try daemonset for now and looking forward to the new feature.
