### ISSUE TITLE
[Question]how many installation ways that should be provided for end users.

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#846]
**What happened**:
  1. At present, we have provided 5 ways for end users to install OpenYurt cluster. and from the beginner's perspective, there are too many installation ways and it's easy get confused for end users. https://openyurt.io/docs/next/installation/summary
  
  2. [YurtCluster](https://github.com/openyurtio/yurtcluster-operator) is a controller that used for converting K8s to OpenYurt or vice versa. As OpenYurt evolves, in order to use some features(like service topology, InClusterConfig etc.), pods on edge nodes should be restarted after node conversion. so these kind of requirements are very hard to satisfy by YurtCluster.

**What you expected to happen**:
maybe we need to reduce some installation ways, at the same time, we need to define the concrete scenario for every installation ways. and I want to introduce my consideration about installation ways that we should provide to end users.
1. OpenYurt Experience Center:
   - end user only need to join edge nodes.
   - used for showing new features of OpenYurt and integrating with other open source projects.
 
2. Manually Setup
   - Use in a production environment
   - Installation steps:  k8s master --> k8s addon configure --> helm install OpenYurt --> yurtadm join edge nodes
   - helm charts of OpenYurt are managed here: https://github.com/openyurtio/openyurt-helm

3. Yurtadm init
    - base on the [sealer](https://github.com/sealerio/sealer), to create a OpenYurt cluster
    - not recommend to use in production environment before stable stage
    -  use `yurtadm` to join edge nodes

and other installation ways like `yurtctl convert/revert` and `YurtCluster` will be deprecated in the future. and `YurtCluster` will be used for OpenYurt cluster's status inspection and fault alarm, etc.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@gnunu @SataQiu @lonelyCZ @hwq830 @cndoit18 @Congrool

**Comment by cndoit18** [comment]
I like this👍 
cc @zhangzhenyuyu

**Comment by SataQiu** [comment]
+1

**Comment by gnunu** [comment]
+1

**Comment by huiwq1990** [comment]
+1
