### ISSUE TITLE
[feature request] openyurt components crd naming convention and style

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/openyurt#852]
**What would you like to be added**:

Currently, openyurt components have different naming convention and style, like `yurt-app-manager's` [UnderScoreCase](https://github.com/openyurtio/yurt-app-manager/blob/master/pkg/yurtappmanager/apis/apps/v1alpha1/yurtingress_types.go#L74
) and `yurt-edgex-manager's` [AllLowCase](https://github.com/openyurtio/yurt-edgex-manager/blob/main/api/v1alpha1/edgex_types.go#L54).  It's better use `CamelCase`, like [k8s's](https://github.com/kubernetes/kubernetes/blob/fa7309438f7c6dc1c1d981ba05b3f174ea25d502/staging/src/k8s.io/api/core/v1/types.go#L3186)

```
	ImagePullSecrets []LocalObjectReference `json:"imagePullSecrets,omitempty" patchStrategy:"merge" patchMergeKey:"name" protobuf:"bytes,15,rep,name=imagePullSecrets"`
```

**Why is this needed**:

It's more canonicalization and reduce crd upgrade risk.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@huiwq1990 Very appreciate for your issue, and i agree with your suggestion to conform for K8s naming convention. 
 i think we can revise the CRD naming convention in OpenYurt v0.8.0.

**Comment by YTGhost** [comment]
Does this feature still need to be done? I think I can do it.

**Comment by rambohe-ch** [comment]
> Does this feature still need to be done? I think I can do it.

@YTGhost I think nobody is focusing on this issue, and i'm glad that you can pick up this issue. 
/assign @YTGhost

**Comment by YTGhost** [comment]
> > Does this feature still need to be done? I think I can do it.
> 
> @YTGhost I think nobody is focusing on this issue, and i'm glad that you can pick up this issue. /assign @YTGhost

PTAL
