### ISSUE TITLE
ASOC 2022: Make container network solution(calico) work on the OpenYurt even if cloud-edge network off

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#857]
# Describe your problem
  Deploy container network solution(calico) in OpenYurt cluster, and make calico network can work even if edge nodes restart when cloud-edge network off.
  Meanwhile, when the edge network can not work properly for some unknown reasons(like iptables settings fault), provide a way or a tool to detect the network problem.

  在OpenYurt集群中部署calico容器网络方案，并且保证在云边网络断连状态下即使边缘节点重启calico网络也能正常工作。同时，当边缘网络由于某些未知原因(如iptables设置错误)无法正常工作时，提供一种检测网络问题的方法或工具。

# Additional context
This issue is part of our [Alibaba Summer of Code (2022) Program](https://github.com/openyurtio/openyurt/issues/851)

Difficulty: Hard
Mentor: wangchenglong (@luckymrwang )

**Comment by rambohe-ch** [comment]
@Congrool please comment and close this issue.

**Comment by Congrool** [comment]
Work of this issue has been completed in #882 . #882 introduces great changes to yurthub which not only containing supporting calico and should be merged according to the community road map.
.
So, I close this issue. If any further problem found, we can discuss in #882.
