### ISSUE TITLE
[feature request] yurtadm token subcommand

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/openyurt#859]
**What would you like to be added**:

Add a `token` subcommand for admin when need to join an edge node.

**Why is this needed**:

When join a edge node by execute `yurtadm join`, we should set token parameter. Openyurt should provide a way to generate the token, for examle imitate `kubeadm join`'s implementation.

**others**
/kind feature

**Comment by Congrool** [comment]
sounds good, agree +1

**Comment by rambohe-ch** [comment]
@huiwq1990 Very appreciate for your suggestion. would you be able to take over this work?

**Comment by huiwq1990** [comment]
I wolud like to implement this. There ary many subcommends, like `yurtadm token create`, `yurtadm token list` and so on. How many features do `yurtadm token` should cover. I suggest we just implement `yurtadm token create`, and  close the loop on `yurtadm`. If openyurt users want to use more management functions, we cloud recommend them use `kubeadm`. 
@Congrool @rambohe-ch What's your suggestions?

**Comment by rambohe-ch** [comment]
> I wolud like to implement this. There ary many subcommends, like `yurtadm token create`, `yurtadm token list` and so on. How many features do `yurtadm token` should cover. I suggest we just implement `yurtadm token create`, and close the loop on `yurtadm`. If openyurt users want to use more management functions, we cloud recommend them use `kubeadm`. @Congrool @rambohe-ch What's your suggestions?

@huiwq1990 I think feature of command `yurtadm token create` is the same as `kubeadm token create`. and how about wrap `kubeadm token` in `yurtadm token` command, so maybe we will not confused how many features does `yurtadm token` should cover.
