### ISSUE TITLE
[feature request]when nodepool or service change, service topology function can work

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#871]
**What would you like to be added**:
For `servicetopology` filter in Yurthub, beside endpointSlice resource, nodePool and service change can be handled.
maybe `endpoints` filter also should be enhanced.

**Why is this needed**:
`servicetopology` filter in Yurthub can work properly when endpointSlices resource change. if nodePool or service resource change, like updating topology annotation for service or removing node from nodePool, endpointslices on the edge nodes will not be updated.

**others**
/kind feature

**Comment by LinFCai** [comment]
@rambohe-ch. Hello, I will take over this work.

**Comment by rambohe-ch** [comment]
> @rambohe-ch. Hello, I will take over this work.

@LinFCai Thank you for taking over this work. /assign @LinFCai

**Comment by rambohe-ch** [comment]
@LinFCai please post a proposal about this feature before making code pull request. and how to make the proposal, you can reference this example: https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20210720-data-filtering-framework.md

**Comment by LinFCai** [comment]
ok

**Comment by rambohe-ch** [comment]
@LinFCai Hi, Do you have any progress for this issue?

**Comment by LinFCai** [comment]
@rambohe-ch I have posted the proposal here https://github.com/openyurtio/openyurt/pull/1006.
