### ISSUE TITLE
[Question] what's the cm of yurt-tunnel-nodes

### ISSUE THREAD

**Issue by dbaicss** [openyurtio/openyurt#876]
![image](https://user-images.githubusercontent.com/45416253/172803475-1a193bec-b090-4eff-9305-2157efb7df4b.png)
文档里面安装openyurt的前置条件，需要把coredns改成ds方式部署，挂载yurt-tunnel-nodes这个cm，这个cm哪里有？
/kind question

**Comment by Congrool** [comment]
It should be under ns kube-system. You can check it with: 
```bash
$ kubectl get cm yurt-tunnel-nodes -nkube-system
NAME                DATA   AGE
yurt-tunnel-nodes   1      3d3h
```

**Comment by dbaicss** [comment]
ok,thanks,got it!

**Comment by rambohe-ch** [comment]
@dbaicss I think this issue has been solved, so i will go to close this issue. and you can reopen it if you need to continue to follow this case.
