### ISSUE TITLE
yurtadm init failed on sealer v0.8.5 cluster

### ISSUE THREAD

**Issue by jgmiao** [openyurtio/openyurt#890]
yurtadm versioin
![image](https://user-images.githubusercontent.com/6794193/174256269-8cf97b4b-c978-4148-8a25-1c196c0c3f99.png)

i have initialized the k8s cluster with sealer v0.8.5, then i init openyurt with yurtadm failed: 
`Error: The existing sealer version v0.8.5 is not supported, please clean it. Valid server versions are [v0.6.1].`

![image](https://user-images.githubusercontent.com/6794193/174256590-85947c5f-2cb7-4d48-886d-0f7fbb4f8d5a.png)

![image](https://user-images.githubusercontent.com/6794193/174257120-ffc5ba15-7175-40cb-b729-3090ea9d6f93.png)

**Comment by windydayc** [comment]
Now yurtadm only support sealer v0.6.1.

**Comment by windydayc** [comment]
Currently, it is recommended to install openyurt manually. 
https://openyurt.io/docs/installation/manually-setup

**Comment by jgmiao** [comment]
> 

ok, i try it
