### ISSUE TITLE
[BUG]yurt-hub container can't start when rejoin yurt cluster.

### ISSUE THREAD

**Issue by showeriszero** [openyurtio/openyurt#891]
**What happened**:
yurt-hub container report follow error:
iptables v1.8.7 (legacy): Couldn't load target `NOTRACK':No such file or directory
when rejoin yurt cluster.

**What you expected to happen**:
yurt-hub container start successed.

**How to reproduce it (as minimally and precisely as possible)**:
rejoin cluster, manual install Yurthub.

**Anything else we need to know?**:
hardware is arm64.

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):　v1.19.8
- OS (e.g: `cat /etc/os-release`):　Ubuntu 18.04.6 LTS (Bionic Beaver)
- Kernel (e.g. `uname -a`):　4.9.140-tegra
- Install tools:
- Others:

**others**

/kind bug

**Comment by rambohe-ch** [comment]
Fixes by #966
