### ISSUE TITLE
[feature request] use `kube-webhook-certgen` manage webhook certificate 

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/openyurt#893]
**What would you like to be added**:

Use [kube-webhook-certgen](https://github.com/jet/kube-webhook-certgen) to generate webhook certificate, like [ingress-nginx](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx/templates/admission-webhooks or [kubevela](https://github.com/kubevela/kubevela/tree/master/charts/vela-core/templates/admission-webhooks).

**Why is this needed**:
yurt-app-manager and raven-controller-manager implement generate certificate by themself, which is not easy to maintenance. Detail code show in file  [webhook_controller.go](https://github.com/openyurtio/yurt-app-manager/blob/master/pkg/yurtappmanager/webhook/util/controller/webhook_controller.go#L205) 

**others**
/kind feature

**Comment by rambohe-ch** [comment]
/assign @kadisi @zzguang @DrmagicE @njucjc

@huiwq1990 It looks like we will import a new component(kube-webhook-certgen) in OpenYurt cluster if we use kube-webhook-certgen to generate webhook certificate. so would you be able to introduce the differences and advantages of kube-webhook-certgen?

**Comment by huiwq1990** [comment]
> @huiwq1990 Maybe we can discuss this issue in the next community meeting.

Ok, I will attend a meeting.

**Comment by gnunu** [comment]
> /assign @kadisi @zzguang @DrmagicE @njucjc
> 
> @huiwq1990 It looks like we will import a new component(kube-webhook-certgen) in OpenYurt cluster if we use kube-webhook-certgen to generate webhook certificate. so would you be able to introduce the differences and advantages of kube-webhook-certgen?

@rambohe-ch @huiwq1990 Sounds we would have at least four repo's in need of cert generation for webhook (openyurt, yurt-app-manager, raven, pool-coordinator). We do need a common API for this. How do we do that? We have theses choices:
1) Use https://github.com/jet/kube-webhook-certgen
2) Add a new certs repo under openyurt.io
3) Expose this part from yurt-app-manager
4) Add an API repo for the whole OpenYurt, then add certs related functions into this repo.

Which one is the best?

**Comment by huiwq1990** [comment]
@gnunu @rambohe-ch I recommend the first one. As:
1) [kube-webhook-certgen](https://github.com/jet/kube-webhook-certgen) could patch k8s webhooks and generate certs for https server;
2) If we maintain the certs code, we need cover unit tests and there are not difference in implementing mechanisms;
3) Some famous projects use it too, it's relatively mature;

**Comment by huiwq1990** [comment]
https://github.com/kubevela/kubevela/discussions/4490

**Comment by huiwq1990** [comment]
Someone post the `admissionregistration/v1beta1` issue in https://github.com/jet/kube-webhook-certgen/issues/30 . `jet/kube-webhook-certgen` does not want to solve it and recommand use https://github.com/kubernetes/ingress-nginx/tree/main/images/kube-webhook-certgen. So does we maintain the code ourself?
@rambohe-ch @gnunu

**Comment by rambohe-ch** [comment]
> [kubevela/kubevela#4490](https://github.com/kubevela/kubevela/discussions/4490) @rambohe-ch @gnunu the project alreay maintian the webhook patch function, we can follow it.

@huiwq1990 I think it's not good idea to maintain a `kube-webhook-certgen` repo in OpenYurt. If kubevela has maintained a  repo, maybe we can use it or leverage it.

**Comment by rambohe-ch** [comment]
yurt-app-manager and yurt-edgex-manager have already used `kube-webhook-certgen` to manage webhook certificate.
