### ISSUE TITLE
[feature request] add grafana to help monitor openyurt itself

### ISSUE THREAD

**Issue by adamzhoul** [openyurtio/openyurt#895]
**What would you like to be added**:

add grafana page to monitor openyurt.

**Why is this needed**:

to help monitoring openyurt components.
I see some like yurthub、yurttunnel have exposed metric already.

if we provide an out-of-box grafana page, it will be nice.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@adamzhoul yes, it's a good idea to add configuration for prometheus. Would you like to update this tutorial?
https://openyurt.io/docs/user-manuals/monitoring/prometheus
