### ISSUE TITLE
Openyurt DingTalk Invitation Code Expired 

### ISSUE THREAD

**Issue by shubham-cmyk** [openyurtio/openyurt#896]
I am not able to join the DingTalk group of openyurt can someone update the group join QR code.

**Comment by whisperzzZ** [comment]
The DingTalk group number is 31993519 and you can search using that number

**Comment by shubham-cmyk** [comment]
@whisperzzZ It shows also Invalid

**Comment by whisperzzZ** [comment]
> @whisperzzZ It is showing invalid

Type 31993519 in the search box and then  choose the  'Search public groups: 31993519' button?( ‘网络查找公开群组’)
I've tried it on my phone and it's available. Sry for not giving you the QR code ,it seems only administrators can share it.

**Comment by shubham-cmyk** [comment]
Thanks a lot!
