### ISSUE TITLE
[feature request]About edge ingress revealing the hostnetwork mode

### ISSUE THREAD

**Issue by yingjianjian** [openyurtio/openyurt#898]
**What would you like to be added**:
At present, the ports revealed by edge ingress are all large random port numbers. We want to fix 80 port access.

reason:

1. there may not be an agent on the customer's side, but it doesn't seem reasonable to add a port number when accessing services,

2. the nodeport port is not fixed. When accessing each node pool, you need to check the port corresponding to the node pool level

**Why is this needed**:
We want to fix 80 port access.

**others**
/kind feature

**Comment by zzguang** [comment]
Edge ingress is focusing on ingress feature from nodepool level and expose the service through NodePort/EIP to outside of the nodepool, users are not aware which node in the pool is hosting the nginx ingress controller. If we introduce the host network node, it seems not make sense. I have no idea whether it is a common requirement and how to support it by now, any suggestions are welcome.

**Comment by yingjianjian** [comment]
> > **What would you like to be added**: At present, the ports revealed by edge ingress are all large random port numbers. We want to fix 80 port access.
> > reason:
> > 
> > 1. there may not be an agent on the customer's side, but it doesn't seem reasonable to add a port number when accessing services,
> > 2. the nodeport port is not fixed. When accessing each node pool, you need to check the port corresponding to the node pool level
> > 
> > **Why is this needed**: We want to fix 80 port access.
> > **others** /kind feature
> 
> @yingjianjian Because each node pool will use a unique NodePort service for nginx ingress controller and service port should be different, so maybe we can not fix port 80 for all services of nginx ingress controller.

Yes, I understand, so I was wondering whether the hostnetwork mode can be provided so that port 80 can be used, but I can't judge whether this part is meaningful
