### ISSUE TITLE
[feature request] fuzz testing support

### ISSUE THREAD

**Issue by huiwq1990** [openyurtio/openyurt#900]
**What would you like to be added**: 

1) Add openyurt to [CNCF-Fuzzing](https://github.com/cncf/cncf-fuzzing)

2) Continuous fuzzing by way of [OSS-Fuzz](https://github.com/google/oss-fuzz) 

**Why is this needed**:
1) Fuzz will improve openyurt security

2) Fuzz is gaining more and more cncf projects

3) Recently I  write a test case for yurtappdaemon, and find a nil pointer bug
![image](https://user-images.githubusercontent.com/4555057/176982298-d4ac0d92-34d3-46e7-9aa9-5ddd9ea2fada.png)

**Reference**

https://www.cncf.io/blog/2022/06/28/improving-security-by-fuzzing-the-cncf-landscape/

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@huiwq1990 It's a good idea to add fuzz testing support for OpenYurt. and i think we can support it in the 2022 OSPP topic. @Congrool @lorrielau Do you have any comments?

**Comment by Congrool** [comment]
Sry for late reply. I'm not familiar with the fuzzing test, a little time needed to figure it out.
