### ISSUE TITLE
OSPP 2022: Edge application update model in cloud-edge collaboration architecture

### ISSUE THREAD

**Issue by hxcGit** [openyurtio/openyurt#914]
# Describe your problem
In cloud-edge collaboration scenario, the edge is connected to the cloud through the public network, and the edge nodes may be disconnected from the cloud due to various objective or subjective factors. The update of Workloads (Deployment, DaemonSet, etc.) in the native Kubernetes relies on the connectivity of the edge nodes to the cloud network. Therefore, when the cloud-edge network is disconnected,  workloads cannot be successfully updated, we need to explore a suitable way to update the application.

在云边协同场景下，边缘与云端通过公网连接(例如WIFI，4G，5G等)，由于各种客观或主观因素，边缘节点可能与云端断开网络连接。而原生Kubernetes中的Workload(如Deployment，DaemonSet等)的升级都依赖边缘节点与云端网络连通。因此当云边网络断连状态下，如何完成边缘业务的升级成为云边协同场景下一个非常值得探索的课题。

This issue is part of [summer-ospp](https://summer-ospp.ac.cn/#/org/prodetail/225fc0106)

Mentor: Bingchang Tang

**Comment by rambohe-ch** [comment]
Fixes by #921
