### ISSUE TITLE
[performanace test] add performance metrics and test data for yurthub component

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#915]
**What would you like to be added**:
Yurthub component is a sidecar on edge nodes for forwarding traffic between K8s master(like kube-apiserver) and K8w worker components(like kubelet, kube-proxy, etc.). It's important to add test data for yurthub component that include the following performance metrics:
- resource metrics: cpu, memory
- requests traffic: the traffic between kube-apiserver and edge nodes
- request latency: the latency of requests that comes from edge nodes.

**Why is this needed**:
add performance test data for yurthub, so end user can decide to use yurthub or not based on these data.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
we will post a performance test report for 100 edge nodes OpenYurt cluster.

**Comment by luc99hen** [comment]
- 2000 Pod 
- 1000 Service

**Comment by luc99hen** [comment]
The report has been submit in https://github.com/openyurtio/openyurt.io/pull/199 .

**Comment by rambohe-ch** [comment]
> The report has been submit in [openyurtio/openyurt.io#199](https://github.com/openyurtio/openyurt.io/pull/199) .

@luc99hen i will close this issue.
