### ISSUE TITLE
[unit test] improve unit test coverage for yurthub

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#917]
**What would you like to be added**:
improve unit test coverage for yurthub:

- current coverage: 45%
https://app.codecov.io/gh/openyurtio/openyurt/compare/911/tree/pkg/yurthub

- target coverage: 70%

**Why is this needed**:
improve unit test coverage for OpenYurt project.

**others**
/kind feature

**Comment by Congrool** [comment]
Since we're pending at #882 which has great changes on yurthub cache components, could we write unit tests after #882 being merged? Otherwise we have to rewrite these tests later.

Also, we'd better do #857 based on #882, otherwise we have to retest it later.

**Comment by rambohe-ch** [comment]
> Since we're pending at #882 which has great changes on yurthub cache components, could we write unit tests after #882 being merged? Otherwise we have to rewrite these tests later.
> 
> Also, we'd better do #857 based on #882, otherwise we have to retest it later.

@Congrool ok, i will focus on reviewing #882 and merge this pull request before unit test.
