### ISSUE TITLE
[feature request] Need /retest bot command

### ISSUE THREAD

**Issue by Congrool** [openyurtio/openyurt#923]
**What would you like to be added**:

Add new command `/retest` to bot. It can re-trigger the CI to retest the pr.

**Why is this needed**:

Sometimes the CI(Github Action) may fail by accident, for example e2e-tests fail for timeout. We need a way for contributors to retest their pr in this case.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
@Congrool It's a good idea to add /retest command.

**Comment by rambohe-ch** [comment]
@kadisi would you be able to handle this case?

**Comment by rambohe-ch** [comment]
@Congrool `/rerun` command is supported, reviewers or higher member comment `/rerun` on the pull requests, all failed workflows will be triggered to rerun. #1784
