### ISSUE TITLE
[Question] What's the best practice of adding cache agent?

### ISSUE THREAD

**Issue by Congrool** [openyurtio/openyurt#937]
**What happened**:

If users want to cache resources for a new agent, they should 
1. first, figure out the cache-agent's client name, which may not always be same as its component name, such as `go-http-client` for `calico-node`
2. second, add the cache-agent's name to the cache_agents field of yurt-hub-cfg
3. third, restart the component in order to let all resources it needed to pass the yurthub and be cached

The 1st and 3rd step is not that convenient for developers and users. 
1. The developers of openyurt should figure out the map between client name and component name, and the users can only pick what they need in this map. 
2. If the component is deployed as daemonset, it means running instance on each edge node should be restart to make sure all resources it need during runtime be cached at local.

**What you expected to happen**:

There should be a more user-friendly and extensible way to implement the edge cache, avoiding adaptation work for community and restart work for users.

**Anything else we need to know?**:

It's a dicussion of how to cache resources, and maybe also the further work we need to do.

**others**
/kind question

**Comment by rambohe-ch** [comment]
@Congrool cache_agents can be set with "*" to enable cache for all components that access kube-apiserver through yurthub. and this feature is added in the pull request: https://github.com/openyurtio/openyurt/pull/727

**Comment by rambohe-ch** [comment]
@Congrool i think this issue can be closed now because "*" is supported to configure cache_agents. and restart of components improvement maybe need to discuss in the future.

and you can feel free to reopen this issue if you need.
