### ISSUE TITLE
[Question] Will provide several installation methods in the future

### ISSUE THREAD

**Issue by slm940208** [openyurtio/openyurt#939]
The official documentation was removed from the installation method of yurtcluster-operator. Is it not supported by the follow-up?
Will provide several installation methods in the future

**Comment by Congrool** [comment]
Yes, in summary
1. Manual installation will be remained as it is.
2. yurtadm init/join is under improvement, see https://github.com/openyurtio/openyurt/pull/902
3. Helm install will be supported in the future, see https://github.com/openyurtio/openyurt/blob/master/docs/proposals/20220526-install-openyurt-components-using-helm.md
