### ISSUE TITLE
[feature request] Do not post coverage rate to Codecov when it is not `openyurtio/openyurt`

### ISSUE THREAD

**Issue by Congrool** [openyurtio/openyurt#946]
**What would you like to be added**:

We should not post coverage rate to Codecov when we run CI in our forked repo. It always results in failure.

**Why is this needed**:

Sometimes we may trigger the CI in our forked repos to figure out if our prs can pass the CI. But in the forked repo, CI always tries to post the unit test coverage rate to the Codecov site which will fail.

**others**
/kind feature

**Comment by rambohe-ch** [comment]
> 

@Congrool It's a good idea, and will you revise workflow to fix this problem?

**Comment by Congrool** [comment]
Sure.
/assign
