### ISSUE TITLE
[BUG] yurthub invalid arguments error when using yurtadm join

### ISSUE THREAD

**Issue by luc99hen** [openyurtio/openyurt#949]
**What happened**:
Yurthub fails to start when using `yurtadm join`  to join a new node into cluster.

**What you expected to happen**:
`yurtadm` join node succesfully

**How to reproduce it (as minimally and precisely as possible)**:
Use `yurtadm join` to join a new node, it stuck in the postcheck `wait hub agent ready` phase.

**Anything else we need to know?**:
The log of exited yurthub container: 
`Error: invalid argument "" for "--enable-dummy-if" flag: strconv.ParseBool: parsing "": invalid syntax.` 
After checking the generated `/etc/kubernetes/manifests/yurthub.yaml`, we will see this
```yaml
command:
    - yurthub
    - --v=2
    - --server-addr=https://192.168.0.86:6443
    - --node-name=$(NODE_NAME)
    - --join-token=jfsnze.c05kn77m7y1ror9h
    - --working-mode=cloud
    - --enable-dummy-if=
    - --enable-node-pool=
```
It seems that `--enable-dummy-if` is assigned with an invalid null value.

**Environment**:
- OpenYurt version: 0.7.0
- Kubernetes version (use `kubectl version`): v1.22.12
- OS (e.g: `cat /etc/os-release`): CentOS Linux release 7.9.2009
- Kernel (e.g. `uname -a`): 3.10.0-1160.71.1.el7.x86_64
- Install tools: kubeadm & yurtadm 
- Others:

**others**

/kind bug

**Comment by Congrool** [comment]
The reason may be obvious. We should use `--enable-dummy-if=true` or `--enable-dummy-if` instead of `--enable-dummy-if=`, same for `--enable-node-pool=`.

**Comment by Congrool** [comment]
It should be a bug that `yurtadm join` cannot correctly handle arguments of bool.

**Comment by luc99hen** [comment]
Agree +1.  This file was generated [here](https://github.com/openyurtio/openyurt/blob/68a18eeda469fedc9511c4cb669549e3cf5bd213/pkg/yurtadm/cmd/join/phases/joinnode.go#L184). And the passed `ctx` misses these options.  Also the `yurtadm` that I used are downloaded from release v0.7.0. This seems to be fixed in the [PR](https://github.com/openyurtio/openyurt/pull/863). Use the latest `yurtadm` will be fine.

> The reason may be obvious. We should use `--enable-dummy-if=true` or `--enable-dummy-if` instead of `--enable-dummy-if=`, same for `--enable-node-pool=`.

**Comment by rambohe-ch** [comment]
@luc99hen Thank you for raising issue. would you be able to post a pull request to fix this problem?

**Comment by Congrool** [comment]
@rambohe-ch It seems has been solved. Maybe we need backport #863 to v0.7.0 as @luc99hen mentioned.

**Comment by rambohe-ch** [comment]
@luc99hen @Congrool I have backported #863 to branch release-v0.7.
