### ISSUE TITLE
[Question] yurt-tunnel-server server certificate valided failed from APIServer；

### ISSUE THREAD

**Issue by jingxiongljx** [openyurtio/openyurt#951]
**What happened**:
kubectl logs pod from edge-workers. Notified failed to verify x509 server certificate.
![image](https://user-images.githubusercontent.com/89091250/184608294-9ddfa1d3-e700-4e77-aae7-eab4da92f755.png)

May apiserver not verify server certificate from yurt-tunnel-server?

**What you expected to happen**:
can get logs from APIServer（from edge-tunnel）.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OpenYurt version:
- Kubernetes version (use `kubectl version`):
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**others**
/kind question

**Comment by rambohe-ch** [comment]
@jingxiongljx Thank you for raising issue. we have come across the same problem in the issue: https://github.com/openyurtio/openyurt/issues/535, and you need to unset the parameter `--kubelet-certificate-authority` of kube-apiserver.
