### ISSUE TITLE
[feature request]use one repo to manage all api in OpenYurt

### ISSUE THREAD

**Issue by rambohe-ch** [openyurtio/openyurt#953]
**What would you like to be added**:
I want to create a repo named `openyurtio/api` to manage all of the external API types of OpenYurt.  and the api structure as following:
```
openyurtio/api
   - apps
       - v1alpha1
       - v1beta1
   - device
       - v1alpha1
   - network
       - v1alpha1
    - coordinator (TBD)
        - v1alpha1
```
and the relationship between directory and repo is:
```
apps  <-->  yurt-app-manager
device <--> yurt-device-controller
network <--> raven-controller-manager
coordinator <--> pool-coordinator
```

**Why is this needed**:
as you known, there are several api repos in OpenYurt community, it's not convenient to import by other clients, and it's very hard to manage so many repos. the current api repos as following:
1. https://github.com/openyurtio/yurt-app-manager-api
2. https://github.com/openyurtio/yurt-device-controller-api

moreover, we have some other API definition in other repos, like [raven-controller-manager](https://github.com/openyurtio/raven-controller-manager) and pool-coordinator.
 

**others**
by the way, in order to sync charts and api files from scattered repos, we will create the following two github secrets for each repo.
```
SYNC_CHARTS_SECRET:  for syncing helm charts to openyurtio/openyurt-helm
SYNC_API_SECRET: for syncing api files to openyurtio/api
``` 

/kind feature

**Comment by gnunu** [comment]
Good move!

**Comment by rambohe-ch** [comment]
@huiwq1990 I have created two new repos for managing OpenYurt api and OpenYurt client.
- openyurtio/api: https://github.com/openyurtio/api
- openyurtio/client_golang: https://github.com/openyurtio/client_golang 

and i have added the following organization secrets for the corresponding repos:
- SYNC_API_SECRET:  [openyurtio/api](https://github.com/openyurtio/api)
- SYNC_CHARTS_SECRET: [openyurtio/openyurt-helm](https://github.com/openyurtio/openyurt-helm)
- SYNC_CLIENT_SECRET: [openyurt/client_golang](https://github.com/openyurtio/client_golang )

please the above secrets in your pipeline.

**Comment by huiwq1990** [comment]
@rambohe-ch  DO you mean:
https://github.com/openyurtio/yurt-app-manager/tree/master/pkg/yurtappmanager/apis  sync to [openyurtio/api](https://github.com/openyurtio/api)

https://github.com/openyurtio/yurt-app-manager/tree/master/pkg/yurtappmanager/client sync to [openyurt/client_golang](https://github.com/openyurtio/client_golang)

I think it's better put all of them in one repo, as they are generated by same crd definition and used together.

**Comment by rambohe-ch** [comment]
> @rambohe-ch DO you mean: https://github.com/openyurtio/yurt-app-manager/tree/master/pkg/yurtappmanager/apis sync to [openyurtio/api](https://github.com/openyurtio/api)
> 
> https://github.com/openyurtio/yurt-app-manager/tree/master/pkg/yurtappmanager/client sync to [openyurt/client_golang](https://github.com/openyurtio/client_golang)
> 
> I think it's better put all of them in one repo, as they are generated by same crd definition and used together.

@huiwq1990 Yes, it's more convenient to put all of them in one repo, and we can optimize `api` and `client` in the future.
so i will delete the `openyurtio/client_golang` repo temporarily.
