### ISSUE TITLE
[BUG] YurtHub cache resource namespace hava error

### ISSUE THREAD

**Issue by slm940208** [openyurtio/openyurt#957]
![image](https://user-images.githubusercontent.com/40267976/185342893-0b73e091-ce3d-4998-8579-e1072af4d24e.png)

if resource is namespace，in method saveListObject，info.Namespace is nil, so the cachekey is comp/namespace/kube-system, but in method saveOneObject, info.Namespace is kube-system, so the cachekey is comp/namespace/kube-system/kube-system.

if yurtHub unable to connect apiserver, There is an error in getting a resource from the local cache.

**Comment by rambohe-ch** [comment]
@slm940208 Thank you for raising issue. as we known, component CoreDNS need to list/watch namespace resource from kube-apsierver, and yurthub can cache the namespace data for CoreDNS as following:
![image](https://user-images.githubusercontent.com/57081505/185345869-0d2e169c-477c-41a2-9aaa-4023e3855c2d.png)

**Comment by slm940208** [comment]
@rambohe-ch My component is cilium, There are requests for list and get namespaces, but the order is not guaranteed. Therefore, getting data from the local cache will be reported as an error when starting. now cache is /etc/kubernetes/cache/cilium-agent/namespaces/kube-system, so request for list try to get /etc/kubernetes/cache/cilium-agent/namespaces/kube-system/**kube-system** will error.

**Comment by slm940208** [comment]
@lonelymemo  My component is cilium, There are requests for list and get namespaces, but the order is not guaranteed. Therefore, getting data from the local cache will be reported as an error when starting. now cache is /etc/kubernetes/cache/cilium-agent/namespaces/kube-system, so request for get try to get /etc/kubernetes/cache/cilium-agent/namespaces/kube-system/kube-system will error.

**Comment by rambohe-ch** [comment]
> @lonelymemo My component is cilium, There are requests for list and get namespaces, but the order is not guaranteed. Therefore, getting data from the local cache will be reported as an error when starting. now cache is /etc/kubernetes/cache/cilium-agent/namespaces/kube-system, so request for get try to get /etc/kubernetes/cache/cilium-agent/namespaces/kube-system/kube-system will error.

@slm940208 Thanks for your reply. it sounds like that `list namespaces` has no problem. but `get namespace` maybe fall into error. Would you like to make a pull request to fix this problem?

**Comment by slm940208** [comment]
@rambohe-ch Ok，i will try to  make a pull request to fix this problem.
