### ISSUE TITLE
[Question] changing LGTM is restricted to collaborators

### ISSUE THREAD

**Issue by Congrool** [openyurtio/openyurt#986]
**What happened**:

When `/lgtm`, the bot says 

>@Congrool: changing LGTM is restricted to collaborators
>
>详情
>In response to https://github.com/openyurtio/openyurt/pull/983#issuecomment-1237905090:
>
>/lgtm
>
>Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md). If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.

**What you expected to happen**:

It's better to enable all approvers and reviewers in [OWNERS](https://github.com/openyurtio/openyurt/blob/master/OWNERS) to label pr as lgtm.

**others**
/kind question

**Comment by rambohe-ch** [comment]
@kadisi Do you know how to configure these setting?

**Comment by Congrool** [comment]
It seems we are using prow as CI/CD tech stack. But I've never seen any config files of deploying prow. Like plugins.yaml which is a configmap containing settings about lgtm plugin.

See https://github.com/kubernetes/test-infra/blob/master/prow/plugins/approve/approvers/README.md#lgtm-label

More details about option about lgtm plugin can be found here: https://pkg.go.dev/k8s.io/test-infra/prow/plugins?utm_source=godoc#Lgtm

Maybe we can change settings there. I'm not sure, any other suggestions? @rambohe-ch @kadisi

**Comment by rambohe-ch** [comment]
@kadisi PTAL

**Comment by Congrool** [comment]
Seems lgtm can be used again, as tested in #981 . So close the issue.
/close

**Comment by fengshunli** [comment]
lgtm

**Comment by rambohe-ch** [comment]
> can't lgtm

@fengshunli i have added the rights for your, please have a try again.

**Comment by fengshunli** [comment]
ok
