### ISSUE TITLE
[feature request] Add missing helm charts for openyurt

### ISSUE THREAD

**Issue by luc99hen** [openyurtio/openyurt#987]
**What would you like to be added**:
Add several missing helm charts of openyurt components: yurthub-cfg, yurt-tunnel-dns.

**Why is this needed**:
We need to convert the entire installation process of openyurt to Helm installation

**others**
/kind feature

**Comment by luc99hen** [comment]
Currently `yurt-tunnel-dns` is deployed in the preparing phase, and it has to be setup properly before modifying `api-server` config. If we move it into the helm charts, it seems that `api-server` modification has to be made after helm install.

**Comment by rambohe-ch** [comment]
> Currently `yurt-tunnel-dns` is deployed in the preparing phase, and it has to be setup properly before modifying `api-server` config. If we move it into the helm charts, it seems that `api-server` modification has to be made after helm install. Therefore, `yurt-tunnel-dns` is better to keep it as it is. What do you think? @rambohe-ch

@luc99hen Yes, maybe we'd better to keep yurt-tunnel-dns unchanged. and other components we can make them managed by helm.
